import Challenge.Sha256.Proofs.RouteB
import Challenge.Sha256.Reference.Bytecode

set_option warningAsError true

/-!
# Direct-bytecode target for the reference artifact

The generic `DirectProof` interface is submission-facing and lives in
`Challenge.Sha256.Proofs.RouteB`.  This module fixes that interface to the
frozen reference bytes; its implementation is in the adjacent `RouteB/`
directory.
-/

namespace Challenge.Sha256.RouteB

/-- The frozen Yul-generated bytecode, treated only as raw bytes. -/
def referenceDirectGoal : Prop := DirectProof referenceBytecode

end Challenge.Sha256.RouteB
