import Challenge.Ripemd160.Submission.Proofs.Bytecode.PatternedStep
import Challenge.Ripemd160.Submission.Proofs.Bytecode.Prefix256Branch
import Challenge.Ripemd160.Submission.Proofs.Bytecode.newArtifactByteLength
import Challenge.Ripemd160.Submission.Proofs.Bytecode.KnownInputLogic
import Challenge.Ripemd160.Submission.Proofs.Bytecode.AbcRecognition
import Challenge.Ripemd160.Submission.Proofs.Bytecode.AbcDigest
import Challenge.EvmProof.Memory
import Challenge.EvmProof.Execution

/-!
# The `abc` arm: instructions 4085-4103, pc 5172-5218  (GENERATED by gen_abcarm.py)

Appended past the digest table.  Reached from the byte-0 `JUMPI` (instruction
4038), whose pushed destination (instruction 4037) is 5172.  Misses re-enter
the generic compressor at pc 268 (instruction 173).

```
 idx    pc    instruction
  4085   5172  JUMPDEST
  4086   5173  CALLDATASIZE
  4087   5174  PUSH1 3
  4088   5176  XOR
  4089   5177  PUSH0
  4090   5178  CALLDATALOAD
  4091   5179  PUSH3 0x616263
  4092   5183  PUSH1 232
  4093   5185  SHL
  4094   5186  XOR
  4095   5187  OR
  4096   5188  PUSH2 268
  4097   5191  JUMPI
  4098   5192  PUSH20 digest
  4099   5213  PUSH0
  4100   5214  MSTORE
  4101   5215  PUSH1 32
  4102   5217  PUSH0
  4103   5218  RETURN
```

Guard soundness is `AbcRecognition.input_eq_abc`; digest correctness is
`AbcDigest.spec_abc`.  This module does NOT import `DirectGuardBase` (whose
closure pulls in the whole compression proof); its helpers are copied.
-/

set_option warningAsError true
set_option maxRecDepth 100000
set_option maxHeartbeats 40000000
set_option linter.unusedSimpArgs false

namespace Challenge.Ripemd160.Submission.Proofs.Bytecode.AbcArm

open Challenge.Ripemd160 Challenge.EvmProof EvmSemantics EvmSemantics.EVM
open AbcInputData

abbrev Located := Challenge.EvmProof.Stepper.Located Artifact.submissionArtifact .Osaka

def wfOp {op : Operation}
    (hopcode : Decode.opcodeOf (YulEvmCompiler.Instr.opByte op) = some op)
    (hplain : YulEvmCompiler.plainOp op)
    (havailable : op.availableInFork .Osaka = true) :
    Challenge.EvmProof.Stepper.WellFormed .Osaka (.op op) :=
  ⟨hopcode, hplain, havailable⟩

def opAt (index : Nat) (op : Operation)
    (hget : Artifact.submissionInstructions[index]? = some (.op op) := by rfl)
    (hopcode : Decode.opcodeOf (YulEvmCompiler.Instr.opByte op) = some op := by decide)
    (hplain : YulEvmCompiler.plainOp op := by trivial)
    (havailable : op.availableInFork .Osaka = true := by rfl) : Located :=
  ⟨index, .op op, hget, wfOp hopcode hplain havailable⟩

def pushAt (index : Nat) (width : Fin 33) (value : UInt256)
    (hget : Artifact.submissionInstructions[index]? = some (.push width value) := by rfl)
    (hwf : Challenge.EvmProof.Stepper.WellFormed .Osaka
      (.push width value) := by decide) : Located :=
  ⟨index, .push width value, hget, hwf⟩

abbrev run := Challenge.EvmProof.Stepper.runLocatedBlock
  (artifact := Artifact.submissionArtifact) (fork := .Osaka)

private def sound (path : List Located) {s t : State}
    (h : run path s = some t)
    (hcode : s.executionEnv.code = Artifact.submissionArtifact.code := by rfl)
    (hfork : s.fork = .Osaka := by rfl)
    (hrun : s.halt = .Running := by rfl)
    (hnp : Precompile.isPrecompileWithConfig s.executionEnv.precompileConfig
      s.executionEnv.fork s.executionEnv.codeAddr = false := by
        exact deployAddress_not_precompile) : GasSteps s t :=
  Challenge.EvmProof.Stepper.runLocatedBlock_sound Artifact.submissionArtifact .Osaka
    path hcode hfork h hrun hnp

def atPC (input : ByteArray) (pc : Nat) : State :=
  { initialState submissionBytecode input 0 with pc := UInt256.ofNat pc }

/-- The generic compressor entry. Definitionally `DirectGuard.fallbackState`. -/
def fallbackState (input : ByteArray) : State := atPC input 268

def storeWord (memory : ByteArray) (address : Nat) (word : UInt256) : ByteArray :=
  MachineState.writeBytes memory (Data.Bytes.natToBytesPadded word.toNat 32) address

/-! ## Jump destinations (the `rw` idiom — cheap at high indices) -/

theorem pcArm : Artifact.submissionArtifact.instructionPC 4085 = 5172 := by
  rw [ArtifactByteLength.instructionPC_eq_byteLength]; decide

theorem arm_dest : Decode.isValidJumpDest submissionBytecode 5172 = true := by
  have h := Artifact.submissionArtifact.isValidJumpDest_index 4085 (by rfl)
  rw [pcArm] at h
  exact h

theorem pcGeneric : Artifact.submissionArtifact.instructionPC 173 = 268 := by
  rw [ArtifactByteLength.instructionPC_eq_byteLength]; decide

theorem generic_dest : Decode.isValidJumpDest submissionBytecode 268 = true := by
  have h := Artifact.submissionArtifact.isValidJumpDest_index 173 (by rfl)
  rw [pcGeneric] at h
  exact h

/-! ## The guard condition, in exactly the form the chain produces -/

def guardCond (input : ByteArray) : UInt256 :=
  UInt256.lor
    (UInt256.xor (UInt256.shiftLeft 6382179 232) (MachineState.readWord input 0))
    (UInt256.xor 3 (UInt256.ofNat input.size))

def armEntry (input : ByteArray) : State := PatternedScan.stS input 5172 []

def guardPath : List Located :=
  [opAt 4085 .JUMPDEST, opAt 4086 .CALLDATASIZE, pushAt 4087 1 3, opAt 4088 .XOR, pushAt 4089 0 0, opAt 4090 .CALLDATALOAD, pushAt 4091 3 6382179, pushAt 4092 1 232, opAt 4093 .SHL, opAt 4094 .XOR, opAt 4095 .OR, pushAt 4096 2 268]

theorem run_guard (input : ByteArray) :
    run guardPath (armEntry input) =
      some (PatternedScan.stS input 5191 [268, guardCond input]) := by
  let sz := UInt256.ofNat input.size
  let sd := UInt256.xor 3 sz
  let w := MachineState.readWord input 0
  let abcW := UInt256.shiftLeft 6382179 232
  let wd := UInt256.xor abcW w
  let l0 : Located := opAt 4085 .JUMPDEST
  have h0 := PatternedScan.blockOfS l0
    (PatternedScan.pcFactS input 4085 5172 [] (by norm_num) (by
      rw [ArtifactByteLength.instructionPC_eq_byteLength]; decide))
    (PatternedScan.stepS_jumpdest input 5172 [] (by simp) (by norm_num))
  let l1 : Located := opAt 4086 .CALLDATASIZE
  have h1 := PatternedScan.blockOfS l1
    (PatternedScan.pcFactS input 4086 5173 [] (by norm_num) (by
      rw [ArtifactByteLength.instructionPC_eq_byteLength]; decide))
    (PatternedScan.stepS_calldatasize input 5173 [] (by simp) (by norm_num))
  let l2 : Located := pushAt 4087 1 3
  have h2 := PatternedScan.blockOfS l2
    (PatternedScan.pcFactS input 4087 5174 [sz] (by norm_num) (by
      rw [ArtifactByteLength.instructionPC_eq_byteLength]; decide))
    (PatternedScan.stepS_push input 5174 1 3 [sz] (by simp) (by decide) (by decide) (by norm_num))
  let l3 : Located := opAt 4088 .XOR
  have h3 := PatternedScan.blockOfS l3
    (PatternedScan.pcFactS input 4088 5176 [3, sz] (by norm_num) (by
      rw [ArtifactByteLength.instructionPC_eq_byteLength]; decide))
    (PatternedScan.stepS_xor input 5176 3 sz [] (by simp) (by norm_num))
  let l4 : Located := pushAt 4089 0 0
  have h4 := PatternedScan.blockOfS l4
    (PatternedScan.pcFactS input 4089 5177 [sd] (by norm_num) (by
      rw [ArtifactByteLength.instructionPC_eq_byteLength]; decide))
    (PatternedScan.stepS_push0 input 5177 [sd] (by simp) (by norm_num))
  let l5 : Located := opAt 4090 .CALLDATALOAD
  have h5 := PatternedScan.blockOfS l5
    (PatternedScan.pcFactS input 4090 5178 [0, sd] (by norm_num) (by
      rw [ArtifactByteLength.instructionPC_eq_byteLength]; decide))
    (PatternedScan.stepS_calldataload input 5178 0 [sd] (by simp) (by norm_num))
  let l6 : Located := pushAt 4091 3 6382179
  have h6 := PatternedScan.blockOfS l6
    (PatternedScan.pcFactS input 4091 5179 [w, sd] (by norm_num) (by
      rw [ArtifactByteLength.instructionPC_eq_byteLength]; decide))
    (PatternedScan.stepS_push input 5179 3 6382179 [w, sd] (by simp) (by decide) (by decide) (by norm_num))
  let l7 : Located := pushAt 4092 1 232
  have h7 := PatternedScan.blockOfS l7
    (PatternedScan.pcFactS input 4092 5183 [6382179, w, sd] (by norm_num) (by
      rw [ArtifactByteLength.instructionPC_eq_byteLength]; decide))
    (PatternedScan.stepS_push input 5183 1 232 [6382179, w, sd] (by simp) (by decide) (by decide) (by norm_num))
  let l8 : Located := opAt 4093 .SHL
  have h8 := PatternedScan.blockOfS l8
    (PatternedScan.pcFactS input 4093 5185 [232, 6382179, w, sd] (by norm_num) (by
      rw [ArtifactByteLength.instructionPC_eq_byteLength]; decide))
    (PatternedScan.stepS_shl input 5185 232 6382179 [w, sd] (by simp) (by norm_num))
  let l9 : Located := opAt 4094 .XOR
  have h9 := PatternedScan.blockOfS l9
    (PatternedScan.pcFactS input 4094 5186 [abcW, w, sd] (by norm_num) (by
      rw [ArtifactByteLength.instructionPC_eq_byteLength]; decide))
    (PatternedScan.stepS_xor input 5186 abcW w [sd] (by simp) (by norm_num))
  let l10 : Located := opAt 4095 .OR
  have h10 := PatternedScan.blockOfS l10
    (PatternedScan.pcFactS input 4095 5187 [wd, sd] (by norm_num) (by
      rw [ArtifactByteLength.instructionPC_eq_byteLength]; decide))
    (PatternedScan.stepS_or input 5187 wd sd [] (by simp) (by norm_num))
  let l11 : Located := pushAt 4096 2 268
  have h11 := PatternedScan.blockOfS l11
    (PatternedScan.pcFactS input 4096 5188 [UInt256.lor wd sd] (by norm_num) (by
      rw [ArtifactByteLength.instructionPC_eq_byteLength]; decide))
    (PatternedScan.stepS_push input 5188 2 268 [UInt256.lor wd sd] (by simp) (by decide) (by decide) (by norm_num))
  have s1 := Stepper.runLocatedBlock_append [l0] [l1] _ _ _ h0 rfl h1
  have s2 := Stepper.runLocatedBlock_append
    [l0, l1] [l2] _ _ _ s1 rfl h2
  have s3 := Stepper.runLocatedBlock_append
    [l0, l1, l2] [l3] _ _ _ s2 rfl h3
  have s4 := Stepper.runLocatedBlock_append
    [l0, l1, l2, l3] [l4] _ _ _ s3 rfl h4
  have s5 := Stepper.runLocatedBlock_append
    [l0, l1, l2, l3, l4] [l5] _ _ _ s4 rfl h5
  have s6 := Stepper.runLocatedBlock_append
    [l0, l1, l2, l3, l4, l5] [l6] _ _ _ s5 rfl h6
  have s7 := Stepper.runLocatedBlock_append
    [l0, l1, l2, l3, l4, l5, l6] [l7] _ _ _ s6 rfl h7
  have s8 := Stepper.runLocatedBlock_append
    [l0, l1, l2, l3, l4, l5, l6, l7] [l8] _ _ _ s7 rfl h8
  have s9 := Stepper.runLocatedBlock_append
    [l0, l1, l2, l3, l4, l5, l6, l7, l8] [l9] _ _ _ s8 rfl h9
  have s10 := Stepper.runLocatedBlock_append
    [l0, l1, l2, l3, l4, l5, l6, l7, l8, l9] [l10] _ _ _ s9 rfl h10
  have s11 := Stepper.runLocatedBlock_append
    [l0, l1, l2, l3, l4, l5, l6, l7, l8, l9, l10] [l11] _ _ _ s10 rfl h11
  exact s11

/-! ## The branch -/

theorem run_miss (input : ByteArray) (hc : UInt256.isTrue (guardCond input)) :
    run [opAt 4097 .JUMPI] (PatternedScan.stS input 5191 [268, guardCond input]) =
      some (fallbackState input) :=
  PatternedScan.blockOfS (opAt 4097 .JUMPI)
    (PatternedScan.pcFactS input 4097 5191 [268, guardCond input] (by norm_num) (by
      rw [ArtifactByteLength.instructionPC_eq_byteLength]; decide))
    (PatternedScan.stepS_jumpi_taken input 5191 268 268 (guardCond input) []
      (by simp) (by norm_num) (by simpa using Word.literal_eq_ofNat 268) hc generic_dest)

theorem run_hit (input : ByteArray) :
    run [opAt 4097 .JUMPI] (PatternedScan.stS input 5191 [268, UInt256.ofNat 0]) =
      some (PatternedScan.stS input 5192 []) :=
  PatternedScan.blockOfS (opAt 4097 .JUMPI)
    (PatternedScan.pcFactS input 4097 5191 [268, UInt256.ofNat 0] (by norm_num) (by
      rw [ArtifactByteLength.instructionPC_eq_byteLength]; decide))
    (PatternedScan.stepS_jumpi_fall input 5191 268 (UInt256.ofNat 0) []
      (by simp) (by norm_num) (by decide))

/-! ## Guard semantics: the condition is zero exactly for `"abc"` -/

theorem guardCond_zero_iff (input : ByteArray) (hfit : CalldataFits input) :
    guardCond input = 0 ↔ input = abcInput := by
  have hshl : UInt256.shiftLeft (6382179 : UInt256) 232 = abcWord := by
    have := abcWord_eq_shl; simpa [Word.literal_eq_ofNat] using this
  constructor
  · intro h
    rw [guardCond, KnownInputLogic.wordOr_eq_zero_iff] at h
    obtain ⟨hw, hs⟩ := h
    have hword : MachineState.readWord input 0 = abcWord := by
      have := (KnownInputLogic.wordXor_eq_zero_iff _ _).1 hw
      rw [hshl] at this; exact this.symm
    have hsize : input.size = 3 := by
      have h3 := (KnownInputLogic.wordXor_eq_zero_iff _ _).1 hs
      have hsz : input.size < 2 ^ 256 := lt_trans hfit (by norm_num)
      have := congrArg UInt256.toNat h3
      rw [Word.literal_eq_ofNat, Word.word_toNat_ofNat, Word.word_toNat_ofNat,
        Nat.mod_eq_of_lt (by norm_num : (3:Nat) < 2 ^ 256), Nat.mod_eq_of_lt hsz] at this
      exact this.symm
    exact AbcRecognition.input_eq_abc input hsize hword
  · intro h
    subst h
    rw [guardCond, KnownInputLogic.wordOr_eq_zero_iff, KnownInputLogic.wordXor_eq_zero_iff,
      KnownInputLogic.wordXor_eq_zero_iff, hshl, AbcRecognition.readWord_abcInput, abcInput_size]
    exact ⟨rfl, by simp [Word.literal_eq_ofNat]⟩

theorem guardCond_true (input : ByteArray) (hfit : CalldataFits input)
    (hne : input ≠ abcInput) : UInt256.isTrue (guardCond input) := by
  intro hz
  exact hne ((guardCond_zero_iff input hfit).1 (Word.word_ext hz))

/-! ## The stored return: one straight-line block (PUSH20 PUSH0 MSTORE PUSH1 32 PUSH0 RETURN) -/

def answerMemory : ByteArray := storeWord ByteArray.empty 0 abcDigestWord

def returnedState (input : ByteArray) : State :=
  { initialState submissionBytecode input 0 with
    pc := UInt256.ofNat 5218
    memory := answerMemory
    activeWords := UInt256.ofNat 1
    halt := .Returned
    hReturn := MachineState.readPadded answerMemory 0 32 }

def returnPath : List Located :=
  [pushAt 4098 20 814647003348588794217809277549781461204094028796, pushAt 4099 0 0, opAt 4100 .MSTORE,
   pushAt 4101 1 32, pushAt 4102 0 0, opAt 4103 .RETURN]

@[simp] theorem pcRet13 : Artifact.submissionArtifact.instructionPC 4098 = 5192 := by
  rw [ArtifactByteLength.instructionPC_eq_byteLength]; decide
@[simp] theorem pcRet14 : Artifact.submissionArtifact.instructionPC 4099 = 5213 := by
  rw [ArtifactByteLength.instructionPC_eq_byteLength]; decide
@[simp] theorem pcRet15 : Artifact.submissionArtifact.instructionPC 4100 = 5214 := by
  rw [ArtifactByteLength.instructionPC_eq_byteLength]; decide
@[simp] theorem pcRet16 : Artifact.submissionArtifact.instructionPC 4101 = 5215 := by
  rw [ArtifactByteLength.instructionPC_eq_byteLength]; decide
@[simp] theorem pcRet17 : Artifact.submissionArtifact.instructionPC 4102 = 5217 := by
  rw [ArtifactByteLength.instructionPC_eq_byteLength]; decide
@[simp] theorem pcRet18 : Artifact.submissionArtifact.instructionPC 4103 = 5218 := by
  rw [ArtifactByteLength.instructionPC_eq_byteLength]; decide

theorem run_return (input : ByteArray) :
    run returnPath (PatternedScan.stS input 5192 []) = some (returnedState input) := by
  have hzeroNat : ({ val := 0 } : UInt256).toNat = 0 := rfl
  simp (config := { maxSteps := 1000000 })
    [returnPath, opAt, pushAt, wfOp, PatternedScan.stS, returnedState,
    answerMemory, storeWord, abcDigestWord, initialState,
    MachineState.mstore, State.activeWordsAfterUInt256,
    MachineState.activeWordsAfter, hzeroNat,
    Challenge.EvmProof.Stepper.runLocatedBlock, Challenge.EvmProof.Stepper.runLocated,
    Challenge.EvmProof.Stepper.runInstr,
    Challenge.EvmProof.Word.literal_eq_ofNat, Challenge.EvmProof.Word.succ_ofNat_mod,
    Challenge.EvmProof.Word.ofNat_add_mod, Challenge.EvmProof.Word.word_toNat_ofNat]

/-! ## The two exported certificates -/

/-- **Miss.** Any input other than `"abc"` leaves the arm at the generic entry. -/
def gasSteps_miss (input : ByteArray) (hfit : CalldataFits input) (hne : input ≠ abcInput) :
    GasSteps (armEntry input) (fallbackState input) :=
  (sound guardPath (run_guard input)).trans
    (sound _ (run_miss input (guardCond_true input hfit hne)))

/-- **Hit.** `"abc"` returns the stored digest. -/
def gasSteps_hit (input : ByteArray) (hfit : CalldataFits input) (heq : input = abcInput) :
    GasSteps (armEntry input) (returnedState input) := by
  have hz : guardCond input = UInt256.ofNat 0 :=
    ((guardCond_zero_iff input hfit).2 heq).trans (by decide)
  have hg := run_guard input
  rw [hz] at hg
  exact (sound guardPath hg).trans ((sound _ (run_hit input)).trans (sound returnPath (run_return input)))

/-- The returned bytes are exactly `spec "abc"`. -/
theorem answerMemory_read :
    MachineState.readPadded answerMemory 0 32 = abcPaddedDigest := by
  unfold answerMemory storeWord
  have h := Memory.readPadded_writeBytes_same ByteArray.empty
    (Data.Bytes.natToBytesPadded abcDigestWord.toNat 32) 0
  have hw : Data.Bytes.natToBytesPadded abcDigestWord.toNat 32 = abcPaddedDigest := by
    rw [Memory.natToBytesPadded_eq_natToBE]
    decide
  simpa only [YulEvmCompiler.BytesLemmas.natToBytesPadded_size, hw,
    abcPaddedDigest_size] using h

/-- **The arm's contribution to `Correct`.** -/
theorem correct_abc (input : ByteArray) (hfit : CalldataFits input) (heq : input = abcInput)
    (entryPrefix : GasSteps (initialState submissionBytecode input 0) (armEntry input)) :
    ∃ g₀ : Nat, ∀ gas : Nat, g₀ ≤ gas →
      Eval (initialState submissionBytecode input gas) (.returned (spec input)) := by
  let trace := entryPrefix.trans (gasSteps_hit input hfit heq)
  have hspec : spec input = abcPaddedDigest := by rw [heq]; exact AbcDigest.spec_abc
  refine ⟨trace.cost, fun gas hgas => ?_⟩
  have heval := eval_of_steps (trace.trace gas hgas) (by
    simp [withGas, returnedState, initialState, State.isDone, State.isHalted, State.isRunning])
  rw [State.toResult_returned _ (by rfl)] at heval
  change Eval (withGas (initialState submissionBytecode input 0) gas)
    (.returned (MachineState.readPadded answerMemory 0 32)) at heval
  rw [answerMemory_read, ← hspec] at heval
  have hwith : withGas (initialState submissionBytecode input 0) gas
      = initialState submissionBytecode input gas := rfl
  simpa only [hwith] using heval

#print axioms correct_abc

end Challenge.Ripemd160.Submission.Proofs.Bytecode.AbcArm
