import Challenge.Ripemd160.Submission.Proofs.Bytecode.CachedMaskHelper

set_option warningAsError true
set_option maxRecDepth 100000
set_option maxHeartbeats 10000000

namespace Challenge.Ripemd160.Submission.Proofs.Bytecode.CachedMaskHoistHelper

open EvmSemantics EvmSemantics.EVM YulEvmCompiler Challenge.EvmProof
open StackRoundTemplate StackRoundTrace QuadRoundState QuadRoundTemplate
open PairRoundTemplate QuadGapTemplate

def leftTemplate0 (_constant : UInt256) : List Instr :=
  [.op .JUMPDEST,
     .op .MLOAD,
     .op (.Dup ⟨10, by decide⟩),
     .op (.Dup ⟨12, by decide⟩),
     .op .XOR,
     .op (.Dup ⟨13, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op (.Swap ⟨0, by decide⟩),
     .op (.Swap ⟨8, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨14, by decide⟩),
     .op .AND,
     .op (.Dup ⟨13, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨11, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨13, by decide⟩),
     .op .AND,
     .op (.Swap ⟨8, by decide⟩),
     .op (.Dup ⟨12, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨10, by decide⟩),
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨9, by decide⟩),
     .op (.Dup ⟨9, by decide⟩),
     .op .XOR,
     .op (.Dup ⟨12, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op .ADD,
     .op (.Dup ⟨12, by decide⟩),
     .op .AND,
     .op (.Dup ⟨11, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨8, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨11, by decide⟩),
     .op .AND,
     .op (.Swap ⟨5, by decide⟩),
     .op (.Dup ⟨10, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨7, by decide⟩),
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨6, by decide⟩),
     .op (.Dup ⟨8, by decide⟩),
     .op .XOR,
     .op (.Dup ⟨9, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op .ADD,
     .op (.Dup ⟨10, by decide⟩),
     .op .AND,
     .op (.Dup ⟨9, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨7, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨9, by decide⟩),
     .op .AND,
     .op (.Swap ⟨4, by decide⟩),
     .op (.Dup ⟨8, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨6, by decide⟩),
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨5, by decide⟩),
     .op (.Dup ⟨5, by decide⟩),
     .op .XOR,
     .op (.Dup ⟨8, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op .ADD,
     .op (.Dup ⟨8, by decide⟩),
     .op .AND,
     .op (.Dup ⟨7, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨4, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨7, by decide⟩),
     .op .AND,
     .op (.Swap ⟨1, by decide⟩),
     .op (.Dup ⟨6, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨3, by decide⟩),
     .op (.Swap ⟨0, by decide⟩)]

def leftTemplate1 (constant : UInt256) : List Instr :=
  [.op .JUMPDEST,
     .op .MLOAD,
     .op (.Dup ⟨11, by decide⟩),
     .op (.Dup ⟨13, by decide⟩),
     .op .XOR,
     .op (.Dup ⟨11, by decide⟩),
     .op .AND,
     .op (.Dup ⟨13, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op (.Swap ⟨0, by decide⟩),
     .op (.Swap ⟨8, by decide⟩),
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .op (.Dup ⟨14, by decide⟩),
     .op .AND,
     .op (.Dup ⟨13, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨11, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨13, by decide⟩),
     .op .AND,
     .op (.Swap ⟨8, by decide⟩),
     .op (.Dup ⟨12, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨10, by decide⟩),
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨8, by decide⟩),
     .op (.Dup ⟨12, by decide⟩),
     .op .XOR,
     .op (.Dup ⟨10, by decide⟩),
     .op .AND,
     .op (.Dup ⟨12, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .op (.Dup ⟨12, by decide⟩),
     .op .AND,
     .op (.Dup ⟨11, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨8, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨11, by decide⟩),
     .op .AND,
     .op (.Swap ⟨5, by decide⟩),
     .op (.Dup ⟨10, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨7, by decide⟩),
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨7, by decide⟩),
     .op (.Dup ⟨9, by decide⟩),
     .op .XOR,
     .op (.Dup ⟨7, by decide⟩),
     .op .AND,
     .op (.Dup ⟨9, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .op (.Dup ⟨10, by decide⟩),
     .op .AND,
     .op (.Dup ⟨9, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨7, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨9, by decide⟩),
     .op .AND,
     .op (.Swap ⟨4, by decide⟩),
     .op (.Dup ⟨8, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨6, by decide⟩),
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨4, by decide⟩),
     .op (.Dup ⟨8, by decide⟩),
     .op .XOR,
     .op (.Dup ⟨6, by decide⟩),
     .op .AND,
     .op (.Dup ⟨8, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .op (.Dup ⟨8, by decide⟩),
     .op .AND,
     .op (.Dup ⟨7, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨4, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨7, by decide⟩),
     .op .AND,
     .op (.Swap ⟨1, by decide⟩),
     .op (.Dup ⟨6, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨3, by decide⟩),
     .op (.Swap ⟨0, by decide⟩)]

def leftTemplate2 (constant : UInt256) : List Instr :=
  [.op .JUMPDEST,
     .op .MLOAD,
     .op (.Dup ⟨11, by decide⟩),
     .op .NOT,
     .op (.Dup ⟨11, by decide⟩),
     .op .OR,
     .op (.Dup ⟨13, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op (.Swap ⟨0, by decide⟩),
     .op (.Swap ⟨8, by decide⟩),
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .op (.Dup ⟨14, by decide⟩),
     .op .AND,
     .op (.Dup ⟨13, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨11, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨13, by decide⟩),
     .op .AND,
     .op (.Swap ⟨8, by decide⟩),
     .op (.Dup ⟨12, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨10, by decide⟩),
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨8, by decide⟩),
     .op .NOT,
     .op (.Dup ⟨10, by decide⟩),
     .op .OR,
     .op (.Dup ⟨12, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .op (.Dup ⟨12, by decide⟩),
     .op .AND,
     .op (.Dup ⟨11, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨8, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨11, by decide⟩),
     .op .AND,
     .op (.Swap ⟨5, by decide⟩),
     .op (.Dup ⟨10, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨7, by decide⟩),
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨7, by decide⟩),
     .op .NOT,
     .op (.Dup ⟨7, by decide⟩),
     .op .OR,
     .op (.Dup ⟨9, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .op (.Dup ⟨10, by decide⟩),
     .op .AND,
     .op (.Dup ⟨9, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨7, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨9, by decide⟩),
     .op .AND,
     .op (.Swap ⟨4, by decide⟩),
     .op (.Dup ⟨8, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨6, by decide⟩),
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨4, by decide⟩),
     .op .NOT,
     .op (.Dup ⟨6, by decide⟩),
     .op .OR,
     .op (.Dup ⟨8, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .op (.Dup ⟨8, by decide⟩),
     .op .AND,
     .op (.Dup ⟨7, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨4, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨7, by decide⟩),
     .op .AND,
     .op (.Swap ⟨1, by decide⟩),
     .op (.Dup ⟨6, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨3, by decide⟩),
     .op (.Swap ⟨0, by decide⟩)]

def leftTemplate3 (constant : UInt256) : List Instr :=
  [.op .JUMPDEST,
     .op .MLOAD,
     .op (.Dup ⟨10, by decide⟩),
     .op (.Dup ⟨12, by decide⟩),
     .op .XOR,
     .op (.Dup ⟨13, by decide⟩),
     .op .AND,
     .op (.Dup ⟨12, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op (.Swap ⟨0, by decide⟩),
     .op (.Swap ⟨8, by decide⟩),
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .op (.Dup ⟨14, by decide⟩),
     .op .AND,
     .op (.Dup ⟨13, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨11, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨13, by decide⟩),
     .op .AND,
     .op (.Swap ⟨8, by decide⟩),
     .op (.Dup ⟨12, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨10, by decide⟩),
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨9, by decide⟩),
     .op (.Dup ⟨9, by decide⟩),
     .op .XOR,
     .op (.Dup ⟨12, by decide⟩),
     .op .AND,
     .op (.Dup ⟨9, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .op (.Dup ⟨12, by decide⟩),
     .op .AND,
     .op (.Dup ⟨11, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨8, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨11, by decide⟩),
     .op .AND,
     .op (.Swap ⟨5, by decide⟩),
     .op (.Dup ⟨10, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨7, by decide⟩),
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨6, by decide⟩),
     .op (.Dup ⟨8, by decide⟩),
     .op .XOR,
     .op (.Dup ⟨9, by decide⟩),
     .op .AND,
     .op (.Dup ⟨8, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .op (.Dup ⟨10, by decide⟩),
     .op .AND,
     .op (.Dup ⟨9, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨7, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨9, by decide⟩),
     .op .AND,
     .op (.Swap ⟨4, by decide⟩),
     .op (.Dup ⟨8, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨6, by decide⟩),
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨5, by decide⟩),
     .op (.Dup ⟨5, by decide⟩),
     .op .XOR,
     .op (.Dup ⟨8, by decide⟩),
     .op .AND,
     .op (.Dup ⟨5, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .op (.Dup ⟨8, by decide⟩),
     .op .AND,
     .op (.Dup ⟨7, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨4, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨7, by decide⟩),
     .op .AND,
     .op (.Swap ⟨1, by decide⟩),
     .op (.Dup ⟨6, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨3, by decide⟩),
     .op (.Swap ⟨0, by decide⟩)]

def leftTemplate4 (constant : UInt256) : List Instr :=
  [.op .JUMPDEST,
     .op .MLOAD,
     .op (.Dup ⟨12, by decide⟩),
     .op .NOT,
     .op (.Dup ⟨12, by decide⟩),
     .op .OR,
     .op (.Dup ⟨11, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op (.Swap ⟨0, by decide⟩),
     .op (.Swap ⟨8, by decide⟩),
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .op (.Dup ⟨14, by decide⟩),
     .op .AND,
     .op (.Dup ⟨13, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨11, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨13, by decide⟩),
     .op .AND,
     .op (.Swap ⟨8, by decide⟩),
     .op (.Dup ⟨12, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨10, by decide⟩),
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨11, by decide⟩),
     .op .NOT,
     .op (.Dup ⟨9, by decide⟩),
     .op .OR,
     .op (.Dup ⟨10, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .op (.Dup ⟨12, by decide⟩),
     .op .AND,
     .op (.Dup ⟨11, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨8, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨11, by decide⟩),
     .op .AND,
     .op (.Swap ⟨5, by decide⟩),
     .op (.Dup ⟨10, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨7, by decide⟩),
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨8, by decide⟩),
     .op .NOT,
     .op (.Dup ⟨8, by decide⟩),
     .op .OR,
     .op (.Dup ⟨7, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .op (.Dup ⟨10, by decide⟩),
     .op .AND,
     .op (.Dup ⟨9, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨7, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨9, by decide⟩),
     .op .AND,
     .op (.Swap ⟨4, by decide⟩),
     .op (.Dup ⟨8, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨6, by decide⟩),
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨7, by decide⟩),
     .op .NOT,
     .op (.Dup ⟨5, by decide⟩),
     .op .OR,
     .op (.Dup ⟨6, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .op (.Dup ⟨8, by decide⟩),
     .op .AND,
     .op (.Dup ⟨7, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨4, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨7, by decide⟩),
     .op .AND,
     .op (.Swap ⟨1, by decide⟩),
     .op (.Dup ⟨6, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨3, by decide⟩),
     .op (.Swap ⟨0, by decide⟩)]

def rightTemplate0 (_constant : UInt256) : List Instr :=
  [.op .JUMPDEST,
     .op .MLOAD,
     .op (.Dup ⟨10, by decide⟩),
     .op (.Dup ⟨12, by decide⟩),
     .op .XOR,
     .op (.Dup ⟨13, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op (.Swap ⟨0, by decide⟩),
     .op (.Swap ⟨8, by decide⟩),
     .op .ADD,
     .push 4 (UInt256.ofNat 4294967295),
     .op .AND,
     .op (.Dup ⟨13, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨11, by decide⟩),
     .op .ADD,
     .push 4 (UInt256.ofNat 4294967295),
     .op .AND,
     .op (.Swap ⟨8, by decide⟩),
     .op (.Dup ⟨12, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨10, by decide⟩),
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨9, by decide⟩),
     .op (.Dup ⟨9, by decide⟩),
     .op .XOR,
     .op (.Dup ⟨12, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op .ADD,
     .push 4 (UInt256.ofNat 4294967295),
     .op .AND,
     .op (.Dup ⟨11, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨8, by decide⟩),
     .op .ADD,
     .push 4 (UInt256.ofNat 4294967295),
     .op .AND,
     .op (.Swap ⟨5, by decide⟩),
     .op (.Dup ⟨10, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨7, by decide⟩),
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨6, by decide⟩),
     .op (.Dup ⟨8, by decide⟩),
     .op .XOR,
     .op (.Dup ⟨9, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op .ADD,
     .op (.Dup ⟨15, by decide⟩),
     .op .AND,
     .op (.Dup ⟨9, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨7, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨14, by decide⟩),
     .op .AND,
     .op (.Swap ⟨4, by decide⟩),
     .op (.Dup ⟨8, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨6, by decide⟩),
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨5, by decide⟩),
     .op (.Dup ⟨5, by decide⟩),
     .op .XOR,
     .op (.Dup ⟨8, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op .ADD,
     .op (.Dup ⟨13, by decide⟩),
     .op .AND,
     .op (.Dup ⟨7, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨4, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨12, by decide⟩),
     .op .AND,
     .op (.Swap ⟨1, by decide⟩),
     .op (.Dup ⟨6, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨3, by decide⟩),
     .op (.Swap ⟨0, by decide⟩)]

def rightTemplate1 (constant : UInt256) : List Instr :=
  [.op .JUMPDEST,
     .op .MLOAD,
     .op (.Dup ⟨11, by decide⟩),
     .op (.Dup ⟨13, by decide⟩),
     .op .XOR,
     .op (.Dup ⟨11, by decide⟩),
     .op .AND,
     .op (.Dup ⟨13, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op (.Swap ⟨0, by decide⟩),
     .op (.Swap ⟨8, by decide⟩),
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .push 4 (UInt256.ofNat 4294967295),
     .op .AND,
     .op (.Dup ⟨13, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨11, by decide⟩),
     .op .ADD,
     .push 4 (UInt256.ofNat 4294967295),
     .op .AND,
     .op (.Swap ⟨8, by decide⟩),
     .op (.Dup ⟨12, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨10, by decide⟩),
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨8, by decide⟩),
     .op (.Dup ⟨12, by decide⟩),
     .op .XOR,
     .op (.Dup ⟨10, by decide⟩),
     .op .AND,
     .op (.Dup ⟨12, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .push 4 (UInt256.ofNat 4294967295),
     .op .AND,
     .op (.Dup ⟨11, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨8, by decide⟩),
     .op .ADD,
     .push 4 (UInt256.ofNat 4294967295),
     .op .AND,
     .op (.Swap ⟨5, by decide⟩),
     .op (.Dup ⟨10, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨7, by decide⟩),
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨7, by decide⟩),
     .op (.Dup ⟨9, by decide⟩),
     .op .XOR,
     .op (.Dup ⟨7, by decide⟩),
     .op .AND,
     .op (.Dup ⟨9, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .op (.Dup ⟨15, by decide⟩),
     .op .AND,
     .op (.Dup ⟨9, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨7, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨14, by decide⟩),
     .op .AND,
     .op (.Swap ⟨4, by decide⟩),
     .op (.Dup ⟨8, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨6, by decide⟩),
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨4, by decide⟩),
     .op (.Dup ⟨8, by decide⟩),
     .op .XOR,
     .op (.Dup ⟨6, by decide⟩),
     .op .AND,
     .op (.Dup ⟨8, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .op (.Dup ⟨13, by decide⟩),
     .op .AND,
     .op (.Dup ⟨7, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨4, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨12, by decide⟩),
     .op .AND,
     .op (.Swap ⟨1, by decide⟩),
     .op (.Dup ⟨6, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨3, by decide⟩),
     .op (.Swap ⟨0, by decide⟩)]

def rightTemplate2 (constant : UInt256) : List Instr :=
  [.op .JUMPDEST,
     .op .MLOAD,
     .op (.Dup ⟨11, by decide⟩),
     .op .NOT,
     .op (.Dup ⟨11, by decide⟩),
     .op .OR,
     .op (.Dup ⟨13, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op (.Swap ⟨0, by decide⟩),
     .op (.Swap ⟨8, by decide⟩),
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .push 4 (UInt256.ofNat 4294967295),
     .op .AND,
     .op (.Dup ⟨13, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨11, by decide⟩),
     .op .ADD,
     .push 4 (UInt256.ofNat 4294967295),
     .op .AND,
     .op (.Swap ⟨8, by decide⟩),
     .op (.Dup ⟨12, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨10, by decide⟩),
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨8, by decide⟩),
     .op .NOT,
     .op (.Dup ⟨10, by decide⟩),
     .op .OR,
     .op (.Dup ⟨12, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .push 4 (UInt256.ofNat 4294967295),
     .op .AND,
     .op (.Dup ⟨11, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨8, by decide⟩),
     .op .ADD,
     .push 4 (UInt256.ofNat 4294967295),
     .op .AND,
     .op (.Swap ⟨5, by decide⟩),
     .op (.Dup ⟨10, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨7, by decide⟩),
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨7, by decide⟩),
     .op .NOT,
     .op (.Dup ⟨7, by decide⟩),
     .op .OR,
     .op (.Dup ⟨9, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .op (.Dup ⟨15, by decide⟩),
     .op .AND,
     .op (.Dup ⟨9, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨7, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨14, by decide⟩),
     .op .AND,
     .op (.Swap ⟨4, by decide⟩),
     .op (.Dup ⟨8, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨6, by decide⟩),
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨4, by decide⟩),
     .op .NOT,
     .op (.Dup ⟨6, by decide⟩),
     .op .OR,
     .op (.Dup ⟨8, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .op (.Dup ⟨13, by decide⟩),
     .op .AND,
     .op (.Dup ⟨7, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨4, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨12, by decide⟩),
     .op .AND,
     .op (.Swap ⟨1, by decide⟩),
     .op (.Dup ⟨6, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨3, by decide⟩),
     .op (.Swap ⟨0, by decide⟩)]

def rightTemplate3 (constant : UInt256) : List Instr :=
  [.op .JUMPDEST,
     .op .MLOAD,
     .op (.Dup ⟨10, by decide⟩),
     .op (.Dup ⟨12, by decide⟩),
     .op .XOR,
     .op (.Dup ⟨13, by decide⟩),
     .op .AND,
     .op (.Dup ⟨12, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op (.Swap ⟨0, by decide⟩),
     .op (.Swap ⟨8, by decide⟩),
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .push 4 (UInt256.ofNat 4294967295),
     .op .AND,
     .op (.Dup ⟨13, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨11, by decide⟩),
     .op .ADD,
     .push 4 (UInt256.ofNat 4294967295),
     .op .AND,
     .op (.Swap ⟨8, by decide⟩),
     .op (.Dup ⟨12, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨10, by decide⟩),
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨9, by decide⟩),
     .op (.Dup ⟨9, by decide⟩),
     .op .XOR,
     .op (.Dup ⟨12, by decide⟩),
     .op .AND,
     .op (.Dup ⟨9, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .push 4 (UInt256.ofNat 4294967295),
     .op .AND,
     .op (.Dup ⟨11, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨8, by decide⟩),
     .op .ADD,
     .push 4 (UInt256.ofNat 4294967295),
     .op .AND,
     .op (.Swap ⟨5, by decide⟩),
     .op (.Dup ⟨10, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨7, by decide⟩),
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨6, by decide⟩),
     .op (.Dup ⟨8, by decide⟩),
     .op .XOR,
     .op (.Dup ⟨9, by decide⟩),
     .op .AND,
     .op (.Dup ⟨8, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .op (.Dup ⟨15, by decide⟩),
     .op .AND,
     .op (.Dup ⟨9, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨7, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨14, by decide⟩),
     .op .AND,
     .op (.Swap ⟨4, by decide⟩),
     .op (.Dup ⟨8, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨6, by decide⟩),
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨5, by decide⟩),
     .op (.Dup ⟨5, by decide⟩),
     .op .XOR,
     .op (.Dup ⟨8, by decide⟩),
     .op .AND,
     .op (.Dup ⟨5, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .op (.Dup ⟨13, by decide⟩),
     .op .AND,
     .op (.Dup ⟨7, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨4, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨12, by decide⟩),
     .op .AND,
     .op (.Swap ⟨1, by decide⟩),
     .op (.Dup ⟨6, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨3, by decide⟩),
     .op (.Swap ⟨0, by decide⟩)]

def rightTemplate4 (constant : UInt256) : List Instr :=
  [.op .JUMPDEST,
     .op .MLOAD,
     .op (.Dup ⟨12, by decide⟩),
     .op .NOT,
     .op (.Dup ⟨12, by decide⟩),
     .op .OR,
     .op (.Dup ⟨11, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op (.Swap ⟨0, by decide⟩),
     .op (.Swap ⟨8, by decide⟩),
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .push 4 (UInt256.ofNat 4294967295),
     .op .AND,
     .op (.Dup ⟨13, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨11, by decide⟩),
     .op .ADD,
     .push 4 (UInt256.ofNat 4294967295),
     .op .AND,
     .op (.Swap ⟨8, by decide⟩),
     .op (.Dup ⟨12, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨10, by decide⟩),
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨11, by decide⟩),
     .op .NOT,
     .op (.Dup ⟨9, by decide⟩),
     .op .OR,
     .op (.Dup ⟨10, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .push 4 (UInt256.ofNat 4294967295),
     .op .AND,
     .op (.Dup ⟨11, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨8, by decide⟩),
     .op .ADD,
     .push 4 (UInt256.ofNat 4294967295),
     .op .AND,
     .op (.Swap ⟨5, by decide⟩),
     .op (.Dup ⟨10, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨7, by decide⟩),
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨8, by decide⟩),
     .op .NOT,
     .op (.Dup ⟨8, by decide⟩),
     .op .OR,
     .op (.Dup ⟨7, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .op (.Dup ⟨15, by decide⟩),
     .op .AND,
     .op (.Dup ⟨9, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨7, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨14, by decide⟩),
     .op .AND,
     .op (.Swap ⟨4, by decide⟩),
     .op (.Dup ⟨8, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨6, by decide⟩),
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨7, by decide⟩),
     .op .NOT,
     .op (.Dup ⟨5, by decide⟩),
     .op .OR,
     .op (.Dup ⟨6, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .op (.Dup ⟨13, by decide⟩),
     .op .AND,
     .op (.Dup ⟨7, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨4, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨12, by decide⟩),
     .op .AND,
     .op (.Swap ⟨1, by decide⟩),
     .op (.Dup ⟨6, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨3, by decide⟩),
     .op (.Swap ⟨0, by decide⟩)]

def leftTemplate (j : Nat) (constant : UInt256) : List Instr :=
  match j with
  | 0 => leftTemplate0 constant
  | 1 => leftTemplate1 constant
  | 2 => leftTemplate2 constant
  | 3 => leftTemplate3 constant
  | _ => leftTemplate4 constant

def rightTemplate (j : Nat) (constant : UInt256) : List Instr :=
  match j with
  | 0 => rightTemplate0 constant
  | 1 => rightTemplate1 constant
  | 2 => rightTemplate2 constant
  | 3 => rightTemplate3 constant
  | _ => rightTemplate4 constant

set_option linter.unusedSimpArgs false in
theorem left_equiv (j : Nat) (hj : j < 5)
    (s : State) (startPC p0 p1 p2 p3 returnPC : UInt256)
    (r0 r1 r2 r3 : Nat) (constant : UInt256)
    (working : Compression.EvmWorking) (rho : List UInt256)
    (hstack : rho.length < 1006) (hrun : s.halt = .Running) :
    runInstrSeq (leftTemplate j constant)
      (quadHelperEntry s startPC p0 p1 p2 p3 returnPC
        r0 r1 r2 r3 working (mask :: rho)) =
    Option.map (fun out => {out with pc := pcAfter startPC (leftTemplate j constant)})
      (runInstrSeq (CachedMaskHelper.leftTemplate j constant)
        (quadHelperEntry s startPC p0 p1 p2 p3 returnPC
          r0 r1 r2 r3 working (mask :: rho))) := by
  have hcap (m : Nat) (hm : m ≤ 18) : rho.length + m < 1024 := by omega
  have hadd (u v : UInt256) : u.add v = u + v := rfl
  have hassoc (u v w : UInt256) : (u + v) + w = u + (v + w) := by
    apply Word.word_ext
    change ((u.val + v.val) + w.val).val = (u.val + (v.val + w.val)).val
    simp [Fin.add_def, Nat.add_assoc]
  have hpc (u : UInt256) (a b : Nat) :
      (u + UInt256.ofNat a) + UInt256.ofNat b =
        u + UInt256.ofNat (a + b) := by
    rw [hassoc, Word.ofNat_add_mod]
  interval_cases j <;>
    simp (config := { maxSteps := 5000000 })
      [leftTemplate, leftTemplate0, leftTemplate1, leftTemplate2,
       leftTemplate3, leftTemplate4, CachedMaskHelper.leftTemplate,
       quadHelperEntry, roundWords,
       runInstrSeq, Stepper.runInstr, pcAfter, List.exchange,
       hrun, hcap, UInt256.succ, Instr.size, Instr.size_op, Instr.size_push,
       State.activeWordsAfterUInt256, hadd, Word.word_add_comm, hpc,
       Word.ofNat_add_mod, Word.word_toNat_ofNat, Nat.add_assoc]

set_option linter.unusedSimpArgs false in
theorem right_equiv (j : Nat) (hj : j < 5)
    (s : State) (startPC p0 p1 p2 p3 returnPC : UInt256)
    (r0 r1 r2 r3 : Nat) (constant : UInt256)
    (working : Compression.EvmWorking) (a b c d e : UInt256)
    (rho : List UInt256)
    (hstack : rho.length < 1001) (hrun : s.halt = .Running) :
    runInstrSeq (rightTemplate j constant)
      (quadHelperEntry s startPC p0 p1 p2 p3 returnPC
        r0 r1 r2 r3 working (a :: b :: c :: d :: e :: mask :: rho)) =
    Option.map (fun out => {out with pc := pcAfter startPC (rightTemplate j constant)})
      (runInstrSeq (CachedMaskHelper.rightTemplate j constant)
        (quadHelperEntry s startPC p0 p1 p2 p3 returnPC
          r0 r1 r2 r3 working (a :: b :: c :: d :: e :: mask :: rho))) := by
  have hcap (m : Nat) (hm : m ≤ 23) : rho.length + m < 1024 := by omega
  have hadd (u v : UInt256) : u.add v = u + v := rfl
  have hassoc (u v w : UInt256) : (u + v) + w = u + (v + w) := by
    apply Word.word_ext
    change ((u.val + v.val) + w.val).val = (u.val + (v.val + w.val)).val
    simp [Fin.add_def, Nat.add_assoc]
  have hpc (u : UInt256) (a b : Nat) :
      (u + UInt256.ofNat a) + UInt256.ofNat b =
        u + UInt256.ofNat (a + b) := by
    rw [hassoc, Word.ofNat_add_mod]
  interval_cases j <;>
    simp (config := { maxSteps := 5000000 })
      [rightTemplate, rightTemplate0, rightTemplate1, rightTemplate2,
       rightTemplate3, rightTemplate4, CachedMaskHelper.rightTemplate,
       quadHelperEntry, roundWords,
       runInstrSeq, Stepper.runInstr, pcAfter, List.exchange,
       hrun, hcap, UInt256.succ, Instr.size, Instr.size_op, Instr.size_push,
       State.activeWordsAfterUInt256, hadd, Word.word_add_comm, hpc,
       Word.ofNat_add_mod, Word.word_toNat_ofNat, Nat.add_assoc]

theorem run_left (j : Nat) (hj : j < 5)
    (s : State) (startPC p0 p1 p2 p3 returnPC : UInt256)
    (r0 r1 r2 r3 : Nat) (working : Compression.EvmWorking)
    (constant : UInt256) (rho : List UInt256)
    (hzero : j = 0 → constant = 0)
    (hstack : rho.length < 1006) (hrun : s.halt = .Running)
    (hrot0 : r0 ≤ 32) (hrot1 : r1 ≤ 32)
    (hrot2 : r2 ≤ 32) (hrot3 : r3 ≤ 32) :
    runInstrSeq (leftTemplate j constant)
      (quadHelperEntry s startPC p0 p1 p2 p3 returnPC
        r0 r1 r2 r3 working (mask :: rho)) =
      some (quadAfterHelperBeforeJump s (pcAfter startPC (leftTemplate j constant))
        returnPC j working p0 p1 p2 p3 r0 r1 r2 r3 constant (mask :: rho)) := by
  rw [left_equiv j hj s startPC p0 p1 p2 p3 returnPC r0 r1 r2 r3
    constant working rho hstack hrun]
  rw [CachedMaskHelper.run_left j hj s startPC p0 p1 p2 p3 returnPC
    r0 r1 r2 r3 working constant rho hzero hstack hrun
    hrot0 hrot1 hrot2 hrot3]
  rfl

theorem run_right (j : Nat) (hj : j < 5)
    (s : State) (startPC p0 p1 p2 p3 returnPC : UInt256)
    (r0 r1 r2 r3 : Nat) (working : Compression.EvmWorking)
    (constant a b c d e : UInt256) (rho : List UInt256)
    (hzero : j = 0 → constant = 0)
    (hstack : rho.length < 1001) (hrun : s.halt = .Running)
    (hrot0 : r0 ≤ 32) (hrot1 : r1 ≤ 32)
    (hrot2 : r2 ≤ 32) (hrot3 : r3 ≤ 32) :
    runInstrSeq (rightTemplate j constant)
      (quadHelperEntry s startPC p0 p1 p2 p3 returnPC
        r0 r1 r2 r3 working (a :: b :: c :: d :: e :: mask :: rho)) =
      some (quadAfterHelperBeforeJump s (pcAfter startPC (rightTemplate j constant))
        returnPC j working p0 p1 p2 p3 r0 r1 r2 r3 constant
          (a :: b :: c :: d :: e :: mask :: rho)) := by
  rw [right_equiv j hj s startPC p0 p1 p2 p3 returnPC r0 r1 r2 r3
    constant working a b c d e rho hstack hrun]
  rw [CachedMaskHelper.run_right j hj s startPC p0 p1 p2 p3 returnPC
    r0 r1 r2 r3 working constant a b c d e rho hzero hstack hrun
    hrot0 hrot1 hrot2 hrot3]
  rfl

set_option linter.unusedSimpArgs false in
theorem left_advances (j : Nat) (hj : j < 5) (constant : UInt256) :
    ∀ instruction ∈ leftTemplate j constant,
      PairMultiplyLift.Advances instruction := by
  intro instruction hmem
  interval_cases j <;>
    simp [leftTemplate, leftTemplate0, leftTemplate1, leftTemplate2,
      leftTemplate3, leftTemplate4] at hmem <;>
    simp_all [PairMultiplyLift.Advances, SharedCallTrace.Advances] <;>
    aesop (add safe constructors StraightLine)

set_option linter.unusedSimpArgs false in
theorem right_advances (j : Nat) (hj : j < 5) (constant : UInt256) :
    ∀ instruction ∈ rightTemplate j constant,
      PairMultiplyLift.Advances instruction := by
  intro instruction hmem
  interval_cases j <;>
    simp [rightTemplate, rightTemplate0, rightTemplate1, rightTemplate2,
      rightTemplate3, rightTemplate4] at hmem <;>
    simp_all [PairMultiplyLift.Advances, SharedCallTrace.Advances] <;>
    aesop (add safe constructors StraightLine)

#print axioms left_equiv
#print axioms right_equiv
#print axioms run_left
#print axioms run_right
#print axioms left_advances
#print axioms right_advances

end Challenge.Ripemd160.Submission.Proofs.Bytecode.CachedMaskHoistHelper

