import Challenge.Ripemd160.Submission.Proofs.Bytecode.ConstpropQuad

set_option warningAsError true
set_option maxRecDepth 50000
set_option maxHeartbeats 8000000

namespace Challenge.Ripemd160.Submission.Proofs.Bytecode.CachedMaskHelper

open EvmSemantics EvmSemantics.EVM YulEvmCompiler Challenge.EvmProof
open StackRoundTemplate StackRoundTrace QuadRoundState QuadRoundTemplate
open PairRoundTemplate QuadGapTemplate

def leftTemplate (j : Nat) (constant : UInt256) : List Instr :=
  match j with
  | 0 =>
    [.op .JUMPDEST,
     .op .MLOAD,
     .op (.Dup ⟨10, by decide⟩),
     .op (.Dup ⟨12, by decide⟩),
     .op .XOR,
     .op (.Dup ⟨13, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op (.Swap ⟨0, by decide⟩),
     .op (.Swap ⟨8, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨14, by decide⟩),
     .op .AND,
     .op (.Dup ⟨13, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨11, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨13, by decide⟩),
     .op .AND,
     .op (.Swap ⟨8, by decide⟩),
     .op (.Dup ⟨12, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨9, by decide⟩),
     .op (.Dup ⟨9, by decide⟩),
     .op .XOR,
     .op (.Dup ⟨2, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op (.Swap ⟨0, by decide⟩),
     .op (.Swap ⟨10, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨12, by decide⟩),
     .op .AND,
     .op (.Dup ⟨11, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨8, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨11, by decide⟩),
     .op .AND,
     .op (.Swap ⟨5, by decide⟩),
     .op (.Dup ⟨10, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨7, by decide⟩),
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨6, by decide⟩),
     .op (.Dup ⟨8, by decide⟩),
     .op .XOR,
     .op (.Dup ⟨9, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op .ADD,
     .op (.Dup ⟨10, by decide⟩),
     .op .AND,
     .op (.Dup ⟨9, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨7, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨9, by decide⟩),
     .op .AND,
     .op (.Swap ⟨4, by decide⟩),
     .op (.Dup ⟨8, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨5, by decide⟩),
     .op (.Dup ⟨5, by decide⟩),
     .op .XOR,
     .op (.Dup ⟨2, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op (.Swap ⟨0, by decide⟩),
     .op (.Swap ⟨6, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨8, by decide⟩),
     .op .AND,
     .op (.Dup ⟨7, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨4, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨7, by decide⟩),
     .op .AND,
     .op (.Swap ⟨1, by decide⟩),
     .op (.Dup ⟨6, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨3, by decide⟩),
     .op (.Swap ⟨0, by decide⟩)]
  | 1 =>
    [.op .JUMPDEST,
     .op .MLOAD,
     .op (.Dup ⟨11, by decide⟩),
     .op (.Dup ⟨13, by decide⟩),
     .op .XOR,
     .op (.Dup ⟨11, by decide⟩),
     .op .AND,
     .op (.Dup ⟨13, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op (.Swap ⟨0, by decide⟩),
     .op (.Swap ⟨8, by decide⟩),
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .op (.Dup ⟨14, by decide⟩),
     .op .AND,
     .op (.Dup ⟨13, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨11, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨13, by decide⟩),
     .op .AND,
     .op (.Swap ⟨8, by decide⟩),
     .op (.Dup ⟨12, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨8, by decide⟩),
     .op (.Dup ⟨2, by decide⟩),
     .op .XOR,
     .op (.Dup ⟨10, by decide⟩),
     .op .AND,
     .op (.Dup ⟨2, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op (.Swap ⟨0, by decide⟩),
     .op (.Swap ⟨10, by decide⟩),
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .op (.Dup ⟨12, by decide⟩),
     .op .AND,
     .op (.Dup ⟨11, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨8, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨11, by decide⟩),
     .op .AND,
     .op (.Swap ⟨5, by decide⟩),
     .op (.Dup ⟨10, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨7, by decide⟩),
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨7, by decide⟩),
     .op (.Dup ⟨9, by decide⟩),
     .op .XOR,
     .op (.Dup ⟨7, by decide⟩),
     .op .AND,
     .op (.Dup ⟨9, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .op (.Dup ⟨10, by decide⟩),
     .op .AND,
     .op (.Dup ⟨9, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨7, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨9, by decide⟩),
     .op .AND,
     .op (.Swap ⟨4, by decide⟩),
     .op (.Dup ⟨8, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨4, by decide⟩),
     .op (.Dup ⟨2, by decide⟩),
     .op .XOR,
     .op (.Dup ⟨6, by decide⟩),
     .op .AND,
     .op (.Dup ⟨2, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op (.Swap ⟨0, by decide⟩),
     .op (.Swap ⟨6, by decide⟩),
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .op (.Dup ⟨8, by decide⟩),
     .op .AND,
     .op (.Dup ⟨7, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨4, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨7, by decide⟩),
     .op .AND,
     .op (.Swap ⟨1, by decide⟩),
     .op (.Dup ⟨6, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨3, by decide⟩),
     .op (.Swap ⟨0, by decide⟩)]
  | 2 =>
    [.op .JUMPDEST,
     .op .MLOAD,
     .op (.Dup ⟨11, by decide⟩),
     .op .NOT,
     .op (.Dup ⟨11, by decide⟩),
     .op .OR,
     .op (.Dup ⟨13, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op (.Swap ⟨0, by decide⟩),
     .op (.Swap ⟨8, by decide⟩),
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .op (.Dup ⟨14, by decide⟩),
     .op .AND,
     .op (.Dup ⟨13, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨11, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨13, by decide⟩),
     .op .AND,
     .op (.Swap ⟨8, by decide⟩),
     .op (.Dup ⟨12, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨8, by decide⟩),
     .op .NOT,
     .op (.Dup ⟨10, by decide⟩),
     .op .OR,
     .op (.Dup ⟨2, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op (.Swap ⟨0, by decide⟩),
     .op (.Swap ⟨10, by decide⟩),
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .op (.Dup ⟨12, by decide⟩),
     .op .AND,
     .op (.Dup ⟨11, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨8, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨11, by decide⟩),
     .op .AND,
     .op (.Swap ⟨5, by decide⟩),
     .op (.Dup ⟨10, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨7, by decide⟩),
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨7, by decide⟩),
     .op .NOT,
     .op (.Dup ⟨7, by decide⟩),
     .op .OR,
     .op (.Dup ⟨9, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .op (.Dup ⟨10, by decide⟩),
     .op .AND,
     .op (.Dup ⟨9, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨7, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨9, by decide⟩),
     .op .AND,
     .op (.Swap ⟨4, by decide⟩),
     .op (.Dup ⟨8, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨4, by decide⟩),
     .op .NOT,
     .op (.Dup ⟨6, by decide⟩),
     .op .OR,
     .op (.Dup ⟨2, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op (.Swap ⟨0, by decide⟩),
     .op (.Swap ⟨6, by decide⟩),
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .op (.Dup ⟨8, by decide⟩),
     .op .AND,
     .op (.Dup ⟨7, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨4, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨7, by decide⟩),
     .op .AND,
     .op (.Swap ⟨1, by decide⟩),
     .op (.Dup ⟨6, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨3, by decide⟩),
     .op (.Swap ⟨0, by decide⟩)]
  | 3 =>
    [.op .JUMPDEST,
     .op .MLOAD,
     .op (.Dup ⟨10, by decide⟩),
     .op (.Dup ⟨12, by decide⟩),
     .op .XOR,
     .op (.Dup ⟨13, by decide⟩),
     .op .AND,
     .op (.Dup ⟨12, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op (.Swap ⟨0, by decide⟩),
     .op (.Swap ⟨8, by decide⟩),
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .op (.Dup ⟨14, by decide⟩),
     .op .AND,
     .op (.Dup ⟨13, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨11, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨13, by decide⟩),
     .op .AND,
     .op (.Swap ⟨8, by decide⟩),
     .op (.Dup ⟨12, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨9, by decide⟩),
     .op (.Dup ⟨9, by decide⟩),
     .op .XOR,
     .op (.Dup ⟨2, by decide⟩),
     .op .AND,
     .op (.Dup ⟨9, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op (.Swap ⟨0, by decide⟩),
     .op (.Swap ⟨10, by decide⟩),
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .op (.Dup ⟨12, by decide⟩),
     .op .AND,
     .op (.Dup ⟨11, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨8, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨11, by decide⟩),
     .op .AND,
     .op (.Swap ⟨5, by decide⟩),
     .op (.Dup ⟨10, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨7, by decide⟩),
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨6, by decide⟩),
     .op (.Dup ⟨8, by decide⟩),
     .op .XOR,
     .op (.Dup ⟨9, by decide⟩),
     .op .AND,
     .op (.Dup ⟨8, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .op (.Dup ⟨10, by decide⟩),
     .op .AND,
     .op (.Dup ⟨9, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨7, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨9, by decide⟩),
     .op .AND,
     .op (.Swap ⟨4, by decide⟩),
     .op (.Dup ⟨8, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨5, by decide⟩),
     .op (.Dup ⟨5, by decide⟩),
     .op .XOR,
     .op (.Dup ⟨2, by decide⟩),
     .op .AND,
     .op (.Dup ⟨5, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op (.Swap ⟨0, by decide⟩),
     .op (.Swap ⟨6, by decide⟩),
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .op (.Dup ⟨8, by decide⟩),
     .op .AND,
     .op (.Dup ⟨7, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨4, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨7, by decide⟩),
     .op .AND,
     .op (.Swap ⟨1, by decide⟩),
     .op (.Dup ⟨6, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨3, by decide⟩),
     .op (.Swap ⟨0, by decide⟩)]
  | _ =>
    [.op .JUMPDEST,
     .op .MLOAD,
     .op (.Dup ⟨12, by decide⟩),
     .op .NOT,
     .op (.Dup ⟨12, by decide⟩),
     .op .OR,
     .op (.Dup ⟨11, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op (.Swap ⟨0, by decide⟩),
     .op (.Swap ⟨8, by decide⟩),
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .op (.Dup ⟨14, by decide⟩),
     .op .AND,
     .op (.Dup ⟨13, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨11, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨13, by decide⟩),
     .op .AND,
     .op (.Swap ⟨8, by decide⟩),
     .op (.Dup ⟨12, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨1, by decide⟩),
     .op .NOT,
     .op (.Dup ⟨9, by decide⟩),
     .op .OR,
     .op (.Dup ⟨10, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op (.Swap ⟨0, by decide⟩),
     .op (.Swap ⟨10, by decide⟩),
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .op (.Dup ⟨12, by decide⟩),
     .op .AND,
     .op (.Dup ⟨11, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨8, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨11, by decide⟩),
     .op .AND,
     .op (.Swap ⟨5, by decide⟩),
     .op (.Dup ⟨10, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨7, by decide⟩),
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨8, by decide⟩),
     .op .NOT,
     .op (.Dup ⟨8, by decide⟩),
     .op .OR,
     .op (.Dup ⟨7, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .op (.Dup ⟨10, by decide⟩),
     .op .AND,
     .op (.Dup ⟨9, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨7, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨9, by decide⟩),
     .op .AND,
     .op (.Swap ⟨4, by decide⟩),
     .op (.Dup ⟨8, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨1, by decide⟩),
     .op .NOT,
     .op (.Dup ⟨5, by decide⟩),
     .op .OR,
     .op (.Dup ⟨6, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op (.Swap ⟨0, by decide⟩),
     .op (.Swap ⟨6, by decide⟩),
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .op (.Dup ⟨8, by decide⟩),
     .op .AND,
     .op (.Dup ⟨7, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨4, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨7, by decide⟩),
     .op .AND,
     .op (.Swap ⟨1, by decide⟩),
     .op (.Dup ⟨6, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨3, by decide⟩),
     .op (.Swap ⟨0, by decide⟩)]

def rightTemplate (j : Nat) (constant : UInt256) : List Instr :=
  match j with
  | 0 =>
    [.op .JUMPDEST,
     .op .MLOAD,
     .op (.Dup ⟨10, by decide⟩),
     .op (.Dup ⟨12, by decide⟩),
     .op .XOR,
     .op (.Dup ⟨13, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op (.Swap ⟨0, by decide⟩),
     .op (.Swap ⟨8, by decide⟩),
     .op .ADD,
     .push 4 (UInt256.ofNat 4294967295),
     .op .AND,
     .op (.Dup ⟨13, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨11, by decide⟩),
     .op .ADD,
     .push 4 (UInt256.ofNat 4294967295),
     .op .AND,
     .op (.Swap ⟨8, by decide⟩),
     .op (.Dup ⟨12, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨9, by decide⟩),
     .op (.Dup ⟨9, by decide⟩),
     .op .XOR,
     .op (.Dup ⟨2, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op (.Swap ⟨0, by decide⟩),
     .op (.Swap ⟨10, by decide⟩),
     .op .ADD,
     .push 4 (UInt256.ofNat 4294967295),
     .op .AND,
     .op (.Dup ⟨11, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨8, by decide⟩),
     .op .ADD,
     .push 4 (UInt256.ofNat 4294967295),
     .op .AND,
     .op (.Swap ⟨5, by decide⟩),
     .op (.Dup ⟨10, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨7, by decide⟩),
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨6, by decide⟩),
     .op (.Dup ⟨8, by decide⟩),
     .op .XOR,
     .op (.Dup ⟨9, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op .ADD,
     .op (.Dup ⟨15, by decide⟩),
     .op .AND,
     .op (.Dup ⟨9, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨7, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨14, by decide⟩),
     .op .AND,
     .op (.Swap ⟨4, by decide⟩),
     .op (.Dup ⟨8, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨5, by decide⟩),
     .op (.Dup ⟨5, by decide⟩),
     .op .XOR,
     .op (.Dup ⟨2, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op (.Swap ⟨0, by decide⟩),
     .op (.Swap ⟨6, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨13, by decide⟩),
     .op .AND,
     .op (.Dup ⟨7, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨4, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨12, by decide⟩),
     .op .AND,
     .op (.Swap ⟨1, by decide⟩),
     .op (.Dup ⟨6, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨3, by decide⟩),
     .op (.Swap ⟨0, by decide⟩)]
  | 1 =>
    [.op .JUMPDEST,
     .op .MLOAD,
     .op (.Dup ⟨11, by decide⟩),
     .op (.Dup ⟨13, by decide⟩),
     .op .XOR,
     .op (.Dup ⟨11, by decide⟩),
     .op .AND,
     .op (.Dup ⟨13, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op (.Swap ⟨0, by decide⟩),
     .op (.Swap ⟨8, by decide⟩),
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .push 4 (UInt256.ofNat 4294967295),
     .op .AND,
     .op (.Dup ⟨13, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨11, by decide⟩),
     .op .ADD,
     .push 4 (UInt256.ofNat 4294967295),
     .op .AND,
     .op (.Swap ⟨8, by decide⟩),
     .op (.Dup ⟨12, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨8, by decide⟩),
     .op (.Dup ⟨2, by decide⟩),
     .op .XOR,
     .op (.Dup ⟨10, by decide⟩),
     .op .AND,
     .op (.Dup ⟨2, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op (.Swap ⟨0, by decide⟩),
     .op (.Swap ⟨10, by decide⟩),
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .push 4 (UInt256.ofNat 4294967295),
     .op .AND,
     .op (.Dup ⟨11, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨8, by decide⟩),
     .op .ADD,
     .push 4 (UInt256.ofNat 4294967295),
     .op .AND,
     .op (.Swap ⟨5, by decide⟩),
     .op (.Dup ⟨10, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨7, by decide⟩),
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨7, by decide⟩),
     .op (.Dup ⟨9, by decide⟩),
     .op .XOR,
     .op (.Dup ⟨7, by decide⟩),
     .op .AND,
     .op (.Dup ⟨9, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .op (.Dup ⟨15, by decide⟩),
     .op .AND,
     .op (.Dup ⟨9, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨7, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨14, by decide⟩),
     .op .AND,
     .op (.Swap ⟨4, by decide⟩),
     .op (.Dup ⟨8, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨4, by decide⟩),
     .op (.Dup ⟨2, by decide⟩),
     .op .XOR,
     .op (.Dup ⟨6, by decide⟩),
     .op .AND,
     .op (.Dup ⟨2, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op (.Swap ⟨0, by decide⟩),
     .op (.Swap ⟨6, by decide⟩),
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .op (.Dup ⟨13, by decide⟩),
     .op .AND,
     .op (.Dup ⟨7, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨4, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨12, by decide⟩),
     .op .AND,
     .op (.Swap ⟨1, by decide⟩),
     .op (.Dup ⟨6, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨3, by decide⟩),
     .op (.Swap ⟨0, by decide⟩)]
  | 2 =>
    [.op .JUMPDEST,
     .op .MLOAD,
     .op (.Dup ⟨11, by decide⟩),
     .op .NOT,
     .op (.Dup ⟨11, by decide⟩),
     .op .OR,
     .op (.Dup ⟨13, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op (.Swap ⟨0, by decide⟩),
     .op (.Swap ⟨8, by decide⟩),
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .push 4 (UInt256.ofNat 4294967295),
     .op .AND,
     .op (.Dup ⟨13, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨11, by decide⟩),
     .op .ADD,
     .push 4 (UInt256.ofNat 4294967295),
     .op .AND,
     .op (.Swap ⟨8, by decide⟩),
     .op (.Dup ⟨12, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨8, by decide⟩),
     .op .NOT,
     .op (.Dup ⟨10, by decide⟩),
     .op .OR,
     .op (.Dup ⟨2, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op (.Swap ⟨0, by decide⟩),
     .op (.Swap ⟨10, by decide⟩),
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .push 4 (UInt256.ofNat 4294967295),
     .op .AND,
     .op (.Dup ⟨11, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨8, by decide⟩),
     .op .ADD,
     .push 4 (UInt256.ofNat 4294967295),
     .op .AND,
     .op (.Swap ⟨5, by decide⟩),
     .op (.Dup ⟨10, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨7, by decide⟩),
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨7, by decide⟩),
     .op .NOT,
     .op (.Dup ⟨7, by decide⟩),
     .op .OR,
     .op (.Dup ⟨9, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .op (.Dup ⟨15, by decide⟩),
     .op .AND,
     .op (.Dup ⟨9, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨7, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨14, by decide⟩),
     .op .AND,
     .op (.Swap ⟨4, by decide⟩),
     .op (.Dup ⟨8, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨4, by decide⟩),
     .op .NOT,
     .op (.Dup ⟨6, by decide⟩),
     .op .OR,
     .op (.Dup ⟨2, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op (.Swap ⟨0, by decide⟩),
     .op (.Swap ⟨6, by decide⟩),
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .op (.Dup ⟨13, by decide⟩),
     .op .AND,
     .op (.Dup ⟨7, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨4, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨12, by decide⟩),
     .op .AND,
     .op (.Swap ⟨1, by decide⟩),
     .op (.Dup ⟨6, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨3, by decide⟩),
     .op (.Swap ⟨0, by decide⟩)]
  | 3 =>
    [.op .JUMPDEST,
     .op .MLOAD,
     .op (.Dup ⟨10, by decide⟩),
     .op (.Dup ⟨12, by decide⟩),
     .op .XOR,
     .op (.Dup ⟨13, by decide⟩),
     .op .AND,
     .op (.Dup ⟨12, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op (.Swap ⟨0, by decide⟩),
     .op (.Swap ⟨8, by decide⟩),
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .push 4 (UInt256.ofNat 4294967295),
     .op .AND,
     .op (.Dup ⟨13, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨11, by decide⟩),
     .op .ADD,
     .push 4 (UInt256.ofNat 4294967295),
     .op .AND,
     .op (.Swap ⟨8, by decide⟩),
     .op (.Dup ⟨12, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨9, by decide⟩),
     .op (.Dup ⟨9, by decide⟩),
     .op .XOR,
     .op (.Dup ⟨2, by decide⟩),
     .op .AND,
     .op (.Dup ⟨9, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op (.Swap ⟨0, by decide⟩),
     .op (.Swap ⟨10, by decide⟩),
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .push 4 (UInt256.ofNat 4294967295),
     .op .AND,
     .op (.Dup ⟨11, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨8, by decide⟩),
     .op .ADD,
     .push 4 (UInt256.ofNat 4294967295),
     .op .AND,
     .op (.Swap ⟨5, by decide⟩),
     .op (.Dup ⟨10, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨7, by decide⟩),
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨6, by decide⟩),
     .op (.Dup ⟨8, by decide⟩),
     .op .XOR,
     .op (.Dup ⟨9, by decide⟩),
     .op .AND,
     .op (.Dup ⟨8, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .op (.Dup ⟨15, by decide⟩),
     .op .AND,
     .op (.Dup ⟨9, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨7, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨14, by decide⟩),
     .op .AND,
     .op (.Swap ⟨4, by decide⟩),
     .op (.Dup ⟨8, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨5, by decide⟩),
     .op (.Dup ⟨5, by decide⟩),
     .op .XOR,
     .op (.Dup ⟨2, by decide⟩),
     .op .AND,
     .op (.Dup ⟨5, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op (.Swap ⟨0, by decide⟩),
     .op (.Swap ⟨6, by decide⟩),
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .op (.Dup ⟨13, by decide⟩),
     .op .AND,
     .op (.Dup ⟨7, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨4, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨12, by decide⟩),
     .op .AND,
     .op (.Swap ⟨1, by decide⟩),
     .op (.Dup ⟨6, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨3, by decide⟩),
     .op (.Swap ⟨0, by decide⟩)]
  | _ =>
    [.op .JUMPDEST,
     .op .MLOAD,
     .op (.Dup ⟨12, by decide⟩),
     .op .NOT,
     .op (.Dup ⟨12, by decide⟩),
     .op .OR,
     .op (.Dup ⟨11, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op (.Swap ⟨0, by decide⟩),
     .op (.Swap ⟨8, by decide⟩),
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .push 4 (UInt256.ofNat 4294967295),
     .op .AND,
     .op (.Dup ⟨13, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨11, by decide⟩),
     .op .ADD,
     .push 4 (UInt256.ofNat 4294967295),
     .op .AND,
     .op (.Swap ⟨8, by decide⟩),
     .op (.Dup ⟨12, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨1, by decide⟩),
     .op .NOT,
     .op (.Dup ⟨9, by decide⟩),
     .op .OR,
     .op (.Dup ⟨10, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op (.Swap ⟨0, by decide⟩),
     .op (.Swap ⟨10, by decide⟩),
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .push 4 (UInt256.ofNat 4294967295),
     .op .AND,
     .op (.Dup ⟨11, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨8, by decide⟩),
     .op .ADD,
     .push 4 (UInt256.ofNat 4294967295),
     .op .AND,
     .op (.Swap ⟨5, by decide⟩),
     .op (.Dup ⟨10, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨7, by decide⟩),
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨8, by decide⟩),
     .op .NOT,
     .op (.Dup ⟨8, by decide⟩),
     .op .OR,
     .op (.Dup ⟨7, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .op (.Dup ⟨15, by decide⟩),
     .op .AND,
     .op (.Dup ⟨9, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨7, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨14, by decide⟩),
     .op .AND,
     .op (.Swap ⟨4, by decide⟩),
     .op (.Dup ⟨8, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨0, by decide⟩),
     .op .MLOAD,
     .op (.Dup ⟨1, by decide⟩),
     .op .NOT,
     .op (.Dup ⟨5, by decide⟩),
     .op .OR,
     .op (.Dup ⟨6, by decide⟩),
     .op .XOR,
     .op .ADD,
     .op (.Swap ⟨0, by decide⟩),
     .op (.Swap ⟨6, by decide⟩),
     .op .ADD,
     .push 4 constant,
     .op .ADD,
     .op (.Dup ⟨13, by decide⟩),
     .op .AND,
     .op (.Dup ⟨7, by decide⟩),
     .op .MUL,
     .op (.Swap ⟨0, by decide⟩),
     .op .SHR,
     .op (.Dup ⟨4, by decide⟩),
     .op .ADD,
     .op (.Dup ⟨12, by decide⟩),
     .op .AND,
     .op (.Swap ⟨1, by decide⟩),
     .op (.Dup ⟨6, by decide⟩),
     .op .MUL,
     .push 1 (UInt256.ofNat 22),
     .op .SHR,
     .op (.Swap ⟨3, by decide⟩),
     .op (.Swap ⟨0, by decide⟩)]

set_option linter.unusedSimpArgs false in
theorem left_equiv (j : Nat) (hj : j < 5)
    (s : State) (startPC p0 p1 p2 p3 returnPC : UInt256)
    (r0 r1 r2 r3 : Nat) (constant : UInt256)
    (working : Compression.EvmWorking) (rho : List UInt256)
    (hstack : rho.length < 1006) (hrun : s.halt = .Running) :
    runInstrSeq (leftTemplate j constant)
      (quadHelperEntry s startPC p0 p1 p2 p3 returnPC
        r0 r1 r2 r3 working (mask :: rho)) =
    Option.map
      (fun out => {out with pc := pcAfter startPC (leftTemplate j constant)})
      (runInstrSeq (quadBeforeJumpTemplate j constant)
        (quadHelperEntry s startPC p0 p1 p2 p3 returnPC
          r0 r1 r2 r3 working (mask :: rho))) := by
  have hcap (m : Nat) (hm : m ≤ 18) : rho.length + m < 1024 := by omega
  have hadd (u v : UInt256) : u.add v = u + v := rfl
  interval_cases j <;> simp (config := { maxSteps := 3000000 })
    [leftTemplate, quadBeforeJumpTemplate, firstFTemplate, cachedTailFTemplate,
     firstBoolean, secondBoolean, QuadGapTemplate.d, QuadGapTemplate.w,
     pairFirstBooleanOps, pairSecondBooleanOps,
     pairDup7, pairDup8, pairDup9, pairDup10, pairSwap5, pairSwap7,
     cachedQrot10, cachedCfold9, cachedQrot8, cachedCfold7,
     cachedDup10, cachedDup9, cachedDup8, cachedDup7,
     quadHelperEntry, roundEntry, roundWords, op, push1, push4, c22, mask,
     dup1, dup2, dup3, dup4, dup5, dup6, swap1, swap2, swap3, swap4,
     runInstrSeq, Stepper.runInstr, pcAfter, List.exchange,
     hrun, hcap, UInt256.succ, Instr.size, Instr.size_op, Instr.size_push,
     State.activeWordsAfterUInt256, hadd, Word.ofNat_add_mod,
     Word.word_toNat_ofNat, Nat.add_assoc, Word.word_add_comm]

set_option linter.unusedSimpArgs false in
theorem right_equiv (j : Nat) (hj : j < 5)
    (s : State) (startPC p0 p1 p2 p3 returnPC : UInt256)
    (r0 r1 r2 r3 : Nat) (constant : UInt256)
    (working : Compression.EvmWorking) (a b c d e : UInt256) (rho : List UInt256)
    (hstack : rho.length < 1001) (hrun : s.halt = .Running) :
    runInstrSeq (rightTemplate j constant)
      (quadHelperEntry s startPC p0 p1 p2 p3 returnPC
        r0 r1 r2 r3 working (a :: b :: c :: d :: e :: mask :: rho)) =
    Option.map
      (fun out => {out with pc := pcAfter startPC (rightTemplate j constant)})
      (runInstrSeq (quadBeforeJumpTemplate j constant)
        (quadHelperEntry s startPC p0 p1 p2 p3 returnPC
          r0 r1 r2 r3 working (a :: b :: c :: d :: e :: mask :: rho))) := by
  have hcap (m : Nat) (hm : m ≤ 23) : rho.length + m < 1024 := by omega
  have hadd (u v : UInt256) : u.add v = u + v := rfl
  interval_cases j <;> simp (config := { maxSteps := 3000000 })
    [rightTemplate, quadBeforeJumpTemplate, firstFTemplate, cachedTailFTemplate,
     firstBoolean, secondBoolean, QuadGapTemplate.d, QuadGapTemplate.w,
     pairFirstBooleanOps, pairSecondBooleanOps,
     pairDup7, pairDup8, pairDup9, pairDup10, pairSwap5, pairSwap7,
     cachedQrot10, cachedCfold9, cachedQrot8, cachedCfold7,
     cachedDup10, cachedDup9, cachedDup8, cachedDup7,
     quadHelperEntry, roundEntry, roundWords, op, push1, push4, c22, mask,
     dup1, dup2, dup3, dup4, dup5, dup6, swap1, swap2, swap3, swap4,
     runInstrSeq, Stepper.runInstr, pcAfter, List.exchange,
     hrun, hcap, UInt256.succ, Instr.size, Instr.size_op, Instr.size_push,
     State.activeWordsAfterUInt256, hadd, Word.ofNat_add_mod,
     Word.word_toNat_ofNat, Nat.add_assoc, Word.word_add_comm]

theorem run_left (j : Nat) (hj : j < 5)
    (s : State) (startPC p0 p1 p2 p3 returnPC : UInt256)
    (r0 r1 r2 r3 : Nat) (working : Compression.EvmWorking)
    (constant : UInt256) (rho : List UInt256)
    (hzero : j = 0 → constant = 0)
    (hstack : rho.length < 1006) (hrun : s.halt = .Running)
    (hrot0 : r0 ≤ 32) (hrot1 : r1 ≤ 32)
    (hrot2 : r2 ≤ 32) (hrot3 : r3 ≤ 32) :
    runInstrSeq (leftTemplate j constant)
      (quadHelperEntry s startPC p0 p1 p2 p3 returnPC
        r0 r1 r2 r3 working (mask :: rho)) =
      some (quadAfterHelperBeforeJump s (pcAfter startPC (leftTemplate j constant))
        returnPC j working p0 p1 p2 p3 r0 r1 r2 r3 constant (mask :: rho)) := by
  rw [left_equiv j hj s startPC p0 p1 p2 p3 returnPC r0 r1 r2 r3
    constant working rho hstack hrun]
  rw [QuadRoundTrace.runInstrSeq_quad j hj s startPC p0 p1 p2 p3 returnPC
    r0 r1 r2 r3 working constant (mask :: rho) hzero
    (by simp only [List.length_cons]; omega) hrun hrot0 hrot1 hrot2 hrot3]
  rfl

theorem run_right (j : Nat) (hj : j < 5)
    (s : State) (startPC p0 p1 p2 p3 returnPC : UInt256)
    (r0 r1 r2 r3 : Nat) (working : Compression.EvmWorking)
    (constant a b c d e : UInt256) (rho : List UInt256)
    (hzero : j = 0 → constant = 0)
    (hstack : rho.length < 1001) (hrun : s.halt = .Running)
    (hrot0 : r0 ≤ 32) (hrot1 : r1 ≤ 32)
    (hrot2 : r2 ≤ 32) (hrot3 : r3 ≤ 32) :
    runInstrSeq (rightTemplate j constant)
      (quadHelperEntry s startPC p0 p1 p2 p3 returnPC
        r0 r1 r2 r3 working (a :: b :: c :: d :: e :: mask :: rho)) =
      some (quadAfterHelperBeforeJump s (pcAfter startPC (rightTemplate j constant))
        returnPC j working p0 p1 p2 p3 r0 r1 r2 r3 constant
          (a :: b :: c :: d :: e :: mask :: rho)) := by
  rw [right_equiv j hj s startPC p0 p1 p2 p3 returnPC r0 r1 r2 r3
    constant working a b c d e rho hstack hrun]
  rw [QuadRoundTrace.runInstrSeq_quad j hj s startPC p0 p1 p2 p3 returnPC
    r0 r1 r2 r3 working constant (a :: b :: c :: d :: e :: mask :: rho) hzero
    (by simp only [List.length_cons]; omega) hrun hrot0 hrot1 hrot2 hrot3]
  rfl

set_option linter.unusedSimpArgs false in
theorem left_advances (j : Nat) (hj : j < 5) (constant : UInt256) :
    ∀ instruction ∈ leftTemplate j constant, PairMultiplyLift.Advances instruction := by
  intro instruction hmem
  interval_cases j <;> simp [leftTemplate] at hmem <;>
    simp_all [PairMultiplyLift.Advances, SharedCallTrace.Advances] <;>
    aesop (add safe constructors StraightLine)

set_option linter.unusedSimpArgs false in
theorem right_advances (j : Nat) (hj : j < 5) (constant : UInt256) :
    ∀ instruction ∈ rightTemplate j constant, PairMultiplyLift.Advances instruction := by
  intro instruction hmem
  interval_cases j <;> simp [rightTemplate] at hmem <;>
    simp_all [PairMultiplyLift.Advances, SharedCallTrace.Advances] <;>
    aesop (add safe constructors StraightLine)

/-- Exact located execution for any certified pure helper implementation. -/
theorem runLocated_of_raw {artifact : ProgramArtifact} {fork : Fork}
    (helperCode : List Instr)
    (hform : ∀ i ∈ helperCode, PairMultiplyLift.Advances i)
    (j : Nat) (p0 p1 p2 p3 : UInt256) (r0 r1 r2 r3 : Nat)
    (constant : UInt256) (site : GenericRoundSite artifact fork helperCode)
    (s : State) (returnPC : UInt256) (working : Compression.EvmWorking)
    (rho : List UInt256)
    (hraw : runInstrSeq helperCode
      (quadHelperEntry s site.startPC p0 p1 p2 p3 returnPC r0 r1 r2 r3 working rho) =
      some (quadAfterHelperBeforeJump s (pcAfter site.startPC helperCode)
        returnPC j working p0 p1 p2 p3 r0 r1 r2 r3 constant rho)) :
    Stepper.runLocatedBlock site.path
      (quadHelperEntry s site.startPC p0 p1 p2 p3 returnPC r0 r1 r2 r3 working rho) =
      some (quadAfterHelperBeforeJump s site.endPC
        returnPC j working p0 p1 p2 p3 r0 r1 r2 r3 constant rho) := by
  have hend : site.endPC = pcAfter site.startPC helperCode := by
    have h := endPC_eq_pcAfter_sites site.sites site.startPC site.endPC
      site.head_eq site.end_eq site.contiguous
    rwa [site.instruction_eq] at h
  rw [PairMultiplyLift.runLocatedBlock_eq_raw site hform
    (quadHelperEntry s site.startPC p0 p1 p2 p3 returnPC r0 r1 r2 r3 working rho) rfl]
  rw [hraw, ← hend]

def gasSteps_of_raw {artifact : ProgramArtifact} {fork : Fork}
    (helperCode : List Instr)
    (hform : ∀ i ∈ helperCode, PairMultiplyLift.Advances i)
    (j : Nat) (p0 p1 p2 p3 : UInt256) (r0 r1 r2 r3 : Nat)
    (constant : UInt256) (site : GenericRoundSite artifact fork helperCode)
    (s : State) (returnPC : UInt256) (working : Compression.EvmWorking)
    (rho : List UInt256)
    (hraw : runInstrSeq helperCode
      (quadHelperEntry s site.startPC p0 p1 p2 p3 returnPC r0 r1 r2 r3 working rho) =
      some (quadAfterHelperBeforeJump s (pcAfter site.startPC helperCode)
        returnPC j working p0 p1 p2 p3 r0 r1 r2 r3 constant rho))
    (hrun : s.halt = .Running) (hcode : s.executionEnv.code = artifact.code)
    (hfork : s.fork = fork)
    (hnp : Precompile.isPrecompileWithConfig s.executionEnv.precompileConfig
      s.executionEnv.fork s.executionEnv.codeAddr = false) :
    GasSteps
      (quadHelperEntry s site.startPC p0 p1 p2 p3 returnPC r0 r1 r2 r3 working rho)
      (quadAfterHelperBeforeJump s site.endPC
        returnPC j working p0 p1 p2 p3 r0 r1 r2 r3 constant rho) := by
  exact Stepper.runLocatedBlock_sound artifact fork site.path hcode hfork
    (runLocated_of_raw helperCode hform j p0 p1 p2 p3 r0 r1 r2 r3
      constant site s returnPC working rho hraw) hrun hnp

#print axioms left_equiv
#print axioms right_equiv
#print axioms run_left
#print axioms run_right
#print axioms left_advances
#print axioms right_advances
#print axioms gasSteps_of_raw

end Challenge.Ripemd160.Submission.Proofs.Bytecode.CachedMaskHelper
