import Challenge.Ripemd160.Submission.Proofs.Bytecode.DenseScheduleTemplate
import Init.Data.BitVec.Bitblast

set_option warningAsError true
set_option maxRecDepth 30000
set_option maxHeartbeats 10000000

/-!
# Multiplication-based endian stages

The dense schedule helper swaps adjacent 8-bit lanes and then adjacent
16-bit lanes.  Each stage forms the XOR difference in the low lane of each
pair.  Multiplication by `1 + 2^shift` copies that difference into both lanes;
XORing it back into the input therefore performs the same swap as the former
shift/AND/OR expression.

The two theorems here are deliberately independent of the generated bytecode
artifact.  They are fixed-width identities for exactly the two masks executed
by the helper.
-/

namespace Challenge.Ripemd160.Submission.Proofs.Bytecode.DenseEndianMultiply

open EvmSemantics
open Challenge.EvmProof
open Challenge.Ripemd160.Submission.Proofs.Bytecode.DenseScheduleTemplate

private def toBitVec (value : UInt256) : BitVec 256 :=
  BitVec.ofFin value.val

private theorem toBitVec_injective : Function.Injective toBitVec := by
  intro a b h
  cases a with
  | mk a =>
    cases b with
    | mk b =>
      cases h
      rfl

private theorem toBitVec_ofNat (value : Nat) :
    toBitVec (UInt256.ofNat value) = BitVec.ofNat 256 value := by
  rfl

private theorem toBitVec_xor (a b : UInt256) :
    toBitVec (UInt256.xor a b) = toBitVec a ^^^ toBitVec b := by
  apply BitVec.eq_of_toNat_eq
  change (UInt256.xor a b).toNat = _
  rw [BitVec.toNat_xor]
  change (a.val ^^^ b.val).val = a.toNat ^^^ b.toNat
  rw [Fin.xor_val]
  apply Nat.mod_eq_of_lt
  exact Nat.lt_of_lt_of_le
    (Nat.xor_lt_two_pow a.val.isLt b.val.isLt) (by rfl)

private theorem toBitVec_land (a b : UInt256) :
    toBitVec (UInt256.land a b) = toBitVec a &&& toBitVec b := by
  apply BitVec.eq_of_toNat_eq
  change (UInt256.land a b).toNat = _
  rw [Challenge.EvmProof.Word.word_toNat_land, BitVec.toNat_and]
  rfl

private theorem toBitVec_lor (a b : UInt256) :
    toBitVec (UInt256.lor a b) = toBitVec a ||| toBitVec b := by
  apply BitVec.eq_of_toNat_eq
  change (UInt256.lor a b).toNat = _
  rw [Challenge.EvmProof.Word.word_toNat_lor, BitVec.toNat_or]
  rfl

private theorem toBitVec_mul (a b : UInt256) :
    toBitVec (UInt256.mul a b) = toBitVec a * toBitVec b := by
  apply BitVec.eq_of_toNat_eq
  change (UInt256.mul a b).toNat = _
  rw [BitVec.toNat_mul]
  change (a.val * b.val).val = (a.toNat * b.toNat) % 2 ^ 256
  rw [Fin.val_mul]
  rfl

private theorem toBitVec_shr8 (a : UInt256) :
    toBitVec (UInt256.shiftRight a (UInt256.ofNat 8)) = toBitVec a >>> 8 := by
  apply BitVec.eq_of_toNat_eq
  change (UInt256.shiftRight a (UInt256.ofNat 8)).toNat = _
  rw [Challenge.EvmProof.Word.shiftRight_toNat a (by norm_num),
    BitVec.toNat_ushiftRight]
  rfl

private theorem toBitVec_shr16 (a : UInt256) :
    toBitVec (UInt256.shiftRight a (UInt256.ofNat 16)) = toBitVec a >>> 16 := by
  apply BitVec.eq_of_toNat_eq
  change (UInt256.shiftRight a (UInt256.ofNat 16)).toNat = _
  rw [Challenge.EvmProof.Word.shiftRight_toNat a (by norm_num),
    BitVec.toNat_ushiftRight]
  rfl

private theorem toBitVec_shl8 (a : UInt256) :
    toBitVec (UInt256.shiftLeft a (UInt256.ofNat 8)) = toBitVec a <<< 8 := by
  apply BitVec.eq_of_toNat_eq
  change (UInt256.shiftLeft a (UInt256.ofNat 8)).toNat = _
  rw [BitVec.toNat_shiftLeft]
  unfold UInt256.shiftLeft
  simp only [Challenge.EvmProof.Word.word_toNat_ofNat]
  norm_num
  change (a.toNat <<< 8) % UInt256.size % 2 ^ 256 =
    (a.toNat <<< 8) % 2 ^ 256
  rw [show UInt256.size = 2 ^ 256 by rfl, Nat.mod_mod]

private theorem toBitVec_shl16 (a : UInt256) :
    toBitVec (UInt256.shiftLeft a (UInt256.ofNat 16)) = toBitVec a <<< 16 := by
  apply BitVec.eq_of_toNat_eq
  change (UInt256.shiftLeft a (UInt256.ofNat 16)).toNat = _
  rw [BitVec.toNat_shiftLeft]
  unfold UInt256.shiftLeft
  simp only [Challenge.EvmProof.Word.word_toNat_ofNat]
  norm_num
  change (a.toNat <<< 16) % UInt256.size % 2 ^ 256 =
    (a.toNat <<< 16) % 2 ^ 256
  rw [show UInt256.size = 2 ^ 256 by rfl, Nat.mod_mod]

private theorem masked_disjoint (x mask : BitVec w) (shift : Nat)
    (h : (mask <<< shift) &&& mask = 0#w) :
    ((x &&& mask) <<< shift) &&& (x &&& mask) = 0#w := by
  rw [BitVec.shiftLeft_and_distrib]
  calc
    ((x <<< shift) &&& (mask <<< shift)) &&& (x &&& mask) =
        ((x <<< shift) &&& x) &&& ((mask <<< shift) &&& mask) := by
      ac_rfl
    _ = 0#w := by rw [h]; simp

set_option linter.unusedSimpArgs false in
private theorem endian8 (value : BitVec 256) :
    ((BitVec.ofNat 256 257) * (((value >>> 8) ^^^ value) &&&
      BitVec.ofNat 256 0x00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff)) ^^^ value =
    ((value &&& BitVec.ofNat 256 0x00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff) <<< 8) |||
      ((value >>> 8) &&& BitVec.ofNat 256 0x00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff) := by
  rw [show BitVec.ofNat 256 257 = BitVec.twoPow 256 8 + 1#256 by decide,
    BitVec.add_mul, BitVec.twoPow_mul_eq_shiftLeft, BitVec.one_mul]
  rw [BitVec.add_eq_or_of_and_eq_zero _ _ (masked_disjoint _ _ _ (by decide))]
  apply BitVec.eq_of_getLsbD_eq
  intro i hi
  interval_cases i <;>
    simp [BitVec.getLsbD_shiftLeft, BitVec.getLsbD_ushiftRight,
      BitVec.getLsbD_ofNat, Nat.testBit, Bool.xor_assoc, Bool.xor_comm,
      Bool.xor_left_comm]

set_option linter.unusedSimpArgs false in
private theorem endian16 (value : BitVec 256) :
    ((BitVec.ofNat 256 65537) * (((value >>> 16) ^^^ value) &&&
      BitVec.ofNat 256 0x0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff)) ^^^ value =
    ((value &&& BitVec.ofNat 256 0x0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff) <<< 16) |||
      ((value >>> 16) &&& BitVec.ofNat 256 0x0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff) := by
  rw [show BitVec.ofNat 256 65537 = BitVec.twoPow 256 16 + 1#256 by decide,
    BitVec.add_mul, BitVec.twoPow_mul_eq_shiftLeft, BitVec.one_mul]
  rw [BitVec.add_eq_or_of_and_eq_zero _ _ (masked_disjoint _ _ _ (by decide))]
  apply BitVec.eq_of_getLsbD_eq
  intro i hi
  interval_cases i <;>
    simp [BitVec.getLsbD_shiftLeft, BitVec.getLsbD_ushiftRight,
      BitVec.getLsbD_ofNat, Nat.testBit, Bool.xor_assoc, Bool.xor_comm,
      Bool.xor_left_comm]

theorem multipliedStage8_eq_packedStage (value : UInt256) :
    multipliedStage value 8 mask8 = packedStage value 8 mask8 := by
  apply toBitVec_injective
  simp only [multipliedStage, endianDelta, endianFactor, packedStage,
    toBitVec_xor, toBitVec_land, toBitVec_lor, toBitVec_mul,
    toBitVec_ofNat, toBitVec_shr8, toBitVec_shl8, mask8]
  exact endian8 (toBitVec value)

theorem multipliedStage16_eq_packedStage (value : UInt256) :
    multipliedStage value 16 mask16 = packedStage value 16 mask16 := by
  apply toBitVec_injective
  simp only [multipliedStage, endianDelta, endianFactor, packedStage,
    toBitVec_xor, toBitVec_land, toBitVec_lor, toBitVec_mul,
    toBitVec_ofNat, toBitVec_shr16, toBitVec_shl16, mask16]
  exact endian16 (toBitVec value)

end Challenge.Ripemd160.Submission.Proofs.Bytecode.DenseEndianMultiply
