import Challenge.Ripemd160.Submission.Proofs.Bytecode.StackRoundTemplate
import YulEvmCompiler.Instr

set_option warningAsError true
set_option maxRecDepth 30000

/-!
# Q4M quad-round helper templates (generated by scripts/gen_lean.py)

The quad helper receives `[p0, return-PC, M0, p1, M1, p2, M2, p3, M3, A, B, C, D, E]`
where `M_i = (2^32 + 1) <<< r_i`. The final `JUMP` is outside the before-jump
template. Each helper is the concatenation of a JUMPDEST segment, four round
segments, and a fix-up permutation segment.
-/

namespace Challenge.Ripemd160.Submission.Proofs.Bytecode.QuadRoundTemplate

open EvmSemantics
open EvmSemantics.EVM
open YulEvmCompiler
open Challenge.EvmProof
open Challenge.Ripemd160.Submission.Proofs.Bytecode.StackRoundTemplate

def push5 (value : UInt256) : Instr := .push ⟨5, by decide⟩ value

def foldM : UInt256 := UInt256.ofNat 0x0100000001


def seg0_0 : List Instr :=
  [op .JUMPDEST]

def seg0_1 : List Instr :=
  [op .MLOAD,
   .op (.Dup ⟨12, by decide⟩),
   .op (.Dup ⟨12, by decide⟩),
   .op (.Dup ⟨12, by decide⟩),
   op .XOR,
   op .XOR,
   op .ADD,
   .op (.Swap ⟨0, by decide⟩),
   .op (.Swap ⟨8, by decide⟩),
   op .ADD,
   push4 mask,
   op .AND,
   op .MUL,
   push1 (UInt256.ofNat 32),
   op .SHR,
   .op (.Dup ⟨11, by decide⟩),
   op .ADD,
   push4 mask,
   op .AND,
   .op (.Swap ⟨8, by decide⟩),
   push5 foldM,
   op .MUL,
   push1 (UInt256.ofNat 22),
   op .SHR]

def seg0_2 : List Instr :=
  [.op (.Swap ⟨0, by decide⟩),
   op .MLOAD,
   .op (.Dup ⟨1, by decide⟩),
   .op (.Dup ⟨9, by decide⟩),
   .op (.Dup ⟨11, by decide⟩),
   op .XOR,
   op .XOR,
   op .ADD,
   .op (.Swap ⟨0, by decide⟩),
   .op (.Swap ⟨10, by decide⟩),
   op .ADD,
   push4 mask,
   op .AND,
   op .MUL,
   push1 (UInt256.ofNat 32),
   op .SHR,
   .op (.Dup ⟨8, by decide⟩),
   op .ADD,
   push4 mask,
   op .AND,
   .op (.Swap ⟨5, by decide⟩),
   push5 foldM,
   op .MUL,
   push1 (UInt256.ofNat 22),
   op .SHR]

def seg0_3 : List Instr :=
  [.op (.Swap ⟨0, by decide⟩),
   op .MLOAD,
   .op (.Dup ⟨1, by decide⟩),
   .op (.Dup ⟨8, by decide⟩),
   .op (.Dup ⟨8, by decide⟩),
   op .XOR,
   op .XOR,
   op .ADD,
   .op (.Swap ⟨0, by decide⟩),
   .op (.Swap ⟨7, by decide⟩),
   op .ADD,
   push4 mask,
   op .AND,
   op .MUL,
   push1 (UInt256.ofNat 32),
   op .SHR,
   .op (.Dup ⟨7, by decide⟩),
   op .ADD,
   push4 mask,
   op .AND,
   .op (.Swap ⟨4, by decide⟩),
   push5 foldM,
   op .MUL,
   push1 (UInt256.ofNat 22),
   op .SHR]

def seg0_4 : List Instr :=
  [.op (.Swap ⟨0, by decide⟩),
   op .MLOAD,
   .op (.Dup ⟨1, by decide⟩),
   .op (.Dup ⟨5, by decide⟩),
   .op (.Dup ⟨7, by decide⟩),
   op .XOR,
   op .XOR,
   op .ADD,
   .op (.Swap ⟨0, by decide⟩),
   .op (.Swap ⟨6, by decide⟩),
   op .ADD,
   push4 mask,
   op .AND,
   op .MUL,
   push1 (UInt256.ofNat 32),
   op .SHR,
   .op (.Dup ⟨4, by decide⟩),
   op .ADD,
   push4 mask,
   op .AND,
   .op (.Swap ⟨1, by decide⟩),
   push5 foldM,
   op .MUL,
   push1 (UInt256.ofNat 22),
   op .SHR]

def seg0_5 : List Instr :=
  [.op (.Swap ⟨3, by decide⟩),
   .op (.Swap ⟨0, by decide⟩)]

def seg1_0 : List Instr :=
  [op .JUMPDEST]

def seg1_1 (constant : UInt256) : List Instr :=
  [op .MLOAD,
   .op (.Dup ⟨12, by decide⟩),
   .op (.Dup ⟨11, by decide⟩),
   .op (.Dup ⟨1, by decide⟩),
   .op (.Dup ⟨14, by decide⟩),
   op .XOR,
   op .AND,
   op .XOR,
   op .ADD,
   .op (.Swap ⟨0, by decide⟩),
   .op (.Swap ⟨8, by decide⟩),
   op .ADD,
   push4 constant,
   op .ADD,
   push4 mask,
   op .AND,
   op .MUL,
   push1 (UInt256.ofNat 32),
   op .SHR,
   .op (.Dup ⟨11, by decide⟩),
   op .ADD,
   push4 mask,
   op .AND,
   .op (.Swap ⟨8, by decide⟩),
   push5 foldM,
   op .MUL,
   push1 (UInt256.ofNat 22),
   op .SHR]

def seg1_2 (constant : UInt256) : List Instr :=
  [.op (.Swap ⟨0, by decide⟩),
   op .MLOAD,
   .op (.Dup ⟨1, by decide⟩),
   .op (.Dup ⟨10, by decide⟩),
   .op (.Dup ⟨1, by decide⟩),
   .op (.Dup ⟨11, by decide⟩),
   op .XOR,
   op .AND,
   op .XOR,
   op .ADD,
   .op (.Swap ⟨0, by decide⟩),
   .op (.Swap ⟨10, by decide⟩),
   op .ADD,
   push4 constant,
   op .ADD,
   push4 mask,
   op .AND,
   op .MUL,
   push1 (UInt256.ofNat 32),
   op .SHR,
   .op (.Dup ⟨8, by decide⟩),
   op .ADD,
   push4 mask,
   op .AND,
   .op (.Swap ⟨5, by decide⟩),
   push5 foldM,
   op .MUL,
   push1 (UInt256.ofNat 22),
   op .SHR]

def seg1_3 (constant : UInt256) : List Instr :=
  [.op (.Swap ⟨0, by decide⟩),
   op .MLOAD,
   .op (.Dup ⟨1, by decide⟩),
   .op (.Dup ⟨7, by decide⟩),
   .op (.Dup ⟨1, by decide⟩),
   .op (.Dup ⟨10, by decide⟩),
   op .XOR,
   op .AND,
   op .XOR,
   op .ADD,
   .op (.Swap ⟨0, by decide⟩),
   .op (.Swap ⟨7, by decide⟩),
   op .ADD,
   push4 constant,
   op .ADD,
   push4 mask,
   op .AND,
   op .MUL,
   push1 (UInt256.ofNat 32),
   op .SHR,
   .op (.Dup ⟨7, by decide⟩),
   op .ADD,
   push4 mask,
   op .AND,
   .op (.Swap ⟨4, by decide⟩),
   push5 foldM,
   op .MUL,
   push1 (UInt256.ofNat 22),
   op .SHR]

def seg1_4 (constant : UInt256) : List Instr :=
  [.op (.Swap ⟨0, by decide⟩),
   op .MLOAD,
   .op (.Dup ⟨1, by decide⟩),
   .op (.Dup ⟨6, by decide⟩),
   .op (.Dup ⟨1, by decide⟩),
   .op (.Dup ⟨7, by decide⟩),
   op .XOR,
   op .AND,
   op .XOR,
   op .ADD,
   .op (.Swap ⟨0, by decide⟩),
   .op (.Swap ⟨6, by decide⟩),
   op .ADD,
   push4 constant,
   op .ADD,
   push4 mask,
   op .AND,
   op .MUL,
   push1 (UInt256.ofNat 32),
   op .SHR,
   .op (.Dup ⟨4, by decide⟩),
   op .ADD,
   push4 mask,
   op .AND,
   .op (.Swap ⟨1, by decide⟩),
   push5 foldM,
   op .MUL,
   push1 (UInt256.ofNat 22),
   op .SHR]

def seg1_5 : List Instr :=
  [.op (.Swap ⟨3, by decide⟩),
   .op (.Swap ⟨0, by decide⟩)]

def seg2_0 : List Instr :=
  [op .JUMPDEST]

def seg2_1 (constant : UInt256) : List Instr :=
  [op .MLOAD,
   .op (.Dup ⟨12, by decide⟩),
   .op (.Dup ⟨12, by decide⟩),
   op .NOT,
   .op (.Dup ⟨12, by decide⟩),
   op .OR,
   op .XOR,
   op .ADD,
   .op (.Swap ⟨0, by decide⟩),
   .op (.Swap ⟨8, by decide⟩),
   op .ADD,
   push4 constant,
   op .ADD,
   push4 mask,
   op .AND,
   op .MUL,
   push1 (UInt256.ofNat 32),
   op .SHR,
   .op (.Dup ⟨11, by decide⟩),
   op .ADD,
   push4 mask,
   op .AND,
   .op (.Swap ⟨8, by decide⟩),
   push5 foldM,
   op .MUL,
   push1 (UInt256.ofNat 22),
   op .SHR]

def seg2_2 (constant : UInt256) : List Instr :=
  [.op (.Swap ⟨0, by decide⟩),
   op .MLOAD,
   .op (.Dup ⟨1, by decide⟩),
   .op (.Dup ⟨9, by decide⟩),
   op .NOT,
   .op (.Dup ⟨11, by decide⟩),
   op .OR,
   op .XOR,
   op .ADD,
   .op (.Swap ⟨0, by decide⟩),
   .op (.Swap ⟨10, by decide⟩),
   op .ADD,
   push4 constant,
   op .ADD,
   push4 mask,
   op .AND,
   op .MUL,
   push1 (UInt256.ofNat 32),
   op .SHR,
   .op (.Dup ⟨8, by decide⟩),
   op .ADD,
   push4 mask,
   op .AND,
   .op (.Swap ⟨5, by decide⟩),
   push5 foldM,
   op .MUL,
   push1 (UInt256.ofNat 22),
   op .SHR]

def seg2_3 (constant : UInt256) : List Instr :=
  [.op (.Swap ⟨0, by decide⟩),
   op .MLOAD,
   .op (.Dup ⟨1, by decide⟩),
   .op (.Dup ⟨8, by decide⟩),
   op .NOT,
   .op (.Dup ⟨8, by decide⟩),
   op .OR,
   op .XOR,
   op .ADD,
   .op (.Swap ⟨0, by decide⟩),
   .op (.Swap ⟨7, by decide⟩),
   op .ADD,
   push4 constant,
   op .ADD,
   push4 mask,
   op .AND,
   op .MUL,
   push1 (UInt256.ofNat 32),
   op .SHR,
   .op (.Dup ⟨7, by decide⟩),
   op .ADD,
   push4 mask,
   op .AND,
   .op (.Swap ⟨4, by decide⟩),
   push5 foldM,
   op .MUL,
   push1 (UInt256.ofNat 22),
   op .SHR]

def seg2_4 (constant : UInt256) : List Instr :=
  [.op (.Swap ⟨0, by decide⟩),
   op .MLOAD,
   .op (.Dup ⟨1, by decide⟩),
   .op (.Dup ⟨5, by decide⟩),
   op .NOT,
   .op (.Dup ⟨7, by decide⟩),
   op .OR,
   op .XOR,
   op .ADD,
   .op (.Swap ⟨0, by decide⟩),
   .op (.Swap ⟨6, by decide⟩),
   op .ADD,
   push4 constant,
   op .ADD,
   push4 mask,
   op .AND,
   op .MUL,
   push1 (UInt256.ofNat 32),
   op .SHR,
   .op (.Dup ⟨4, by decide⟩),
   op .ADD,
   push4 mask,
   op .AND,
   .op (.Swap ⟨1, by decide⟩),
   push5 foldM,
   op .MUL,
   push1 (UInt256.ofNat 22),
   op .SHR]

def seg2_5 : List Instr :=
  [.op (.Swap ⟨3, by decide⟩),
   .op (.Swap ⟨0, by decide⟩)]

def seg3_0 : List Instr :=
  [op .JUMPDEST]

def seg3_1 (constant : UInt256) : List Instr :=
  [op .MLOAD,
   .op (.Dup ⟨11, by decide⟩),
   .op (.Dup ⟨13, by decide⟩),
   .op (.Dup ⟨1, by decide⟩),
   .op (.Dup ⟨13, by decide⟩),
   op .XOR,
   op .AND,
   op .XOR,
   op .ADD,
   .op (.Swap ⟨0, by decide⟩),
   .op (.Swap ⟨8, by decide⟩),
   op .ADD,
   push4 constant,
   op .ADD,
   push4 mask,
   op .AND,
   op .MUL,
   push1 (UInt256.ofNat 32),
   op .SHR,
   .op (.Dup ⟨11, by decide⟩),
   op .ADD,
   push4 mask,
   op .AND,
   .op (.Swap ⟨8, by decide⟩),
   push5 foldM,
   op .MUL,
   push1 (UInt256.ofNat 22),
   op .SHR]

def seg3_2 (constant : UInt256) : List Instr :=
  [.op (.Swap ⟨0, by decide⟩),
   op .MLOAD,
   .op (.Dup ⟨8, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op (.Dup ⟨1, by decide⟩),
   .op (.Dup ⟨12, by decide⟩),
   op .XOR,
   op .AND,
   op .XOR,
   op .ADD,
   .op (.Swap ⟨0, by decide⟩),
   .op (.Swap ⟨10, by decide⟩),
   op .ADD,
   push4 constant,
   op .ADD,
   push4 mask,
   op .AND,
   op .MUL,
   push1 (UInt256.ofNat 32),
   op .SHR,
   .op (.Dup ⟨8, by decide⟩),
   op .ADD,
   push4 mask,
   op .AND,
   .op (.Swap ⟨5, by decide⟩),
   push5 foldM,
   op .MUL,
   push1 (UInt256.ofNat 22),
   op .SHR]

def seg3_3 (constant : UInt256) : List Instr :=
  [.op (.Swap ⟨0, by decide⟩),
   op .MLOAD,
   .op (.Dup ⟨7, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op (.Dup ⟨1, by decide⟩),
   .op (.Dup ⟨9, by decide⟩),
   op .XOR,
   op .AND,
   op .XOR,
   op .ADD,
   .op (.Swap ⟨0, by decide⟩),
   .op (.Swap ⟨7, by decide⟩),
   op .ADD,
   push4 constant,
   op .ADD,
   push4 mask,
   op .AND,
   op .MUL,
   push1 (UInt256.ofNat 32),
   op .SHR,
   .op (.Dup ⟨7, by decide⟩),
   op .ADD,
   push4 mask,
   op .AND,
   .op (.Swap ⟨4, by decide⟩),
   push5 foldM,
   op .MUL,
   push1 (UInt256.ofNat 22),
   op .SHR]

def seg3_4 (constant : UInt256) : List Instr :=
  [.op (.Swap ⟨0, by decide⟩),
   op .MLOAD,
   .op (.Dup ⟨4, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op (.Dup ⟨1, by decide⟩),
   .op (.Dup ⟨8, by decide⟩),
   op .XOR,
   op .AND,
   op .XOR,
   op .ADD,
   .op (.Swap ⟨0, by decide⟩),
   .op (.Swap ⟨6, by decide⟩),
   op .ADD,
   push4 constant,
   op .ADD,
   push4 mask,
   op .AND,
   op .MUL,
   push1 (UInt256.ofNat 32),
   op .SHR,
   .op (.Dup ⟨4, by decide⟩),
   op .ADD,
   push4 mask,
   op .AND,
   .op (.Swap ⟨1, by decide⟩),
   push5 foldM,
   op .MUL,
   push1 (UInt256.ofNat 22),
   op .SHR]

def seg3_5 : List Instr :=
  [.op (.Swap ⟨3, by decide⟩),
   .op (.Swap ⟨0, by decide⟩)]

def seg4_0 : List Instr :=
  [op .JUMPDEST]

def seg4_1 (constant : UInt256) : List Instr :=
  [op .MLOAD,
   .op (.Dup ⟨12, by decide⟩),
   op .NOT,
   .op (.Dup ⟨12, by decide⟩),
   op .OR,
   .op (.Dup ⟨11, by decide⟩),
   op .XOR,
   op .ADD,
   .op (.Swap ⟨0, by decide⟩),
   .op (.Swap ⟨8, by decide⟩),
   op .ADD,
   push4 constant,
   op .ADD,
   push4 mask,
   op .AND,
   op .MUL,
   push1 (UInt256.ofNat 32),
   op .SHR,
   .op (.Dup ⟨11, by decide⟩),
   op .ADD,
   push4 mask,
   op .AND,
   .op (.Swap ⟨8, by decide⟩),
   push5 foldM,
   op .MUL,
   push1 (UInt256.ofNat 22),
   op .SHR]

def seg4_2 (constant : UInt256) : List Instr :=
  [.op (.Swap ⟨0, by decide⟩),
   op .MLOAD,
   .op (.Dup ⟨1, by decide⟩),
   op .NOT,
   .op (.Dup ⟨9, by decide⟩),
   op .OR,
   .op (.Dup ⟨10, by decide⟩),
   op .XOR,
   op .ADD,
   .op (.Swap ⟨0, by decide⟩),
   .op (.Swap ⟨10, by decide⟩),
   op .ADD,
   push4 constant,
   op .ADD,
   push4 mask,
   op .AND,
   op .MUL,
   push1 (UInt256.ofNat 32),
   op .SHR,
   .op (.Dup ⟨8, by decide⟩),
   op .ADD,
   push4 mask,
   op .AND,
   .op (.Swap ⟨5, by decide⟩),
   push5 foldM,
   op .MUL,
   push1 (UInt256.ofNat 22),
   op .SHR]

def seg4_3 (constant : UInt256) : List Instr :=
  [.op (.Swap ⟨0, by decide⟩),
   op .MLOAD,
   .op (.Dup ⟨1, by decide⟩),
   op .NOT,
   .op (.Dup ⟨8, by decide⟩),
   op .OR,
   .op (.Dup ⟨7, by decide⟩),
   op .XOR,
   op .ADD,
   .op (.Swap ⟨0, by decide⟩),
   .op (.Swap ⟨7, by decide⟩),
   op .ADD,
   push4 constant,
   op .ADD,
   push4 mask,
   op .AND,
   op .MUL,
   push1 (UInt256.ofNat 32),
   op .SHR,
   .op (.Dup ⟨7, by decide⟩),
   op .ADD,
   push4 mask,
   op .AND,
   .op (.Swap ⟨4, by decide⟩),
   push5 foldM,
   op .MUL,
   push1 (UInt256.ofNat 22),
   op .SHR]

def seg4_4 (constant : UInt256) : List Instr :=
  [.op (.Swap ⟨0, by decide⟩),
   op .MLOAD,
   .op (.Dup ⟨1, by decide⟩),
   op .NOT,
   .op (.Dup ⟨5, by decide⟩),
   op .OR,
   .op (.Dup ⟨6, by decide⟩),
   op .XOR,
   op .ADD,
   .op (.Swap ⟨0, by decide⟩),
   .op (.Swap ⟨6, by decide⟩),
   op .ADD,
   push4 constant,
   op .ADD,
   push4 mask,
   op .AND,
   op .MUL,
   push1 (UInt256.ofNat 32),
   op .SHR,
   .op (.Dup ⟨4, by decide⟩),
   op .ADD,
   push4 mask,
   op .AND,
   .op (.Swap ⟨1, by decide⟩),
   push5 foldM,
   op .MUL,
   push1 (UInt256.ofNat 22),
   op .SHR]

def seg4_5 : List Instr :=
  [.op (.Swap ⟨3, by decide⟩),
   .op (.Swap ⟨0, by decide⟩)]

def quadBeforeJumpTemplate0 (_constant : UInt256) : List Instr :=
  seg0_0 ++ seg0_1 ++ seg0_2 ++ seg0_3 ++ seg0_4 ++ seg0_5

def quadBeforeJumpTemplate1 (constant : UInt256) : List Instr :=
  seg1_0 ++ seg1_1 constant ++ seg1_2 constant ++ seg1_3 constant ++ seg1_4 constant ++ seg1_5

def quadBeforeJumpTemplate2 (constant : UInt256) : List Instr :=
  seg2_0 ++ seg2_1 constant ++ seg2_2 constant ++ seg2_3 constant ++ seg2_4 constant ++ seg2_5

def quadBeforeJumpTemplate3 (constant : UInt256) : List Instr :=
  seg3_0 ++ seg3_1 constant ++ seg3_2 constant ++ seg3_3 constant ++ seg3_4 constant ++ seg3_5

def quadBeforeJumpTemplate4 (constant : UInt256) : List Instr :=
  seg4_0 ++ seg4_1 constant ++ seg4_2 constant ++ seg4_3 constant ++ seg4_4 constant ++ seg4_5

def quadBeforeJumpTemplate (j : Nat) (constant : UInt256) : List Instr :=
  match j with
  | 0 => quadBeforeJumpTemplate0 constant
  | 1 => quadBeforeJumpTemplate1 constant
  | 2 => quadBeforeJumpTemplate2 constant
  | 3 => quadBeforeJumpTemplate3 constant
  | _ => quadBeforeJumpTemplate4 constant

def quadTemplate (j : Nat) (constant : UInt256) : List Instr :=
  quadBeforeJumpTemplate j constant ++ [op .JUMP]

@[simp] theorem quadBeforeJumpTemplate_length_0 (constant : UInt256) :
    (quadBeforeJumpTemplate 0 constant).length = 102 := by
  rfl

@[simp] theorem quadTemplate_length_0 (constant : UInt256) :
    (quadTemplate 0 constant).length = 103 := by
  rfl

@[simp] theorem quadBeforeJumpTemplate_length_1 (constant : UInt256) :
    (quadBeforeJumpTemplate 1 constant).length = 118 := by
  rfl

@[simp] theorem quadTemplate_length_1 (constant : UInt256) :
    (quadTemplate 1 constant).length = 119 := by
  rfl

@[simp] theorem quadBeforeJumpTemplate_length_2 (constant : UInt256) :
    (quadBeforeJumpTemplate 2 constant).length = 114 := by
  rfl

@[simp] theorem quadTemplate_length_2 (constant : UInt256) :
    (quadTemplate 2 constant).length = 115 := by
  rfl

@[simp] theorem quadBeforeJumpTemplate_length_3 (constant : UInt256) :
    (quadBeforeJumpTemplate 3 constant).length = 118 := by
  rfl

@[simp] theorem quadTemplate_length_3 (constant : UInt256) :
    (quadTemplate 3 constant).length = 119 := by
  rfl

@[simp] theorem quadBeforeJumpTemplate_length_4 (constant : UInt256) :
    (quadBeforeJumpTemplate 4 constant).length = 114 := by
  rfl

@[simp] theorem quadTemplate_length_4 (constant : UInt256) :
    (quadTemplate 4 constant).length = 115 := by
  rfl

end Challenge.Ripemd160.Submission.Proofs.Bytecode.QuadRoundTemplate
