import Challenge.Ripemd160.Submission.Proofs.Bytecode.QuadRoundState

set_option warningAsError true
set_option maxRecDepth 30000
set_option maxHeartbeats 4000000

/-!
# Q4M raw evaluator traces for Boolean form 2 (generated by scripts/gen_lean.py)

Each segment theorem evaluates one round of the quad helper on arbitrary
256-bit stack words with `Stepper.runInstr`; the composition theorem chains
them into the before-jump template.
-/

namespace Challenge.Ripemd160.Submission.Proofs.Bytecode.QuadRawTrace2

open EvmSemantics
open EvmSemantics.EVM
open YulEvmCompiler
open Challenge.EvmProof
open Challenge.Ripemd160.Submission.Proofs.Bytecode.Compression
open Challenge.Ripemd160.Submission.Proofs.Bytecode.StackRoundTemplate
open Challenge.Ripemd160.Submission.Proofs.Bytecode.StackRoundTrace
open Challenge.Ripemd160.Submission.Proofs.Bytecode.QuadRoundTemplate
open Challenge.Ripemd160.Submission.Proofs.Bytecode.QuadRoundState


set_option linter.unusedSimpArgs false in
theorem runInstrSeq_round0 (s : State) (startPC p0 p1 p2 p3 returnPC M0 M1 M2 M3 constant : UInt256)
    (x : EvmWorking) (rest : List UInt256)
    (hstack : rest.length < 1000) (hrun : s.halt = .Running)
    (hactive : 67 ≤ s.activeWords.toNat)
    (hp0 : p0.toNat + 32 ≤ 2144) (hp1 : p1.toNat + 32 ≤ 2144)
    (hp2 : p2.toNat + 32 ≤ 2144) (hp3 : p3.toNat + 32 ≤ 2144) :
    runInstrSeq (seg2_0 ++ seg2_1 constant)
      { s with pc := startPC, stack := [p0, returnPC, M0, p1, M1, p2, M2, p3, M3, x.a, x.b, x.c, x.d, x.e] ++ rest } =
    some { s with pc := pcAfter startPC (seg2_0 ++ seg2_1 constant), stack := [(qRound x 2 (MachineState.readWord s.memory p0.toNat) M0 constant).d, p1, M1, p2, M2, p3, M3, returnPC, (qRound x 2 (MachineState.readWord s.memory p0.toNat) M0 constant).c, (qRound x 2 (MachineState.readWord s.memory p0.toNat) M0 constant).b, (qRound x 2 (MachineState.readWord s.memory p0.toNat) M0 constant).e, (qRound x 2 (MachineState.readWord s.memory p0.toNat) M0 constant).a] ++ rest } := by
  have hcap (m : Nat) (hm : m ≤ 24) : rest.length + m < 1024 := by omega
  have hadd (u v : UInt256) : u + v = u.add v := rfl
  have hA0 := ScheduleActiveWords.activeWordsAfterUInt256_eq s p0.toNat 32 (by omega)
  simp only [State.activeWordsAfterUInt256] at hA0
  have hA1 := ScheduleActiveWords.activeWordsAfterUInt256_eq s p1.toNat 32 (by omega)
  simp only [State.activeWordsAfterUInt256] at hA1
  have hA2 := ScheduleActiveWords.activeWordsAfterUInt256_eq s p2.toNat 32 (by omega)
  simp only [State.activeWordsAfterUInt256] at hA2
  have hA3 := ScheduleActiveWords.activeWordsAfterUInt256_eq s p3.toNat 32 (by omega)
  simp only [State.activeWordsAfterUInt256] at hA3
  simp (config := { maxSteps := 2000000 }) (discharger := omega)
    [seg2_0, seg2_1, qRound, qf, qSum, runInstrSeq, Stepper.runInstr,
      op, push1, push4, push5, mask, foldM, List.exchange, hrun, hcap, hadd, pcAfter,
      exchange_swap1, exchange_swap2, exchange_swap3, exchange_swap4, exchange_swap5, exchange_swap6,
      exchange_swap7, exchange_swap8, exchange_swap9, exchange_swap10, exchange_swap11, exchange_swap12,
      State.activeWordsAfterUInt256, hA0, hA1, hA2, hA3,
      UInt256.succ, Instr.size, Instr.size_push, Instr.size_op, Nat.add_assoc,
      Challenge.EvmProof.Word.word_toNat_ofNat, Challenge.EvmProof.Word.ofNat_add_mod,
      Challenge.EvmProof.Word.succ_ofNat, List.getElem?_cons_zero, List.getElem?_cons_succ]

set_option linter.unusedSimpArgs false in
theorem runInstrSeq_round1 (s : State) (startPC p0 p1 p2 p3 returnPC M0 M1 M2 M3 constant : UInt256)
    (x : EvmWorking) (rest : List UInt256)
    (hstack : rest.length < 1000) (hrun : s.halt = .Running)
    (hactive : 67 ≤ s.activeWords.toNat)
    (hp0 : p0.toNat + 32 ≤ 2144) (hp1 : p1.toNat + 32 ≤ 2144)
    (hp2 : p2.toNat + 32 ≤ 2144) (hp3 : p3.toNat + 32 ≤ 2144) :
    runInstrSeq (seg2_2 constant)
      { s with pc := pcAfter startPC (seg2_0 ++ seg2_1 constant), stack := [(qRound x 2 (MachineState.readWord s.memory p0.toNat) M0 constant).d, p1, M1, p2, M2, p3, M3, returnPC, (qRound x 2 (MachineState.readWord s.memory p0.toNat) M0 constant).c, (qRound x 2 (MachineState.readWord s.memory p0.toNat) M0 constant).b, (qRound x 2 (MachineState.readWord s.memory p0.toNat) M0 constant).e, (qRound x 2 (MachineState.readWord s.memory p0.toNat) M0 constant).a] ++ rest } =
    some { s with pc := pcAfter startPC ((seg2_0 ++ seg2_1 constant) ++ seg2_2 constant), stack := [(qRound (qRound x 2 (MachineState.readWord s.memory p0.toNat) M0 constant) 2 (MachineState.readWord s.memory p1.toNat) M1 constant).d, p2, M2, p3, M3, returnPC, (qRound (qRound x 2 (MachineState.readWord s.memory p0.toNat) M0 constant) 2 (MachineState.readWord s.memory p1.toNat) M1 constant).b, (qRound (qRound x 2 (MachineState.readWord s.memory p0.toNat) M0 constant) 2 (MachineState.readWord s.memory p1.toNat) M1 constant).c, (qRound (qRound x 2 (MachineState.readWord s.memory p0.toNat) M0 constant) 2 (MachineState.readWord s.memory p1.toNat) M1 constant).a, (qRound (qRound x 2 (MachineState.readWord s.memory p0.toNat) M0 constant) 2 (MachineState.readWord s.memory p1.toNat) M1 constant).e] ++ rest } := by
  have hcap (m : Nat) (hm : m ≤ 24) : rest.length + m < 1024 := by omega
  have hadd (u v : UInt256) : u + v = u.add v := rfl
  have hA0 := ScheduleActiveWords.activeWordsAfterUInt256_eq s p0.toNat 32 (by omega)
  simp only [State.activeWordsAfterUInt256] at hA0
  have hA1 := ScheduleActiveWords.activeWordsAfterUInt256_eq s p1.toNat 32 (by omega)
  simp only [State.activeWordsAfterUInt256] at hA1
  have hA2 := ScheduleActiveWords.activeWordsAfterUInt256_eq s p2.toNat 32 (by omega)
  simp only [State.activeWordsAfterUInt256] at hA2
  have hA3 := ScheduleActiveWords.activeWordsAfterUInt256_eq s p3.toNat 32 (by omega)
  simp only [State.activeWordsAfterUInt256] at hA3
  simp (config := { maxSteps := 2000000 }) (discharger := omega)
    [seg2_0, seg2_1, seg2_2, qRound, qf, qSum, runInstrSeq, Stepper.runInstr,
      op, push1, push4, push5, mask, foldM, List.exchange, hrun, hcap, hadd, pcAfter,
      exchange_swap1, exchange_swap2, exchange_swap3, exchange_swap4, exchange_swap5, exchange_swap6,
      exchange_swap7, exchange_swap8, exchange_swap9, exchange_swap10, exchange_swap11, exchange_swap12,
      State.activeWordsAfterUInt256, hA0, hA1, hA2, hA3,
      UInt256.succ, Instr.size, Instr.size_push, Instr.size_op, Nat.add_assoc,
      Challenge.EvmProof.Word.word_toNat_ofNat, Challenge.EvmProof.Word.ofNat_add_mod,
      Challenge.EvmProof.Word.succ_ofNat, List.getElem?_cons_zero, List.getElem?_cons_succ]

set_option linter.unusedSimpArgs false in
theorem runInstrSeq_round2 (s : State) (startPC p0 p1 p2 p3 returnPC M0 M1 M2 M3 constant : UInt256)
    (x : EvmWorking) (rest : List UInt256)
    (hstack : rest.length < 1000) (hrun : s.halt = .Running)
    (hactive : 67 ≤ s.activeWords.toNat)
    (hp0 : p0.toNat + 32 ≤ 2144) (hp1 : p1.toNat + 32 ≤ 2144)
    (hp2 : p2.toNat + 32 ≤ 2144) (hp3 : p3.toNat + 32 ≤ 2144) :
    runInstrSeq (seg2_3 constant)
      { s with pc := pcAfter startPC ((seg2_0 ++ seg2_1 constant) ++ seg2_2 constant), stack := [(qRound (qRound x 2 (MachineState.readWord s.memory p0.toNat) M0 constant) 2 (MachineState.readWord s.memory p1.toNat) M1 constant).d, p2, M2, p3, M3, returnPC, (qRound (qRound x 2 (MachineState.readWord s.memory p0.toNat) M0 constant) 2 (MachineState.readWord s.memory p1.toNat) M1 constant).b, (qRound (qRound x 2 (MachineState.readWord s.memory p0.toNat) M0 constant) 2 (MachineState.readWord s.memory p1.toNat) M1 constant).c, (qRound (qRound x 2 (MachineState.readWord s.memory p0.toNat) M0 constant) 2 (MachineState.readWord s.memory p1.toNat) M1 constant).a, (qRound (qRound x 2 (MachineState.readWord s.memory p0.toNat) M0 constant) 2 (MachineState.readWord s.memory p1.toNat) M1 constant).e] ++ rest } =
    some { s with pc := pcAfter startPC (((seg2_0 ++ seg2_1 constant) ++ seg2_2 constant) ++ seg2_3 constant), stack := [(qRound (qRound (qRound x 2 (MachineState.readWord s.memory p0.toNat) M0 constant) 2 (MachineState.readWord s.memory p1.toNat) M1 constant) 2 (MachineState.readWord s.memory p2.toNat) M2 constant).d, p3, M3, returnPC, (qRound (qRound (qRound x 2 (MachineState.readWord s.memory p0.toNat) M0 constant) 2 (MachineState.readWord s.memory p1.toNat) M1 constant) 2 (MachineState.readWord s.memory p2.toNat) M2 constant).c, (qRound (qRound (qRound x 2 (MachineState.readWord s.memory p0.toNat) M0 constant) 2 (MachineState.readWord s.memory p1.toNat) M1 constant) 2 (MachineState.readWord s.memory p2.toNat) M2 constant).b, (qRound (qRound (qRound x 2 (MachineState.readWord s.memory p0.toNat) M0 constant) 2 (MachineState.readWord s.memory p1.toNat) M1 constant) 2 (MachineState.readWord s.memory p2.toNat) M2 constant).e, (qRound (qRound (qRound x 2 (MachineState.readWord s.memory p0.toNat) M0 constant) 2 (MachineState.readWord s.memory p1.toNat) M1 constant) 2 (MachineState.readWord s.memory p2.toNat) M2 constant).a] ++ rest } := by
  have hcap (m : Nat) (hm : m ≤ 24) : rest.length + m < 1024 := by omega
  have hadd (u v : UInt256) : u + v = u.add v := rfl
  have hA0 := ScheduleActiveWords.activeWordsAfterUInt256_eq s p0.toNat 32 (by omega)
  simp only [State.activeWordsAfterUInt256] at hA0
  have hA1 := ScheduleActiveWords.activeWordsAfterUInt256_eq s p1.toNat 32 (by omega)
  simp only [State.activeWordsAfterUInt256] at hA1
  have hA2 := ScheduleActiveWords.activeWordsAfterUInt256_eq s p2.toNat 32 (by omega)
  simp only [State.activeWordsAfterUInt256] at hA2
  have hA3 := ScheduleActiveWords.activeWordsAfterUInt256_eq s p3.toNat 32 (by omega)
  simp only [State.activeWordsAfterUInt256] at hA3
  simp (config := { maxSteps := 2000000 }) (discharger := omega)
    [seg2_0, seg2_1, seg2_2, seg2_3, qRound, qf, qSum, runInstrSeq, Stepper.runInstr,
      op, push1, push4, push5, mask, foldM, List.exchange, hrun, hcap, hadd, pcAfter,
      exchange_swap1, exchange_swap2, exchange_swap3, exchange_swap4, exchange_swap5, exchange_swap6,
      exchange_swap7, exchange_swap8, exchange_swap9, exchange_swap10, exchange_swap11, exchange_swap12,
      State.activeWordsAfterUInt256, hA0, hA1, hA2, hA3,
      UInt256.succ, Instr.size, Instr.size_push, Instr.size_op, Nat.add_assoc,
      Challenge.EvmProof.Word.word_toNat_ofNat, Challenge.EvmProof.Word.ofNat_add_mod,
      Challenge.EvmProof.Word.succ_ofNat, List.getElem?_cons_zero, List.getElem?_cons_succ]

set_option linter.unusedSimpArgs false in
theorem runInstrSeq_round3 (s : State) (startPC p0 p1 p2 p3 returnPC M0 M1 M2 M3 constant : UInt256)
    (x : EvmWorking) (rest : List UInt256)
    (hstack : rest.length < 1000) (hrun : s.halt = .Running)
    (hactive : 67 ≤ s.activeWords.toNat)
    (hp0 : p0.toNat + 32 ≤ 2144) (hp1 : p1.toNat + 32 ≤ 2144)
    (hp2 : p2.toNat + 32 ≤ 2144) (hp3 : p3.toNat + 32 ≤ 2144) :
    runInstrSeq (seg2_4 constant)
      { s with pc := pcAfter startPC (((seg2_0 ++ seg2_1 constant) ++ seg2_2 constant) ++ seg2_3 constant), stack := [(qRound (qRound (qRound x 2 (MachineState.readWord s.memory p0.toNat) M0 constant) 2 (MachineState.readWord s.memory p1.toNat) M1 constant) 2 (MachineState.readWord s.memory p2.toNat) M2 constant).d, p3, M3, returnPC, (qRound (qRound (qRound x 2 (MachineState.readWord s.memory p0.toNat) M0 constant) 2 (MachineState.readWord s.memory p1.toNat) M1 constant) 2 (MachineState.readWord s.memory p2.toNat) M2 constant).c, (qRound (qRound (qRound x 2 (MachineState.readWord s.memory p0.toNat) M0 constant) 2 (MachineState.readWord s.memory p1.toNat) M1 constant) 2 (MachineState.readWord s.memory p2.toNat) M2 constant).b, (qRound (qRound (qRound x 2 (MachineState.readWord s.memory p0.toNat) M0 constant) 2 (MachineState.readWord s.memory p1.toNat) M1 constant) 2 (MachineState.readWord s.memory p2.toNat) M2 constant).e, (qRound (qRound (qRound x 2 (MachineState.readWord s.memory p0.toNat) M0 constant) 2 (MachineState.readWord s.memory p1.toNat) M1 constant) 2 (MachineState.readWord s.memory p2.toNat) M2 constant).a] ++ rest } =
    some { s with pc := pcAfter startPC ((((seg2_0 ++ seg2_1 constant) ++ seg2_2 constant) ++ seg2_3 constant) ++ seg2_4 constant), stack := [(qRound (qRound (qRound (qRound x 2 (MachineState.readWord s.memory p0.toNat) M0 constant) 2 (MachineState.readWord s.memory p1.toNat) M1 constant) 2 (MachineState.readWord s.memory p2.toNat) M2 constant) 2 (MachineState.readWord s.memory p3.toNat) M3 constant).d, returnPC, (qRound (qRound (qRound (qRound x 2 (MachineState.readWord s.memory p0.toNat) M0 constant) 2 (MachineState.readWord s.memory p1.toNat) M1 constant) 2 (MachineState.readWord s.memory p2.toNat) M2 constant) 2 (MachineState.readWord s.memory p3.toNat) M3 constant).b, (qRound (qRound (qRound (qRound x 2 (MachineState.readWord s.memory p0.toNat) M0 constant) 2 (MachineState.readWord s.memory p1.toNat) M1 constant) 2 (MachineState.readWord s.memory p2.toNat) M2 constant) 2 (MachineState.readWord s.memory p3.toNat) M3 constant).c, (qRound (qRound (qRound (qRound x 2 (MachineState.readWord s.memory p0.toNat) M0 constant) 2 (MachineState.readWord s.memory p1.toNat) M1 constant) 2 (MachineState.readWord s.memory p2.toNat) M2 constant) 2 (MachineState.readWord s.memory p3.toNat) M3 constant).a, (qRound (qRound (qRound (qRound x 2 (MachineState.readWord s.memory p0.toNat) M0 constant) 2 (MachineState.readWord s.memory p1.toNat) M1 constant) 2 (MachineState.readWord s.memory p2.toNat) M2 constant) 2 (MachineState.readWord s.memory p3.toNat) M3 constant).e] ++ rest } := by
  have hcap (m : Nat) (hm : m ≤ 24) : rest.length + m < 1024 := by omega
  have hadd (u v : UInt256) : u + v = u.add v := rfl
  have hA0 := ScheduleActiveWords.activeWordsAfterUInt256_eq s p0.toNat 32 (by omega)
  simp only [State.activeWordsAfterUInt256] at hA0
  have hA1 := ScheduleActiveWords.activeWordsAfterUInt256_eq s p1.toNat 32 (by omega)
  simp only [State.activeWordsAfterUInt256] at hA1
  have hA2 := ScheduleActiveWords.activeWordsAfterUInt256_eq s p2.toNat 32 (by omega)
  simp only [State.activeWordsAfterUInt256] at hA2
  have hA3 := ScheduleActiveWords.activeWordsAfterUInt256_eq s p3.toNat 32 (by omega)
  simp only [State.activeWordsAfterUInt256] at hA3
  simp (config := { maxSteps := 2000000 }) (discharger := omega)
    [seg2_0, seg2_1, seg2_2, seg2_3, seg2_4, qRound, qf, qSum, runInstrSeq, Stepper.runInstr,
      op, push1, push4, push5, mask, foldM, List.exchange, hrun, hcap, hadd, pcAfter,
      exchange_swap1, exchange_swap2, exchange_swap3, exchange_swap4, exchange_swap5, exchange_swap6,
      exchange_swap7, exchange_swap8, exchange_swap9, exchange_swap10, exchange_swap11, exchange_swap12,
      State.activeWordsAfterUInt256, hA0, hA1, hA2, hA3,
      UInt256.succ, Instr.size, Instr.size_push, Instr.size_op, Nat.add_assoc,
      Challenge.EvmProof.Word.word_toNat_ofNat, Challenge.EvmProof.Word.ofNat_add_mod,
      Challenge.EvmProof.Word.succ_ofNat, List.getElem?_cons_zero, List.getElem?_cons_succ]

set_option linter.unusedSimpArgs false in
theorem runInstrSeq_fixup (s : State) (startPC p0 p1 p2 p3 returnPC M0 M1 M2 M3 constant : UInt256)
    (x : EvmWorking) (rest : List UInt256)
    (hstack : rest.length < 1000) (hrun : s.halt = .Running)
    (hactive : 67 ≤ s.activeWords.toNat)
    (hp0 : p0.toNat + 32 ≤ 2144) (hp1 : p1.toNat + 32 ≤ 2144)
    (hp2 : p2.toNat + 32 ≤ 2144) (hp3 : p3.toNat + 32 ≤ 2144) :
    runInstrSeq (seg2_5)
      { s with pc := pcAfter startPC ((((seg2_0 ++ seg2_1 constant) ++ seg2_2 constant) ++ seg2_3 constant) ++ seg2_4 constant), stack := [(qRound (qRound (qRound (qRound x 2 (MachineState.readWord s.memory p0.toNat) M0 constant) 2 (MachineState.readWord s.memory p1.toNat) M1 constant) 2 (MachineState.readWord s.memory p2.toNat) M2 constant) 2 (MachineState.readWord s.memory p3.toNat) M3 constant).d, returnPC, (qRound (qRound (qRound (qRound x 2 (MachineState.readWord s.memory p0.toNat) M0 constant) 2 (MachineState.readWord s.memory p1.toNat) M1 constant) 2 (MachineState.readWord s.memory p2.toNat) M2 constant) 2 (MachineState.readWord s.memory p3.toNat) M3 constant).b, (qRound (qRound (qRound (qRound x 2 (MachineState.readWord s.memory p0.toNat) M0 constant) 2 (MachineState.readWord s.memory p1.toNat) M1 constant) 2 (MachineState.readWord s.memory p2.toNat) M2 constant) 2 (MachineState.readWord s.memory p3.toNat) M3 constant).c, (qRound (qRound (qRound (qRound x 2 (MachineState.readWord s.memory p0.toNat) M0 constant) 2 (MachineState.readWord s.memory p1.toNat) M1 constant) 2 (MachineState.readWord s.memory p2.toNat) M2 constant) 2 (MachineState.readWord s.memory p3.toNat) M3 constant).a, (qRound (qRound (qRound (qRound x 2 (MachineState.readWord s.memory p0.toNat) M0 constant) 2 (MachineState.readWord s.memory p1.toNat) M1 constant) 2 (MachineState.readWord s.memory p2.toNat) M2 constant) 2 (MachineState.readWord s.memory p3.toNat) M3 constant).e] ++ rest } =
    some { s with pc := pcAfter startPC (((((seg2_0 ++ seg2_1 constant) ++ seg2_2 constant) ++ seg2_3 constant) ++ seg2_4 constant) ++ seg2_5), stack := [returnPC, (qRound (qRound (qRound (qRound x 2 (MachineState.readWord s.memory p0.toNat) M0 constant) 2 (MachineState.readWord s.memory p1.toNat) M1 constant) 2 (MachineState.readWord s.memory p2.toNat) M2 constant) 2 (MachineState.readWord s.memory p3.toNat) M3 constant).a, (qRound (qRound (qRound (qRound x 2 (MachineState.readWord s.memory p0.toNat) M0 constant) 2 (MachineState.readWord s.memory p1.toNat) M1 constant) 2 (MachineState.readWord s.memory p2.toNat) M2 constant) 2 (MachineState.readWord s.memory p3.toNat) M3 constant).b, (qRound (qRound (qRound (qRound x 2 (MachineState.readWord s.memory p0.toNat) M0 constant) 2 (MachineState.readWord s.memory p1.toNat) M1 constant) 2 (MachineState.readWord s.memory p2.toNat) M2 constant) 2 (MachineState.readWord s.memory p3.toNat) M3 constant).c, (qRound (qRound (qRound (qRound x 2 (MachineState.readWord s.memory p0.toNat) M0 constant) 2 (MachineState.readWord s.memory p1.toNat) M1 constant) 2 (MachineState.readWord s.memory p2.toNat) M2 constant) 2 (MachineState.readWord s.memory p3.toNat) M3 constant).d, (qRound (qRound (qRound (qRound x 2 (MachineState.readWord s.memory p0.toNat) M0 constant) 2 (MachineState.readWord s.memory p1.toNat) M1 constant) 2 (MachineState.readWord s.memory p2.toNat) M2 constant) 2 (MachineState.readWord s.memory p3.toNat) M3 constant).e] ++ rest } := by
  have hcap (m : Nat) (hm : m ≤ 24) : rest.length + m < 1024 := by omega
  have hadd (u v : UInt256) : u + v = u.add v := rfl
  have hA0 := ScheduleActiveWords.activeWordsAfterUInt256_eq s p0.toNat 32 (by omega)
  simp only [State.activeWordsAfterUInt256] at hA0
  have hA1 := ScheduleActiveWords.activeWordsAfterUInt256_eq s p1.toNat 32 (by omega)
  simp only [State.activeWordsAfterUInt256] at hA1
  have hA2 := ScheduleActiveWords.activeWordsAfterUInt256_eq s p2.toNat 32 (by omega)
  simp only [State.activeWordsAfterUInt256] at hA2
  have hA3 := ScheduleActiveWords.activeWordsAfterUInt256_eq s p3.toNat 32 (by omega)
  simp only [State.activeWordsAfterUInt256] at hA3
  simp (discharger := omega)
    [seg2_0, seg2_1, seg2_2, seg2_3, seg2_4, seg2_5, runInstrSeq, Stepper.runInstr,
      op, push1, push4, push5, mask, foldM, List.exchange, hrun, hcap, hadd, pcAfter,
      exchange_swap1, exchange_swap2, exchange_swap3, exchange_swap4, exchange_swap5, exchange_swap6,
      exchange_swap7, exchange_swap8, exchange_swap9, exchange_swap10, exchange_swap11, exchange_swap12,
      State.activeWordsAfterUInt256, hA0, hA1, hA2, hA3,
      UInt256.succ, Instr.size, Instr.size_push, Instr.size_op, Nat.add_assoc,
      Challenge.EvmProof.Word.word_toNat_ofNat, Challenge.EvmProof.Word.ofNat_add_mod,
      Challenge.EvmProof.Word.succ_ofNat, List.getElem?_cons_zero, List.getElem?_cons_succ]

/-- Complete before-jump evaluation of the quad helper for this form. -/
theorem runInstrSeq_template (s : State) (startPC p0 p1 p2 p3 returnPC M0 M1 M2 M3 constant : UInt256)
    (x : EvmWorking) (rest : List UInt256)
    (hstack : rest.length < 1000) (hrun : s.halt = .Running)
    (hactive : 67 ≤ s.activeWords.toNat)
    (hp0 : p0.toNat + 32 ≤ 2144) (hp1 : p1.toNat + 32 ≤ 2144)
    (hp2 : p2.toNat + 32 ≤ 2144) (hp3 : p3.toNat + 32 ≤ 2144) :
    runInstrSeq (quadBeforeJumpTemplate 2 constant)
      (quadHelperEntry s startPC p0 p1 p2 p3 returnPC M0 M1 M2 M3 x rest) =
    some (quadAfterHelperBeforeJump s (pcAfter startPC (quadBeforeJumpTemplate 2 constant))
      returnPC (quadWorking s x 2 p0 p1 p2 p3 M0 M1 M2 M3 constant) rest) := by
  have hrun' : ∀ (pc : UInt256) (st : List UInt256),
      ({ s with pc := pc, stack := st } : State).halt = .Running := by
    intro pc st; simpa using hrun
  have h0 := runInstrSeq_round0 s startPC p0 p1 p2 p3 returnPC M0 M1 M2 M3 constant x rest hstack hrun hactive hp0 hp1 hp2 hp3
  have h1 := runInstrSeq_round1 s startPC p0 p1 p2 p3 returnPC M0 M1 M2 M3 constant x rest hstack hrun hactive hp0 hp1 hp2 hp3
  have h2 := runInstrSeq_round2 s startPC p0 p1 p2 p3 returnPC M0 M1 M2 M3 constant x rest hstack hrun hactive hp0 hp1 hp2 hp3
  have h3 := runInstrSeq_round3 s startPC p0 p1 p2 p3 returnPC M0 M1 M2 M3 constant x rest hstack hrun hactive hp0 hp1 hp2 hp3
  have h5 := runInstrSeq_fixup s startPC p0 p1 p2 p3 returnPC M0 M1 M2 M3 constant x rest hstack hrun hactive hp0 hp1 hp2 hp3
  have hentry : quadHelperEntry s startPC p0 p1 p2 p3 returnPC M0 M1 M2 M3 x rest =
      { s with pc := startPC, stack := [p0, returnPC, M0, p1, M1, p2, M2, p3, M3, x.a, x.b, x.c, x.d, x.e] ++ rest } := by
    simp [quadHelperEntry, roundWords]
  have hexit : quadAfterHelperBeforeJump s (pcAfter startPC (quadBeforeJumpTemplate 2 constant)) returnPC
      (quadWorking s x 2 p0 p1 p2 p3 M0 M1 M2 M3 constant) rest =
      { s with pc := pcAfter startPC (((((seg2_0 ++ seg2_1 constant) ++ seg2_2 constant) ++ seg2_3 constant) ++ seg2_4 constant) ++ seg2_5), stack := [returnPC, (qRound (qRound (qRound (qRound x 2 (MachineState.readWord s.memory p0.toNat) M0 constant) 2 (MachineState.readWord s.memory p1.toNat) M1 constant) 2 (MachineState.readWord s.memory p2.toNat) M2 constant) 2 (MachineState.readWord s.memory p3.toNat) M3 constant).a, (qRound (qRound (qRound (qRound x 2 (MachineState.readWord s.memory p0.toNat) M0 constant) 2 (MachineState.readWord s.memory p1.toNat) M1 constant) 2 (MachineState.readWord s.memory p2.toNat) M2 constant) 2 (MachineState.readWord s.memory p3.toNat) M3 constant).b, (qRound (qRound (qRound (qRound x 2 (MachineState.readWord s.memory p0.toNat) M0 constant) 2 (MachineState.readWord s.memory p1.toNat) M1 constant) 2 (MachineState.readWord s.memory p2.toNat) M2 constant) 2 (MachineState.readWord s.memory p3.toNat) M3 constant).c, (qRound (qRound (qRound (qRound x 2 (MachineState.readWord s.memory p0.toNat) M0 constant) 2 (MachineState.readWord s.memory p1.toNat) M1 constant) 2 (MachineState.readWord s.memory p2.toNat) M2 constant) 2 (MachineState.readWord s.memory p3.toNat) M3 constant).d, (qRound (qRound (qRound (qRound x 2 (MachineState.readWord s.memory p0.toNat) M0 constant) 2 (MachineState.readWord s.memory p1.toNat) M1 constant) 2 (MachineState.readWord s.memory p2.toNat) M2 constant) 2 (MachineState.readWord s.memory p3.toNat) M3 constant).e] ++ rest } := by
    simp only [quadAfterHelperBeforeJump, quadWorking, roundWords, quadBeforeJumpTemplate, quadBeforeJumpTemplate2]
  rw [hentry, hexit]
  show runInstrSeq (((((seg2_0 ++ seg2_1 constant) ++ seg2_2 constant) ++ seg2_3 constant) ++ seg2_4 constant) ++ seg2_5) _ = _
  refine runInstrSeq_append ?_ h5 (hrun' _ _)
  refine runInstrSeq_append ?_ h3 (hrun' _ _)
  refine runInstrSeq_append ?_ h2 (hrun' _ _)
  exact runInstrSeq_append h0 h1 (hrun' _ _)

end Challenge.Ripemd160.Submission.Proofs.Bytecode.QuadRawTrace2
