import Challenge.Ripemd160.Submission.Proofs.Bytecode.PairedDivMaskCache
import Challenge.Ripemd160.Submission.Proofs.Bytecode.PairTable144Scratch
import Challenge.Ripemd160.Submission.Proofs.Bytecode.PairTable144Pad
import Challenge.Ripemd160.Submission.Proofs.Bytecode.PairTable144Active
set_option warningAsError true
namespace Challenge.Ripemd160.Submission.Proofs.Bytecode.Table144Setup
open EvmSemantics EvmSemantics.EVM YulEvmCompiler Challenge.EvmProof
theorem push0_toNat : ({val := 0} : UInt256).toNat = 0 := rfl

def initialTemplate : List Instr :=
  [ .op .JUMPDEST,
    .push ⟨4, by decide⟩ (UInt256.ofNat 4294967295),
    .push ⟨2, by decide⟩ (UInt256.ofNat 257),
    .push ⟨0, by decide⟩ (UInt256.ofNat 0),
    .op .NOT,
    .op .DIV,
    .push ⟨3, by decide⟩ (UInt256.ofNat 65537),
    .push ⟨0, by decide⟩ (UInt256.ofNat 0),
    .op .NOT,
    .op .DIV,
    .op (.Swap ⟨2, by decide⟩),
    .op (.Dup ⟨0, by decide⟩),
    .op .MLOAD,
    .op (.Swap ⟨0, by decide⟩),
    .push ⟨1, by decide⟩ (UInt256.ofNat 32),
    .op .ADD,
    .op .MLOAD ]
def endianTemplate : List Instr :=
  [ .op (.Dup ⟨0, by decide⟩),
    .op (.Dup ⟨0, by decide⟩),
    .push ⟨1, by decide⟩ (UInt256.ofNat 8),
    .op .SHR,
    .op .XOR,
    .op (.Dup ⟨3, by decide⟩),
    .op .AND,
    .push ⟨2, by decide⟩ (UInt256.ofNat 257),
    .op .MUL,
    .op .XOR,
    .op (.Dup ⟨0, by decide⟩),
    .op (.Dup ⟨0, by decide⟩),
    .push ⟨1, by decide⟩ (UInt256.ofNat 16),
    .op .SHR,
    .op .XOR,
    .op (.Dup ⟨5, by decide⟩),
    .op .AND,
    .push ⟨3, by decide⟩ (UInt256.ofNat 65537),
    .op .MUL,
    .op .XOR,
    .push ⟨1, by decide⟩ (UInt256.ofNat 60),
    .op .MSTORE,
    .op (.Dup ⟨0, by decide⟩),
    .op (.Dup ⟨0, by decide⟩),
    .push ⟨1, by decide⟩ (UInt256.ofNat 8),
    .op .SHR,
    .op .XOR,
    .op (.Dup ⟨2, by decide⟩),
    .op .AND,
    .push ⟨2, by decide⟩ (UInt256.ofNat 257),
    .op .MUL,
    .op .XOR,
    .op (.Dup ⟨0, by decide⟩),
    .op (.Dup ⟨0, by decide⟩),
    .push ⟨1, by decide⟩ (UInt256.ofNat 16),
    .op .SHR,
    .op .XOR,
    .op (.Dup ⟨4, by decide⟩),
    .op .AND,
    .push ⟨3, by decide⟩ (UInt256.ofNat 65537),
    .op .MUL,
    .op .XOR,
    .push ⟨1, by decide⟩ (UInt256.ofNat 28),
    .op .MSTORE,
    .op .POP,
    .op (.Swap ⟨0, by decide⟩),
    .op .POP ]
def poolTemplate : List Instr :=
  [ .push ⟨1, by decide⟩ (UInt256.ofNat 60),
    .op .MLOAD,
    .op (.Dup ⟨1, by decide⟩),
    .op .AND,
    .push ⟨1, by decide⟩ (UInt256.ofNat 12),
    .op .MLOAD,
    .op (.Dup ⟨2, by decide⟩),
    .op .AND,
    .push ⟨1, by decide⟩ (UInt256.ofNat 24),
    .op .MLOAD,
    .op (.Dup ⟨3, by decide⟩),
    .op .AND,
    .push ⟨1, by decide⟩ (UInt256.ofNat 36),
    .op .MLOAD,
    .op (.Dup ⟨4, by decide⟩),
    .op .AND,
    .push ⟨1, by decide⟩ (UInt256.ofNat 4),
    .op .MLOAD,
    .op (.Dup ⟨5, by decide⟩),
    .op .AND,
    .push ⟨1, by decide⟩ (UInt256.ofNat 44),
    .op .MLOAD,
    .op (.Dup ⟨6, by decide⟩),
    .op .AND,
    .push ⟨1, by decide⟩ (UInt256.ofNat 32),
    .op .MLOAD,
    .op (.Dup ⟨7, by decide⟩),
    .op .AND,
    .push ⟨1, by decide⟩ (UInt256.ofNat 52),
    .op .MLOAD,
    .op (.Dup ⟨8, by decide⟩),
    .op .AND,
    .push ⟨1, by decide⟩ (UInt256.ofNat 40),
    .op .MLOAD,
    .op (.Dup ⟨9, by decide⟩),
    .op .AND,
    .push ⟨1, by decide⟩ (UInt256.ofNat 16),
    .op .MLOAD,
    .op (.Dup ⟨10, by decide⟩),
    .op .AND,
    .push ⟨1, by decide⟩ (UInt256.ofNat 28),
    .op .MLOAD,
    .op (.Dup ⟨11, by decide⟩),
    .op .AND,
    .push ⟨1, by decide⟩ (UInt256.ofNat 48),
    .op .MLOAD,
    .op (.Dup ⟨12, by decide⟩),
    .op .AND,
    .push ⟨1, by decide⟩ (UInt256.ofNat 8),
    .op .MLOAD,
    .op (.Dup ⟨13, by decide⟩),
    .op .AND,
    .push ⟨1, by decide⟩ (UInt256.ofNat 20),
    .op .MLOAD,
    .op (.Dup ⟨14, by decide⟩),
    .op .AND,
    .push ⟨1, by decide⟩ (UInt256.ofNat 56),
    .op .MLOAD,
    .op (.Dup ⟨15, by decide⟩),
    .op .AND,
    .op (.Swap ⟨14, by decide⟩),
    .push ⟨0, by decide⟩ (UInt256.ofNat 0),
    .op .MLOAD,
    .op .AND ]
def storesTemplate : List Instr :=
  [ .op (.Dup ⟨12, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 1386),
    .op .MSTORE,
    .op (.Dup ⟨6, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 1368),
    .op .MSTORE,
    .op (.Dup ⟨0, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 1350),
    .op .MSTORE,
    .op (.Dup ⟨1, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 1332),
    .op .MSTORE,
    .op (.Dup ⟨3, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 1314),
    .op .MSTORE,
    .op (.Dup ⟨10, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 1296),
    .op .MSTORE,
    .op (.Dup ⟨4, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 1278),
    .op .MSTORE,
    .op (.Dup ⟨8, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 1260),
    .op .MSTORE,
    .op (.Dup ⟨12, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 1242),
    .op .MSTORE,
    .op (.Dup ⟨2, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 1224),
    .op .MSTORE,
    .op (.Dup ⟨4, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 1206),
    .op .MSTORE,
    .op (.Dup ⟨2, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 1188),
    .op .MSTORE,
    .op (.Dup ⟨8, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 1170),
    .op .MSTORE,
    .op (.Dup ⟨15, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 1152),
    .op .MSTORE,
    .op (.Dup ⟨10, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 1134),
    .op .MSTORE,
    .op (.Dup ⟨2, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 1116),
    .op .MSTORE,
    .op (.Dup ⟨5, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 1098),
    .op .MSTORE,
    .op (.Dup ⟨0, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 1080),
    .op .MSTORE,
    .op (.Dup ⟨3, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 1062),
    .op .MSTORE,
    .op (.Dup ⟨1, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 1044),
    .op .MSTORE,
    .op (.Dup ⟨4, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 1026),
    .op .MSTORE,
    .op (.Dup ⟨10, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 1008),
    .op .MSTORE,
    .op (.Dup ⟨11, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 990),
    .op .MSTORE,
    .op (.Dup ⟨8, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 972),
    .op .MSTORE,
    .op (.Dup ⟨2, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 954),
    .op .MSTORE,
    .op (.Dup ⟨9, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 936),
    .op .MSTORE,
    .op (.Dup ⟨0, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 918),
    .op .MSTORE,
    .op (.Dup ⟨13, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 900),
    .op .MSTORE,
    .push ⟨2, by decide⟩ (UInt256.ofNat 882),
    .op .MSTORE,
    .op (.Dup ⟨13, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 864),
    .op .MSTORE,
    .op (.Dup ⟨2, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 846),
    .op .MSTORE,
    .op (.Dup ⟨6, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 828),
    .op .MSTORE,
    .op (.Dup ⟨0, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 810),
    .op .MSTORE,
    .op (.Dup ⟨5, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 792),
    .op .MSTORE,
    .op (.Dup ⟨0, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 774),
    .op .MSTORE,
    .op (.Dup ⟨4, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 756),
    .op .MSTORE,
    .op (.Dup ⟨2, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 738),
    .op .MSTORE,
    .op (.Dup ⟨13, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 720),
    .op .MSTORE,
    .op (.Dup ⟨10, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 702),
    .op .MSTORE,
    .op (.Dup ⟨4, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 684),
    .op .MSTORE,
    .op (.Dup ⟨8, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 666),
    .op .MSTORE,
    .op (.Dup ⟨4, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 648),
    .op .MSTORE,
    .op (.Dup ⟨10, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 630),
    .op .MSTORE,
    .op (.Dup ⟨3, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 612),
    .op .MSTORE,
    .op (.Dup ⟨11, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 594),
    .op .MSTORE,
    .op (.Dup ⟨8, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 576),
    .op .MSTORE,
    .op (.Dup ⟨13, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 558),
    .op .MSTORE,
    .push ⟨2, by decide⟩ (UInt256.ofNat 540),
    .op .MSTORE,
    .push ⟨2, by decide⟩ (UInt256.ofNat 522),
    .op .MSTORE,
    .op (.Dup ⟨12, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 504),
    .op .MSTORE,
    .op (.Dup ⟨10, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 486),
    .op .MSTORE,
    .push ⟨2, by decide⟩ (UInt256.ofNat 468),
    .op .MSTORE,
    .op (.Dup ⟨11, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 450),
    .op .MSTORE,
    .op (.Dup ⟨8, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 432),
    .op .MSTORE,
    .op (.Dup ⟨3, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 414),
    .op .MSTORE,
    .op (.Dup ⟨2, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 396),
    .op .MSTORE,
    .push ⟨2, by decide⟩ (UInt256.ofNat 378),
    .op .MSTORE,
    .push ⟨2, by decide⟩ (UInt256.ofNat 360),
    .op .MSTORE,
    .op (.Dup ⟨7, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 342),
    .op .MSTORE,
    .op (.Dup ⟨0, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 324),
    .op .MSTORE,
    .op (.Dup ⟨8, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 306),
    .op .MSTORE,
    .op (.Dup ⟨1, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 288),
    .op .MSTORE,
    .op (.Dup ⟨7, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 270),
    .op .MSTORE,
    .op (.Dup ⟨1, by decide⟩),
    .push ⟨1, by decide⟩ (UInt256.ofNat 252),
    .op .MSTORE,
    .push ⟨1, by decide⟩ (UInt256.ofNat 234),
    .op .MSTORE,
    .op (.Dup ⟨3, by decide⟩),
    .push ⟨1, by decide⟩ (UInt256.ofNat 216),
    .op .MSTORE,
    .op (.Dup ⟨1, by decide⟩),
    .push ⟨1, by decide⟩ (UInt256.ofNat 198),
    .op .MSTORE,
    .push ⟨1, by decide⟩ (UInt256.ofNat 180),
    .op .MSTORE,
    .op (.Dup ⟨1, by decide⟩),
    .push ⟨1, by decide⟩ (UInt256.ofNat 162),
    .op .MSTORE,
    .push ⟨1, by decide⟩ (UInt256.ofNat 144),
    .op .MSTORE,
    .push ⟨1, by decide⟩ (UInt256.ofNat 126),
    .op .MSTORE,
    .push ⟨1, by decide⟩ (UInt256.ofNat 108),
    .op .MSTORE,
    .op (.Dup ⟨4, by decide⟩),
    .push ⟨1, by decide⟩ (UInt256.ofNat 90),
    .op .MSTORE,
    .push ⟨1, by decide⟩ (UInt256.ofNat 72),
    .op .MSTORE,
    .push ⟨1, by decide⟩ (UInt256.ofNat 54),
    .op .MSTORE,
    .push ⟨1, by decide⟩ (UInt256.ofNat 36),
    .op .MSTORE,
    .push ⟨1, by decide⟩ (UInt256.ofNat 18),
    .op .MSTORE,
    .push ⟨0, by decide⟩ (UInt256.ofNat 0),
    .op .MSTORE ]
def padTemplate : List Instr :=
  [ .push ⟨2, by decide⟩ (UInt256.ofNat 1418),
    .op .CALLDATASIZE,
    .push ⟨0, by decide⟩ (UInt256.ofNat 0),
    .op .CALLDATACOPY,
    .op .CALLDATASIZE,
    .push ⟨1, by decide⟩ (UInt256.ofNat 227),
    .op .SHL,
    .push ⟨1, by decide⟩ (UInt256.ofNat 224),
    .op .SHR,
    .op .CALLDATASIZE,
    .push ⟨1, by decide⟩ (UInt256.ofNat 29),
    .op .SHR,
    .push ⟨4, by decide⟩ (UInt256.ofNat 4294967295),
    .op .AND,
    .push ⟨1, by decide⟩ (UInt256.ofNat 128),
    .op (.Dup ⟨0, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 1350),
    .op .MSTORE,
    .op (.Dup ⟨2, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 1152),
    .op .MSTORE,
    .op (.Dup ⟨0, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 1080),
    .op .MSTORE,
    .op (.Dup ⟨0, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 918),
    .op .MSTORE,
    .push ⟨2, by decide⟩ (UInt256.ofNat 882),
    .op .MSTORE,
    .op (.Dup ⟨0, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 864),
    .op .MSTORE,
    .op (.Dup ⟨0, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 720),
    .op .MSTORE,
    .op (.Dup ⟨0, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 558),
    .op .MSTORE,
    .op (.Dup ⟨1, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 504),
    .op .MSTORE,
    .op (.Dup ⟨1, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 450),
    .op .MSTORE,
    .op (.Dup ⟨0, by decide⟩),
    .push ⟨2, by decide⟩ (UInt256.ofNat 306),
    .op .MSTORE,
    .op (.Dup ⟨1, by decide⟩),
    .push ⟨1, by decide⟩ (UInt256.ofNat 90),
    .op .MSTORE,
    .push ⟨1, by decide⟩ (UInt256.ofNat 18),
    .op .MSTORE,
    .push ⟨0, by decide⟩ (UInt256.ofNat 0),
    .op .MSTORE ]
def cacheTemplate : List Instr :=
  [ .op .JUMPDEST,
    .push ⟨14, by decide⟩ (UInt256.ofNat 20282409608374036906851256238088),
    .push ⟨1, by decide⟩ (UInt256.ofNat 15),
    .push ⟨5, by decide⟩ (UInt256.ofNat 17179869188),
    .op (.Dup ⟨2, by decide⟩),
    .op .SUB,
    .push ⟨1, by decide⟩ (UInt256.ofNat 127),
    .push ⟨4, by decide⟩ (UInt256.ofNat 4294967295),
    .op (.Dup ⟨0, by decide⟩),
    .push ⟨1, by decide⟩ (UInt256.ofNat 72),
    .op .SHL,
    .op (.Dup ⟨0, by decide⟩),
    .op (.Dup ⟨2, by decide⟩),
    .op .ADD,
    .op (.Swap ⟨1, by decide⟩),
    .push ⟨1, by decide⟩ (UInt256.ofNat 28),
    .op (.Swap ⟨1, by decide⟩),
    .push ⟨1, by decide⟩ (UInt256.ofNat 72),
    .op .SHL,
    .op (.Dup ⟨1, by decide⟩),
    .op (.Dup ⟨1, by decide⟩),
    .op .ADD,
    .op (.Dup ⟨2, by decide⟩),
    .op (.Dup ⟨1, by decide⟩),
    .op .DIV ]
def hashTemplate : List Instr :=
  [ .op (.Dup ⟨14, by decide⟩),
    .op (.Dup ⟨1, by decide⟩),
    .op .MUL,
    .op (.Dup ⟨14, by decide⟩),
    .op (.Dup ⟨2, by decide⟩),
    .op .MUL,
    .op (.Dup ⟨14, by decide⟩),
    .op (.Dup ⟨3, by decide⟩),
    .op .MUL,
    .op (.Dup ⟨14, by decide⟩),
    .op (.Dup ⟨4, by decide⟩),
    .op .MUL,
    .op (.Dup ⟨14, by decide⟩),
    .op (.Dup ⟨5, by decide⟩),
    .op .MUL ]
def factorTemplate : List Instr :=
  [ .op (.Dup ⟨14, by decide⟩),
    .push ⟨5, by decide⟩ (UInt256.ofNat 240518168632),
    .op .ADD,
    .op (.Swap ⟨5, by decide⟩),
    .op .POP ]
def keyTemplate : List Instr :=
  [ .push ⟨4, by decide⟩ (UInt256.ofNat 1352829926),
    .push ⟨1, by decide⟩ (UInt256.ofNat 144),
    .op .SHL ]
def poolStack (words : Nat → UInt256) : List UInt256 :=
  [words 0, words 5, words 2, words 12, words 7, words 4, words 10, words 13, words 8, words 11, words 1, words 9, words 6, words 3, words 15, words 14]
end Challenge.Ripemd160.Submission.Proofs.Bytecode.Table144Setup
