import Challenge.Modexp.Submission.Proofs.Fast.CiosStackCacheFrames
import Challenge.Modexp.Submission.Proofs.Fast.CiosCachedPrograms

set_option warningAsError true

/-! Exact blocks decoded from the 661462-gas prototype, raw SHA256
1d2aeafe40ae602df5bef3b1fb7a96c7068260a2cbcf2e4dcaa19a919131339c.
These lists do not assert that the complete candidate theorem is proved. -/
namespace Challenge.Modexp.Submission.Proofs.Fast.CiosStackCachePrograms

open EvmSemantics EvmSemantics.EVM YulEvmCompiler

/-- Bytes 4476 through 4590. -/
def entry : List Instr :=
  [.op .JUMPDEST,
   .push 2 9440,
   .op .MLOAD,
   .push 2 9376,
   .op .MLOAD,
   .push 1 32,
   .op .MLOAD,
   .push 0 0,
   .op .MLOAD,
   .push 2 9408,
   .op .MLOAD,
   .op .MLOAD,
   .push 0 0,
   .push 0 0,
   .push 0 0,
   .op (.Swap ⟨1, by decide⟩),
   .op (.Swap ⟨3, by decide⟩),
   .op (.Swap ⟨5, by decide⟩),
   .op (.Swap ⟨7, by decide⟩),
   .op (.Swap ⟨0, by decide⟩),
   .op (.Swap ⟨2, by decide⟩),
   .op (.Swap ⟨4, by decide⟩),
   .op (.Swap ⟨6, by decide⟩),
   .op (.Swap ⟨8, by decide⟩),
   .op (.Swap ⟨0, by decide⟩),
   .push 32 115792089237316195423570985008687907853269984665640564039457584007913129639935,
   .op (.Swap ⟨1, by decide⟩),
   .push 32 115792089237316195423570985008687907853269984665640564039457584007913129639904,
   .op (.Swap ⟨1, by decide⟩),
   .push 2 9344,
   .op .MLOAD,
   .push 1 128,
   .op .EQ,
   .op (.Swap ⟨1, by decide⟩),
   .op (.Swap ⟨0, by decide⟩),
   .push 2 9344,
   .op .MLOAD,
   .op (.Dup ⟨0, by decide⟩),
   .push 1 64,
   .op .ADD,
   .op .CALLDATASIZE,
   .push 2 8192,
   .op .CALLDATACOPY,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Dup ⟨3, by decide⟩),
   .op .ADD,
   .push 1 32,
   .op (.Swap ⟨0, by decide⟩),
   .op .SUB,
   .push 1 32,
   .op (.Dup ⟨4, by decide⟩),
   .op .SUB,
   .op (.Swap ⟨3, by decide⟩),
   .op .POP,
   .op (.Swap ⟨1, by decide⟩),
   .op .ADD,
   .op (.Swap ⟨0, by decide⟩),
   .push 1 32,
   .op (.Dup ⟨2, by decide⟩),
   .op .SUB,
   .op (.Swap ⟨1, by decide⟩),
   .op .POP]

/-- Bytes 4476 through 4478. -/
def prologue : List Instr :=
  [.op .JUMPDEST,
   .push 2 9440,
   .op .MLOAD,
   .push 2 9376,
   .op .MLOAD,
   .push 1 32,
   .op .MLOAD,
   .push 0 0,
   .op .MLOAD,
   .push 2 9408,
   .op .MLOAD,
   .op .MLOAD,
   .push 0 0,
   .push 0 0,
   .push 0 0,
   .op (.Swap ⟨1, by decide⟩),
   .op (.Swap ⟨3, by decide⟩),
   .op (.Swap ⟨5, by decide⟩),
   .op (.Swap ⟨7, by decide⟩),
   .op (.Swap ⟨0, by decide⟩),
   .op (.Swap ⟨2, by decide⟩),
   .op (.Swap ⟨4, by decide⟩),
   .op (.Swap ⟨6, by decide⟩),
   .op (.Swap ⟨8, by decide⟩),
   .op (.Swap ⟨0, by decide⟩)]

/-- Bytes 4508 through 4555. -/
def entryHead : List Instr :=
  [.push 32 115792089237316195423570985008687907853269984665640564039457584007913129639935,
   .op (.Swap ⟨1, by decide⟩),
   .push 32 115792089237316195423570985008687907853269984665640564039457584007913129639904,
   .op (.Swap ⟨1, by decide⟩),
   .push 2 9344,
   .op .MLOAD,
   .push 1 128,
   .op .EQ,
   .op (.Swap ⟨1, by decide⟩),
   .op (.Swap ⟨0, by decide⟩)]

/-- Bytes 4585 through 4590. -/
def entryBody : List Instr :=
  [.push 2 9344,
   .op .MLOAD,
   .op (.Dup ⟨0, by decide⟩),
   .push 1 64,
   .op .ADD,
   .op .CALLDATASIZE,
   .push 2 8192,
   .op .CALLDATACOPY,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Dup ⟨3, by decide⟩),
   .op .ADD,
   .push 1 32,
   .op (.Swap ⟨0, by decide⟩),
   .op .SUB,
   .push 1 32,
   .op (.Dup ⟨4, by decide⟩),
   .op .SUB,
   .op (.Swap ⟨3, by decide⟩),
   .op .POP,
   .op (.Swap ⟨1, by decide⟩),
   .op .ADD,
   .op (.Swap ⟨0, by decide⟩),
   .push 1 32,
   .op (.Dup ⟨2, by decide⟩),
   .op .SUB,
   .op (.Swap ⟨1, by decide⟩),
   .op .POP]

/-- Bytes 4620 through 4595. -/
def out : List Instr :=
  [.op .JUMPDEST,
   .op (.Dup ⟨0, by decide⟩),
   .op .MLOAD,
   .push 0 0,
   .op (.Dup ⟨3, by decide⟩)]

/-- Bytes 4625 through 4600. -/
def l1Dispatch : List Instr :=
  [.op (.Dup ⟨6, by decide⟩),
   .push 2 4782,
   .op .JUMPI]

/-- Bytes 4630 through 4638. -/
def l1Mac0 : List Instr :=
  [.op (.Dup ⟨0, by decide⟩),
   .op .MLOAD,
   .op (.Dup ⟨9, by decide⟩),
   .op (.Dup ⟨4, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .MUL,
   .op (.Swap ⟨1, by decide⟩),
   .op (.Dup ⟨5, by decide⟩),
   .op .MULMOD,
   .op (.Dup ⟨1, by decide⟩),
   .op (.Dup ⟨1, by decide⟩),
   .op .LT,
   .op .SUB,
   .op (.Dup ⟨3, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨4, by decide⟩),
   .op .GT,
   .op .SUB,
   .op .SUB,
   .op (.Dup ⟨2, by decide⟩),
   .push 2 8480,
   .op .MLOAD,
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨3, by decide⟩),
   .op .GT,
   .op .ADD,
   .op (.Swap ⟨1, by decide⟩),
   .push 2 8480,
   .op .MSTORE,
   .op (.Dup ⟨7, by decide⟩),
   .op .ADD]

/-- Bytes 4668 through 4676. -/
def l1Mac1 : List Instr :=
  [.op (.Dup ⟨0, by decide⟩),
   .op .MLOAD,
   .op (.Dup ⟨9, by decide⟩),
   .op (.Dup ⟨4, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .MUL,
   .op (.Swap ⟨1, by decide⟩),
   .op (.Dup ⟨5, by decide⟩),
   .op .MULMOD,
   .op (.Dup ⟨1, by decide⟩),
   .op (.Dup ⟨1, by decide⟩),
   .op .LT,
   .op .SUB,
   .op (.Dup ⟨3, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨4, by decide⟩),
   .op .GT,
   .op .SUB,
   .op .SUB,
   .op (.Dup ⟨2, by decide⟩),
   .push 2 8448,
   .op .MLOAD,
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨3, by decide⟩),
   .op .GT,
   .op .ADD,
   .op (.Swap ⟨1, by decide⟩),
   .push 2 8448,
   .op .MSTORE,
   .op (.Dup ⟨7, by decide⟩),
   .op .ADD]

/-- Bytes 4706 through 4714. -/
def l1Mac2 : List Instr :=
  [.op (.Dup ⟨0, by decide⟩),
   .op .MLOAD,
   .op (.Dup ⟨9, by decide⟩),
   .op (.Dup ⟨4, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .MUL,
   .op (.Swap ⟨1, by decide⟩),
   .op (.Dup ⟨5, by decide⟩),
   .op .MULMOD,
   .op (.Dup ⟨1, by decide⟩),
   .op (.Dup ⟨1, by decide⟩),
   .op .LT,
   .op .SUB,
   .op (.Dup ⟨3, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨4, by decide⟩),
   .op .GT,
   .op .SUB,
   .op .SUB,
   .op (.Dup ⟨2, by decide⟩),
   .push 2 8416,
   .op .MLOAD,
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨3, by decide⟩),
   .op .GT,
   .op .ADD,
   .op (.Swap ⟨1, by decide⟩),
   .push 2 8416,
   .op .MSTORE,
   .op (.Dup ⟨7, by decide⟩),
   .op .ADD]

/-- Bytes 4744 through 4752. -/
def l1Mac3 : List Instr :=
  [.op (.Dup ⟨0, by decide⟩),
   .op .MLOAD,
   .op (.Dup ⟨9, by decide⟩),
   .op (.Dup ⟨4, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .MUL,
   .op (.Swap ⟨1, by decide⟩),
   .op (.Dup ⟨5, by decide⟩),
   .op .MULMOD,
   .op (.Dup ⟨1, by decide⟩),
   .op (.Dup ⟨1, by decide⟩),
   .op .LT,
   .op .SUB,
   .op (.Dup ⟨3, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨4, by decide⟩),
   .op .GT,
   .op .SUB,
   .op .SUB,
   .op (.Dup ⟨2, by decide⟩),
   .push 2 8384,
   .op .MLOAD,
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨3, by decide⟩),
   .op .GT,
   .op .ADD,
   .op (.Swap ⟨1, by decide⟩),
   .push 2 8384,
   .op .MSTORE,
   .op (.Dup ⟨7, by decide⟩),
   .op .ADD]

/-- Bytes 4782 through 4753. -/
def l1Join : List Instr :=
  [.op .JUMPDEST]

/-- Bytes 4783 through 4791. -/
def l1Mac4 : List Instr :=
  [.op (.Dup ⟨0, by decide⟩),
   .op .MLOAD,
   .op (.Dup ⟨9, by decide⟩),
   .op (.Dup ⟨4, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .MUL,
   .op (.Swap ⟨1, by decide⟩),
   .op (.Dup ⟨5, by decide⟩),
   .op .MULMOD,
   .op (.Dup ⟨1, by decide⟩),
   .op (.Dup ⟨1, by decide⟩),
   .op .LT,
   .op .SUB,
   .op (.Dup ⟨3, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨4, by decide⟩),
   .op .GT,
   .op .SUB,
   .op .SUB,
   .op (.Dup ⟨2, by decide⟩),
   .push 2 8352,
   .op .MLOAD,
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨3, by decide⟩),
   .op .GT,
   .op .ADD,
   .op (.Swap ⟨1, by decide⟩),
   .push 2 8352,
   .op .MSTORE,
   .op (.Dup ⟨7, by decide⟩),
   .op .ADD]

/-- Bytes 4821 through 4824. -/
def l1Mac5 : List Instr :=
  [.op (.Dup ⟨0, by decide⟩),
   .op .MLOAD,
   .op (.Dup ⟨9, by decide⟩),
   .op (.Dup ⟨4, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .MUL,
   .op (.Swap ⟨1, by decide⟩),
   .op (.Dup ⟨5, by decide⟩),
   .op .MULMOD,
   .op (.Dup ⟨1, by decide⟩),
   .op (.Dup ⟨1, by decide⟩),
   .op .LT,
   .op .SUB,
   .op (.Dup ⟨3, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨4, by decide⟩),
   .op .GT,
   .op .SUB,
   .op .SUB,
   .op (.Dup ⟨2, by decide⟩),
   .op (.Dup ⟨13, by decide⟩),
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨3, by decide⟩),
   .op .GT,
   .op .ADD,
   .op (.Swap ⟨1, by decide⟩),
   .op (.Swap ⟨11, by decide⟩),
   .op .POP,
   .op (.Dup ⟨7, by decide⟩),
   .op .ADD]

/-- Bytes 4854 through 4857. -/
def l1Mac6 : List Instr :=
  [.op (.Dup ⟨0, by decide⟩),
   .op .MLOAD,
   .op (.Dup ⟨9, by decide⟩),
   .op (.Dup ⟨4, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .MUL,
   .op (.Swap ⟨1, by decide⟩),
   .op (.Dup ⟨5, by decide⟩),
   .op .MULMOD,
   .op (.Dup ⟨1, by decide⟩),
   .op (.Dup ⟨1, by decide⟩),
   .op .LT,
   .op .SUB,
   .op (.Dup ⟨3, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨4, by decide⟩),
   .op .GT,
   .op .SUB,
   .op .SUB,
   .op (.Dup ⟨2, by decide⟩),
   .op (.Dup ⟨12, by decide⟩),
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨3, by decide⟩),
   .op .GT,
   .op .ADD,
   .op (.Swap ⟨1, by decide⟩),
   .op (.Swap ⟨10, by decide⟩),
   .op .POP,
   .op (.Dup ⟨7, by decide⟩),
   .op .ADD]

/-- Bytes 4887 through 4889. -/
def l1Mac7 : List Instr :=
  [.op (.Dup ⟨0, by decide⟩),
   .op .MLOAD,
   .op (.Dup ⟨9, by decide⟩),
   .op (.Dup ⟨4, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .MUL,
   .op (.Swap ⟨1, by decide⟩),
   .op (.Dup ⟨5, by decide⟩),
   .op .MULMOD,
   .op (.Dup ⟨1, by decide⟩),
   .op (.Dup ⟨1, by decide⟩),
   .op .LT,
   .op .SUB,
   .op (.Dup ⟨3, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨4, by decide⟩),
   .op .GT,
   .op .SUB,
   .op .SUB,
   .op (.Dup ⟨2, by decide⟩),
   .op (.Dup ⟨11, by decide⟩),
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨3, by decide⟩),
   .op .GT,
   .op .ADD,
   .op (.Swap ⟨1, by decide⟩),
   .op (.Swap ⟨9, by decide⟩),
   .op .POP,
   .op .POP]

/-- Bytes 4919 through 4905. -/
def midStore : List Instr :=
  [.op (.Dup ⟨0, by decide⟩),
   .push 2 8224,
   .op .MLOAD,
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .push 2 8224,
   .op .MSTORE,
   .op .LT,
   .push 2 8192,
   .op .MSTORE]

/-- Bytes 4935 through 4923. -/
def midProduct : List Instr :=
  [.op (.Dup ⟨14, by decide⟩),
   .op .MLOAD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Dup ⟨15, by decide⟩),
   .op .MUL,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Dup ⟨13, by decide⟩),
   .op (.Dup ⟨10, by decide⟩),
   .op (.Swap ⟨1, by decide⟩),
   .op .MULMOD,
   .op (.Swap ⟨0, by decide⟩),
   .op (.Swap ⟨1, by decide⟩),
   .op (.Dup ⟨1, by decide⟩),
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨1, by decide⟩),
   .op .GT,
   .op .ADD]

/-- Bytes 4953 through 4928. -/
def l2Dispatch : List Instr :=
  [.op (.Dup ⟨6, by decide⟩),
   .push 2 5110,
   .op .JUMPI]

/-- Bytes 4958 through 4966. -/
def l2Mac0 : List Instr :=
  [.push 2 192,
   .op .MLOAD,
   .op (.Dup ⟨9, by decide⟩),
   .op (.Dup ⟨3, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .MUL,
   .op (.Swap ⟨1, by decide⟩),
   .op (.Dup ⟨4, by decide⟩),
   .op .MULMOD,
   .op (.Dup ⟨1, by decide⟩),
   .op (.Dup ⟨1, by decide⟩),
   .op .LT,
   .op .SUB,
   .op (.Dup ⟨2, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨3, by decide⟩),
   .op .GT,
   .op .SUB,
   .op .SUB,
   .op (.Dup ⟨1, by decide⟩),
   .push 2 8448,
   .op .MLOAD,
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨2, by decide⟩),
   .op .GT,
   .op .ADD,
   .op (.Swap ⟨0, by decide⟩),
   .push 2 8480,
   .op .MSTORE]

/-- Bytes 4996 through 5004. -/
def l2Mac1 : List Instr :=
  [.push 2 160,
   .op .MLOAD,
   .op (.Dup ⟨9, by decide⟩),
   .op (.Dup ⟨3, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .MUL,
   .op (.Swap ⟨1, by decide⟩),
   .op (.Dup ⟨4, by decide⟩),
   .op .MULMOD,
   .op (.Dup ⟨1, by decide⟩),
   .op (.Dup ⟨1, by decide⟩),
   .op .LT,
   .op .SUB,
   .op (.Dup ⟨2, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨3, by decide⟩),
   .op .GT,
   .op .SUB,
   .op .SUB,
   .op (.Dup ⟨1, by decide⟩),
   .push 2 8416,
   .op .MLOAD,
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨2, by decide⟩),
   .op .GT,
   .op .ADD,
   .op (.Swap ⟨0, by decide⟩),
   .push 2 8448,
   .op .MSTORE]

/-- Bytes 5034 through 5042. -/
def l2Mac2 : List Instr :=
  [.push 2 128,
   .op .MLOAD,
   .op (.Dup ⟨9, by decide⟩),
   .op (.Dup ⟨3, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .MUL,
   .op (.Swap ⟨1, by decide⟩),
   .op (.Dup ⟨4, by decide⟩),
   .op .MULMOD,
   .op (.Dup ⟨1, by decide⟩),
   .op (.Dup ⟨1, by decide⟩),
   .op .LT,
   .op .SUB,
   .op (.Dup ⟨2, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨3, by decide⟩),
   .op .GT,
   .op .SUB,
   .op .SUB,
   .op (.Dup ⟨1, by decide⟩),
   .push 2 8384,
   .op .MLOAD,
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨2, by decide⟩),
   .op .GT,
   .op .ADD,
   .op (.Swap ⟨0, by decide⟩),
   .push 2 8416,
   .op .MSTORE]

/-- Bytes 5072 through 5080. -/
def l2Mac3 : List Instr :=
  [.push 2 96,
   .op .MLOAD,
   .op (.Dup ⟨9, by decide⟩),
   .op (.Dup ⟨3, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .MUL,
   .op (.Swap ⟨1, by decide⟩),
   .op (.Dup ⟨4, by decide⟩),
   .op .MULMOD,
   .op (.Dup ⟨1, by decide⟩),
   .op (.Dup ⟨1, by decide⟩),
   .op .LT,
   .op .SUB,
   .op (.Dup ⟨2, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨3, by decide⟩),
   .op .GT,
   .op .SUB,
   .op .SUB,
   .op (.Dup ⟨1, by decide⟩),
   .push 2 8352,
   .op .MLOAD,
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨2, by decide⟩),
   .op .GT,
   .op .ADD,
   .op (.Swap ⟨0, by decide⟩),
   .push 2 8384,
   .op .MSTORE]

/-- Bytes 5110 through 5081. -/
def l2Join : List Instr :=
  [.op .JUMPDEST]

/-- Bytes 5111 through 5116. -/
def l2Mac4 : List Instr :=
  [.push 2 64,
   .op .MLOAD,
   .op (.Dup ⟨9, by decide⟩),
   .op (.Dup ⟨3, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .MUL,
   .op (.Swap ⟨1, by decide⟩),
   .op (.Dup ⟨4, by decide⟩),
   .op .MULMOD,
   .op (.Dup ⟨1, by decide⟩),
   .op (.Dup ⟨1, by decide⟩),
   .op .LT,
   .op .SUB,
   .op (.Dup ⟨2, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨3, by decide⟩),
   .op .GT,
   .op .SUB,
   .op .SUB,
   .op (.Dup ⟨1, by decide⟩),
   .op (.Dup ⟨13, by decide⟩),
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨2, by decide⟩),
   .op .GT,
   .op .ADD,
   .op (.Swap ⟨0, by decide⟩),
   .push 2 8352,
   .op .MSTORE]

/-- Bytes 5146 through 5146. -/
def l2Mac5 : List Instr :=
  [.op (.Dup ⟨14, by decide⟩),
   .op (.Dup ⟨9, by decide⟩),
   .op (.Dup ⟨3, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .MUL,
   .op (.Swap ⟨1, by decide⟩),
   .op (.Dup ⟨4, by decide⟩),
   .op .MULMOD,
   .op (.Dup ⟨1, by decide⟩),
   .op (.Dup ⟨1, by decide⟩),
   .op .LT,
   .op .SUB,
   .op (.Dup ⟨2, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨3, by decide⟩),
   .op .GT,
   .op .SUB,
   .op .SUB,
   .op (.Dup ⟨1, by decide⟩),
   .op (.Dup ⟨12, by decide⟩),
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨2, by decide⟩),
   .op .GT,
   .op .ADD,
   .op (.Swap ⟨0, by decide⟩),
   .op (.Swap ⟨11, by decide⟩),
   .op .POP]

/-- Bytes 5176 through 5176. -/
def l2Mac6 : List Instr :=
  [.op (.Dup ⟨13, by decide⟩),
   .op (.Dup ⟨9, by decide⟩),
   .op (.Dup ⟨3, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .MUL,
   .op (.Swap ⟨1, by decide⟩),
   .op (.Dup ⟨4, by decide⟩),
   .op .MULMOD,
   .op (.Dup ⟨1, by decide⟩),
   .op (.Dup ⟨1, by decide⟩),
   .op .LT,
   .op .SUB,
   .op (.Dup ⟨2, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨3, by decide⟩),
   .op .GT,
   .op .SUB,
   .op .SUB,
   .op (.Dup ⟨1, by decide⟩),
   .op (.Dup ⟨11, by decide⟩),
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨2, by decide⟩),
   .op .GT,
   .op .ADD,
   .op (.Swap ⟨0, by decide⟩),
   .op (.Swap ⟨10, by decide⟩),
   .op .POP]

/-- Bytes 5206 through 5179. -/
def tailCleanup : List Instr :=
  [.op (.Swap ⟨1, by decide⟩),
   .op .POP,
   .op .POP]

/-- Bytes 5209 through 5198. -/
def tailStore : List Instr :=
  [.op (.Dup ⟨0, by decide⟩),
   .push 2 8224,
   .op .MLOAD,
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨8, by decide⟩),
   .op .POP,
   .op .LT,
   .push 2 8192,
   .op .MLOAD,
   .op .ADD,
   .push 2 8224,
   .op .MSTORE]

/-- Bytes 5228 through 5207. -/
def tailTest : List Instr :=
  [.op (.Dup ⟨4, by decide⟩),
   .op .ADD,
   .op (.Dup ⟨2, by decide⟩),
   .op (.Dup ⟨1, by decide⟩),
   .op .GT,
   .push 2 4620,
   .op .JUMPI]

/-- Bytes 5237 through 5234. -/
def exit : List Instr :=
  [.op .POP,
   .op .POP,
   .op .POP,
   .op .POP,
   .op .POP,
   .op .POP,
   .push 2 8256,
   .op .MSTORE,
   .push 2 8288,
   .op .MSTORE,
   .push 2 8320,
   .op .MSTORE,
   .op .POP,
   .op .POP,
   .op .POP,
   .op .POP,
   .op .POP,
   .push 2 2288,
   .op .JUMP]

theorem entry_split : entry = (prologue ++ entryHead) ++ entryBody := rfl

end Challenge.Modexp.Submission.Proofs.Fast.CiosStackCachePrograms
