import Challenge.Modexp.Submission.Proofs.Fast.CiosStackCacheFrames
import Challenge.Modexp.Submission.Proofs.Fast.CiosCachedPrograms

set_option warningAsError true

/-! Exact blocks decoded from the 663659-gas prototype, raw SHA256
037aeb69c38a88ab1236856371455115158c782368347c09ff6fbb1f0644793d.
These lists do not assert that the complete candidate theorem is proved. -/
namespace Challenge.Modexp.Submission.Proofs.Fast.CiosStackCachePrograms

open EvmSemantics EvmSemantics.EVM YulEvmCompiler

/-- Bytes 4481 through 4594. -/
def entry : List Instr :=
  [.op .JUMPDEST,
   .push 2 9440,
   .op .MLOAD,
   .push 2 9376,
   .op .MLOAD,
   .push 1 32,
   .op .MLOAD,
   .push 0 0,
   .op .MLOAD,
   .push 2 9408,
   .op .MLOAD,
   .op .MLOAD,
   .push 0 0,
   .push 0 0,
   .push 0 0,
   .op (.Swap ⟨1, by decide⟩),
   .op (.Swap ⟨3, by decide⟩),
   .op (.Swap ⟨5, by decide⟩),
   .op (.Swap ⟨7, by decide⟩),
   .op (.Swap ⟨0, by decide⟩),
   .op (.Swap ⟨2, by decide⟩),
   .op (.Swap ⟨4, by decide⟩),
   .op (.Swap ⟨6, by decide⟩),
   .op (.Swap ⟨8, by decide⟩),
   .op (.Swap ⟨0, by decide⟩),
   .push 32 115792089237316195423570985008687907853269984665640564039457584007913129639904,
   .op (.Swap ⟨1, by decide⟩),
   .push 0 0,
   .op .NOT,
   .op (.Swap ⟨2, by decide⟩),
   .op (.Swap ⟨1, by decide⟩),
   .push 2 9344,
   .op .MLOAD,
   .push 1 128,
   .op .EQ,
   .op (.Swap ⟨1, by decide⟩),
   .op (.Swap ⟨0, by decide⟩),
   .push 2 9344,
   .op .MLOAD,
   .op (.Dup ⟨0, by decide⟩),
   .push 1 64,
   .op .ADD,
   .op .CALLDATASIZE,
   .push 2 8192,
   .op .CALLDATACOPY,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Dup ⟨3, by decide⟩),
   .op .ADD,
   .push 1 32,
   .op (.Swap ⟨0, by decide⟩),
   .op .SUB,
   .push 1 32,
   .op (.Dup ⟨4, by decide⟩),
   .op .SUB,
   .op (.Swap ⟨3, by decide⟩),
   .op .POP,
   .op (.Swap ⟨1, by decide⟩),
   .op .ADD,
   .op (.Swap ⟨0, by decide⟩),
   .push 1 32,
   .op (.Dup ⟨2, by decide⟩),
   .op .SUB,
   .op (.Swap ⟨1, by decide⟩),
   .op .POP]

/-- Bytes 4481 through 4512. -/
def prologue : List Instr :=
  [.op .JUMPDEST,
   .push 2 9440,
   .op .MLOAD,
   .push 2 9376,
   .op .MLOAD,
   .push 1 32,
   .op .MLOAD,
   .push 0 0,
   .op .MLOAD,
   .push 2 9408,
   .op .MLOAD,
   .op .MLOAD,
   .push 0 0,
   .push 0 0,
   .push 0 0,
   .op (.Swap ⟨1, by decide⟩),
   .op (.Swap ⟨3, by decide⟩),
   .op (.Swap ⟨5, by decide⟩),
   .op (.Swap ⟨7, by decide⟩),
   .op (.Swap ⟨0, by decide⟩),
   .op (.Swap ⟨2, by decide⟩),
   .op (.Swap ⟨4, by decide⟩),
   .op (.Swap ⟨6, by decide⟩),
   .op (.Swap ⟨8, by decide⟩),
   .op (.Swap ⟨0, by decide⟩)]

/-- Bytes 4513 through 4559. -/
def entryHead : List Instr :=
  [.push 32 115792089237316195423570985008687907853269984665640564039457584007913129639904,
   .op (.Swap ⟨1, by decide⟩),
   .push 0 0,
   .op .NOT,
   .op (.Swap ⟨2, by decide⟩),
   .op (.Swap ⟨1, by decide⟩),
   .push 2 9344,
   .op .MLOAD,
   .push 1 128,
   .op .EQ,
   .op (.Swap ⟨1, by decide⟩),
   .op (.Swap ⟨0, by decide⟩)]

/-- Bytes 4560 through 4594. -/
def entryBody : List Instr :=
  [.push 2 9344,
   .op .MLOAD,
   .op (.Dup ⟨0, by decide⟩),
   .push 1 64,
   .op .ADD,
   .op .CALLDATASIZE,
   .push 2 8192,
   .op .CALLDATACOPY,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Dup ⟨3, by decide⟩),
   .op .ADD,
   .push 1 32,
   .op (.Swap ⟨0, by decide⟩),
   .op .SUB,
   .push 1 32,
   .op (.Dup ⟨4, by decide⟩),
   .op .SUB,
   .op (.Swap ⟨3, by decide⟩),
   .op .POP,
   .op (.Swap ⟨1, by decide⟩),
   .op .ADD,
   .op (.Swap ⟨0, by decide⟩),
   .push 1 32,
   .op (.Dup ⟨2, by decide⟩),
   .op .SUB,
   .op (.Swap ⟨1, by decide⟩),
   .op .POP]

/-- Bytes 4595 through 4599. -/
def out : List Instr :=
  [.op .JUMPDEST,
   .op (.Dup ⟨0, by decide⟩),
   .op .MLOAD,
   .push 0 0,
   .op (.Dup ⟨3, by decide⟩)]

/-- Bytes 4600 through 4604. -/
def l1Dispatch : List Instr :=
  [.op (.Dup ⟨6, by decide⟩),
   .push 2 4757,
   .op .JUMPI]

/-- Bytes 4605 through 4642. -/
def l1Mac0 : List Instr :=
  [.op (.Dup ⟨0, by decide⟩),
   .op .MLOAD,
   .op (.Dup ⟨9, by decide⟩),
   .op (.Dup ⟨4, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .MUL,
   .op (.Swap ⟨1, by decide⟩),
   .op (.Dup ⟨5, by decide⟩),
   .op .MULMOD,
   .op (.Dup ⟨1, by decide⟩),
   .op (.Dup ⟨1, by decide⟩),
   .op .LT,
   .op .SUB,
   .op (.Dup ⟨3, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨4, by decide⟩),
   .op .GT,
   .op .SUB,
   .op .SUB,
   .op (.Dup ⟨2, by decide⟩),
   .push 2 8480,
   .op .MLOAD,
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨3, by decide⟩),
   .op .GT,
   .op .ADD,
   .op (.Swap ⟨1, by decide⟩),
   .push 2 8480,
   .op .MSTORE,
   .op (.Dup ⟨7, by decide⟩),
   .op .ADD]

/-- Bytes 4643 through 4680. -/
def l1Mac1 : List Instr :=
  [.op (.Dup ⟨0, by decide⟩),
   .op .MLOAD,
   .op (.Dup ⟨9, by decide⟩),
   .op (.Dup ⟨4, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .MUL,
   .op (.Swap ⟨1, by decide⟩),
   .op (.Dup ⟨5, by decide⟩),
   .op .MULMOD,
   .op (.Dup ⟨1, by decide⟩),
   .op (.Dup ⟨1, by decide⟩),
   .op .LT,
   .op .SUB,
   .op (.Dup ⟨3, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨4, by decide⟩),
   .op .GT,
   .op .SUB,
   .op .SUB,
   .op (.Dup ⟨2, by decide⟩),
   .push 2 8448,
   .op .MLOAD,
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨3, by decide⟩),
   .op .GT,
   .op .ADD,
   .op (.Swap ⟨1, by decide⟩),
   .push 2 8448,
   .op .MSTORE,
   .op (.Dup ⟨7, by decide⟩),
   .op .ADD]

/-- Bytes 4681 through 4718. -/
def l1Mac2 : List Instr :=
  [.op (.Dup ⟨0, by decide⟩),
   .op .MLOAD,
   .op (.Dup ⟨9, by decide⟩),
   .op (.Dup ⟨4, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .MUL,
   .op (.Swap ⟨1, by decide⟩),
   .op (.Dup ⟨5, by decide⟩),
   .op .MULMOD,
   .op (.Dup ⟨1, by decide⟩),
   .op (.Dup ⟨1, by decide⟩),
   .op .LT,
   .op .SUB,
   .op (.Dup ⟨3, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨4, by decide⟩),
   .op .GT,
   .op .SUB,
   .op .SUB,
   .op (.Dup ⟨2, by decide⟩),
   .push 2 8416,
   .op .MLOAD,
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨3, by decide⟩),
   .op .GT,
   .op .ADD,
   .op (.Swap ⟨1, by decide⟩),
   .push 2 8416,
   .op .MSTORE,
   .op (.Dup ⟨7, by decide⟩),
   .op .ADD]

/-- Bytes 4719 through 4756. -/
def l1Mac3 : List Instr :=
  [.op (.Dup ⟨0, by decide⟩),
   .op .MLOAD,
   .op (.Dup ⟨9, by decide⟩),
   .op (.Dup ⟨4, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .MUL,
   .op (.Swap ⟨1, by decide⟩),
   .op (.Dup ⟨5, by decide⟩),
   .op .MULMOD,
   .op (.Dup ⟨1, by decide⟩),
   .op (.Dup ⟨1, by decide⟩),
   .op .LT,
   .op .SUB,
   .op (.Dup ⟨3, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨4, by decide⟩),
   .op .GT,
   .op .SUB,
   .op .SUB,
   .op (.Dup ⟨2, by decide⟩),
   .push 2 8384,
   .op .MLOAD,
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨3, by decide⟩),
   .op .GT,
   .op .ADD,
   .op (.Swap ⟨1, by decide⟩),
   .push 2 8384,
   .op .MSTORE,
   .op (.Dup ⟨7, by decide⟩),
   .op .ADD]

/-- Bytes 4757 through 4757. -/
def l1Join : List Instr :=
  [.op .JUMPDEST]

/-- Bytes 4758 through 4795. -/
def l1Mac4 : List Instr :=
  [.op (.Dup ⟨0, by decide⟩),
   .op .MLOAD,
   .op (.Dup ⟨9, by decide⟩),
   .op (.Dup ⟨4, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .MUL,
   .op (.Swap ⟨1, by decide⟩),
   .op (.Dup ⟨5, by decide⟩),
   .op .MULMOD,
   .op (.Dup ⟨1, by decide⟩),
   .op (.Dup ⟨1, by decide⟩),
   .op .LT,
   .op .SUB,
   .op (.Dup ⟨3, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨4, by decide⟩),
   .op .GT,
   .op .SUB,
   .op .SUB,
   .op (.Dup ⟨2, by decide⟩),
   .push 2 8352,
   .op .MLOAD,
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨3, by decide⟩),
   .op .GT,
   .op .ADD,
   .op (.Swap ⟨1, by decide⟩),
   .push 2 8352,
   .op .MSTORE,
   .op (.Dup ⟨7, by decide⟩),
   .op .ADD]

/-- Bytes 4796 through 4828. -/
def l1Mac5 : List Instr :=
  [.op (.Dup ⟨0, by decide⟩),
   .op .MLOAD,
   .op (.Dup ⟨9, by decide⟩),
   .op (.Dup ⟨4, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .MUL,
   .op (.Swap ⟨1, by decide⟩),
   .op (.Dup ⟨5, by decide⟩),
   .op .MULMOD,
   .op (.Dup ⟨1, by decide⟩),
   .op (.Dup ⟨1, by decide⟩),
   .op .LT,
   .op .SUB,
   .op (.Dup ⟨3, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨4, by decide⟩),
   .op .GT,
   .op .SUB,
   .op .SUB,
   .op (.Dup ⟨2, by decide⟩),
   .op (.Dup ⟨13, by decide⟩),
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨3, by decide⟩),
   .op .GT,
   .op .ADD,
   .op (.Swap ⟨1, by decide⟩),
   .op (.Swap ⟨11, by decide⟩),
   .op .POP,
   .op (.Dup ⟨7, by decide⟩),
   .op .ADD]

/-- Bytes 4829 through 4861. -/
def l1Mac6 : List Instr :=
  [.op (.Dup ⟨0, by decide⟩),
   .op .MLOAD,
   .op (.Dup ⟨9, by decide⟩),
   .op (.Dup ⟨4, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .MUL,
   .op (.Swap ⟨1, by decide⟩),
   .op (.Dup ⟨5, by decide⟩),
   .op .MULMOD,
   .op (.Dup ⟨1, by decide⟩),
   .op (.Dup ⟨1, by decide⟩),
   .op .LT,
   .op .SUB,
   .op (.Dup ⟨3, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨4, by decide⟩),
   .op .GT,
   .op .SUB,
   .op .SUB,
   .op (.Dup ⟨2, by decide⟩),
   .op (.Dup ⟨12, by decide⟩),
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨3, by decide⟩),
   .op .GT,
   .op .ADD,
   .op (.Swap ⟨1, by decide⟩),
   .op (.Swap ⟨10, by decide⟩),
   .op .POP,
   .op (.Dup ⟨7, by decide⟩),
   .op .ADD]

/-- Bytes 4862 through 4893. -/
def l1Mac7 : List Instr :=
  [.op (.Dup ⟨0, by decide⟩),
   .op .MLOAD,
   .op (.Dup ⟨9, by decide⟩),
   .op (.Dup ⟨4, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .MUL,
   .op (.Swap ⟨1, by decide⟩),
   .op (.Dup ⟨5, by decide⟩),
   .op .MULMOD,
   .op (.Dup ⟨1, by decide⟩),
   .op (.Dup ⟨1, by decide⟩),
   .op .LT,
   .op .SUB,
   .op (.Dup ⟨3, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨4, by decide⟩),
   .op .GT,
   .op .SUB,
   .op .SUB,
   .op (.Dup ⟨2, by decide⟩),
   .op (.Dup ⟨11, by decide⟩),
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨3, by decide⟩),
   .op .GT,
   .op .ADD,
   .op (.Swap ⟨1, by decide⟩),
   .op (.Swap ⟨9, by decide⟩),
   .op .POP,
   .op .POP]

/-- Bytes 4894 through 4909. -/
def midStore : List Instr :=
  [.op (.Dup ⟨0, by decide⟩),
   .push 2 8224,
   .op .MLOAD,
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .push 2 8224,
   .op .MSTORE,
   .op .LT,
   .push 2 8192,
   .op .MSTORE]

/-- Bytes 4910 through 4927. -/
def midProduct : List Instr :=
  [.op (.Dup ⟨14, by decide⟩),
   .op .MLOAD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Dup ⟨15, by decide⟩),
   .op .MUL,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Dup ⟨13, by decide⟩),
   .op (.Dup ⟨10, by decide⟩),
   .op (.Swap ⟨1, by decide⟩),
   .op .MULMOD,
   .op (.Swap ⟨0, by decide⟩),
   .op (.Swap ⟨1, by decide⟩),
   .op (.Dup ⟨1, by decide⟩),
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨1, by decide⟩),
   .op .GT,
   .op .ADD]

/-- Bytes 4928 through 4932. -/
def l2Dispatch : List Instr :=
  [.op (.Dup ⟨6, by decide⟩),
   .push 2 5085,
   .op .JUMPI]

/-- Bytes 4933 through 4970. -/
def l2Mac0 : List Instr :=
  [.push 2 192,
   .op .MLOAD,
   .op (.Dup ⟨9, by decide⟩),
   .op (.Dup ⟨3, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .MUL,
   .op (.Swap ⟨1, by decide⟩),
   .op (.Dup ⟨4, by decide⟩),
   .op .MULMOD,
   .op (.Dup ⟨1, by decide⟩),
   .op (.Dup ⟨1, by decide⟩),
   .op .LT,
   .op .SUB,
   .op (.Dup ⟨2, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨3, by decide⟩),
   .op .GT,
   .op .SUB,
   .op .SUB,
   .op (.Dup ⟨1, by decide⟩),
   .push 2 8448,
   .op .MLOAD,
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨2, by decide⟩),
   .op .GT,
   .op .ADD,
   .op (.Swap ⟨0, by decide⟩),
   .push 2 8480,
   .op .MSTORE]

/-- Bytes 4971 through 5008. -/
def l2Mac1 : List Instr :=
  [.push 2 160,
   .op .MLOAD,
   .op (.Dup ⟨9, by decide⟩),
   .op (.Dup ⟨3, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .MUL,
   .op (.Swap ⟨1, by decide⟩),
   .op (.Dup ⟨4, by decide⟩),
   .op .MULMOD,
   .op (.Dup ⟨1, by decide⟩),
   .op (.Dup ⟨1, by decide⟩),
   .op .LT,
   .op .SUB,
   .op (.Dup ⟨2, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨3, by decide⟩),
   .op .GT,
   .op .SUB,
   .op .SUB,
   .op (.Dup ⟨1, by decide⟩),
   .push 2 8416,
   .op .MLOAD,
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨2, by decide⟩),
   .op .GT,
   .op .ADD,
   .op (.Swap ⟨0, by decide⟩),
   .push 2 8448,
   .op .MSTORE]

/-- Bytes 5009 through 5046. -/
def l2Mac2 : List Instr :=
  [.push 2 128,
   .op .MLOAD,
   .op (.Dup ⟨9, by decide⟩),
   .op (.Dup ⟨3, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .MUL,
   .op (.Swap ⟨1, by decide⟩),
   .op (.Dup ⟨4, by decide⟩),
   .op .MULMOD,
   .op (.Dup ⟨1, by decide⟩),
   .op (.Dup ⟨1, by decide⟩),
   .op .LT,
   .op .SUB,
   .op (.Dup ⟨2, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨3, by decide⟩),
   .op .GT,
   .op .SUB,
   .op .SUB,
   .op (.Dup ⟨1, by decide⟩),
   .push 2 8384,
   .op .MLOAD,
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨2, by decide⟩),
   .op .GT,
   .op .ADD,
   .op (.Swap ⟨0, by decide⟩),
   .push 2 8416,
   .op .MSTORE]

/-- Bytes 5047 through 5084. -/
def l2Mac3 : List Instr :=
  [.push 2 96,
   .op .MLOAD,
   .op (.Dup ⟨9, by decide⟩),
   .op (.Dup ⟨3, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .MUL,
   .op (.Swap ⟨1, by decide⟩),
   .op (.Dup ⟨4, by decide⟩),
   .op .MULMOD,
   .op (.Dup ⟨1, by decide⟩),
   .op (.Dup ⟨1, by decide⟩),
   .op .LT,
   .op .SUB,
   .op (.Dup ⟨2, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨3, by decide⟩),
   .op .GT,
   .op .SUB,
   .op .SUB,
   .op (.Dup ⟨1, by decide⟩),
   .push 2 8352,
   .op .MLOAD,
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨2, by decide⟩),
   .op .GT,
   .op .ADD,
   .op (.Swap ⟨0, by decide⟩),
   .push 2 8384,
   .op .MSTORE]

/-- Bytes 5085 through 5085. -/
def l2Join : List Instr :=
  [.op .JUMPDEST]

/-- Bytes 5086 through 5120. -/
def l2Mac4 : List Instr :=
  [.push 2 64,
   .op .MLOAD,
   .op (.Dup ⟨9, by decide⟩),
   .op (.Dup ⟨3, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .MUL,
   .op (.Swap ⟨1, by decide⟩),
   .op (.Dup ⟨4, by decide⟩),
   .op .MULMOD,
   .op (.Dup ⟨1, by decide⟩),
   .op (.Dup ⟨1, by decide⟩),
   .op .LT,
   .op .SUB,
   .op (.Dup ⟨2, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨3, by decide⟩),
   .op .GT,
   .op .SUB,
   .op .SUB,
   .op (.Dup ⟨1, by decide⟩),
   .op (.Dup ⟨13, by decide⟩),
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨2, by decide⟩),
   .op .GT,
   .op .ADD,
   .op (.Swap ⟨0, by decide⟩),
   .push 2 8352,
   .op .MSTORE]

/-- Bytes 5121 through 5150. -/
def l2Mac5 : List Instr :=
  [.op (.Dup ⟨14, by decide⟩),
   .op (.Dup ⟨9, by decide⟩),
   .op (.Dup ⟨3, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .MUL,
   .op (.Swap ⟨1, by decide⟩),
   .op (.Dup ⟨4, by decide⟩),
   .op .MULMOD,
   .op (.Dup ⟨1, by decide⟩),
   .op (.Dup ⟨1, by decide⟩),
   .op .LT,
   .op .SUB,
   .op (.Dup ⟨2, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨3, by decide⟩),
   .op .GT,
   .op .SUB,
   .op .SUB,
   .op (.Dup ⟨1, by decide⟩),
   .op (.Dup ⟨12, by decide⟩),
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨2, by decide⟩),
   .op .GT,
   .op .ADD,
   .op (.Swap ⟨0, by decide⟩),
   .op (.Swap ⟨11, by decide⟩),
   .op .POP]

/-- Bytes 5151 through 5180. -/
def l2Mac6 : List Instr :=
  [.op (.Dup ⟨13, by decide⟩),
   .op (.Dup ⟨9, by decide⟩),
   .op (.Dup ⟨3, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .MUL,
   .op (.Swap ⟨1, by decide⟩),
   .op (.Dup ⟨4, by decide⟩),
   .op .MULMOD,
   .op (.Dup ⟨1, by decide⟩),
   .op (.Dup ⟨1, by decide⟩),
   .op .LT,
   .op .SUB,
   .op (.Dup ⟨2, by decide⟩),
   .op (.Dup ⟨2, by decide⟩),
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨3, by decide⟩),
   .op .GT,
   .op .SUB,
   .op .SUB,
   .op (.Dup ⟨1, by decide⟩),
   .op (.Dup ⟨11, by decide⟩),
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨2, by decide⟩),
   .op .GT,
   .op .ADD,
   .op (.Swap ⟨0, by decide⟩),
   .op (.Swap ⟨10, by decide⟩),
   .op .POP]

/-- Bytes 5181 through 5183. -/
def tailCleanup : List Instr :=
  [.op (.Swap ⟨1, by decide⟩),
   .op .POP,
   .op .POP]

/-- Bytes 5184 through 5202. -/
def tailStore : List Instr :=
  [.op (.Dup ⟨0, by decide⟩),
   .push 2 8224,
   .op .MLOAD,
   .op .ADD,
   .op (.Dup ⟨0, by decide⟩),
   .op (.Swap ⟨8, by decide⟩),
   .op .POP,
   .op .LT,
   .push 2 8192,
   .op .MLOAD,
   .op .ADD,
   .push 2 8224,
   .op .MSTORE]

/-- Bytes 5203 through 5211. -/
def tailTest : List Instr :=
  [.op (.Dup ⟨4, by decide⟩),
   .op .ADD,
   .op (.Dup ⟨2, by decide⟩),
   .op (.Dup ⟨1, by decide⟩),
   .op .GT,
   .push 2 4595,
   .op .JUMPI]

/-- Bytes 5212 through 5238. -/
def exit : List Instr :=
  [.op .POP,
   .op .POP,
   .op .POP,
   .op .POP,
   .op .POP,
   .op .POP,
   .push 2 8256,
   .op .MSTORE,
   .push 2 8288,
   .op .MSTORE,
   .push 2 8320,
   .op .MSTORE,
   .op .POP,
   .op .POP,
   .op .POP,
   .op .POP,
   .op .POP,
   .push 2 2304,
   .op .JUMP]

theorem entry_split : entry = (prologue ++ entryHead) ++ entryBody := rfl

end Challenge.Modexp.Submission.Proofs.Fast.CiosStackCachePrograms
