/-
FiosPC.lean -- `fastPC` tables for the instructions the FIOS patch APPENDS.

The patch moved no instruction index, so every existing `fastPC` table in
Fast/Defs.lean still holds VERBATIM: the index -> pc map is unchanged below 2956,
because the two edited instructions (idx 1380 PUSH2 immediate, idx 1381 MLOAD to
JUMP) both kept their widths.  These tables extend the map over the appended
indices 2956..3177.  Generated by emit_fios_lean.py; regenerate after any rebase.
-/
import Challenge.Modexp.Submission.Proofs.Fast.Defs
set_option warningAsError true
set_option maxRecDepth 40000
set_option maxHeartbeats 4000000

namespace Challenge.Modexp.Submission.Proofs.Fast

open EvmSemantics
open EvmSemantics.EVM
open Challenge.Modexp.Submission.Proofs.Bytecode

theorem jumpDest5351 :
    Decode.isValidJumpDest Challenge.Modexp.submissionBytecode 5351 = true :=
  Artifact.isValidJumpDest_index 3102 (by rfl)

theorem jumpDest5488 :
    Decode.isValidJumpDest Challenge.Modexp.submissionBytecode 5488 = true :=
  Artifact.isValidJumpDest_index 3134 (by rfl)

theorem jumpDest5653 :
    Decode.isValidJumpDest Challenge.Modexp.submissionBytecode 5653 = true :=
  Artifact.isValidJumpDest_index 3201 (by rfl)

@[simp] theorem fastPCFios0 (i : Nat) (hi : 3102 <= i) (hii : i <= 3141) :
    Artifact.submissionArtifact.instructionPC i =
      [5351,5352,5355,5356,5357,5359,5360,5361,5364,5365,5366,5399,5400,5403,5404,5407,5408,5409,5410,5411,5412,5413,5414,5447,5448,5449,5450,5451,5452,5453,5454,5487,5488,5489,5490,5491,5492,5493,5494,5495][i - 3102]! := by
  interval_cases i <;> decide

@[simp] theorem fastPCFios1 (i : Nat) (hi : 3142 <= i) (hii : i <= 3181) :
    Artifact.submissionArtifact.instructionPC i =
      [5496,5497,5498,5499,5500,5533,5534,5535,5536,5537,5538,5539,5540,5541,5542,5543,5544,5545,5546,5547,5548,5549,5550,5551,5552,5553,5556,5557,5558,5559,5560,5561,5562,5563,5564,5565,5566,5567,5600,5601][i - 3142]! := by
  interval_cases i <;> decide

@[simp] theorem fastPCFios2 (i : Nat) (hi : 3182 <= i) (hii : i <= 3221) :
    Artifact.submissionArtifact.instructionPC i =
      [5602,5603,5604,5605,5606,5607,5608,5609,5610,5611,5612,5613,5614,5615,5616,5617,5618,5619,5652,5653,5654,5655,5656,5657,5658,5659,5660,5661,5662,5663,5696,5697,5698,5699,5700,5701,5702,5703,5704,5705][i - 3182]! := by
  interval_cases i <;> decide

@[simp] theorem fastPCFios3 (i : Nat) (hi : 3222 <= i) (hii : i <= 3261) :
    Artifact.submissionArtifact.instructionPC i =
      [5706,5707,5708,5709,5710,5711,5712,5713,5714,5715,5716,5717,5718,5719,5720,5721,5722,5723,5724,5725,5726,5727,5728,5729,5730,5731,5764,5765,5766,5767,5768,5769,5770,5771,5772,5773,5774,5775,5776,5777][i - 3222]! := by
  interval_cases i <;> decide

@[simp] theorem fastPCFios4 (i : Nat) (hi : 3262 <= i) (hii : i <= 3301) :
    Artifact.submissionArtifact.instructionPC i =
      [5778,5779,5780,5781,5782,5783,5784,5785,5786,5787,5788,5789,5790,5791,5793,5794,5795,5828,5829,5832,5833,5834,5837,5838,5839,5842,5843,5844,5845,5846,5847,5848,5849,5850,5851,5852,5855,5856,5857,5858][i - 3262]! := by
  interval_cases i <;> decide

@[simp] theorem fastPCFios5 (i : Nat) (hi : 3302 <= i) (hii : i <= 3323) :
    Artifact.submissionArtifact.instructionPC i =
      [5859,5862,5863,5864,5865,5866,5899,5900,5901,5902,5903,5906,5907,5908,5909,5910,5911,5912,5913,5914,5915,5918][i - 3302]! := by
  interval_cases i <;> decide

end Challenge.Modexp.Submission.Proofs.Fast
