import Challenge.Modexp.Submission.Proofs.Fast.CiosCachedPrograms

set_option warningAsError true

/-!
# M9: instruction sequences of the eight straight conversion MAC blocks
(generated by evidence/root/mx-m9-lemmas/gen_m9_mac.py from rows.json ad60d3dac181; do not edit by hand)

Each block `b = 0..7` of the M9 conversion product section is
`PUSH2 (0x5e0 - 32b); MLOAD; DUP4` followed by `CiosCached.macFusedProgram T T`, `T = 0x920 - 32b`
(30 instructions, 36 bytes).  Blocks 0 and 4 carry the entry `JUMPDEST`s (pc 2682 and 2827).  The section is
entered by E6 (`PUSH0 NOT SWAP1 PUSH0 PUSH2 0x6a2 MLOAD JUMP`, pc 2673) and left through `SWAP1 SWAP2 POP`
(pc 2972), falling into the unchanged top-limb fixup at pc 2975.

## Assumed from the tree (unchanged by the port)
* `Challenge.Modexp.Submission.Proofs.Fast.CiosCached.macFusedProgram : UInt256 → UInt256 → List Instr`
  (`Proofs/Fast/CiosCachedPrograms.lean`; `= macProductProgram.take 6 ++ macFusedPostProgram tl ts`).
* `YulEvmCompiler.Instr` with constructors `.push (w : Fin 33) (v : UInt256)` and `.op (o : Operation)`,
  `Operation.Dup`/`.Swap` taking `{ idx : Fin 16 }`.
-/

namespace Challenge.Modexp.Submission.Proofs.Fast.M9Mac

open EvmSemantics EvmSemantics.EVM YulEvmCompiler
open Challenge.Modexp.Submission.Proofs.Fast

/-- `PUSH2 a; MLOAD; DUP4`: load the modulus limb and lift the mask into `run_fused`'s frame. -/
def loadProgram (a : UInt256) : List Instr :=
  [.push 2 a, .op .MLOAD, .op (.Dup ⟨3, by decide⟩)]

/-- One straight MAC block without its `JUMPDEST` (30 instructions, 36 bytes). -/
def blockProgram (a t : UInt256) : List Instr :=
  loadProgram a ++ CiosCached.macFusedProgram t t

/-- Blocks 0 and 4, `JUMPDEST` included (29 instructions, 37 bytes). -/
def headProgram (a t : UInt256) : List Instr :=
  [.op .JUMPDEST] ++ blockProgram a t

/-- One straight MAC block on a known-zero incoming carry: `macFusedZeroProgram` spends `PUSH0`
where `macFusedProgram` spends the `DUP4` that reproduces the carry.  Same 36 bytes, one gas
cheaper (30 instructions). -/
def blockZeroProgram (a t : UInt256) : List Instr :=
  loadProgram a ++ CiosCached.macFusedZeroProgram t t

/-- Block 0 only, `JUMPDEST` included (29 instructions, 37 bytes).  Block 4 must *not* use this
schedule: pc 2827 is both jumped to (four limbs, carry zero) and fallen into from block 3
(carry nonzero), so its incoming carry is not known to be zero.  Block 0's `JUMPDEST` at pc 2682
has no fall-through predecessor — pc 2681 is an unconditional `JUMP` — and its only jump
predecessor is that `JUMP`, which enters with the literal `PUSH0` of `entryProgram` on top. -/
def headZeroProgram (a t : UInt256) : List Instr :=
  [.op .JUMPDEST] ++ blockZeroProgram a t

/-- `SWAP1 SWAP2 POP`: drop the mask, leaving `[carry, q]` above the shift counter. -/
def exitProgram : List Instr :=
  [.op (.Swap ⟨0, by decide⟩), .op (.Swap ⟨1, by decide⟩), .op .POP]

/-- E6: `PUSH0 NOT SWAP1 PUSH0 PUSH2 0x6a2 MLOAD JUMP` — build the chain frame `[0, q, 2^256-1]` and
jump to the entry cached at `0x6a2 = 1698`. -/
def entryProgram : List Instr :=
  [.push 0 0, .op .NOT, .op (.Swap ⟨0, by decide⟩), .push 0 0, .push 2 1698, .op .MLOAD, .op .JUMP]

end Challenge.Modexp.Submission.Proofs.Fast.M9Mac
