import Challenge.Modexp.Submission.Proofs.Fast.M9MacBlocks
import Challenge.Modexp.Submission.Proofs.Fast.M9MacRun

set_option warningAsError true

/-!
# M9: gas traces of the straight MAC chain
(generated by evidence/root/mx-m9-lemmas/gen_m9_mac.py from rows.json ad60d3dac181; do not edit by hand)

* `gasSteps_block b`  : one block on any MAC state (the `KernelChain.gasSteps_l1Step` shape).
* `gasSteps_run m b`   : blocks `b..7` (`b + m = 8`) from the start of block `b` to the exit at pc 2972,
                         producing `SquareModel.l1Run q bi 1280 n j m` (the `gasSteps_l1Run` recursion).
* `gasSteps_exit`      : `SWAP1 SWAP2 POP`, pc 2972 → 2975 (old 3119, the unchanged top-limb fixup).
* `gasSteps_chain n`   : the whole section for `n = 4 ∨ n = 8` from the entry `JUMPDEST` (2682 for eight
                         limbs, 2827 for four) to pc 2975, with `Monpro.l1Step um q 1280 n n` — the statement
                         that replaces the old `Shift.gasSteps_macLoop` (plus its `POP POP POP`).
* `gasSteps_entry n`   : E6 from pc 2673 with `[q] ++ rest` to the entry `JUMPDEST`, given the cached word.
* `gasSteps_macChain n`: `gasSteps_entry` then `gasSteps_chain`.

`1280` is `Shift.NEG` (`Proofs/Fast/ShiftModel.lean`, `def NEG : Nat := 1280`, `rfl`); it is written as a
literal so that this module does not import `ShiftModel` (whose closure is `Exp`).

## Assumed from the tree (unchanged by the port), beyond `M9MacBlocks` and `M9MacRun`
* `Challenge.Modexp.submissionBytecode_size : submissionBytecode.size = 5137` (`Submission/Bytecode.lean`).
* `Challenge.Modexp.Submission.Proofs.Bytecode.WindowTwentyOneBinding.Environment` and `Block.steps`.
* `Challenge.EvmProof.GasSteps` with `.refl`, `.trans`, `.cast`.
* `Challenge.Modexp.Submission.Proofs.Fast.SquareModel.l1Run`, `l1Run_succ`, `l1Step_eq_l1Run`
  (`l1Step mem bi pa n j = l1Run ⟨mem, UInt256.ofNat 0⟩ bi pa n 0 j`); `Monpro.l1Step`.
-/

namespace Challenge.Modexp.Submission.Proofs.Fast.M9Mac

open EvmSemantics EvmSemantics.EVM YulEvmCompiler
open Challenge.Modexp.Submission.Proofs.Bytecode WindowNibbleKernel WindowTwentyOneBinding
open Challenge.Modexp.Submission.Proofs.Fast Monpro CiosCached

def environment (s : State)
    (hcode : s.executionEnv.code = Challenge.Modexp.submissionBytecode)
    (hfork : s.fork = .Osaka) (hrun : s.halt = .Running)
    (hnp : Precompile.isPrecompileWithConfig s.executionEnv.precompileConfig
      s.executionEnv.fork s.executionEnv.codeAddr = false) :
    Environment Artifact.submissionArtifact .Osaka s :=
  ⟨by change Challenge.Modexp.submissionBytecode.size < 2^256
      rw [Challenge.Modexp.submissionBytecode_size]; decide,
    hcode, hfork, hrun, hnp⟩

/-- Start pc of block `b` (`b = 8`: the exit `SWAP1 SWAP2 POP`).  Blocks 0 and 4 start on their `JUMPDEST`. -/
def startPC : Nat → Nat
  | 0 => 2682
  | 1 => 2719
  | 2 => 2755
  | 3 => 2791
  | 4 => 2827
  | 5 => 2864
  | 6 => 2900
  | 7 => 2936
  | _ => 2972

/-- Entry pc of the section for width `n`: block 0 for eight limbs, block 4 (`2682 + 0x91`) for four. -/
def entryPC : Nat → Nat
  | 4 => 2827
  | _ => 2682

/-! ## One block -/

/-- Block `b` (`b < 8`) performs limb step `j = b + n - 8` of width `n` on any MAC state. -/
def gasSteps_block (b : Nat) (hb : b < 8) (s : State) (m : MacState) (bi : UInt256)
    (n j : Nat) (rest : List UInt256) (hrest : rest.length ≤ 1014)
    (hrun : s.halt = .Running)
    (hcode : s.executionEnv.code = Challenge.Modexp.submissionBytecode)
    (hfork : s.fork = .Osaka)
    (hnp : Precompile.isPrecompileWithConfig s.executionEnv.precompileConfig
      s.executionEnv.fork s.executionEnv.codeAddr = false)
    (hact : 88 ≤ s.activeWords.toNat) (hn : n ≤ 8) (hjb : j + 8 = b + n) :
    Challenge.EvmProof.GasSteps
      (chainState s (UInt256.ofNat (startPC b)) m bi rest)
      (chainState s (UInt256.ofNat (startPC (b + 1))) (SquareModel.l1StepOn m bi 1280 n j) bi rest) := by
  interval_cases b
  · have h := run_head s (UInt256.ofNat 2682) m bi 1280 n j 1504 2336
      (by rw [show n - 1 - j = 7 from by omega]; decide)
      (by rw [show n - 1 - j = 7 from by omega]; decide)
      rest hrest hact (by omega) hn (by omega)
    simp only [Challenge.EvmProof.Word.ofNat_add_mod, Nat.reduceAdd] at h
    show Challenge.EvmProof.GasSteps (chainState s (UInt256.ofNat 2682) m bi rest)
      (chainState s (UInt256.ofNat 2719) (SquareModel.l1StepOn m bi 1280 n j) bi rest)
    exact block0.steps (environment (chainState s (UInt256.ofNat 2682) m bi rest)
      hcode hfork hrun hnp) rfl h
  · have h := run_block s (UInt256.ofNat 2719) m bi 1280 n j 1472 2304
      (by rw [show n - 1 - j = 6 from by omega]; decide)
      (by rw [show n - 1 - j = 6 from by omega]; decide)
      rest hrest hact (by omega) hn (by omega)
    simp only [Challenge.EvmProof.Word.ofNat_add_mod, Nat.reduceAdd] at h
    show Challenge.EvmProof.GasSteps (chainState s (UInt256.ofNat 2719) m bi rest)
      (chainState s (UInt256.ofNat 2755) (SquareModel.l1StepOn m bi 1280 n j) bi rest)
    exact block1.steps (environment (chainState s (UInt256.ofNat 2719) m bi rest)
      hcode hfork hrun hnp) rfl h
  · have h := run_block s (UInt256.ofNat 2755) m bi 1280 n j 1440 2272
      (by rw [show n - 1 - j = 5 from by omega]; decide)
      (by rw [show n - 1 - j = 5 from by omega]; decide)
      rest hrest hact (by omega) hn (by omega)
    simp only [Challenge.EvmProof.Word.ofNat_add_mod, Nat.reduceAdd] at h
    show Challenge.EvmProof.GasSteps (chainState s (UInt256.ofNat 2755) m bi rest)
      (chainState s (UInt256.ofNat 2791) (SquareModel.l1StepOn m bi 1280 n j) bi rest)
    exact block2.steps (environment (chainState s (UInt256.ofNat 2755) m bi rest)
      hcode hfork hrun hnp) rfl h
  · have h := run_block s (UInt256.ofNat 2791) m bi 1280 n j 1408 2240
      (by rw [show n - 1 - j = 4 from by omega]; decide)
      (by rw [show n - 1 - j = 4 from by omega]; decide)
      rest hrest hact (by omega) hn (by omega)
    simp only [Challenge.EvmProof.Word.ofNat_add_mod, Nat.reduceAdd] at h
    show Challenge.EvmProof.GasSteps (chainState s (UInt256.ofNat 2791) m bi rest)
      (chainState s (UInt256.ofNat 2827) (SquareModel.l1StepOn m bi 1280 n j) bi rest)
    exact block3.steps (environment (chainState s (UInt256.ofNat 2791) m bi rest)
      hcode hfork hrun hnp) rfl h
  · have h := run_head s (UInt256.ofNat 2827) m bi 1280 n j 1376 2208
      (by rw [show n - 1 - j = 3 from by omega]; decide)
      (by rw [show n - 1 - j = 3 from by omega]; decide)
      rest hrest hact (by omega) hn (by omega)
    simp only [Challenge.EvmProof.Word.ofNat_add_mod, Nat.reduceAdd] at h
    show Challenge.EvmProof.GasSteps (chainState s (UInt256.ofNat 2827) m bi rest)
      (chainState s (UInt256.ofNat 2864) (SquareModel.l1StepOn m bi 1280 n j) bi rest)
    exact block4.steps (environment (chainState s (UInt256.ofNat 2827) m bi rest)
      hcode hfork hrun hnp) rfl h
  · have h := run_block s (UInt256.ofNat 2864) m bi 1280 n j 1344 2176
      (by rw [show n - 1 - j = 2 from by omega]; decide)
      (by rw [show n - 1 - j = 2 from by omega]; decide)
      rest hrest hact (by omega) hn (by omega)
    simp only [Challenge.EvmProof.Word.ofNat_add_mod, Nat.reduceAdd] at h
    show Challenge.EvmProof.GasSteps (chainState s (UInt256.ofNat 2864) m bi rest)
      (chainState s (UInt256.ofNat 2900) (SquareModel.l1StepOn m bi 1280 n j) bi rest)
    exact block5.steps (environment (chainState s (UInt256.ofNat 2864) m bi rest)
      hcode hfork hrun hnp) rfl h
  · have h := run_block s (UInt256.ofNat 2900) m bi 1280 n j 1312 2144
      (by rw [show n - 1 - j = 1 from by omega]; decide)
      (by rw [show n - 1 - j = 1 from by omega]; decide)
      rest hrest hact (by omega) hn (by omega)
    simp only [Challenge.EvmProof.Word.ofNat_add_mod, Nat.reduceAdd] at h
    show Challenge.EvmProof.GasSteps (chainState s (UInt256.ofNat 2900) m bi rest)
      (chainState s (UInt256.ofNat 2936) (SquareModel.l1StepOn m bi 1280 n j) bi rest)
    exact block6.steps (environment (chainState s (UInt256.ofNat 2900) m bi rest)
      hcode hfork hrun hnp) rfl h
  · have h := run_block s (UInt256.ofNat 2936) m bi 1280 n j 1280 2112
      (by rw [show n - 1 - j = 0 from by omega]; decide)
      (by rw [show n - 1 - j = 0 from by omega]; decide)
      rest hrest hact (by omega) hn (by omega)
    simp only [Challenge.EvmProof.Word.ofNat_add_mod, Nat.reduceAdd] at h
    show Challenge.EvmProof.GasSteps (chainState s (UInt256.ofNat 2936) m bi rest)
      (chainState s (UInt256.ofNat 2972) (SquareModel.l1StepOn m bi 1280 n j) bi rest)
    exact block7.steps (environment (chainState s (UInt256.ofNat 2936) m bi rest)
      hcode hfork hrun hnp) rfl h

/-! ## The chain -/

/-- Peel the first step off a run. -/
theorem l1Run_succ_left (q : MacState) (bi : UInt256) (pa n j : Nat) :
    ∀ m, SquareModel.l1Run q bi pa n j (m + 1) =
      SquareModel.l1Run (SquareModel.l1StepOn q bi pa n j) bi pa n (j + 1) m
  | 0 => rfl
  | m + 1 => by
      rw [SquareModel.l1Run_succ, l1Run_succ_left q bi pa n j m, SquareModel.l1Run_succ]
      congr 1
      omega

/-- Blocks `b..7` (`b + m = 8`) from the start of block `b` to the exit at pc 2972. -/
def gasSteps_run : (m b : Nat) → b + m = 8 →
    (s : State) → (q : MacState) → (bi : UInt256) → (n j : Nat) → (rest : List UInt256) →
    rest.length ≤ 1014 → s.halt = .Running →
    s.executionEnv.code = Challenge.Modexp.submissionBytecode →
    s.fork = .Osaka →
    Precompile.isPrecompileWithConfig s.executionEnv.precompileConfig
      s.executionEnv.fork s.executionEnv.codeAddr = false →
    88 ≤ s.activeWords.toNat → n ≤ 8 → j + 8 = b + n →
    Challenge.EvmProof.GasSteps
      (chainState s (UInt256.ofNat (startPC b)) q bi rest)
      (chainState s (UInt256.ofNat 2972) (SquareModel.l1Run q bi 1280 n j m) bi rest)
  | 0, b, hbm, s, q, bi, n, j, rest, _, _, _, _, _, _, _, _ => by
      obtain rfl : b = 8 := by omega
      exact Challenge.EvmProof.GasSteps.refl _
  | m + 1, b, hbm, s, q, bi, n, j, rest, hrest, hrun, hcode, hfork, hnp, hact, hn, hjb => by
      have h1 := gasSteps_block b (by omega) s q bi n j rest hrest hrun hcode hfork hnp hact hn hjb
      have h2 := gasSteps_run m (b + 1) (by omega) s (SquareModel.l1StepOn q bi 1280 n j) bi n (j + 1)
        rest hrest hrun hcode hfork hnp hact hn (by omega)
      rw [← l1Run_succ_left] at h2
      exact h1.trans h2

/-- `SWAP1 SWAP2 POP` at pc 2972, falling into pc 2975. -/
def gasSteps_exit (s : State) (q : MacState) (bi : UInt256) (rest : List UInt256)
    (hrest : rest.length ≤ 1014) (hrun : s.halt = .Running)
    (hcode : s.executionEnv.code = Challenge.Modexp.submissionBytecode)
    (hfork : s.fork = .Osaka)
    (hnp : Precompile.isPrecompileWithConfig s.executionEnv.precompileConfig
      s.executionEnv.fork s.executionEnv.codeAddr = false) :
    Challenge.EvmProof.GasSteps
      (chainState s (UInt256.ofNat 2972) q bi rest)
      (exitState s (UInt256.ofNat 2975) q bi rest) :=
  exitBlock.steps (environment (chainState s (UInt256.ofNat 2972) q bi rest) hcode hfork hrun hnp) rfl
    (by simpa only [Challenge.EvmProof.Word.ofNat_add_mod, Nat.reduceAdd] using
      run_exit s (UInt256.ofNat 2972) q bi rest hrest)

/-- **The section.**  For `n = 4 ∨ n = 8`, from the entry `JUMPDEST` (`entryPC n`) with the frame
`[0, q, 2^256-1] ++ rest` over `um` to pc 2975 with `[carry, q] ++ rest`, where memory and carry are
`Monpro.l1Step um q 1280 n n` — the old `macLoopState … 0 → midState` followed by `POP POP POP`. -/
def gasSteps_chain (n : Nat) (hn : n = 4 ∨ n = 8) (s : State) (um : ByteArray) (q : UInt256)
    (rest : List UInt256) (hrest : rest.length ≤ 1014) (hrun : s.halt = .Running)
    (hcode : s.executionEnv.code = Challenge.Modexp.submissionBytecode)
    (hfork : s.fork = .Osaka)
    (hnp : Precompile.isPrecompileWithConfig s.executionEnv.precompileConfig
      s.executionEnv.fork s.executionEnv.codeAddr = false)
    (hact : 88 ≤ s.activeWords.toNat) :
    Challenge.EvmProof.GasSteps
      (chainState s (UInt256.ofNat (entryPC n)) ⟨um, UInt256.ofNat 0⟩ q rest)
      (exitState s (UInt256.ofNat 2975) (l1Step um q 1280 n n) q rest) :=
  if h4 : n = 4 then by
    subst h4
    exact ((gasSteps_run 4 4 rfl s ⟨um, UInt256.ofNat 0⟩ q 4 0 rest hrest hrun hcode hfork hnp hact
        (by decide) rfl).trans
      (gasSteps_exit s _ q rest hrest hrun hcode hfork hnp)).cast rfl
      (by rw [SquareModel.l1Step_eq_l1Run])
  else by
    have h8 : n = 8 := by omega
    subst h8
    exact ((gasSteps_run 8 0 rfl s ⟨um, UInt256.ofNat 0⟩ q 8 0 rest hrest hrun hcode hfork hnp hact
        (by decide) rfl).trans
      (gasSteps_exit s _ q rest hrest hrun hcode hfork hnp)).cast rfl
      (by rw [SquareModel.l1Step_eq_l1Run])

/-! ## The E6 entry -/

/-- Both entries are jump destinations. -/
theorem jumpDest_entry (n : Nat) (hn : n = 4 ∨ n = 8) :
    Decode.isValidJumpDest Challenge.Modexp.submissionBytecode (entryPC n) = true := by
  rcases hn with rfl | rfl
  · exact jumpDest2827
  · exact jumpDest2682

/-- E6 at pc 2673 (old 2936): `[q] ++ rest` over `um` to the chain frame at the cached entry. -/
def gasSteps_entry (n : Nat) (hn : n = 4 ∨ n = 8) (s : State) (um : ByteArray) (q : UInt256)
    (rest : List UInt256) (hrest : rest.length ≤ 1014) (hrun : s.halt = .Running)
    (hcode : s.executionEnv.code = Challenge.Modexp.submissionBytecode)
    (hfork : s.fork = .Osaka)
    (hnp : Precompile.isPrecompileWithConfig s.executionEnv.precompileConfig
      s.executionEnv.fork s.executionEnv.codeAddr = false)
    (hact : 88 ≤ s.activeWords.toNat)
    (hcache : MachineState.readWord um 1698 = UInt256.ofNat (entryPC n)) :
    Challenge.EvmProof.GasSteps
      (setupState s (UInt256.ofNat 2673) um q rest)
      (chainState s (UInt256.ofNat (entryPC n)) ⟨um, UInt256.ofNat 0⟩ q rest) :=
  entryBlock.steps (environment (setupState s (UInt256.ofNat 2673) um q rest) hcode hfork hrun hnp) rfl
    (run_entry s (UInt256.ofNat 2673) um q rest (entryPC n) hrest hact hcache
      (by rcases hn with rfl | rfl <;> decide)
      (by rw [hcode]; exact jumpDest_entry n hn))

/-- E6 followed by the section: pc 2673 with `[q] ++ rest` over `um` to pc 2975 with
`[carry, q] ++ rest` over `l1Step um q 1280 n n`. -/
def gasSteps_macChain (n : Nat) (hn : n = 4 ∨ n = 8) (s : State) (um : ByteArray) (q : UInt256)
    (rest : List UInt256) (hrest : rest.length ≤ 1014) (hrun : s.halt = .Running)
    (hcode : s.executionEnv.code = Challenge.Modexp.submissionBytecode)
    (hfork : s.fork = .Osaka)
    (hnp : Precompile.isPrecompileWithConfig s.executionEnv.precompileConfig
      s.executionEnv.fork s.executionEnv.codeAddr = false)
    (hact : 88 ≤ s.activeWords.toNat)
    (hcache : MachineState.readWord um 1698 = UInt256.ofNat (entryPC n)) :
    Challenge.EvmProof.GasSteps
      (setupState s (UInt256.ofNat 2673) um q rest)
      (exitState s (UInt256.ofNat 2975) (l1Step um q 1280 n n) q rest) :=
  (gasSteps_entry n hn s um q rest hrest hrun hcode hfork hnp hact hcache).trans
    (gasSteps_chain n hn s um q rest hrest hrun hcode hfork hnp hact)

end Challenge.Modexp.Submission.Proofs.Fast.M9Mac

#print axioms Challenge.Modexp.Submission.Proofs.Fast.M9Mac.gasSteps_block
#print axioms Challenge.Modexp.Submission.Proofs.Fast.M9Mac.gasSteps_run
#print axioms Challenge.Modexp.Submission.Proofs.Fast.M9Mac.gasSteps_exit
#print axioms Challenge.Modexp.Submission.Proofs.Fast.M9Mac.gasSteps_chain
#print axioms Challenge.Modexp.Submission.Proofs.Fast.M9Mac.gasSteps_entry
#print axioms Challenge.Modexp.Submission.Proofs.Fast.M9Mac.gasSteps_macChain
