import Challenge.Modexp.Submission.Proofs.Fast.M9MacPrograms
import Challenge.Modexp.Submission.Proofs.Fast.CiosCachedFused
import Challenge.Modexp.Submission.Proofs.Fast.SquareModel

set_option warningAsError true
set_option linter.unusedSimpArgs false

/-!
# M9: execution of one straight MAC block, the exit and the E6 entry on any MAC state
(generated by evidence/root/mx-m9-lemmas/gen_m9_mac.py from rows.json ad60d3dac181; do not edit by hand)

The chain frame is `[carry, q, 2^256-1] ++ rest` (top first) over a `Monpro.MacState` (memory and running
carry).  A block loads the `-N` limb at its immediate `a`, duplicates the mask, and runs the already-proven
fused multiply-accumulate (`CiosCachedFused.run_fused`) on `t`, so it performs exactly one
`SquareModel.l1StepOn` step and restores the frame.  This is the `StagedOperandL1.run_l1`/`run_step` shape
with `PUSH2 a; MLOAD; DUP4` in place of the staged load.

## Assumed from the tree (kernel/model layer; unchanged by the port)
* `Challenge.Modexp.Submission.Proofs.Fast.CiosCachedFused.run_fused (template : State) (pc x y c tl ts : UInt256)
    (rest : List UInt256) (hrest : rest.length + 8 < 1024) (hload hstore : UInt256.ofNat (MachineState.activeWordsAfter
    template.activeWords.toNat tl.toNat 32) = template.activeWords) :
    runInstructions (macFusedProgram tl ts) (framed template pc ([maxWord, x, c, y] ++ rest)) = some (framed
    { template with memory := writeBytes template.memory (natToBytesPadded (macSum x y (readWord template.memory
    tl.toNat) c).toNat 32) ts.toNat } (pc + UInt256.ofNat 31) ([macCarry x y (readWord template.memory tl.toNat) c, y]
    ++ rest))` (`Proofs/Fast/CiosCachedFused.lean`).
* `Challenge.Modexp.Submission.Proofs.Fast.CiosCachedMacCore.framed (template : State) (pc : UInt256) (stack : List UInt256) : State`.
* `Challenge.Modexp.Submission.Proofs.Fast.Monpro.MacState` (fields `memory : ByteArray`, `carry : UInt256`),
  `Monpro.maxWord : UInt256` (= `UInt256.ofNat (2^256-1)`), `Monpro.macSum`, `Monpro.macCarry`,
  `Monpro.activeWords_fix (s : State) (off sz : Nat) (hsz : sz ≠ 0) (hoff : off + sz ≤ 2816)
    (hact : 88 ≤ s.activeWords.toNat) : UInt256.ofNat (MachineState.activeWordsAfter s.activeWords.toNat off sz) = s.activeWords`.
* `Challenge.Modexp.Submission.Proofs.Fast.SquareModel.l1StepOn (q : MacState) (bi : UInt256) (pa n j : Nat) : MacState`
  (`Proofs/Fast/SquareModel.lean`; reads `pa + 32(n-1-j)` and `2112 + 32(n-1-j)`, writes the latter).
* `Challenge.Modexp.Submission.Proofs.Bytecode.WindowNibbleKernel.runInstructions`, `runInstructions_append_some`,
  `succ_eq_add`, `word_add_assoc`; `Challenge.EvmProof.Word.ofNat_add_mod`; `Challenge.EvmProof.Stepper.runInstr`.
-/

namespace Challenge.Modexp.Submission.Proofs.Fast.M9Mac

open EvmSemantics EvmSemantics.EVM YulEvmCompiler
open Challenge.Modexp.Submission.Proofs.Bytecode WindowNibbleKernel
open Challenge.Modexp.Submission.Proofs.Fast Monpro CiosCached CiosCachedMacCore

/-- The chain frame `[carry, q, 2^256-1] ++ rest` over the MAC state `m`. -/
def chainState (template : State) (pc : UInt256) (m : MacState) (bi : UInt256)
    (rest : List UInt256) : State :=
  { template with pc := pc, stack := [m.carry, bi, maxWord] ++ rest, memory := m.memory }

/-- After the exit: `[carry, q] ++ rest`. -/
def exitState (template : State) (pc : UInt256) (m : MacState) (bi : UInt256)
    (rest : List UInt256) : State :=
  { template with pc := pc, stack := [m.carry, bi] ++ rest, memory := m.memory }

/-- The section entry state: `q` above `rest`, memory `um`. -/
def setupState (template : State) (pc : UInt256) (um : ByteArray) (bi : UInt256)
    (rest : List UInt256) : State :=
  { template with pc := pc, stack := bi :: rest, memory := um }

theorem run_load (template : State) (pc a carry bi : UInt256) (rest : List UInt256)
    (hrest : rest.length ≤ 1014)
    (hactive : UInt256.ofNat (MachineState.activeWordsAfter
      template.activeWords.toNat a.toNat 32) = template.activeWords) :
    runInstructions (loadProgram a) (framed template pc ([carry, bi, maxWord] ++ rest)) =
    some (framed template (pc + UInt256.ofNat 5)
      ([maxWord, MachineState.readWord template.memory a.toNat, carry, bi, maxWord] ++ rest)) := by
  have hc3 : rest.length + 3 < 1024 := by omega
  have hc4 : rest.length + 4 < 1024 := by omega
  simp (disch := omega) [runInstructions, loadProgram, framed, Challenge.EvmProof.Stepper.runInstr,
    List.getElem?_cons_zero, List.getElem?_cons_succ, List.cons_append, List.nil_append,
    hc3, hc4, State.activeWordsAfterUInt256, hactive,
    succ_eq_add, word_add_assoc, Challenge.EvmProof.Word.ofNat_add_mod]

/-- One straight block (no `JUMPDEST`) performs limb step `j` of width `n` on any MAC state:
the immediates must be the `-N` limb `pa + 32(n-1-j)` and the `t` limb `2112 + 32(n-1-j)`. -/
theorem run_block (template : State) (pc : UInt256) (m : MacState) (bi : UInt256)
    (pa n j : Nat) (a t : UInt256)
    (ha : a.toNat = pa + 32 * (n - 1 - j)) (ht : t.toNat = 2112 + 32 * (n - 1 - j))
    (rest : List UInt256) (hrest : rest.length ≤ 1014)
    (hactive : 88 ≤ template.activeWords.toNat) (hpa : pa + 32 * n ≤ 2784)
    (hn : n ≤ 8) (hj : j < n) :
    runInstructions (blockProgram a t) (chainState template pc m bi rest) =
    some (chainState template (pc + UInt256.ofNat 36) (SquareModel.l1StepOn m bi pa n j) bi rest) := by
  have hactA : UInt256.ofNat (MachineState.activeWordsAfter template.activeWords.toNat
      (pa + 32 * (n - 1 - j)) 32) = template.activeWords :=
    activeWords_fix template _ 32 (by decide) (by omega) hactive
  have hactT : UInt256.ofNat (MachineState.activeWordsAfter template.activeWords.toNat
      (2112 + 32 * (n - 1 - j)) 32) = template.activeWords :=
    activeWords_fix template _ 32 (by decide) (by omega) hactive
  let st : State := { template with memory := m.memory }
  have hA : UInt256.ofNat (MachineState.activeWordsAfter st.activeWords.toNat a.toNat 32) =
      st.activeWords := by simpa only [st, ha] using hactA
  have hT : UInt256.ofNat (MachineState.activeWordsAfter st.activeWords.toNat t.toNat 32) =
      st.activeWords := by simpa only [st, ht] using hactT
  have hl := run_load st pc a m.carry bi rest hrest hA
  have hread : MachineState.readWord st.memory a.toNat =
      MachineState.readWord m.memory (pa + 32 * (n - 1 - j)) := by simp only [st, ha]
  rw [hread] at hl
  have hf := CiosCachedFused.run_fused st (pc + UInt256.ofNat 5)
    (MachineState.readWord m.memory (pa + 32 * (n - 1 - j))) bi m.carry t t
    (maxWord :: rest) (by simp only [List.length_cons]; omega) hT hT
  have hall := runInstructions_append_some _ _ _ _ _ hl hf
  have hpc : (pc + UInt256.ofNat 5) + UInt256.ofNat 31 = pc + UInt256.ofNat 36 := by
    simp [word_add_assoc, Challenge.EvmProof.Word.ofNat_add_mod]
  simpa only [blockProgram, st, chainState, framed, SquareModel.l1StepOn, ht, hpc,
    List.cons_append, List.nil_append] using hall

/-- A head block (`JUMPDEST` included, 37 bytes). -/
theorem run_head (template : State) (pc : UInt256) (m : MacState) (bi : UInt256)
    (pa n j : Nat) (a t : UInt256)
    (ha : a.toNat = pa + 32 * (n - 1 - j)) (ht : t.toNat = 2112 + 32 * (n - 1 - j))
    (rest : List UInt256) (hrest : rest.length ≤ 1014)
    (hactive : 88 ≤ template.activeWords.toNat) (hpa : pa + 32 * n ≤ 2784)
    (hn : n ≤ 8) (hj : j < n) :
    runInstructions (headProgram a t) (chainState template pc m bi rest) =
    some (chainState template (pc + UInt256.ofNat 37) (SquareModel.l1StepOn m bi pa n j) bi rest) := by
  have hc : rest.length + 3 < 1024 := by omega
  have hjd : runInstructions [.op .JUMPDEST] (chainState template pc m bi rest) =
      some (chainState template (pc + UInt256.ofNat 1) m bi rest) := by
    simp [runInstructions, Challenge.EvmProof.Stepper.runInstr, chainState, hc, succ_eq_add]
  have hl := run_block template (pc + UInt256.ofNat 1) m bi pa n j a t ha ht rest hrest
    hactive hpa hn hj
  have h := runInstructions_append_some _ _ _ _ _ hjd hl
  have hpc : pc + UInt256.ofNat 1 + UInt256.ofNat 36 = pc + UInt256.ofNat 37 := by
    rw [word_add_assoc, Challenge.EvmProof.Word.ofNat_add_mod]
  rw [hpc] at h
  exact h

/-- One straight block on a MAC state whose incoming carry is *zero*, with the carry add replaced
by the same-byte `PUSH0 POP` no-op after the existing `lo` copy.  Same conclusion as `run_block`. -/
theorem run_block_zero (template : State) (pc : UInt256) (m : MacState) (bi : UInt256)
    (pa n j : Nat) (a t : UInt256)
    (ha : a.toNat = pa + 32 * (n - 1 - j)) (ht : t.toNat = 2112 + 32 * (n - 1 - j))
    (rest : List UInt256) (hrest : rest.length ≤ 1014)
    (hactive : 88 ≤ template.activeWords.toNat) (hpa : pa + 32 * n ≤ 2784)
    (hn : n ≤ 8) (hj : j < n) (hcarry : m.carry = UInt256.ofNat 0) :
    runInstructions (blockZeroProgram a t) (chainState template pc m bi rest) =
    some (chainState template (pc + UInt256.ofNat 36) (SquareModel.l1StepOn m bi pa n j) bi rest) := by
  have hactA : UInt256.ofNat (MachineState.activeWordsAfter template.activeWords.toNat
      (pa + 32 * (n - 1 - j)) 32) = template.activeWords :=
    activeWords_fix template _ 32 (by decide) (by omega) hactive
  have hactT : UInt256.ofNat (MachineState.activeWordsAfter template.activeWords.toNat
      (2112 + 32 * (n - 1 - j)) 32) = template.activeWords :=
    activeWords_fix template _ 32 (by decide) (by omega) hactive
  let st : State := { template with memory := m.memory }
  have hA : UInt256.ofNat (MachineState.activeWordsAfter st.activeWords.toNat a.toNat 32) =
      st.activeWords := by simpa only [st, ha] using hactA
  have hT : UInt256.ofNat (MachineState.activeWordsAfter st.activeWords.toNat t.toNat 32) =
      st.activeWords := by simpa only [st, ht] using hactT
  have hl := run_load st pc a m.carry bi rest hrest hA
  have hread : MachineState.readWord st.memory a.toNat =
      MachineState.readWord m.memory (pa + 32 * (n - 1 - j)) := by simp only [st, ha]
  rw [hread] at hl
  have hf := CiosCachedFused.run_fused_zero st (pc + UInt256.ofNat 5)
    (MachineState.readWord m.memory (pa + 32 * (n - 1 - j))) bi m.carry t t
    (maxWord :: rest) (by simp only [List.length_cons]; omega) hT hT hcarry
  have hall := runInstructions_append_some _ _ _ _ _ hl hf
  have hpc : (pc + UInt256.ofNat 5) + UInt256.ofNat 31 = pc + UInt256.ofNat 36 := by
    simp [word_add_assoc, Challenge.EvmProof.Word.ofNat_add_mod]
  simpa only [blockZeroProgram, st, chainState, framed, SquareModel.l1StepOn, ht, hpc,
    List.cons_append, List.nil_append] using hall

/-- Block 0 (`JUMPDEST` included, 37 bytes) on a zero incoming carry. -/
theorem run_head_zero (template : State) (pc : UInt256) (m : MacState) (bi : UInt256)
    (pa n j : Nat) (a t : UInt256)
    (ha : a.toNat = pa + 32 * (n - 1 - j)) (ht : t.toNat = 2112 + 32 * (n - 1 - j))
    (rest : List UInt256) (hrest : rest.length ≤ 1014)
    (hactive : 88 ≤ template.activeWords.toNat) (hpa : pa + 32 * n ≤ 2784)
    (hn : n ≤ 8) (hj : j < n) (hcarry : m.carry = UInt256.ofNat 0) :
    runInstructions (headZeroProgram a t) (chainState template pc m bi rest) =
    some (chainState template (pc + UInt256.ofNat 37) (SquareModel.l1StepOn m bi pa n j) bi rest) := by
  have hc : rest.length + 3 < 1024 := by omega
  have hjd : runInstructions [.op .JUMPDEST] (chainState template pc m bi rest) =
      some (chainState template (pc + UInt256.ofNat 1) m bi rest) := by
    simp [runInstructions, Challenge.EvmProof.Stepper.runInstr, chainState, hc, succ_eq_add]
  have hl := run_block_zero template (pc + UInt256.ofNat 1) m bi pa n j a t ha ht rest hrest
    hactive hpa hn hj hcarry
  have h := runInstructions_append_some _ _ _ _ _ hjd hl
  have hpc : pc + UInt256.ofNat 1 + UInt256.ofNat 36 = pc + UInt256.ofNat 37 := by
    rw [word_add_assoc, Challenge.EvmProof.Word.ofNat_add_mod]
  rw [hpc] at h
  exact h

/-- `SWAP1 SWAP2 POP`: `[carry, q, mask] ++ rest` becomes `[carry, q] ++ rest`. -/
theorem run_exit (template : State) (pc : UInt256) (m : MacState) (bi : UInt256)
    (rest : List UInt256) (hrest : rest.length ≤ 1014) :
    runInstructions exitProgram (chainState template pc m bi rest) =
    some (exitState template (pc + UInt256.ofNat 3) m bi rest) := by
  have hc : rest.length + 3 < 1024 := by omega
  simp (disch := omega) [runInstructions, exitProgram, chainState, exitState,
    Challenge.EvmProof.Stepper.runInstr, hc, List.exchange,
    List.getElem?_cons_zero, List.getElem?_cons_succ, List.cons_append, List.nil_append,
    succ_eq_add, word_add_assoc, Challenge.EvmProof.Word.ofNat_add_mod]

private theorem notZero_maxWord : UInt256.lnot (⟨0⟩ : UInt256) = maxWord := by decide

private theorem notZeroOfNat_maxWord : UInt256.lnot (UInt256.ofNat 0) = maxWord := by decide

private theorem push0_ofNat : (⟨0⟩ : UInt256) = UInt256.ofNat 0 := by decide

/-- E6: from `[q] ++ rest` over `um` to the chain frame `[0, q, mask] ++ rest` at the entry cached at 1698. -/
theorem run_entry (template : State) (pc : UInt256) (um : ByteArray) (bi : UInt256)
    (rest : List UInt256) (ent : Nat) (hrest : rest.length ≤ 1014)
    (hactive : 88 ≤ template.activeWords.toNat)
    (hcache : MachineState.readWord um 1698 = UInt256.ofNat ent)
    (hent : ent < 2 ^ 256)
    (hjump : Decode.isValidJumpDest template.executionEnv.code ent = true) :
    runInstructions entryProgram (setupState template pc um bi rest) =
    some (chainState template (UInt256.ofNat ent) ⟨um, UInt256.ofNat 0⟩ bi rest) := by
  have hc1 : rest.length + 1 < 1024 := by omega
  have hc2 : rest.length + 2 < 1024 := by omega
  have hc3 : rest.length + 3 < 1024 := by omega
  have hc4 : rest.length + 4 < 1024 := by omega
  have hact : UInt256.ofNat (MachineState.activeWordsAfter template.activeWords.toNat 1698 32) =
      template.activeWords := activeWords_fix template _ 32 (by decide) (by omega) hactive
  have htoNat : (UInt256.ofNat ent).toNat = ent := by
    rw [Challenge.EvmProof.Word.word_toNat_ofNat, Nat.mod_eq_of_lt hent]
  simp (disch := omega) [runInstructions, entryProgram, setupState, chainState,
    Challenge.EvmProof.Stepper.runInstr, hc1, hc2, hc3, hc4, List.exchange,
    List.getElem?_cons_zero, List.getElem?_cons_succ, List.cons_append, List.nil_append,
    State.activeWordsAfterUInt256, hact, hcache, htoNat, hjump, notZero_maxWord, notZeroOfNat_maxWord, push0_ofNat,
    Challenge.EvmProof.Word.literal_eq_ofNat]

end Challenge.Modexp.Submission.Proofs.Fast.M9Mac

#print axioms Challenge.Modexp.Submission.Proofs.Fast.M9Mac.run_block
#print axioms Challenge.Modexp.Submission.Proofs.Fast.M9Mac.run_head
#print axioms Challenge.Modexp.Submission.Proofs.Fast.M9Mac.run_block_zero
#print axioms Challenge.Modexp.Submission.Proofs.Fast.M9Mac.run_head_zero
#print axioms Challenge.Modexp.Submission.Proofs.Fast.M9Mac.run_exit
#print axioms Challenge.Modexp.Submission.Proofs.Fast.M9Mac.run_entry
