import Challenge.Modexp.Submission.Proofs.Fast.M9MacChain
import Challenge.Modexp.Submission.Proofs.Fast.ShiftModel

set_option warningAsError true

/-!
# M9: the MAC section in the shift-reduce routine's own vocabulary
(generated by evidence/root/mx-m9-lemmas/gen_m9_mac.py from rows.json ad60d3dac181; do not edit by hand)

`gasSteps_macChain` instantiated on the conversion routine's frame: `rest := k :: outer n bsize esize msize`
(`Exp.outer`, five words), `-N` base `Shift.NEG` (= 1280).  This is the statement that replaces
`Shift.gasSteps_macLoop` together with the old `run_macSetup`/`ShiftDispatchTrace.run_dispatch` prefix
and the `POP POP POP` head of `blk3125`: from the old `macSetupState` pc (now 2673) with `[q, k] ++ outer`
over `um` to pc 2975 with `[carry, q, k] ++ outer` over `Monpro.l1Step um q NEG n n`.

## Assumed from the tree (unchanged by the port)
* `Challenge.Modexp.Submission.Proofs.Fast.Exp.outer (n bsize esize msize : Nat) : List UInt256` (five words).
* `Challenge.Modexp.Submission.Proofs.Fast.Shift.NEG : Nat := 1280` (`Proofs/Fast/ShiftModel.lean`).
-/

namespace Challenge.Modexp.Submission.Proofs.Fast.M9Mac

open EvmSemantics EvmSemantics.EVM
open Challenge.Modexp.Submission.Proofs.Fast Monpro

/-- The section on the conversion frame.  `hcache` is the E5-stored entry: `2682` for eight limbs,
`2827 = 2682 + 0x91` for four (`entryPC n`). -/
def gasSteps_macSection (n : Nat) (hn : n = 4 ∨ n = 8) (s : State) (um : ByteArray) (q : UInt256)
    (bsize esize msize k : Nat) (hrun : s.halt = .Running)
    (hcode : s.executionEnv.code = Challenge.Modexp.submissionBytecode)
    (hfork : s.fork = .Osaka)
    (hnp : Precompile.isPrecompileWithConfig s.executionEnv.precompileConfig
      s.executionEnv.fork s.executionEnv.codeAddr = false)
    (hact : 88 ≤ s.activeWords.toNat)
    (hcache : MachineState.readWord um 1698 = UInt256.ofNat (entryPC n)) :
    Challenge.EvmProof.GasSteps
      { s with pc := UInt256.ofNat 2673,
                stack := q :: UInt256.ofNat k :: Exp.outer n bsize esize msize,
                memory := um }
      { s with pc := UInt256.ofNat 2975,
                stack := (l1Step um q Shift.NEG n n).carry :: q :: UInt256.ofNat k ::
                  Exp.outer n bsize esize msize,
                memory := (l1Step um q Shift.NEG n n).memory } :=
  gasSteps_macChain n hn s um q (UInt256.ofNat k :: Exp.outer n bsize esize msize)
    (by simp only [List.length_cons, Exp.outer, List.length_nil]; omega)
    hrun hcode hfork hnp hact hcache

end Challenge.Modexp.Submission.Proofs.Fast.M9Mac

#print axioms Challenge.Modexp.Submission.Proofs.Fast.M9Mac.gasSteps_macSection
