import Challenge.Modexp.Submission.Proofs.Fast.CiosCachedPrograms

set_option warningAsError true

/-!
# M9: instruction sequences of the eight straight conversion MAC blocks
(generated by evidence/root/mx-m9-lemmas/gen_m9_mac.py from rows.json ad60d3dac181; do not edit by hand)

Each block `b = 0..7` of the M9 conversion product section is
`PUSH2 (0x5e0 - 32b); MLOAD; DUP4` followed by `CiosCached.macFusedProgram T T`, `T = 0x920 - 32b`
(30 instructions, 36 bytes).  Blocks 0 and 4 carry the entry `JUMPDEST`s.

The section is entered by E6 and left through `JUMPDEST JUMPDEST JUMPDEST` (pc 3168..3170),
falling into the top-limb fixup at pc 3171 with the chain frame untouched.

## Assumed from the tree (unchanged by the port)
* `Challenge.Modexp.Submission.Proofs.Fast.CiosCached.macFusedProgram : UInt256 → UInt256 → List Instr`
  (`Proofs/Fast/CiosCachedPrograms.lean`; `= macProductProgram.take 6 ++ macFusedPostProgram tl ts`).
* `YulEvmCompiler.Instr` with constructors `.push (w : Fin 33) (v : UInt256)` and `.op (o : Operation)`,
  `Operation.Dup`/`.Swap` taking `{ idx : Fin 16 }`.
-/

namespace Challenge.Modexp.Submission.Proofs.Fast.M9Mac

open EvmSemantics EvmSemantics.EVM YulEvmCompiler
open Challenge.Modexp.Submission.Proofs.Fast

/-- `PUSH2 a; MLOAD; DUP4`: load the modulus limb and lift the mask into `run_fused`'s frame. -/
def loadProgram (a : UInt256) : List Instr :=
  [.push 2 a, .op .MLOAD, .op (.Dup ⟨3, by decide⟩)]

/-- One straight MAC block without its `JUMPDEST` (30 instructions, 36 bytes). -/
def blockProgram (a t : UInt256) : List Instr :=
  loadProgram a ++ CiosCached.macFusedProgram t t

/-- Blocks 0 and 4, `JUMPDEST` included (31 instructions, 37 bytes). -/
def headProgram (a t : UInt256) : List Instr :=
  [.op .JUMPDEST] ++ blockProgram a t


/-- Fused head for a riding straight MAC block: `JUMPDEST DUP2 DUP(d+2) MUL DUP4 DUP(d+3) DUP5 MULMOD`. -/
def rideHead (d : Fin 16) : List Instr :=
  if h : d.val ≤ 13 then
    [.op .JUMPDEST,
     .op (.Dup ⟨1, by decide⟩),
     .op (.Dup ⟨d.val + 1, by omega⟩),
     .op .MUL,
     .op (.Dup ⟨3, by decide⟩),
     .op (.Dup ⟨d.val + 2, by omega⟩),
     .op (.Dup ⟨4, by decide⟩),
     .op .MULMOD]
  else
    [.op (.Dup { idx := d }), .op (.Dup ⟨3, by decide⟩)] ++ CiosCached.macProductProgram.take 6

/-- One straight MAC block whose `-N` limb rides in a stack slot (phases 9/10 chunk
mirroring): fused `rideHead d` followed by `macFusedPostProgram t t` (29 instructions,
33 bytes — no `MLOAD`, no `SWAP2`). -/
def rideProgram (d : Fin 16) (t : UInt256) : List Instr :=
  rideHead d ++ CiosCached.macFusedPostProgram t t

/-- The riding form of block 0: the incoming carry is the literal zero, so the fused
post-schedule spends `PUSH0` where `rideProgram` spends the `DUP4` that reproduces the
carry. -/
def rideZeroProgram (d : Fin 16) (t : UInt256) : List Instr :=
  [.op (.Dup { idx := d }), .op (.Dup ⟨3, by decide⟩)] ++ CiosCached.macFusedZeroProgram t t

/-- Fused head for the top-word riding block 0: `JUMPDEST POP DUP1 DUP(d+2) MUL DUP3 DUP(d+3) DUP4 MULMOD`. -/
def rideTopHead (d : Fin 16) : List Instr :=
  if h : d.val ≤ 13 then
    [.op .JUMPDEST,
     .op .POP,
     .op (.Dup ⟨0, by decide⟩),
     .op (.Dup ⟨d.val + 1, by omega⟩),
     .op .MUL,
     .op (.Dup ⟨2, by decide⟩),
     .op (.Dup ⟨d.val + 2, by omega⟩),
     .op (.Dup ⟨3, by decide⟩),
     .op .MULMOD]
  else
    [.op .POP, .op (.Dup { idx := d }), .op (.Dup ⟨2, by decide⟩)] ++ CiosCached.topProductProgram

def rideTopStore (ts : UInt256) : List Instr :=
  [.op (.Dup ⟨1, by decide⟩), .push 4 ts, .op .MSTORE]

def rideTopCarry : List Instr :=
  [.op (.Dup ⟨0, by decide⟩), .op (.Dup ⟨2, by decide⟩), .op .GT,
   .op (.Swap ⟨0, by decide⟩), .op .SUB, .op .SUB]

def rideTopFill : List Instr := List.replicate 11 (.op .JUMPDEST)

/-- The top-word form of block 0: the incoming carry is the literal zero *and* the accumulator
word it reads was just zeroed by the shift (`ShiftModel.uMem_readWord_limb`, limb `0`), so the
block pops the zero carry, fuses the `-N` limb multiply, stores the low word with `PUSH4`,
computes the carry with `SWAP1 SUB SUB`, and pads with 11 `JUMPDEST`s (33 bytes, 29 instructions). -/
def rideTopProgram (d : Fin 16) (t : UInt256) : List Instr :=
  rideTopHead d ++ ((rideTopStore t ++ rideTopCarry) ++ rideTopFill)

/-- `JUMPDEST JUMPDEST JUMPDEST`: the chain frame `[carry, q, 2^256-1] ++ rest` survives the
fall-through into the top-limb fixup at pc 3171 unchanged, and the fixup gives the mask back
to its slot with `SWAP3 POP` at pc 3184..3185 before `SUB`.  The three former `SWAP1 SWAP2 POP`
opcodes cost 8 gas where three `JUMPDEST`s cost 3. -/
def exitProgram : List Instr :=
  [.op .JUMPDEST]

/-- E6: `PUSH0 NOT SWAP1 PUSH0 DUP5 JUMP` — build the chain frame `[0, q, 2^256-1]` and
jump to the entry parked in the scratch slot (the first riding slot, `shiftEntry`). -/
def entryProgram : List Instr :=
  [.push 0 0, .op .NOT, .op (.Swap ⟨0, by decide⟩), .push 0 0,
   .op (.Dup ⟨4, by decide⟩), .op .JUMP]

end Challenge.Modexp.Submission.Proofs.Fast.M9Mac
