import Challenge.Sha256.ProofSupport.Bytecode
import Challenge.Sha256.Submission.Bytecode

set_option warningAsError true

/-!
# Direct-bytecode target for the reference artifact

The generic `DirectProof` interface is reusable proof support and lives in
`Challenge.Sha256.ProofSupport.Bytecode`.  This module fixes that interface to the
frozen reference bytes; its implementation is in the adjacent `Bytecode/`
directory.
-/

namespace Challenge.Sha256.Submission.Proofs.Bytecode

open Challenge.Sha256.ProofSupport.Bytecode

/-- The frozen Yul-generated bytecode, treated only as raw bytes. -/
def submissionDirectGoal : Prop := DirectProof submissionBytecode

end Challenge.Sha256.Submission.Proofs.Bytecode
