import Challenge.Modexp.Submission.Proofs.Bytecode.WindowTwentyOneGasRoute
import Challenge.Modexp.Submission.Proofs.Bytecode.WindowTwentyOneSlice
import Challenge.EvmProof.Program
import Challenge.EvmProof.Stepper
import Challenge.EvmProof.Word
import Challenge.Modexp.Submission.Bytecode
import Challenge.Modexp.Submission.Proofs.Bytecode.FermatProgram
import Challenge.Modexp.Submission.Proofs.Bytecode.EarlyWordProgram

attribute [simp]
  Challenge.EvmProof.Word.word_toNat_add
  Challenge.EvmProof.Word.word_toNat_sub
  Challenge.EvmProof.Word.word_toNat_lt
  Challenge.EvmProof.Word.word_toNat_isZero
  Challenge.EvmProof.Word.word_toNat_lor
  Challenge.EvmProof.Word.word_toNat_land

set_option warningAsError true
set_option maxRecDepth 20000
set_option maxHeartbeats 2000000

namespace Challenge.Modexp.Submission.Proofs.Bytecode.Artifact

open EvmSemantics
open EvmSemantics.EVM
open YulEvmCompiler

def submissionInstructions : List Instr :=
[
  .push 2 5279,
  .op .JUMP,
  .op .JUMPDEST,
  .op (.Dup ⟨0, by decide⟩),
  .op .CALLDATALOAD,
  .push 0 0,
  .op .BYTE,
  .op (.Swap ⟨1, by decide⟩),
  .op .POP,
  .op .POP,
  .op (.Swap ⟨0, by decide⟩),
  .op .JUMP,
  .op .JUMPDEST,
  .push 2 53,
  .op .JUMP,
  .op .JUMPDEST,
  .push 0 0,
  .op .JUMPDEST,
  .op (.Dup ⟨2, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .op .LT,
  .op .ISZERO,
  .push 2 48,
  .op .JUMPI,
  .push 0 0,
  .op (.Dup ⟨1, by decide⟩),
  .push 1 5,
  .op .SHL,
  .op (.Dup ⟨3, by decide⟩),
  .op .ADD,
  .op .MSTORE,
  .push 1 1,
  .op (.Dup ⟨1, by decide⟩),
  .op .ADD,
  .op (.Swap ⟨0, by decide⟩),
  .op .POP,
  .push 2 21,
  .op .JUMP,
  .op .JUMPDEST,
  .op .POP,
  .op .POP,
  .op .POP,
  .op .JUMP,
  .op .JUMPDEST,
  .push 2 99,
  .op .JUMP,
  .op .JUMPDEST,
  .push 0 0,
  .op .JUMPDEST,
  .op (.Dup ⟨3, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .op .LT,
  .op .ISZERO,
  .push 2 93,
  .op .JUMPI,
  .op (.Dup ⟨0, by decide⟩),
  .push 1 5,
  .op .SHL,
  .op (.Dup ⟨3, by decide⟩),
  .op .ADD,
  .op .MLOAD,
  .op (.Dup ⟨1, by decide⟩),
  .push 1 5,
  .op .SHL,
  .op (.Dup ⟨3, by decide⟩),
  .op .ADD,
  .op .MSTORE,
  .push 1 1,
  .op (.Dup ⟨1, by decide⟩),
  .op .ADD,
  .op (.Swap ⟨0, by decide⟩),
  .op .POP,
  .push 2 60,
  .op .JUMP,
  .op .JUMPDEST,
  .op .POP,
  .op .POP,
  .op .POP,
  .op .POP,
  .op .JUMP,
  .op .JUMPDEST,
  .push 2 305,
  .op .JUMP,
  .op .JUMPDEST,
  .op (.Dup ⟨2, by decide⟩),
  .push 0 0,
  .op .SUB,
  .push 0 0,
  .push 0 0,
  .op .JUMPDEST,
  .op (.Dup ⟨7, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .op .LT,
  .op .ISZERO,
  .push 2 170,
  .op .JUMPI,
  .op (.Dup ⟨0, by decide⟩),
  .push 1 5,
  .op .SHL,
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨5, by decide⟩),
  .op .ADD,
  .op .MLOAD,
  .op (.Dup ⟨4, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op (.Dup ⟨8, by decide⟩),
  .op .ADD,
  .op .MLOAD,
  .op .AND,
  .op (.Dup ⟨1, by decide⟩),
  .op .ADD,
  .op (.Dup ⟨1, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .op .LT,
  .op (.Dup ⟨5, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .ADD,
  .op (.Dup ⟨2, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .op .LT,
  .op (.Dup ⟨1, by decide⟩),
  .op (.Dup ⟨6, by decide⟩),
  .op (.Dup ⟨11, by decide⟩),
  .op .ADD,
  .op .MSTORE,
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨3, by decide⟩),
  .op .OR,
  .op (.Swap ⟨7, by decide⟩),
  .op .POP,
  .op .POP,
  .op .POP,
  .op .POP,
  .op .POP,
  .op .POP,
  .op .POP,
  .push 1 1,
  .op (.Dup ⟨1, by decide⟩),
  .op .ADD,
  .op (.Swap ⟨0, by decide⟩),
  .op .POP,
  .push 2 110,
  .op .JUMP,
  .op .JUMPDEST,
  .op .POP,
  .push 0 0,
  .push 0 0,
  .op .JUMPDEST,
  .op (.Dup ⟨8, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .op .LT,
  .op .ISZERO,
  .push 2 236,
  .op .JUMPI,
  .op (.Dup ⟨0, by decide⟩),
  .push 1 5,
  .op .SHL,
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨6, by decide⟩),
  .op .ADD,
  .op .MLOAD,
  .op (.Dup ⟨1, by decide⟩),
  .op (.Dup ⟨10, by decide⟩),
  .op .ADD,
  .op .MLOAD,
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .SUB,
  .op (.Dup ⟨1, by decide⟩),
  .op (.Dup ⟨3, by decide⟩),
  .op .LT,
  .op (.Dup ⟨6, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .SUB,
  .op (.Dup ⟨7, by decide⟩),
  .op (.Dup ⟨3, by decide⟩),
  .op .LT,
  .op (.Dup ⟨1, by decide⟩),
  .op (.Dup ⟨7, by decide⟩),
  .push 2 5120,
  .op .ADD,
  .op .MSTORE,
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨3, by decide⟩),
  .op .OR,
  .op (.Swap ⟨8, by decide⟩),
  .op .POP,
  .op .POP,
  .op .POP,
  .op .POP,
  .op .POP,
  .op .POP,
  .op .POP,
  .op .POP,
  .push 1 1,
  .op (.Dup ⟨1, by decide⟩),
  .op .ADD,
  .op (.Swap ⟨0, by decide⟩),
  .op .POP,
  .push 2 174,
  .op .JUMP,
  .op .JUMPDEST,
  .op .POP,
  .op (.Dup ⟨0, by decide⟩),
  .op .ISZERO,
  .op (.Dup ⟨2, by decide⟩),
  .op .OR,
  .push 0 0,
  .op .SUB,
  .push 0 0,
  .op .JUMPDEST,
  .op (.Dup ⟨9, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .op .LT,
  .op .ISZERO,
  .push 2 293,
  .op .JUMPI,
  .op (.Dup ⟨0, by decide⟩),
  .push 1 5,
  .op .SHL,
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨7, by decide⟩),
  .op .ADD,
  .op .MLOAD,
  .op (.Dup ⟨1, by decide⟩),
  .push 2 5120,
  .op .ADD,
  .op .MLOAD,
  .op (.Dup ⟨4, by decide⟩),
  .op .NOT,
  .op (.Dup ⟨2, by decide⟩),
  .op .AND,
  .op (.Dup ⟨5, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .AND,
  .op .OR,
  .op (.Dup ⟨3, by decide⟩),
  .op (.Dup ⟨10, by decide⟩),
  .op .ADD,
  .op .MSTORE,
  .op .POP,
  .op .POP,
  .op .POP,
  .push 1 1,
  .op (.Dup ⟨1, by decide⟩),
  .op .ADD,
  .op (.Swap ⟨0, by decide⟩),
  .op .POP,
  .push 2 245,
  .op .JUMP,
  .op .JUMPDEST,
  .op .POP,
  .op .POP,
  .op .POP,
  .op .POP,
  .op .POP,
  .op .POP,
  .op .POP,
  .op .POP,
  .op .POP,
  .op .POP,
  .op .JUMP,
  .op .JUMPDEST,
  .push 2 434,
  .op .JUMP,
  .op .JUMPDEST,
  .push 2 320,
  .op (.Dup ⟨5, by decide⟩),
  .op (.Dup ⟨4, by decide⟩),
  .push 2 19,
  .op .JUMP,
  .op .JUMPDEST,
  .push 2 333,
  .op (.Dup ⟨5, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .push 2 4096,
  .push 2 58,
  .op .JUMP,
  .op .JUMPDEST,
  .push 0 0,
  .op .JUMPDEST,
  .op (.Dup ⟨5, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .op .LT,
  .op .ISZERO,
  .push 2 426,
  .op .JUMPI,
  .op (.Dup ⟨0, by decide⟩),
  .push 1 5,
  .op .SHL,
  .op (.Dup ⟨3, by decide⟩),
  .op .ADD,
  .op .MLOAD,
  .push 0 0,
  .op .JUMPDEST,
  .push 2 256,
  .op (.Dup ⟨1, by decide⟩),
  .op .LT,
  .op .ISZERO,
  .push 2 413,
  .op .JUMPI,
  .push 1 1,
  .op (.Dup ⟨2, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .SHR,
  .op .AND,
  .push 2 383,
  .op (.Dup ⟨9, by decide⟩),
  .op (.Dup ⟨9, by decide⟩),
  .op (.Dup ⟨3, by decide⟩),
  .push 2 4096,
  .op (.Dup ⟨11, by decide⟩),
  .push 2 104,
  .op .JUMP,
  .op .JUMPDEST,
  .push 2 401,
  .op (.Dup ⟨9, by decide⟩),
  .op (.Dup ⟨9, by decide⟩),
  .push 1 1,
  .push 2 4096,
  .push 2 4096,
  .push 2 104,
  .op .JUMP,
  .op .JUMPDEST,
  .op .POP,
  .push 1 1,
  .op (.Dup ⟨1, by decide⟩),
  .op .ADD,
  .op (.Swap ⟨0, by decide⟩),
  .op .POP,
  .push 2 352,
  .op .JUMP,
  .op .JUMPDEST,
  .op .POP,
  .op .POP,
  .push 1 1,
  .op (.Dup ⟨1, by decide⟩),
  .op .ADD,
  .op (.Swap ⟨0, by decide⟩),
  .op .POP,
  .push 2 335,
  .op .JUMP,
  .op .JUMPDEST,
  .op .POP,
  .op .POP,
  .op .POP,
  .op .POP,
  .op .POP,
  .op .POP,
  .op .JUMP,
  .op .JUMPDEST,
  .push 2 512,
  .op .JUMP,
  .op .JUMPDEST,
  .push 0 0,
  .op .JUMPDEST,
  .op (.Dup ⟨2, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .op .LT,
  .op .ISZERO,
  .push 2 506,
  .op .JUMPI,
  .op (.Dup ⟨0, by decide⟩),
  .push 1 1,
  .op (.Dup ⟨4, by decide⟩),
  .op .SUB,
  .op .SUB,
  .op (.Dup ⟨0, by decide⟩),
  .push 1 5,
  .op .SHR,
  .push 1 31,
  .op (.Dup ⟨2, by decide⟩),
  .op .AND,
  .push 1 3,
  .op .SHL,
  .op (.Dup ⟨1, by decide⟩),
  .push 1 5,
  .op .SHL,
  .op (.Dup ⟨7, by decide⟩),
  .op .ADD,
  .push 2 484,
  .push 0 0,
  .op (.Dup ⟨6, by decide⟩),
  .op (.Dup ⟨8, by decide⟩),
  .op .ADD,
  .push 2 4,
  .op .JUMP,
  .op .JUMPDEST,
  .op (.Dup ⟨2, by decide⟩),
  .op .SHL,
  .op (.Dup ⟨1, by decide⟩),
  .op .MLOAD,
  .op .OR,
  .op (.Dup ⟨1, by decide⟩),
  .op .MSTORE,
  .op .POP,
  .op .POP,
  .op .POP,
  .op .POP,
  .push 1 1,
  .op (.Dup ⟨1, by decide⟩),
  .op .ADD,
  .op (.Swap ⟨0, by decide⟩),
  .op .POP,
  .push 2 441,
  .op .JUMP,
  .op .JUMPDEST,
  .op .POP,
  .op .POP,
  .op .POP,
  .op .POP,
  .op .JUMP,
  .op .JUMPDEST,
  .push 2 699,
  .op .JUMP,
  .op .JUMPDEST,
  .op (.Dup ⟨5, by decide⟩),
  .op .CALLDATALOAD,
  .op (.Dup ⟨3, by decide⟩),
  .push 1 32,
  .op .SUB,
  .push 1 3,
  .op .SHL,
  .op .SHR,
  .op (.Dup ⟨0, by decide⟩),
  .push 2 538,
  .op .JUMPI,
  .op (.Dup ⟨3, by decide⟩),
  .push 2 0,
  .op .RETURN,
  .op .JUMPDEST,
  .push 0 0,
  .push 0 0,
  .op .JUMPDEST,
  .op (.Dup ⟨3, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .op .LT,
  .op .ISZERO,
  .push 2 582,
  .op .JUMPI,
  .op (.Dup ⟨2, by decide⟩),
  .push 2 562,
  .push 0 0,
  .op (.Dup ⟨3, by decide⟩),
  .op (.Dup ⟨10, by decide⟩),
  .op .ADD,
  .push 2 4,
  .op .JUMP,
  .op .JUMPDEST,
  .op (.Dup ⟨4, by decide⟩),
  .push 2 256,
  .op (.Dup ⟨5, by decide⟩),
  .op .MULMOD,
  .op .ADDMOD,
  .op (.Swap ⟨1, by decide⟩),
  .op .POP,
  .push 1 1,
  .op .ADD,
  .push 2 541,
  .op .JUMP,
  .push 0 0,
  .push 0 0,
  .push 0 0,
  .op .JUMPDEST,
  .op .POP,
  .op (.Dup ⟨1, by decide⟩),
  .push 1 1,
  .op .MOD,
  .push 0 0,
  .op .JUMPDEST,
  .op (.Dup ⟨5, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .op .EQ,
  .op .JUMPDEST,
  .push 2 669,
  .op .JUMPI,
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨9, by decide⟩),
  .op .ADD,
  .op (.Dup ⟨0, by decide⟩),
  .op .CALLDATALOAD,
  .push 0 0,
  .op .BYTE,
  .push 0 0,
  .op .JUMPDEST,
  .push 2 3454,
  .op .JUMP,
  .push 1 0,
  .op .JUMPDEST,
  .op .JUMPDEST,
  .op .JUMPDEST,
  .push 1 1,
  .op (.Dup ⟨2, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .push 1 7,
  .op .SUB,
  .op .SHR,
  .op .AND,
  .op (.Dup ⟨7, by decide⟩),
  .op (.Dup ⟨6, by decide⟩),
  .op (.Dup ⟨7, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨1, by decide⟩),
  .push 0 0,
  .op .SUB,
  .op (.Dup ⟨9, by decide⟩),
  .op (.Dup ⟨9, by decide⟩),
  .op (.Dup ⟨3, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨2, by decide⟩),
  .op .XOR,
  .op .AND,
  .op (.Dup ⟨1, by decide⟩),
  .op .XOR,
  .op (.Swap ⟨6, by decide⟩),
  .op .POP,
  .op .POP,
  .op .POP,
  .push 1 1,
  .op .ADD,
  .push 2 606,
  .op .JUMP,
  .push 0 0,
  .push 0 0,
  .push 0 0,
  .op .JUMPDEST,
  .op .POP,
  .op .POP,
  .op .POP,
  .push 1 1,
  .op .ADD,
  .push 2 589,
  .op .JUMP,
  .push 0 0,
  .push 0 0,
  .push 0 0,
  .op .JUMPDEST,
  .op .POP,
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨6, by decide⟩),
  .push 1 32,
  .op .SUB,
  .push 1 3,
  .op .SHL,
  .op .SHL,
  .push 0 0,
  .op .MSTORE,
  .op (.Dup ⟨5, by decide⟩),
  .push 4 0,
  .op .RETURN,
  .op .POP,
  .op .POP,
  .op .POP,
  .op .POP,
  .op .POP,
  .op .POP,
  .op .POP,
  .op .POP,
  .op .POP,
  .op .JUMP,
  .op .JUMPDEST,
  .push 2 1196,
  .op .JUMP,
  .op .JUMPDEST,
  .push 1 31,
  .op (.Dup ⟨3, by decide⟩),
  .op .ADD,
  .push 1 5,
  .op .SHR,
  .push 2 721,
  .op (.Dup ⟨1, by decide⟩),
  .push 0 0,
  .push 2 19,
  .op .JUMP,
  .op .JUMPDEST,
  .push 2 733,
  .op (.Dup ⟨1, by decide⟩),
  .push 2 1024,
  .push 2 19,
  .op .JUMP,
  .op .JUMPDEST,
  .push 2 745,
  .op (.Dup ⟨1, by decide⟩),
  .push 2 2048,
  .push 2 19,
  .op .JUMP,
  .op .JUMPDEST,
  .push 2 757,
  .op (.Dup ⟨1, by decide⟩),
  .push 2 6144,
  .push 2 19,
  .op .JUMP,
  .op .JUMPDEST,
  .push 2 768,
  .push 0 0,
  .op (.Dup ⟨5, by decide⟩),
  .op (.Dup ⟨9, by decide⟩),
  .push 2 439,
  .op .JUMP,
  .op .JUMPDEST,
  .push 0 0,
  .push 0 0,
  .op .JUMPDEST,
  .op (.Dup ⟨2, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .op .LT,
  .op .ISZERO,
  .push 2 799,
  .op .JUMPI,
  .op (.Dup ⟨0, by decide⟩),
  .push 1 5,
  .op .SHL,
  .op .MLOAD,
  .op (.Dup ⟨2, by decide⟩),
  .op .OR,
  .op (.Swap ⟨1, by decide⟩),
  .op .POP,
  .push 1 1,
  .op (.Dup ⟨1, by decide⟩),
  .op .ADD,
  .op (.Swap ⟨0, by decide⟩),
  .op .POP,
  .push 2 771,
  .op .JUMP,
  .op .JUMPDEST,
  .op .POP,
  .op (.Dup ⟨0, by decide⟩),
  .push 2 811,
  .op .JUMPI,
  .op (.Dup ⟨4, by decide⟩),
  .push 2 6144,
  .op .RETURN,
  .op .JUMPDEST,
  .push 2 823,
  .op (.Dup ⟨2, by decide⟩),
  .push 2 3072,
  .push 2 19,
  .op .JUMP,
  .op .JUMPDEST,
  .push 1 1,
  .push 2 3072,
  .op .MSTORE,
  .push 0 0,
  .op .JUMPDEST,
  .op (.Dup ⟨3, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .op .LT,
  .op .ISZERO,
  .push 2 925,
  .op .JUMPI,
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨7, by decide⟩),
  .op .ADD,
  .op (.Dup ⟨0, by decide⟩),
  .op .CALLDATALOAD,
  .push 0 0,
  .op .BYTE,
  .push 0 0,
  .op .JUMPDEST,
  .push 1 8,
  .op (.Dup ⟨1, by decide⟩),
  .op .LT,
  .op .ISZERO,
  .push 2 911,
  .op .JUMPI,
  .push 2 875,
  .op (.Dup ⟨6, by decide⟩),
  .push 0 0,
  .push 1 1,
  .push 2 1024,
  .push 2 1024,
  .push 2 104,
  .op .JUMP,
  .op .JUMPDEST,
  .push 2 900,
  .op (.Dup ⟨6, by decide⟩),
  .push 0 0,
  .push 1 1,
  .op (.Dup ⟨5, by decide⟩),
  .op (.Dup ⟨5, by decide⟩),
  .push 1 7,
  .op .SUB,
  .op .SHR,
  .op .AND,
  .push 2 3072,
  .push 2 1024,
  .push 2 104,
  .op .JUMP,
  .op .JUMPDEST,
  .push 1 1,
  .op (.Dup ⟨1, by decide⟩),
  .op .ADD,
  .op (.Swap ⟨0, by decide⟩),
  .op .POP,
  .push 2 848,
  .op .JUMP,
  .op .JUMPDEST,
  .op .POP,
  .op .POP,
  .op .POP,
  .push 1 1,
  .op (.Dup ⟨1, by decide⟩),
  .op .ADD,
  .op (.Swap ⟨0, by decide⟩),
  .op .POP,
  .push 2 831,
  .op .JUMP,
  .op .JUMPDEST,
  .op .POP,
  .push 2 944,
  .op (.Dup ⟨2, by decide⟩),
  .push 0 0,
  .push 1 1,
  .push 2 3072,
  .push 2 2048,
  .push 2 104,
  .op .JUMP,
  .op .JUMPDEST,
  .push 0 0,
  .op .JUMPDEST,
  .op (.Dup ⟨4, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .op .LT,
  .op .ISZERO,
  .push 2 1118,
  .op .JUMPI,
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨8, by decide⟩),
  .op .ADD,
  .op (.Dup ⟨0, by decide⟩),
  .op .CALLDATALOAD,
  .push 0 0,
  .op .BYTE,
  .push 0 0,
  .op .JUMPDEST,
  .push 1 8,
  .op (.Dup ⟨1, by decide⟩),
  .op .LT,
  .op .ISZERO,
  .push 2 1104,
  .op .JUMPI,
  .push 1 1,
  .op (.Dup ⟨2, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .push 1 7,
  .op .SUB,
  .op .SHR,
  .op .AND,
  .push 2 1000,
  .op (.Dup ⟨7, by decide⟩),
  .push 0 0,
  .push 2 3072,
  .push 2 2048,
  .push 2 2048,
  .push 2 310,
  .op .JUMP,
  .op .JUMPDEST,
  .push 2 1015,
  .op (.Dup ⟨7, by decide⟩),
  .push 2 3072,
  .push 2 2048,
  .push 2 58,
  .op .JUMP,
  .op .JUMPDEST,
  .push 2 1034,
  .op (.Dup ⟨7, by decide⟩),
  .push 0 0,
  .push 2 3072,
  .push 2 1024,
  .push 2 2048,
  .push 2 310,
  .op .JUMP,
  .op .JUMPDEST,
  .op (.Dup ⟨0, by decide⟩),
  .push 0 0,
  .op .SUB,
  .push 0 0,
  .op .JUMPDEST,
  .op (.Dup ⟨8, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .op .LT,
  .op .ISZERO,
  .push 2 1090,
  .op .JUMPI,
  .op (.Dup ⟨0, by decide⟩),
  .push 1 5,
  .op .SHL,
  .op (.Dup ⟨0, by decide⟩),
  .push 2 2048,
  .op .ADD,
  .op .MLOAD,
  .op (.Dup ⟨1, by decide⟩),
  .push 2 3072,
  .op .ADD,
  .op .MLOAD,
  .op (.Dup ⟨4, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .op (.Dup ⟨3, by decide⟩),
  .op .XOR,
  .op .AND,
  .op (.Dup ⟨2, by decide⟩),
  .op .XOR,
  .op (.Dup ⟨3, by decide⟩),
  .push 2 2048,
  .op .ADD,
  .op .MSTORE,
  .op .POP,
  .op .POP,
  .op .POP,
  .push 1 1,
  .op (.Dup ⟨1, by decide⟩),
  .op .ADD,
  .op (.Swap ⟨0, by decide⟩),
  .op .POP,
  .push 2 1039,
  .op .JUMP,
  .op .JUMPDEST,
  .op .POP,
  .op .POP,
  .op .POP,
  .push 1 1,
  .op (.Dup ⟨1, by decide⟩),
  .op .ADD,
  .op (.Swap ⟨0, by decide⟩),
  .op .POP,
  .push 2 963,
  .op .JUMP,
  .op .JUMPDEST,
  .op .POP,
  .op .POP,
  .op .POP,
  .push 1 1,
  .op (.Dup ⟨1, by decide⟩),
  .op .ADD,
  .op (.Swap ⟨0, by decide⟩),
  .op .POP,
  .push 2 946,
  .op .JUMP,
  .op .JUMPDEST,
  .op .POP,
  .push 0 0,
  .op .JUMPDEST,
  .op (.Dup ⟨5, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .op .LT,
  .op .ISZERO,
  .push 2 1180,
  .op .JUMPI,
  .op (.Dup ⟨0, by decide⟩),
  .push 1 1,
  .op (.Dup ⟨7, by decide⟩),
  .op .SUB,
  .op .SUB,
  .op (.Dup ⟨0, by decide⟩),
  .push 1 5,
  .op .SHR,
  .push 1 31,
  .op (.Dup ⟨2, by decide⟩),
  .op .AND,
  .push 1 3,
  .op .SHL,
  .push 1 255,
  .op (.Dup ⟨2, by decide⟩),
  .push 1 5,
  .op .SHL,
  .push 2 2048,
  .op .ADD,
  .op .MLOAD,
  .op (.Dup ⟨2, by decide⟩),
  .op .SHR,
  .op .AND,
  .op (.Dup ⟨4, by decide⟩),
  .push 2 6144,
  .op .ADD,
  .op .MSTORE8,
  .op .POP,
  .op .POP,
  .op .POP,
  .push 1 1,
  .op (.Dup ⟨1, by decide⟩),
  .op .ADD,
  .op (.Swap ⟨0, by decide⟩),
  .op .POP,
  .push 2 1121,
  .op .JUMP,
  .op .JUMPDEST,
  .op .POP,
  .op (.Dup ⟨4, by decide⟩),
  .push 2 6144,
  .op .RETURN,
  .op .POP,
  .op .POP,
  .op .POP,
  .op .POP,
  .op .POP,
  .op .POP,
  .op .POP,
  .op .POP,
  .op .JUMP,
  .op .JUMPDEST,
  .push 0 0,
  .op .CALLDATALOAD,
  .push 1 32,
  .op .CALLDATALOAD,
  .push 1 64,
  .op .CALLDATALOAD,
  .push 2 1228,
  .op .JUMP,
  .op .GT,
  .push 2 1024,
  .op (.Dup ⟨3, by decide⟩),
  .op .GT,
  .push 2 1024,
  .op (.Dup ⟨5, by decide⟩),
  .op .GT,
  .op .OR,
  .op .OR,
  .op .ISZERO,
  .push 2 1228,
  .op .JUMPI,
  .op .INVALID,
  .op .JUMPDEST,
  .op (.Dup ⟨0, by decide⟩),
  .push 2 1237,
  .op .JUMPI,
  .push 0 0,
  .push 0 0,
  .op .RETURN,
  .op .JUMPDEST,
  .op (.Dup ⟨2, by decide⟩),
  .push 1 96,
  .op .ADD,
  .op (.Dup ⟨2, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .op .ADD,
  .push 1 32,
  .op (.Dup ⟨3, by decide⟩),
  .op .GT,
  .push 2 1268,
  .op .JUMPI,
  .push 2 1267,
  .op (.Dup ⟨1, by decide⟩),
  .op (.Dup ⟨3, by decide⟩),
  .push 1 96,
  .op (.Dup ⟨6, by decide⟩),
  .op (.Dup ⟨8, by decide⟩),
  .op (.Dup ⟨10, by decide⟩),
  .push 2 2633,
  .op .JUMP,
  .op .JUMPDEST,
  .op .JUMPDEST,
  .push 2 1283,
  .op (.Dup ⟨1, by decide⟩),
  .op (.Dup ⟨3, by decide⟩),
  .push 1 96,
  .op (.Dup ⟨6, by decide⟩),
  .op (.Dup ⟨8, by decide⟩),
  .op (.Dup ⟨10, by decide⟩),
  .push 2 704,
  .op .JUMP,
  .op .JUMPDEST,
  .op .JUMPDEST,
  .op (.Dup ⟨0, by decide⟩),
  .op .ISZERO,
  .push 2 1309,
  .op .JUMPI,
  .push 2 1034,
  .op (.Dup ⟨7, by decide⟩),
  .push 0 0,
  .push 2 3072,
  .push 2 1024,
  .push 2 2048,
  .push 2 310,
  .op .JUMP,
  .op .JUMPDEST,
  .push 2 1034,
  .op .JUMP,
  .op .JUMPDEST,
  .push 1 64,
  .op .CALLDATALOAD,
  .op (.Dup ⟨0, by decide⟩),
  .push 1 33,
  .op .GT,
  .op .JUMPDEST,
  .push 2 1886,
  .op .JUMPI,
  .push 1 32,
  .op .CALLDATALOAD,
  .push 0 0,
  .op .CALLDATALOAD,
  .op (.Dup ⟨2, by decide⟩),
  .push 2 1024,
  .op .LT,
  .op (.Dup ⟨2, by decide⟩),
  .push 2 1024,
  .op .LT,
  .op .OR,
  .op (.Dup ⟨1, by decide⟩),
  .push 2 1024,
  .op .LT,
  .op .OR,
  .push 2 1892,
  .op .JUMPI,
  .op (.Dup ⟨2, by decide⟩),
  .push 1 31,
  .op .ADD,
  .push 1 5,
  .op .SHR,
  .op (.Dup ⟨0, by decide⟩),
  .push 1 5,
  .op .SHL,
  .op (.Dup ⟨3, by decide⟩),
  .op (.Dup ⟨3, by decide⟩),
  .op .ADD,
  .push 1 96,
  .op .ADD,
  .op (.Dup ⟨5, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .SUB,
  .push 1 3,
  .op .SHL,
  .op (.Dup ⟨1, by decide⟩),
  .op .CALLDATALOAD,
  .op (.Swap ⟨0, by decide⟩),
  .op .SHR,
  .op .ISZERO,
  .push 2 1900,
  .op .JUMPI,
  .push 1 32,
  .op (.Dup ⟨6, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .ADD,
  .op .SUB,
  .op .CALLDATALOAD,
  .push 1 1,
  .op .AND,
  .op .ISZERO,
  .push 2 1900,
  .op .JUMPI,
  .op (.Dup ⟨1, by decide⟩),
  .push 2 9344,
  .op .MSTORE,
  .op (.Dup ⟨2, by decide⟩),
  .push 2 9504,
  .op .MSTORE,
  .op (.Dup ⟨3, by decide⟩),
  .push 1 96,
  .op .ADD,
  .push 2 9472,
  .op .MSTORE,
  .op (.Dup ⟨1, by decide⟩),
  .push 1 32,
  .op (.Swap ⟨0, by decide⟩),
  .op .SUB,
  .op (.Dup ⟨0, by decide⟩),
  .push 2 9408,
  .op .MSTORE,
  .op (.Dup ⟨2, by decide⟩),
  .push 2 8224,
  .op .ADD,
  .push 2 9440,
  .op .MSTORE,
  .op (.Dup ⟨2, by decide⟩),
  .op .CALLDATASIZE,
  .push 0 0,
  .op .CALLDATACOPY,
  .op (.Dup ⟨6, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .op (.Dup ⟨5, by decide⟩),
  .op .SUB,
  .op .CALLDATACOPY,
  .op (.Swap ⟨0, by decide⟩),
  .op .POP,
  .op (.Dup ⟨0, by decide⟩),
  .op .MLOAD,
  .op (.Dup ⟨0, by decide⟩),
  .push 2 3,
  .op .MUL,
  .push 1 2,
  .op .XOR,
  .op .JUMPDEST,
  .op .JUMPDEST,
  .op .JUMPDEST,
  .op .JUMPDEST,
  .op .JUMPDEST,
  .op .JUMPDEST,
  .op .JUMPDEST,
  .op .JUMPDEST,
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .MUL,
  .push 1 2,
  .op .SUB,
  .op .MUL,
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .MUL,
  .push 1 2,
  .op .SUB,
  .op .MUL,
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .MUL,
  .push 1 2,
  .op .SUB,
  .op .MUL,
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .MUL,
  .push 1 2,
  .op .SUB,
  .op .MUL,
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .MUL,
  .push 1 2,
  .op .SUB,
  .op .MUL,
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .MUL,
  .push 1 2,
  .op .SUB,
  .op .MUL,
  .push 0 0,
  .op .SUB,
  .push 2 9376,
  .op .MSTORE,
  .op .POP,
  .op .POP,
  .push 1 1,
  .push 2 4096,
  .op .MSTORE,
  .push 2 3816,
  .push 2 4096,
  .push 2 2534,
  .op .JUMP,
  .op .JUMPDEST,
  .push 2 9344,
  .op .MLOAD,
  .push 2 4096,
  .push 2 5120,
  .op .MCOPY,
  .push 2 3330,
  .push 2 5120,
  .push 2 3775,
  .op .JUMP,
  .op .JUMPDEST,
  .push 2 9344,
  .op .MLOAD,
  .push 2 4096,
  .push 2 6144,
  .op .MCOPY,
  .push 1 5,
  .op .JUMPDEST,
  .push 2 1586,
  .push 2 6144,
  .push 2 6144,
  .push 2 6144,
  .push 2 4458,
  .op .JUMP,
  .op .JUMPDEST,
  .op (.Dup ⟨2, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .op .SHR,
  .push 1 1,
  .op .AND,
  .push 2 1024,
  .op .MUL,
  .push 2 4096,
  .op .ADD,
  .push 2 2604,
  .op .JUMP,
  .op .POP,
  .push 2 0,
  .push 2 0,
  .push 2 0,
  .op .JUMPDEST,
  .op .POP,
  .op (.Dup ⟨0, by decide⟩),
  .op .ISZERO,
  .push 2 1631,
  .op .JUMPI,
  .push 0 0,
  .op .NOT,
  .op .ADD,
  .push 3 1569,
  .op .JUMP,
  .op .JUMPDEST,
  .op .POP,
  .op (.Dup ⟨2, by decide⟩),
  .op .ISZERO,
  .push 2 1756,
  .op .JUMPI,
  .push 2 3365,
  .op .JUMP,
  .push 1 0,
  .push 1 0,
  .push 1 0,
  .push 1 0,
  .push 1 0,
  .push 1 0,
  .push 0 0,
  .push 0 0,
  .push 0 0,
  .push 0 0,
  .push 0 0,
  .push 0 0,
  .push 0 0,
  .push 0 0,
  .push 0 0,
  .push 0 0,
  .push 0 0,
  .push 0 0,
  .push 0 0,
  .op .JUMPDEST,
  .op (.Dup ⟨1, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .op .EQ,
  .op .JUMPDEST,
  .push 2 1736,
  .op .JUMPI,
  .push 2 1693,
  .push 2 1024,
  .push 2 5120,
  .push 2 1024,
  .push 2 4458,
  .op .JUMP,
  .op .JUMPDEST,
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .SUB,
  .push 1 5,
  .op .SHL,
  .op (.Dup ⟨5, by decide⟩),
  .op .SUB,
  .push 1 96,
  .op .ADD,
  .op .CALLDATALOAD,
  .op (.Dup ⟨3, by decide⟩),
  .push 2 3040,
  .op .ADD,
  .op .MSTORE,
  .push 2 1728,
  .push 2 1024,
  .push 2 3072,
  .push 2 1024,
  .push 2 2219,
  .op .JUMP,
  .op .JUMPDEST,
  .push 1 1,
  .op .ADD,
  .push 2 1668,
  .op .JUMP,
  .op .JUMPDEST,
  .op .POP,
  .op .POP,
  .push 2 1755,
  .push 2 2048,
  .push 2 6144,
  .push 2 1024,
  .push 2 4458,
  .op .JUMP,
  .op .JUMPDEST,
  .op .JUMPDEST,
  .push 2 3651,
  .op .JUMP,
  .push 1 0,
  .push 1 0,
  .push 1 0,
  .push 1 0,
  .op .JUMPDEST,
  .op (.Dup ⟨4, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .op .EQ,
  .op .JUMPDEST,
  .push 2 1850,
  .op .JUMPI,
  .push 2 2555,
  .op .JUMP,
  .op .POP,
  .op .ADD,
  .op .CALLDATALOAD,
  .push 0 0,
  .op .BYTE,
  .push 1 128,
  .op .JUMPDEST,
  .push 2 1806,
  .push 2 1024,
  .push 2 1024,
  .push 2 1024,
  .push 2 4458,
  .op .JUMP,
  .op .JUMPDEST,
  .op (.Dup ⟨1, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .op .AND,
  .op .ISZERO,
  .push 2 1832,
  .op .JUMPI,
  .push 2 1831,
  .push 2 1024,
  .push 2 2048,
  .push 2 1024,
  .push 2 4458,
  .op .JUMP,
  .op .JUMPDEST,
  .op .JUMPDEST,
  .push 1 1,
  .op .SHR,
  .op (.Dup ⟨0, by decide⟩),
  .push 2 1789,
  .op .JUMPI,
  .op .POP,
  .op .POP,
  .push 1 1,
  .op .ADD,
  .push 2 1769,
  .op .JUMP,
  .op .JUMPDEST,
  .op .POP,
  .push 1 1,
  .op (.Dup ⟨1, by decide⟩),
  .push 2 3040,
  .op .ADD,
  .op .MSTORE,
  .push 2 1876,
  .push 2 1024,
  .push 2 3072,
  .push 2 1024,
  .push 2 4458,
  .op .JUMP,
  .op .JUMPDEST,
  .op (.Dup ⟨4, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .push 2 1024,
  .op .ADD,
  .op .SUB,
  .op .RETURN,
  .op .JUMPDEST,
  .op .POP,
  .push 2 1196,
  .op .JUMP,
  .op .JUMPDEST,
  .op .POP,
  .op .POP,
  .op .POP,
  .push 2 1196,
  .op .JUMP,
  .op .JUMPDEST,
  .op .POP,
  .op .POP,
  .op .POP,
  .op .POP,
  .op .POP,
  .op .POP,
  .push 2 1196,
  .op .JUMP,
  .op .JUMPDEST,
  .push 2 256,
  .op .JUMPDEST,
  .push 2 1926,
  .op (.Dup ⟨2, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .push 2 2219,
  .op .JUMP,
  .op .JUMPDEST,
  .push 1 1,
  .op (.Swap ⟨0, by decide⟩),
  .op .SUB,
  .op (.Dup ⟨0, by decide⟩),
  .push 2 1915,
  .op .JUMPI,
  .op .POP,
  .op .POP,
  .op .JUMP,
  .op .JUMPDEST,
  .push 2 9344,
  .op .MLOAD,
  .op (.Dup ⟨0, by decide⟩),
  .push 1 64,
  .op .ADD,
  .op .CALLDATASIZE,
  .push 2 8192,
  .op .CALLDATACOPY,
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨3, by decide⟩),
  .op .ADD,
  .push 1 32,
  .op (.Swap ⟨0, by decide⟩),
  .op .SUB,
  .push 1 32,
  .op (.Dup ⟨4, by decide⟩),
  .op .SUB,
  .op (.Swap ⟨3, by decide⟩),
  .op .POP,
  .op (.Swap ⟨0, by decide⟩),
  .op .POP,
  .push 1 32,
  .op (.Dup ⟨2, by decide⟩),
  .op .SUB,
  .op (.Swap ⟨1, by decide⟩),
  .op .POP,
  .op .JUMPDEST,
  .op (.Dup ⟨0, by decide⟩),
  .op .MLOAD,
  .push 0 0,
  .push 4 9440,
  .op .MLOAD,
  .op (.Dup ⟨4, by decide⟩),
  .push 7 9344,
  .op .MLOAD,
  .op .ADD,
  .op .JUMPDEST,
  .op (.Dup ⟨3, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .op .MLOAD,
  .op (.Dup ⟨1, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .op .MUL,
  .op (.Swap ⟨1, by decide⟩),
  .push 0 0,
  .op .NOT,
  .op (.Swap ⟨1, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨1, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .op .LT,
  .op (.Dup ⟨2, by decide⟩),
  .op .ADD,
  .op (.Swap ⟨0, by decide⟩),
  .op .SUB,
  .op (.Dup ⟨3, by decide⟩),
  .op .MLOAD,
  .op (.Swap ⟨1, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .ADD,
  .op (.Swap ⟨1, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .LT,
  .op .ADD,
  .op (.Swap ⟨0, by decide⟩),
  .op (.Dup ⟨4, by decide⟩),
  .op .ADD,
  .op (.Swap ⟨3, by decide⟩),
  .op (.Dup ⟨4, by decide⟩),
  .op .LT,
  .op .ADD,
  .op (.Swap ⟨2, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .MSTORE,
  .push 1 31,
  .op .NOT,
  .op .ADD,
  .op (.Swap ⟨0, by decide⟩),
  .push 1 31,
  .op .NOT,
  .op .ADD,
  .op (.Swap ⟨0, by decide⟩),
  .op (.Dup ⟨5, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .op .GT,
  .push 2 1995,
  .op .JUMPI,
  .op .POP,
  .op .POP,
  .op (.Dup ⟨0, by decide⟩),
  .push 2 8224,
  .op .MLOAD,
  .op .ADD,
  .op (.Dup ⟨0, by decide⟩),
  .push 2 8224,
  .op .MSTORE,
  .op .LT,
  .push 2 8192,
  .op .MSTORE,
  .push 2 9440,
  .op .MLOAD,
  .op .MLOAD,
  .push 2 9376,
  .op .MLOAD,
  .op .MUL,
  .op (.Dup ⟨0, by decide⟩),
  .push 2 9408,
  .op .MLOAD,
  .op .MLOAD,
  .op (.Dup ⟨1, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .op .MUL,
  .op (.Swap ⟨1, by decide⟩),
  .push 0 0,
  .op .NOT,
  .op (.Swap ⟨1, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨1, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .op .LT,
  .op (.Dup ⟨2, by decide⟩),
  .op .ADD,
  .op (.Swap ⟨0, by decide⟩),
  .op .SUB,
  .op (.Swap ⟨0, by decide⟩),
  .push 0 0,
  .op .LT,
  .op .ADD,
  .push 2 9440,
  .op .MLOAD,
  .push 1 32,
  .op (.Swap ⟨0, by decide⟩),
  .op .SUB,
  .push 2 9408,
  .op .MLOAD,
  .push 1 32,
  .op (.Swap ⟨0, by decide⟩),
  .op .SUB,
  .op .JUMPDEST,
  .op (.Dup ⟨0, by decide⟩),
  .op .MLOAD,
  .push 0 0,
  .op .NOT,
  .op (.Dup ⟨5, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .MUL,
  .op (.Swap ⟨1, by decide⟩),
  .op (.Dup ⟨6, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨1, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .op .LT,
  .op .SUB,
  .op (.Dup ⟨4, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .ADD,
  .op (.Dup ⟨0, by decide⟩),
  .op (.Swap ⟨5, by decide⟩),
  .op .GT,
  .op .SUB,
  .op .SUB,
  .op (.Dup ⟨3, by decide⟩),
  .op (.Dup ⟨3, by decide⟩),
  .op .MLOAD,
  .op .ADD,
  .op (.Dup ⟨0, by decide⟩),
  .op (.Swap ⟨4, by decide⟩),
  .op .GT,
  .op .ADD,
  .op (.Swap ⟨2, by decide⟩),
  .push 1 32,
  .op (.Dup ⟨3, by decide⟩),
  .push 1 31,
  .op .NOT,
  .op .ADD,
  .op (.Swap ⟨3, by decide⟩),
  .op .ADD,
  .op .MSTORE,
  .push 1 31,
  .op .NOT,
  .op .ADD,
  .push 2 8224,
  .op (.Dup ⟨2, by decide⟩),
  .op .GT,
  .push 2 2119,
  .op .JUMPI,
  .op .POP,
  .op .POP,
  .op (.Swap ⟨1, by decide⟩),
  .op .POP,
  .op .POP,
  .op .JUMPDEST,
  .op (.Dup ⟨0, by decide⟩),
  .push 2 8224,
  .op .MLOAD,
  .op .ADD,
  .op (.Dup ⟨0, by decide⟩),
  .push 2 8256,
  .op .MSTORE,
  .op .LT,
  .push 2 8192,
  .op .MLOAD,
  .op .ADD,
  .push 2 8224,
  .op .MSTORE,
  .push 1 31,
  .op .NOT,
  .op .ADD,
  .op (.Dup ⟨2, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .op .GT,
  .push 2 1974,
  .op .JUMPI,
  .op .POP,
  .op .POP,
  .op .POP,
  .push 2 2304,
  .op .JUMP,
  .op .JUMPDEST,
  .push 2 9344,
  .op .MLOAD,
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .ADD,
  .push 1 32,
  .op (.Swap ⟨0, by decide⟩),
  .op .SUB,
  .op (.Dup ⟨1, by decide⟩),
  .op (.Dup ⟨4, by decide⟩),
  .op .ADD,
  .push 1 32,
  .op (.Swap ⟨0, by decide⟩),
  .op .SUB,
  .op (.Swap ⟨2, by decide⟩),
  .op .POP,
  .op (.Swap ⟨2, by decide⟩),
  .op .POP,
  .op .POP,
  .push 2 9440,
  .op .MLOAD,
  .push 0 0,
  .op .JUMPDEST,
  .op .JUMPDEST,
  .op (.Swap ⟨2, by decide⟩),
  .op (.Swap ⟨0, by decide⟩),
  .op .JUMPDEST,
  .op (.Dup ⟨1, by decide⟩),
  .op .MLOAD,
  .op (.Dup ⟨3, by decide⟩),
  .op .MLOAD,
  .op (.Dup ⟨1, by decide⟩),
  .op .ADD,
  .op (.Swap ⟨0, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .op .LT,
  .op (.Swap ⟨0, by decide⟩),
  .op (.Dup ⟨5, by decide⟩),
  .op .ADD,
  .op (.Swap ⟨4, by decide⟩),
  .op (.Dup ⟨5, by decide⟩),
  .op .LT,
  .op .OR,
  .op (.Swap ⟨3, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .op .MSTORE,
  .push 1 31,
  .op .NOT,
  .op .ADD,
  .op (.Swap ⟨0, by decide⟩),
  .push 1 31,
  .op .NOT,
  .op .ADD,
  .op (.Swap ⟨0, by decide⟩),
  .op (.Swap ⟨1, by decide⟩),
  .push 1 31,
  .op .NOT,
  .op .ADD,
  .op (.Swap ⟨1, by decide⟩),
  .push 2 8224,
  .op (.Dup ⟨1, by decide⟩),
  .op .GT,
  .push 2 2252,
  .op .JUMPI,
  .op .POP,
  .op .POP,
  .op .POP,
  .push 2 8224,
  .op .MSTORE,
  .op .JUMPDEST,
  .push 28 9440,
  .op .MLOAD,
  .push 0 0,
  .op (.Swap ⟨0, by decide⟩),
  .op .JUMPDEST,
  .op (.Dup ⟨0, by decide⟩),
  .op .MLOAD,
  .push 32 115792089237316195423570985008687907853269984665640564039457584007913129631680,
  .op (.Dup ⟨2, by decide⟩),
  .op .ADD,
  .op .MLOAD,
  .op (.Dup ⟨1, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .op .GT,
  .op (.Swap ⟨1, by decide⟩),
  .op .SUB,
  .op (.Dup ⟨3, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .op .SUB,
  .op (.Swap ⟨0, by decide⟩),
  .op (.Dup ⟨4, by decide⟩),
  .op .GT,
  .op (.Swap ⟨0, by decide⟩),
  .op (.Swap ⟨1, by decide⟩),
  .op .OR,
  .op (.Swap ⟨2, by decide⟩),
  .op .POP,
  .push 32 115792089237316195423570985008687907853269984665640564039457584007913129638848,
  .op (.Dup ⟨2, by decide⟩),
  .op .ADD,
  .op .MSTORE,
  .push 32 115792089237316195423570985008687907853269984665640564039457584007913129639904,
  .op .ADD,
  .push 2 8224,
  .op (.Dup ⟨1, by decide⟩),
  .op .GT,
  .push 2 2337,
  .op .JUMPI,
  .op .POP,
  .op .ISZERO,
  .push 2 8224,
  .op .MLOAD,
  .op .OR,
  .push 2 1087,
  .op .NOT,
  .op .MUL,
  .push 2 8256,
  .op .ADD,
  .push 2 9344,
  .op .MLOAD,
  .op (.Swap ⟨1, by decide⟩),
  .op .MCOPY,
  .op .JUMP,
  .op .JUMPDEST,
  .op .JUMPDEST,
  .op .JUMPDEST,
  .push 2 2507,
  .op (.Dup ⟨1, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .push 2 2219,
  .op .JUMP,
  .op .JUMPDEST,
  .push 1 8,
  .op .JUMPDEST,
  .push 2 2521,
  .op (.Dup ⟨2, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .push 2 4458,
  .op .JUMP,
  .op .JUMPDEST,
  .push 0 0,
  .op .NOT,
  .op .ADD,
  .op (.Dup ⟨0, by decide⟩),
  .push 3 2510,
  .op .JUMPI,
  .op .POP,
  .op .POP,
  .op .JUMP,
  .op .JUMPDEST,
  .push 0 0,
  .op .MLOAD,
  .push 1 255,
  .op .SHR,
  .op .ISZERO,
  .push 2 1911,
  .op .JUMPI,
  .push 1 1,
  .push 2 8224,
  .op .MSTORE,
  .push 2 2304,
  .op .JUMP,
  .op .JUMPDEST,
  .op (.Dup ⟨0, by decide⟩),
  .push 2 9472,
  .op .MLOAD,
  .op .ADD,
  .op .CALLDATALOAD,
  .push 0 0,
  .op .BYTE,
  .op (.Dup ⟨1, by decide⟩),
  .op .ISZERO,
  .push 2 2577,
  .op .JUMPI,
  .push 1 128,
  .push 2 1789,
  .op .JUMP,
  .op .JUMPDEST,
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .push 1 1,
  .op .SHR,
  .op .OR,
  .op (.Dup ⟨0, by decide⟩),
  .push 1 2,
  .op .SHR,
  .op .OR,
  .op (.Dup ⟨0, by decide⟩),
  .push 1 4,
  .op .SHR,
  .op .OR,
  .push 1 1,
  .op .SHR,
  .push 1 1,
  .op .ADD,
  .push 2 3624,
  .op .JUMP,
  .op .JUMPDEST,
  .op (.Dup ⟨0, by decide⟩),
  .push 2 4096,
  .op .EQ,
  .push 2 1615,
  .op .JUMPI,
  .push 2 1615,
  .push 2 6144,
  .op (.Dup ⟨2, by decide⟩),
  .push 2 6144,
  .push 2 4458,
  .op .JUMP,
  .op .JUMPDEST,
  .push 2 1615,
  .op .JUMP,
  .op .JUMPDEST,
  .push 1 32,
  .op (.Dup ⟨1, by decide⟩),
  .op .GT,
  .op (.Dup ⟨2, by decide⟩),
  .push 1 32,
  .op .XOR,
  .op .OR,
  .op (.Dup ⟨3, by decide⟩),
  .push 1 32,
  .op .XOR,
  .op .OR,
  .op .ISZERO,
  .push 2 5190,
  .op .JUMPI,
  .push 2 517,
  .op .JUMP,
  .op .JUMPDEST,
  .op (.Dup ⟨0, by decide⟩),
  .op .ISZERO,
  .push 2 3298,
  .op .JUMPI,
  .op (.Dup ⟨5, by decide⟩),
  .op .CALLDATALOAD,
  .op (.Dup ⟨0, by decide⟩),
  .op .ISZERO,
  .push 2 3290,
  .op .JUMPI,
  .op (.Dup ⟨4, by decide⟩),
  .op .CALLDATALOAD,
  .op (.Dup ⟨2, by decide⟩),
  .push 1 32,
  .op .SUB,
  .push 1 3,
  .op .SHL,
  .op .SHR,
  .push 1 1,
  .push 0 0,
  .op .MSTORE,
  .op (.Dup ⟨0, by decide⟩),
  .push 1 32,
  .op .MSTORE,
  .op (.Dup ⟨6, by decide⟩),
  .op .CALLDATALOAD,
  .op (.Swap ⟨1, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨14, by decide⟩),
  .op (.Dup ⟨15, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .push 1 64,
  .op .MSTORE,
  .op (.Dup ⟨14, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .push 1 96,
  .op .MSTORE,
  .op (.Dup ⟨13, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .push 1 128,
  .op .MSTORE,
  .op (.Dup ⟨12, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .push 1 160,
  .op .MSTORE,
  .op (.Dup ⟨11, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .push 1 192,
  .op .MSTORE,
  .op (.Dup ⟨10, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .push 1 224,
  .op .MSTORE,
  .op (.Dup ⟨9, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .push 2 256,
  .op .MSTORE,
  .op (.Dup ⟨8, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .push 2 288,
  .op .MSTORE,
  .op (.Dup ⟨7, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .push 2 320,
  .op .MSTORE,
  .op (.Dup ⟨6, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .push 2 352,
  .op .MSTORE,
  .op (.Dup ⟨5, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .push 2 384,
  .op .MSTORE,
  .op (.Dup ⟨4, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .push 2 416,
  .op .MSTORE,
  .op (.Dup ⟨3, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .push 2 448,
  .op .MSTORE,
  .op (.Dup ⟨2, by decide⟩),
  .op .MULMOD,
  .op .JUMPDEST,
  .push 2 480,
  .op .MSTORE,
  .op .JUMPDEST,
  .op .POP,
  .push 2 480,
  .op (.Dup ⟨1, by decide⟩),
  .push 1 247,
  .op .SHR,
  .op (.Dup ⟨1, by decide⟩),
  .op .AND,
  .op .MLOAD,
  .op (.Swap ⟨1, by decide⟩),
  .push 1 4,
  .op .SHL,
  .push 1 2,
  .op (.Swap ⟨2, by decide⟩),
  .op (.Dup ⟨9, by decide⟩),
  .op .CALLDATALOAD,
  .op (.Swap ⟨0, by decide⟩),
  .op .JUMPDEST,
  .op (.Dup ⟨1, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Swap ⟨14, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨13, by decide⟩),
  .push 1 247,
  .op .SHR,
  .op (.Dup ⟨15, by decide⟩),
  .op .AND,
  .op .MLOAD,
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨8, by decide⟩),
  .push 1 243,
  .op .SHR,
  .op (.Dup ⟨10, by decide⟩),
  .op .AND,
  .op .MLOAD,
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨3, by decide⟩),
  .push 1 239,
  .op .SHR,
  .op (.Dup ⟨5, by decide⟩),
  .op .AND,
  .op .MLOAD,
  .op .MULMOD,
  .op (.Dup ⟨1, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Swap ⟨14, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨13, by decide⟩),
  .push 1 235,
  .op .SHR,
  .op (.Dup ⟨15, by decide⟩),
  .op .AND,
  .op .MLOAD,
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨8, by decide⟩),
  .push 1 231,
  .op .SHR,
  .op (.Dup ⟨10, by decide⟩),
  .op .AND,
  .op .MLOAD,
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨3, by decide⟩),
  .push 1 227,
  .op .SHR,
  .op (.Dup ⟨5, by decide⟩),
  .op .AND,
  .op .MLOAD,
  .op .MULMOD,
  .op (.Dup ⟨1, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Swap ⟨14, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨13, by decide⟩),
  .push 1 223,
  .op .SHR,
  .op (.Dup ⟨15, by decide⟩),
  .op .AND,
  .op .MLOAD,
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨8, by decide⟩),
  .push 1 219,
  .op .SHR,
  .op (.Dup ⟨10, by decide⟩),
  .op .AND,
  .op .MLOAD,
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨3, by decide⟩),
  .push 1 215,
  .op .SHR,
  .op (.Dup ⟨5, by decide⟩),
  .op .AND,
  .op .MLOAD,
  .op .MULMOD,
  .op (.Dup ⟨1, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Swap ⟨14, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨13, by decide⟩),
  .push 1 211,
  .op .SHR,
  .op (.Dup ⟨15, by decide⟩),
  .op .AND,
  .op .MLOAD,
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨8, by decide⟩),
  .push 1 207,
  .op .SHR,
  .op (.Dup ⟨10, by decide⟩),
  .op .AND,
  .op .MLOAD,
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨3, by decide⟩),
  .push 1 203,
  .op .SHR,
  .op (.Dup ⟨5, by decide⟩),
  .op .AND,
  .op .MLOAD,
  .op .MULMOD,
  .op (.Dup ⟨1, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Swap ⟨14, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨13, by decide⟩),
  .push 1 199,
  .op .SHR,
  .op (.Dup ⟨15, by decide⟩),
  .op .AND,
  .op .MLOAD,
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨8, by decide⟩),
  .push 1 195,
  .op .SHR,
  .op (.Dup ⟨10, by decide⟩),
  .op .AND,
  .op .MLOAD,
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨3, by decide⟩),
  .push 1 191,
  .op .SHR,
  .op (.Dup ⟨5, by decide⟩),
  .op .AND,
  .op .MLOAD,
  .op .MULMOD,
  .op (.Dup ⟨1, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Swap ⟨14, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨13, by decide⟩),
  .push 1 187,
  .op .SHR,
  .op (.Dup ⟨15, by decide⟩),
  .op .AND,
  .op .MLOAD,
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨8, by decide⟩),
  .push 1 183,
  .op .SHR,
  .op (.Dup ⟨10, by decide⟩),
  .op .AND,
  .op .MLOAD,
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨3, by decide⟩),
  .push 1 179,
  .op .SHR,
  .op (.Dup ⟨5, by decide⟩),
  .op .AND,
  .op .MLOAD,
  .op .MULMOD,
  .op (.Dup ⟨1, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Swap ⟨14, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨13, by decide⟩),
  .push 1 175,
  .op .SHR,
  .op (.Dup ⟨15, by decide⟩),
  .op .AND,
  .op .MLOAD,
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨8, by decide⟩),
  .push 1 171,
  .op .SHR,
  .op (.Dup ⟨10, by decide⟩),
  .op .AND,
  .op .MLOAD,
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨3, by decide⟩),
  .push 1 167,
  .op .SHR,
  .op (.Dup ⟨5, by decide⟩),
  .op .AND,
  .op .MLOAD,
  .op .MULMOD,
  .op (.Swap ⟨1, by decide⟩),
  .push 1 84,
  .op .SHL,
  .op (.Swap ⟨1, by decide⟩),
  .push 1 1,
  .op (.Dup ⟨5, by decide⟩),
  .op .SUB,
  .op (.Swap ⟨4, by decide⟩),
  .push 2 2821,
  .op .JUMPI,
  .push 0 0,
  .op .MSTORE,
  .push 1 32,
  .push 0 0,
  .op .RETURN,
  .op .JUMPDEST,
  .push 0 0,
  .push 0 0,
  .op .MSTORE,
  .push 1 32,
  .push 0 0,
  .op .RETURN,
  .op .JUMPDEST,
  .op (.Dup ⟨4, by decide⟩),
  .op .CALLDATALOAD,
  .op .ISZERO,
  .op (.Dup ⟨6, by decide⟩),
  .op .CALLDATALOAD,
  .push 1 1,
  .op .MOD,
  .op .MUL,
  .push 0 0,
  .op .MSTORE,
  .push 1 32,
  .push 0 0,
  .op .RETURN,
  .push 15 0,
  .op .JUMPDEST,
  .push 2 9344,
  .op .MLOAD,
  .push 2 5120,
  .push 2 6144,
  .op .MCOPY,
  .op (.Dup ⟨1, by decide⟩),
  .push 1 3,
  .op .LT,
  .op (.Dup ⟨2, by decide⟩),
  .push 1 7,
  .op .LT,
  .op (.Dup ⟨3, by decide⟩),
  .push 1 15,
  .op .LT,
  .op (.Dup ⟨4, by decide⟩),
  .push 1 31,
  .op .LT,
  .op .ADD,
  .op .ADD,
  .op .ADD,
  .push 2 1569,
  .op .JUMP,
  .op .JUMPDEST,
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨3, by decide⟩),
  .op .EQ,
  .push 0 0,
  .op .MLOAD,
  .push 1 255,
  .op .SHR,
  .op .AND,
  .op .ISZERO,
  .push 2 3420,
  .op .JUMPI,
  .op (.Dup ⟨0, by decide⟩),
  .push 1 96,
  .push 2 1024,
  .op .CALLDATACOPY,
  .push 2 1755,
  .push 2 2048,
  .push 2 1024,
  .push 2 6144,
  .push 2 4458,
  .op .JUMP,
  .op .JUMPDEST,
  .push 2 1755,
  .push 2 2048,
  .push 2 6144,
  .push 2 1024,
  .push 2 4458,
  .op .JUMP,
  .op .JUMPDEST,
  .op (.Dup ⟨2, by decide⟩),
  .push 1 31,
  .op .ADD,
  .push 1 5,
  .op .SHR,
  .op (.Dup ⟨3, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .push 1 5,
  .op .SHL,
  .op .SUB,
  .push 1 3,
  .op .SHL,
  .push 1 96,
  .op .CALLDATALOAD,
  .op (.Swap ⟨0, by decide⟩),
  .op .SHR,
  .op (.Dup ⟨2, by decide⟩),
  .push 2 992,
  .op .ADD,
  .op .MSTORE,
  .push 1 1,
  .push 2 1668,
  .op .JUMP,
  .op .JUMPDEST,
  .push 1 1,
  .op (.Dup ⟨6, by decide⟩),
  .op .SUB,
  .op (.Dup ⟨7, by decide⟩),
  .push 1 1,
  .op (.Dup ⟨4, by decide⟩),
  .push 1 7,
  .op .SHR,
  .op .AND,
  .op (.Dup ⟨2, by decide⟩),
  .op .MUL,
  .push 1 1,
  .op .ADD,
  .op (.Dup ⟨1, by decide⟩),
  .op (.Dup ⟨8, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op .MULMOD,
  .op (.Swap ⟨5, by decide⟩),
  .op .POP,
  .op (.Dup ⟨7, by decide⟩),
  .push 1 1,
  .op (.Dup ⟨4, by decide⟩),
  .push 1 6,
  .op .SHR,
  .op .AND,
  .op (.Dup ⟨2, by decide⟩),
  .op .MUL,
  .push 1 1,
  .op .ADD,
  .op (.Dup ⟨1, by decide⟩),
  .op (.Dup ⟨8, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op .MULMOD,
  .op (.Swap ⟨5, by decide⟩),
  .op .POP,
  .op (.Dup ⟨7, by decide⟩),
  .push 1 1,
  .op (.Dup ⟨4, by decide⟩),
  .push 1 5,
  .op .SHR,
  .op .AND,
  .op (.Dup ⟨2, by decide⟩),
  .op .MUL,
  .push 1 1,
  .op .ADD,
  .op (.Dup ⟨1, by decide⟩),
  .op (.Dup ⟨8, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op .MULMOD,
  .op (.Swap ⟨5, by decide⟩),
  .op .POP,
  .op (.Dup ⟨7, by decide⟩),
  .push 1 1,
  .op (.Dup ⟨4, by decide⟩),
  .push 1 4,
  .op .SHR,
  .op .AND,
  .op (.Dup ⟨2, by decide⟩),
  .op .MUL,
  .push 1 1,
  .op .ADD,
  .op (.Dup ⟨1, by decide⟩),
  .op (.Dup ⟨8, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op .MULMOD,
  .op (.Swap ⟨5, by decide⟩),
  .op .POP,
  .op (.Dup ⟨7, by decide⟩),
  .push 1 1,
  .op (.Dup ⟨4, by decide⟩),
  .push 1 3,
  .op .SHR,
  .op .AND,
  .op (.Dup ⟨2, by decide⟩),
  .op .MUL,
  .push 1 1,
  .op .ADD,
  .op (.Dup ⟨1, by decide⟩),
  .op (.Dup ⟨8, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op .MULMOD,
  .op (.Swap ⟨5, by decide⟩),
  .op .POP,
  .op (.Dup ⟨7, by decide⟩),
  .push 1 1,
  .op (.Dup ⟨4, by decide⟩),
  .push 1 2,
  .op .SHR,
  .op .AND,
  .op (.Dup ⟨2, by decide⟩),
  .op .MUL,
  .push 1 1,
  .op .ADD,
  .op (.Dup ⟨1, by decide⟩),
  .op (.Dup ⟨8, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op .MULMOD,
  .op (.Swap ⟨5, by decide⟩),
  .op .POP,
  .op (.Dup ⟨7, by decide⟩),
  .push 1 1,
  .op (.Dup ⟨4, by decide⟩),
  .push 1 1,
  .op .SHR,
  .op .AND,
  .op (.Dup ⟨2, by decide⟩),
  .op .MUL,
  .push 1 1,
  .op .ADD,
  .op (.Dup ⟨1, by decide⟩),
  .op (.Dup ⟨8, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op .MULMOD,
  .op (.Swap ⟨5, by decide⟩),
  .op .POP,
  .op (.Dup ⟨7, by decide⟩),
  .push 2 1,
  .op (.Dup ⟨4, by decide⟩),
  .op .JUMPDEST,
  .op .JUMPDEST,
  .op .AND,
  .op (.Dup ⟨2, by decide⟩),
  .op .MUL,
  .push 1 1,
  .op .ADD,
  .op (.Dup ⟨1, by decide⟩),
  .op (.Dup ⟨8, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op .MULMOD,
  .op .MULMOD,
  .op (.Swap ⟨5, by decide⟩),
  .op .POP,
  .op .POP,
  .push 2 655,
  .op .JUMP,
  .op .JUMPDEST,
  .op (.Dup ⟨1, by decide⟩),
  .op .ISZERO,
  .push 2 3646,
  .op .JUMPI,
  .push 2 9344,
  .op .MLOAD,
  .push 2 2048,
  .push 2 1024,
  .op .MCOPY,
  .push 2 1832,
  .op .JUMP,
  .op .JUMPDEST,
  .push 2 1789,
  .op .JUMP,
  .op .JUMPDEST,
  .op (.Dup ⟨3, by decide⟩),
  .push 1 3,
  .op .EQ,
  .push 2 3690,
  .op .JUMPI,
  .op (.Dup ⟨3, by decide⟩),
  .push 1 1,
  .op .XOR,
  .op .JUMPDEST,
  .push 2 3761,
  .op .JUMPI,
  .push 2 9472,
  .op .MLOAD,
  .op .CALLDATALOAD,
  .push 0 0,
  .op .BYTE,
  .push 1 3,
  .op .XOR,
  .op .JUMPDEST,
  .push 2 3761,
  .op .JUMPI,
  .push 1 1,
  .push 2 3711,
  .op .JUMP,
  .op .JUMPDEST,
  .push 2 9472,
  .op .MLOAD,
  .op .CALLDATALOAD,
  .push 1 232,
  .op .SHR,
  .push 3 65537,
  .op .XOR,
  .op .JUMPDEST,
  .push 2 3761,
  .op .JUMPI,
  .push 1 16,
  .op .JUMPDEST,
  .op .JUMPDEST,
  .push 2 3729,
  .push 2 2048,
  .push 2 2048,
  .push 2 2048,
  .push 2 4458,
  .op .JUMP,
  .op .JUMPDEST,
  .push 1 1,
  .op (.Swap ⟨0, by decide⟩),
  .op .SUB,
  .op (.Dup ⟨0, by decide⟩),
  .push 2 3712,
  .op .JUMPI,
  .op .POP,
  .push 2 3756,
  .push 2 1024,
  .push 2 1024,
  .push 2 2048,
  .push 2 4458,
  .op .JUMP,
  .op .JUMPDEST,
  .push 2 1876,
  .op .JUMP,
  .op .JUMPDEST,
  .op (.Dup ⟨0, by decide⟩),
  .push 2 4096,
  .push 2 1024,
  .op .MCOPY,
  .push 0 0,
  .push 2 1769,
  .op .JUMP,
  .op .JUMPDEST,
  .push 2 9344,
  .op .MLOAD,
  .push 1 128,
  .op .LT,
  .op (.Dup ⟨0, by decide⟩),
  .push 1 8,
  .op (.Swap ⟨0, by decide⟩),
  .op .SHL,
  .op .JUMPDEST,
  .push 2 3799,
  .op (.Dup ⟨3, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .push 2 2219,
  .op .JUMP,
  .op .JUMPDEST,
  .push 0 0,
  .op .NOT,
  .op .ADD,
  .op (.Dup ⟨0, by decide⟩),
  .push 2 3788,
  .op .JUMPI,
  .op .POP,
  .push 1 5,
  .op .SUB,
  .push 2 2510,
  .op .JUMP,
  .op .JUMPDEST,
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨3, by decide⟩),
  .op .EQ,
  .push 0 0,
  .op .MLOAD,
  .push 1 255,
  .op .SHR,
  .op .AND,
  .op .ISZERO,
  .push 2 3860,
  .op .JUMPI,
  .op (.Dup ⟨0, by decide⟩),
  .push 1 96,
  .push 2 1024,
  .op .CALLDATACOPY,
  .op (.Dup ⟨0, by decide⟩),
  .push 1 96,
  .push 2 8256,
  .op .CALLDATACOPY,
  .push 0 0,
  .push 2 8224,
  .op .MSTORE,
  .push 2 3865,
  .push 2 2048,
  .push 2 2304,
  .op .JUMP,
  .op .JUMPDEST,
  .push 2 1533,
  .op .JUMP,
  .op .JUMPDEST,
  .push 1 1,
  .push 2 9408,
  .op .MLOAD,
  .op .JUMPDEST,
  .op (.Dup ⟨0, by decide⟩),
  .op .MLOAD,
  .op .NOT,
  .op (.Dup ⟨2, by decide⟩),
  .op .ADD,
  .op (.Dup ⟨2, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .op .LT,
  .op (.Swap ⟨2, by decide⟩),
  .op .POP,
  .op (.Dup ⟨1, by decide⟩),
  .push 2 5120,
  .op .ADD,
  .op .MSTORE,
  .op (.Dup ⟨0, by decide⟩),
  .op .ISZERO,
  .push 2 3903,
  .op .JUMPI,
  .push 1 31,
  .op .NOT,
  .op .ADD,
  .push 2 3872,
  .op .JUMP,
  .op .JUMPDEST,
  .op .POP,
  .op .POP,
  .push 0 0,
  .op .MLOAD,
  .op (.Dup ⟨0, by decide⟩),
  .push 0 0,
  .op .SUB,
  .op (.Dup ⟨1, by decide⟩),
  .op .AND,
  .op (.Dup ⟨0, by decide⟩),
  .push 2 6144,
  .op .MSTORE,
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .DIV,
  .op (.Dup ⟨0, by decide⟩),
  .push 2 6176,
  .op .MSTORE,
  .op (.Dup ⟨1, by decide⟩),
  .push 0 0,
  .op .SUB,
  .op (.Dup ⟨2, by decide⟩),
  .op (.Swap ⟨0, by decide⟩),
  .op .DIV,
  .push 1 1,
  .op .ADD,
  .push 2 6208,
  .op .MSTORE,
  .op (.Dup ⟨0, by decide⟩),
  .push 0 0,
  .op .SUB,
  .op (.Dup ⟨1, by decide⟩),
  .op (.Swap ⟨0, by decide⟩),
  .op .MOD,
  .push 2 6240,
  .op .MSTORE,
  .op .JUMPDEST,
  .op (.Dup ⟨0, by decide⟩),
  .push 2 3,
  .op .MUL,
  .push 1 2,
  .op .XOR,
  .op .JUMPDEST,
  .op .JUMPDEST,
  .op .JUMPDEST,
  .op .JUMPDEST,
  .op .JUMPDEST,
  .op .JUMPDEST,
  .op .JUMPDEST,
  .op .JUMPDEST,
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .MUL,
  .push 1 2,
  .op .SUB,
  .op .MUL,
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .MUL,
  .push 1 2,
  .op .SUB,
  .op .MUL,
  .op .JUMPDEST,
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .MUL,
  .push 1 2,
  .op .SUB,
  .op .MUL,
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .MUL,
  .push 1 2,
  .op .SUB,
  .op .MUL,
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .MUL,
  .push 1 2,
  .op .SUB,
  .op .MUL,
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .MUL,
  .push 1 2,
  .op .SUB,
  .op .MUL,
  .push 2 6272,
  .op .MSTORE,
  .op .POP,
  .op .POP,
  .op .POP,
  .op (.Dup ⟨1, by decide⟩),
  .op .JUMPDEST,
  .op (.Dup ⟨0, by decide⟩),
  .op .ISZERO,
  .push 2 4452,
  .op .JUMPI,
  .op (.Dup ⟨1, by decide⟩),
  .push 2 2048,
  .push 2 8224,
  .op .MCOPY,
  .push 0 0,
  .push 2 9440,
  .op .MLOAD,
  .op .MSTORE,
  .op .JUMPDEST,
  .push 8 2048,
  .op .MLOAD,
  .push 2 6144,
  .op .MLOAD,
  .op (.Dup ⟨1, by decide⟩),
  .push 2 6208,
  .op .MLOAD,
  .op .MUL,
  .op (.Dup ⟨1, by decide⟩),
  .push 2 2080,
  .op .MLOAD,
  .op .DIV,
  .op .ADD,
  .op (.Swap ⟨1, by decide⟩),
  .op .DIV,
  .op (.Swap ⟨0, by decide⟩),
  .push 2 6176,
  .op .MLOAD,
  .op (.Dup ⟨0, by decide⟩),
  .push 2 6240,
  .op .MLOAD,
  .op (.Dup ⟨4, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨2, by decide⟩),
  .op .ADDMOD,
  .op (.Swap ⟨0, by decide⟩),
  .op .SUB,
  .push 2 6272,
  .op .MLOAD,
  .op .MUL,
  .op (.Dup ⟨0, by decide⟩),
  .push 0 0,
  .op .LT,
  .op (.Swap ⟨0, by decide⟩),
  .op .SUB,
  .op (.Swap ⟨0, by decide⟩),
  .push 2 6176,
  .op .MLOAD,
  .op .JUMPDEST,
  .op .GT,
  .op .ISZERO,
  .push 0 0,
  .op .SUB,
  .op .OR,
  .op .JUMPDEST,
  .push 0 0,
  .push 2 9440,
  .op .MLOAD,
  .push 2 9408,
  .op .MLOAD,
  .push 2 5120,
  .op .ADD,
  .op .JUMPDEST,
  .op (.Dup ⟨0, by decide⟩),
  .op .MLOAD,
  .push 32 115792089237316195423570985008687907853269984665640564039457584007913129639935,
  .op (.Dup ⟨5, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .MUL,
  .op (.Swap ⟨1, by decide⟩),
  .op (.Dup ⟨6, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨1, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .op .LT,
  .op .SUB,
  .op (.Dup ⟨4, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .ADD,
  .op (.Dup ⟨0, by decide⟩),
  .op (.Swap ⟨5, by decide⟩),
  .op .GT,
  .op .SUB,
  .op .SUB,
  .op (.Dup ⟨3, by decide⟩),
  .op (.Dup ⟨3, by decide⟩),
  .op .MLOAD,
  .op .ADD,
  .op (.Dup ⟨0, by decide⟩),
  .op (.Swap ⟨4, by decide⟩),
  .op .GT,
  .op .ADD,
  .op (.Swap ⟨2, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .push 32 115792089237316195423570985008687907853269984665640564039457584007913129639904,
  .op .ADD,
  .op (.Swap ⟨2, by decide⟩),
  .op .MSTORE,
  .push 32 115792089237316195423570985008687907853269984665640564039457584007913129639904,
  .op .ADD,
  .push 2 8224,
  .op (.Dup ⟨2, by decide⟩),
  .op .GT,
  .push 2 4119,
  .op .JUMPI,
  .op .POP,
  .op .POP,
  .push 2 8224,
  .op .MLOAD,
  .op (.Dup ⟨1, by decide⟩),
  .op .ADD,
  .op (.Dup ⟨1, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .op .LT,
  .op (.Swap ⟨1, by decide⟩),
  .op .POP,
  .op (.Dup ⟨2, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .op .LT,
  .op (.Swap ⟨0, by decide⟩),
  .op (.Dup ⟨3, by decide⟩),
  .op (.Swap ⟨0, by decide⟩),
  .op .SUB,
  .op (.Dup ⟨0, by decide⟩),
  .push 2 8224,
  .op .MSTORE,
  .op .POP,
  .op .GT,
  .op (.Swap ⟨0, by decide⟩),
  .op .POP,
  .op .ISZERO,
  .push 2 4363,
  .op .JUMPI,
  .op .JUMPDEST,
  .push 0 0,
  .push 2 9440,
  .op .MLOAD,
  .op .JUMPDEST,
  .op (.Dup ⟨0, by decide⟩),
  .op .MLOAD,
  .op (.Dup ⟨1, by decide⟩),
  .push 2 8256,
  .op (.Swap ⟨0, by decide⟩),
  .op .SUB,
  .op .MLOAD,
  .op (.Dup ⟨1, by decide⟩),
  .op .ADD,
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .GT,
  .op (.Swap ⟨1, by decide⟩),
  .op .POP,
  .op (.Dup ⟨3, by decide⟩),
  .op .ADD,
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨4, by decide⟩),
  .op .GT,
  .op (.Swap ⟨3, by decide⟩),
  .op .POP,
  .op (.Dup ⟨2, by decide⟩),
  .op .MSTORE,
  .op (.Swap ⟨0, by decide⟩),
  .op (.Swap ⟨1, by decide⟩),
  .op .OR,
  .op (.Swap ⟨0, by decide⟩),
  .push 1 31,
  .op .NOT,
  .op .ADD,
  .push 2 8255,
  .op (.Dup ⟨1, by decide⟩),
  .op .GT,
  .push 2 4302,
  .op .JUMPI,
  .op .POP,
  .push 2 8224,
  .op .MLOAD,
  .op (.Dup ⟨1, by decide⟩),
  .op .ADD,
  .op (.Dup ⟨0, by decide⟩),
  .push 2 8224,
  .op .MSTORE,
  .op .LT,
  .op .ISZERO,
  .push 2 4296,
  .op .JUMPI,
  .op .JUMPDEST,
  .push 2 8224,
  .op .MLOAD,
  .op .ISZERO,
  .push 2 4432,
  .op .JUMPI,
  .push 0 0,
  .push 2 9440,
  .op .MLOAD,
  .op .JUMPDEST,
  .op (.Dup ⟨0, by decide⟩),
  .op .MLOAD,
  .op (.Dup ⟨1, by decide⟩),
  .push 2 8256,
  .op (.Swap ⟨0, by decide⟩),
  .op .SUB,
  .op .MLOAD,
  .op (.Dup ⟨1, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .op .GT,
  .op (.Swap ⟨1, by decide⟩),
  .op .SUB,
  .op (.Dup ⟨3, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .op .LT,
  .op (.Swap ⟨0, by decide⟩),
  .op (.Dup ⟨4, by decide⟩),
  .op (.Swap ⟨0, by decide⟩),
  .op .SUB,
  .op (.Dup ⟨3, by decide⟩),
  .op .MSTORE,
  .op .OR,
  .op (.Swap ⟨1, by decide⟩),
  .op .POP,
  .push 1 31,
  .op .NOT,
  .op .ADD,
  .push 2 8255,
  .op (.Dup ⟨1, by decide⟩),
  .op .GT,
  .push 2 4378,
  .op .JUMPI,
  .op .POP,
  .push 2 8224,
  .op .MLOAD,
  .op .SUB,
  .push 2 8224,
  .op .MSTORE,
  .push 2 4363,
  .op .JUMP,
  .op .JUMPDEST,
  .push 2 4443,
  .push 2 2048,
  .push 2 2304,
  .op .JUMP,
  .op .JUMPDEST,
  .push 1 1,
  .op (.Swap ⟨0, by decide⟩),
  .op .SUB,
  .push 2 4017,
  .op .JUMP,
  .op .JUMPDEST,
  .op .POP,
  .push 2 1756,
  .op .JUMP,
  .op .JUMPDEST,
  .push 2 9344,
  .op .MLOAD,
  .op (.Dup ⟨0, by decide⟩),
  .push 1 128,
  .op .EQ,
  .op (.Swap ⟨0, by decide⟩),
  .push 2 256,
  .op .EQ,
  .op .OR,
  .push 2 4481,
  .op .JUMPI,
  .push 2 1939,
  .op .JUMP,
  .op .JUMPDEST,
  .push 1 31,
  .op .NOT,
  .push 2 9344,
  .op .MLOAD,
  .push 1 128,
  .op .EQ,
  .push 1 150,
  .op .MUL,
  .op (.Dup ⟨0, by decide⟩),
  .push 2 4543,
  .op .ADD,
  .op (.Swap ⟨0, by decide⟩),
  .push 2 4888,
  .op .ADD,
  .op (.Swap ⟨3, by decide⟩),
  .push 0 0,
  .op .NOT,
  .op (.Swap ⟨3, by decide⟩),
  .push 2 9344,
  .op .MLOAD,
  .op (.Dup ⟨0, by decide⟩),
  .push 1 64,
  .op .ADD,
  .op .CALLDATASIZE,
  .push 2 8192,
  .op .CALLDATACOPY,
  .op (.Dup ⟨0, by decide⟩),
  .op (.Dup ⟨3, by decide⟩),
  .op .ADD,
  .push 1 32,
  .op (.Swap ⟨0, by decide⟩),
  .op .SUB,
  .push 1 32,
  .op (.Dup ⟨4, by decide⟩),
  .op .SUB,
  .op (.Swap ⟨3, by decide⟩),
  .op .POP,
  .op (.Swap ⟨0, by decide⟩),
  .op .POP,
  .op .JUMPDEST,
  .op (.Dup ⟨0, by decide⟩),
  .op .MLOAD,
  .push 0 0,
  .op (.Dup ⟨5, by decide⟩),
  .op .JUMP,
  .op .JUMPDEST,
  .push 1 224,
  .op (.Dup ⟨4, by decide⟩),
  .op .ADD,
  .op .MLOAD,
  .op (.Dup ⟨8, by decide⟩),
  .op (.Dup ⟨3, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .MUL,
  .op (.Swap ⟨1, by decide⟩),
  .op (.Dup ⟨4, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨1, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .op .LT,
  .op .SUB,
  .op (.Dup ⟨1, by decide⟩),
  .op .ADD,
  .op (.Swap ⟨0, by decide⟩),
  .op (.Swap ⟨1, by decide⟩),
  .op .SUB,
  .op (.Swap ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .push 2 8480,
  .op .MLOAD,
  .op .ADD,
  .op (.Dup ⟨0, by decide⟩),
  .push 2 8480,
  .op .MSTORE,
  .op .LT,
  .op .ADD,
  .push 1 192,
  .op (.Dup ⟨4, by decide⟩),
  .op .ADD,
  .op .MLOAD,
  .op (.Dup ⟨8, by decide⟩),
  .op (.Dup ⟨3, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .MUL,
  .op (.Swap ⟨1, by decide⟩),
  .op (.Dup ⟨4, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨1, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .op .LT,
  .op .SUB,
  .op (.Dup ⟨2, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .ADD,
  .op (.Dup ⟨0, by decide⟩),
  .op (.Swap ⟨3, by decide⟩),
  .op .GT,
  .op .SUB,
  .op .SUB,
  .op (.Swap ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .push 2 8448,
  .op .MLOAD,
  .op .ADD,
  .op (.Dup ⟨0, by decide⟩),
  .push 2 8448,
  .op .MSTORE,
  .op .LT,
  .op .ADD,
  .push 1 160,
  .op (.Dup ⟨4, by decide⟩),
  .op .ADD,
  .op .MLOAD,
  .op (.Dup ⟨8, by decide⟩),
  .op (.Dup ⟨3, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .MUL,
  .op (.Swap ⟨1, by decide⟩),
  .op (.Dup ⟨4, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨1, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .op .LT,
  .op .SUB,
  .op (.Dup ⟨2, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .ADD,
  .op (.Dup ⟨0, by decide⟩),
  .op (.Swap ⟨3, by decide⟩),
  .op .GT,
  .op .SUB,
  .op .SUB,
  .op (.Swap ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .push 2 8416,
  .op .MLOAD,
  .op .ADD,
  .op (.Dup ⟨0, by decide⟩),
  .push 2 8416,
  .op .MSTORE,
  .op .LT,
  .op .ADD,
  .push 1 128,
  .op (.Dup ⟨4, by decide⟩),
  .op .ADD,
  .op .MLOAD,
  .op (.Dup ⟨8, by decide⟩),
  .op (.Dup ⟨3, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .MUL,
  .op (.Swap ⟨1, by decide⟩),
  .op (.Dup ⟨4, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨1, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .op .LT,
  .op .SUB,
  .op (.Dup ⟨2, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .ADD,
  .op (.Dup ⟨0, by decide⟩),
  .op (.Swap ⟨3, by decide⟩),
  .op .GT,
  .op .SUB,
  .op .SUB,
  .op (.Swap ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .push 2 8384,
  .op .MLOAD,
  .op .ADD,
  .op (.Dup ⟨0, by decide⟩),
  .push 2 8384,
  .op .MSTORE,
  .op .LT,
  .op .ADD,
  .op .JUMPDEST,
  .push 1 96,
  .op (.Dup ⟨4, by decide⟩),
  .op .ADD,
  .op .MLOAD,
  .op (.Dup ⟨8, by decide⟩),
  .op (.Dup ⟨3, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .MUL,
  .op (.Swap ⟨1, by decide⟩),
  .op (.Dup ⟨4, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨1, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .op .LT,
  .op .SUB,
  .op (.Dup ⟨2, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .ADD,
  .op (.Dup ⟨0, by decide⟩),
  .op (.Swap ⟨3, by decide⟩),
  .op .GT,
  .op .SUB,
  .op .SUB,
  .op (.Swap ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .push 2 8352,
  .op .MLOAD,
  .op .ADD,
  .op (.Dup ⟨0, by decide⟩),
  .push 2 8352,
  .op .MSTORE,
  .op .LT,
  .op .ADD,
  .push 1 64,
  .op (.Dup ⟨4, by decide⟩),
  .op .ADD,
  .op .MLOAD,
  .op (.Dup ⟨8, by decide⟩),
  .op (.Dup ⟨3, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .MUL,
  .op (.Swap ⟨1, by decide⟩),
  .op (.Dup ⟨4, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨1, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .op .LT,
  .op .SUB,
  .op (.Dup ⟨2, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .ADD,
  .op (.Dup ⟨0, by decide⟩),
  .op (.Swap ⟨3, by decide⟩),
  .op .GT,
  .op .SUB,
  .op .SUB,
  .op (.Swap ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .push 2 8320,
  .op .MLOAD,
  .op .ADD,
  .op (.Dup ⟨0, by decide⟩),
  .push 2 8320,
  .op .MSTORE,
  .op .LT,
  .op .ADD,
  .push 1 32,
  .op (.Dup ⟨4, by decide⟩),
  .op .ADD,
  .op .MLOAD,
  .op (.Dup ⟨8, by decide⟩),
  .op (.Dup ⟨3, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .MUL,
  .op (.Swap ⟨1, by decide⟩),
  .op (.Dup ⟨4, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨1, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .op .LT,
  .op .SUB,
  .op (.Dup ⟨2, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .ADD,
  .op (.Dup ⟨0, by decide⟩),
  .op (.Swap ⟨3, by decide⟩),
  .op .GT,
  .op .SUB,
  .op .SUB,
  .op (.Swap ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .push 2 8288,
  .op .MLOAD,
  .op .ADD,
  .op (.Dup ⟨0, by decide⟩),
  .push 2 8288,
  .op .MSTORE,
  .op .LT,
  .op .ADD,
  .op (.Dup ⟨3, by decide⟩),
  .op .MLOAD,
  .op (.Dup ⟨8, by decide⟩),
  .op (.Dup ⟨3, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .MUL,
  .op (.Swap ⟨1, by decide⟩),
  .op (.Dup ⟨4, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨1, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .op .LT,
  .op .SUB,
  .op (.Dup ⟨2, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .ADD,
  .op (.Dup ⟨0, by decide⟩),
  .op (.Swap ⟨3, by decide⟩),
  .op .GT,
  .op .SUB,
  .op .SUB,
  .op (.Swap ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .push 2 8256,
  .op .MLOAD,
  .op .ADD,
  .op (.Dup ⟨0, by decide⟩),
  .push 2 8256,
  .op .MSTORE,
  .op .LT,
  .op .ADD,
  .op (.Dup ⟨0, by decide⟩),
  .push 2 8224,
  .op .MLOAD,
  .op .ADD,
  .op (.Dup ⟨0, by decide⟩),
  .push 2 8224,
  .op .MSTORE,
  .op .LT,
  .push 2 8192,
  .op .MSTORE,
  .push 2 9440,
  .op .MLOAD,
  .op .MLOAD,
  .op (.Dup ⟨0, by decide⟩),
  .push 2 9376,
  .op .MLOAD,
  .op .MUL,
  .op (.Swap ⟨0, by decide⟩),
  .push 2 9408,
  .op .MLOAD,
  .op .MLOAD,
  .op (.Dup ⟨2, by decide⟩),
  .op (.Dup ⟨10, by decide⟩),
  .op (.Swap ⟨1, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨1, by decide⟩),
  .op .ADD,
  .op (.Dup ⟨0, by decide⟩),
  .op (.Swap ⟨1, by decide⟩),
  .op .GT,
  .op .ADD,
  .op (.Dup ⟨9, by decide⟩),
  .op .JUMP,
  .op .JUMPDEST,
  .push 6 192,
  .op .MLOAD,
  .op (.Dup ⟨9, by decide⟩),
  .op (.Dup ⟨3, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .MUL,
  .op (.Swap ⟨1, by decide⟩),
  .op (.Dup ⟨4, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨1, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .op .LT,
  .op .SUB,
  .op (.Dup ⟨2, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .ADD,
  .op (.Dup ⟨0, by decide⟩),
  .op (.Swap ⟨3, by decide⟩),
  .op .GT,
  .op .SUB,
  .op .SUB,
  .op (.Swap ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .push 2 8448,
  .op .MLOAD,
  .op .ADD,
  .op (.Dup ⟨0, by decide⟩),
  .push 2 8480,
  .op .MSTORE,
  .op .LT,
  .op .ADD,
  .push 1 160,
  .op .MLOAD,
  .op (.Dup ⟨9, by decide⟩),
  .op (.Dup ⟨3, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .MUL,
  .op (.Swap ⟨1, by decide⟩),
  .op (.Dup ⟨4, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨1, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .op .LT,
  .op .SUB,
  .op (.Dup ⟨2, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .ADD,
  .op (.Dup ⟨0, by decide⟩),
  .op (.Swap ⟨3, by decide⟩),
  .op .GT,
  .op .SUB,
  .op .SUB,
  .op (.Swap ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .push 2 8416,
  .op .MLOAD,
  .op .ADD,
  .op (.Dup ⟨0, by decide⟩),
  .push 2 8448,
  .op .MSTORE,
  .op .LT,
  .op .ADD,
  .push 1 128,
  .op .MLOAD,
  .op (.Dup ⟨9, by decide⟩),
  .op (.Dup ⟨3, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .MUL,
  .op (.Swap ⟨1, by decide⟩),
  .op (.Dup ⟨4, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨1, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .op .LT,
  .op .SUB,
  .op (.Dup ⟨2, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .ADD,
  .op (.Dup ⟨0, by decide⟩),
  .op (.Swap ⟨3, by decide⟩),
  .op .GT,
  .op .SUB,
  .op .SUB,
  .op (.Swap ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .push 2 8384,
  .op .MLOAD,
  .op .ADD,
  .op (.Dup ⟨0, by decide⟩),
  .push 2 8416,
  .op .MSTORE,
  .op .LT,
  .op .ADD,
  .push 1 96,
  .op .MLOAD,
  .op (.Dup ⟨9, by decide⟩),
  .op (.Dup ⟨3, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .MUL,
  .op (.Swap ⟨1, by decide⟩),
  .op (.Dup ⟨4, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨1, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .op .LT,
  .op .SUB,
  .op (.Dup ⟨2, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .ADD,
  .op (.Dup ⟨0, by decide⟩),
  .op (.Swap ⟨3, by decide⟩),
  .op .GT,
  .op .SUB,
  .op .SUB,
  .op (.Swap ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .push 2 8352,
  .op .MLOAD,
  .op .ADD,
  .op (.Dup ⟨0, by decide⟩),
  .push 2 8384,
  .op .MSTORE,
  .op .LT,
  .op .ADD,
  .op .JUMPDEST,
  .push 1 64,
  .op .MLOAD,
  .op (.Dup ⟨9, by decide⟩),
  .op (.Dup ⟨3, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .MUL,
  .op (.Swap ⟨1, by decide⟩),
  .op (.Dup ⟨4, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨1, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .op .LT,
  .op .SUB,
  .op (.Dup ⟨2, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .ADD,
  .op (.Dup ⟨0, by decide⟩),
  .op (.Swap ⟨3, by decide⟩),
  .op .GT,
  .op .SUB,
  .op .SUB,
  .op (.Swap ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .push 2 8320,
  .op .MLOAD,
  .op .ADD,
  .op (.Dup ⟨0, by decide⟩),
  .push 2 8352,
  .op .MSTORE,
  .op .LT,
  .op .ADD,
  .push 1 32,
  .op .MLOAD,
  .op (.Dup ⟨9, by decide⟩),
  .op (.Dup ⟨3, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .MUL,
  .op (.Swap ⟨1, by decide⟩),
  .op (.Dup ⟨4, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨1, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .op .LT,
  .op .SUB,
  .op (.Dup ⟨2, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .ADD,
  .op (.Dup ⟨0, by decide⟩),
  .op (.Swap ⟨3, by decide⟩),
  .op .GT,
  .op .SUB,
  .op .SUB,
  .op (.Swap ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .push 2 8288,
  .op .MLOAD,
  .op .ADD,
  .op (.Dup ⟨0, by decide⟩),
  .push 2 8320,
  .op .MSTORE,
  .op .LT,
  .op .ADD,
  .push 0 0,
  .op .MLOAD,
  .op (.Dup ⟨9, by decide⟩),
  .op (.Dup ⟨3, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .MUL,
  .op (.Swap ⟨1, by decide⟩),
  .op (.Dup ⟨4, by decide⟩),
  .op .MULMOD,
  .op (.Dup ⟨1, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .op .LT,
  .op .SUB,
  .op (.Dup ⟨2, by decide⟩),
  .op (.Dup ⟨2, by decide⟩),
  .op .ADD,
  .op (.Dup ⟨0, by decide⟩),
  .op (.Swap ⟨3, by decide⟩),
  .op .GT,
  .op .SUB,
  .op .SUB,
  .op (.Swap ⟨0, by decide⟩),
  .op (.Dup ⟨0, by decide⟩),
  .push 2 8256,
  .op .MLOAD,
  .op .ADD,
  .op (.Dup ⟨0, by decide⟩),
  .push 2 8288,
  .op .MSTORE,
  .op .LT,
  .op .ADD,
  .op (.Swap ⟨1, by decide⟩),
  .op .POP,
  .op .POP,
  .op (.Dup ⟨0, by decide⟩),
  .push 2 8224,
  .op .MLOAD,
  .op .ADD,
  .op (.Dup ⟨0, by decide⟩),
  .push 2 8256,
  .op .MSTORE,
  .op .LT,
  .push 2 8192,
  .op .MLOAD,
  .op .ADD,
  .push 2 8224,
  .op .MSTORE,
  .op (.Dup ⟨4, by decide⟩),
  .op .ADD,
  .op (.Dup ⟨2, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .op .GT,
  .push 2 4537,
  .op .JUMPI,
  .op .POP,
  .op .POP,
  .op .POP,
  .op .POP,
  .op .POP,
  .op .POP,
  .op .POP,
  .push 2 2304,
  .op .JUMP,
  .op .JUMPDEST,
  .op (.Dup ⟨5, by decide⟩),
  .op .CALLDATALOAD,
  .op (.Dup ⟨5, by decide⟩),
  .op .CALLDATALOAD,
  .push 1 1,
  .op (.Dup ⟨2, by decide⟩),
  .op .SUB,
  .op .XOR,
  .push 2 5273,
  .op .JUMPI,
  .op (.Dup ⟨0, by decide⟩),
  .push 32 21888242871839275222246405745257275088696311157297823662689037894645226208583,
  .op .EQ,
  .op (.Dup ⟨1, by decide⟩),
  .push 5 4294968272,
  .op .NOT,
  .op .EQ,
  .op .OR,
  .op .ISZERO,
  .push 2 5273,
  .op .JUMPI,
  .op (.Dup ⟨4, by decide⟩),
  .op .CALLDATALOAD,
  .op (.Dup ⟨2, by decide⟩),
  .push 1 32,
  .op .SUB,
  .push 1 3,
  .op .SHL,
  .op .SHR,
  .op .MOD,
  .push 0 0,
  .op .LT,
  .push 0 0,
  .op .MSTORE,
  .push 1 32,
  .push 0 0,
  .op .RETURN,
  .op .JUMPDEST,
  .op .POP,
  .push 2 2657,
  .op .JUMP,
  .op .JUMPDEST,
  .push 0 0,
  .op .CALLDATALOAD,
  .push 1 32,
  .op .CALLDATALOAD,
  .push 1 64,
  .op .CALLDATALOAD,
  .push 1 32,
  .op (.Dup ⟨3, by decide⟩),
  .op .GT,
  .op (.Dup ⟨2, by decide⟩),
  .push 1 32,
  .op .XOR,
  .op .OR,
  .op (.Dup ⟨1, by decide⟩),
  .push 1 32,
  .op .XOR,
  .op .OR,
  .push 2 5327,
  .op .JUMPI,
  .op (.Dup ⟨2, by decide⟩),
  .push 1 96,
  .op .ADD,
  .op (.Dup ⟨2, by decide⟩),
  .op (.Dup ⟨1, by decide⟩),
  .op .ADD,
  .push 2 1267,
  .op (.Dup ⟨1, by decide⟩),
  .op (.Dup ⟨3, by decide⟩),
  .push 1 96,
  .op (.Dup ⟨6, by decide⟩),
  .op (.Dup ⟨8, by decide⟩),
  .op (.Dup ⟨10, by decide⟩),
  .push 2 5190,
  .op .JUMP,
  .op .JUMPDEST,
  .op .POP,
  .op .POP,
  .op .POP,
  .push 2 1314,
  .op .JUMP
]

theorem submissionInstructions_count : submissionInstructions.length = 3850 := by
  decide

theorem assemble_submissionInstructions :
    assemble submissionInstructions = submissionBytecode := by
  apply ByteArray.ext
  simp (config := { maxSteps := 4000000 })
    [assemble, assembleBytes, submissionInstructions, submissionBytecode,
    submissionBytes, Instr.bytes, natToBE]
  repeat' apply And.intro
  all_goals decide

def submissionArtifact : Challenge.EvmProof.ProgramArtifact where
  code := submissionBytecode
  instructions := submissionInstructions
  assembly_eq := assemble_submissionInstructions

theorem allWellFormed :
    Challenge.EvmProof.Stepper.AllWellFormed submissionArtifact .Osaka := by
  simp (config := { maxSteps := 4000000 })
    [Challenge.EvmProof.Stepper.AllWellFormed, submissionArtifact,
    submissionInstructions, Challenge.EvmProof.Stepper.WellFormed,
    YulEvmCompiler.plainOp]
  repeat' apply And.intro
  all_goals decide

def instructionPC (index : Nat) : Nat := submissionArtifact.instructionPC index

theorem decodeAt_op_index (index : Nat) (op : Operation)
    (hget : submissionInstructions[index]? = some (.op op))
    (hopcode : Decode.opcodeOf (Instr.opByte op) = some op)
    (hplain : YulEvmCompiler.plainOp op) :
    Decode.decodeAt submissionBytecode (instructionPC index) = some (op, none) :=
  Challenge.EvmProof.ProgramArtifact.decodeAt_op_index
    submissionArtifact index op hget hopcode hplain

theorem decodeAt_push_index (index : Nat) (width : Fin 33) (value : UInt256)
    (hget : submissionInstructions[index]? = some (.push width value))
    (hfit : value.toNat < 256 ^ width.val) :
    Decode.decodeAt submissionBytecode (instructionPC index) =
      some (.Push ⟨width⟩, some (value, width.val)) :=
  Challenge.EvmProof.ProgramArtifact.decodeAt_push_index
    submissionArtifact index width value hget hfit

theorem isValidJumpDest_index (index : Nat)
    (hget : submissionInstructions[index]? = some (.op .JUMPDEST)) :
    Decode.isValidJumpDest submissionBytecode (instructionPC index) = true :=
  Challenge.EvmProof.ProgramArtifact.isValidJumpDest_index
    submissionArtifact index hget

private def nine_width :
    WindowTwentyOneBinding.Block submissionArtifact .Osaka 2633 WindowTwentyOneEntry.widthProgram :=
  WindowTwentyOneSlice.block allWellFormed 1813 15 2633 WindowTwentyOneEntry.widthProgram
    (by decide) (by rfl) (by rfl) (by decide)

private def nine_miss :
    WindowTwentyOneBinding.Block submissionArtifact .Osaka 2653 WindowTwentyOneEntry.missProgram :=
  WindowTwentyOneSlice.block allWellFormed 1828 2 2653 WindowTwentyOneEntry.missProgram
    (by decide) (by rfl) (by rfl) (by decide)

private def nine_base :
    WindowTwentyOneBinding.Block submissionArtifact .Osaka 2657 WindowTwentyOneEntry.baseProgram :=
  WindowTwentyOneSlice.block allWellFormed 1830 5 2657 WindowTwentyOneEntry.baseProgram
    (by decide) (by rfl) (by rfl) (by decide)

private def nine_modulus :
    WindowTwentyOneBinding.Block submissionArtifact .Osaka 2664 WindowTwentyOneEntry.modulusProgram :=
  WindowTwentyOneSlice.block allWellFormed 1835 6 2664 WindowTwentyOneEntry.modulusProgram
    (by decide) (by rfl) (by rfl) (by decide)

private def nine_normalize :
    WindowTwentyOneBinding.Block submissionArtifact .Osaka 2672 WindowTwentyOneEntry.normalizeProgram :=
  WindowTwentyOneSlice.block allWellFormed 1841 8 2672 WindowTwentyOneEntry.normalizeProgram
    (by decide) (by rfl) (by rfl) (by decide)

private def nine_table :
    WindowTwentyOneBinding.Block submissionArtifact .Osaka 2682 WindowTwentyOneTableBuild.program :=
  WindowTwentyOneSlice.block allWellFormed 1849 93 2682 WindowTwentyOneTableBuild.program
    (by decide) (by rfl) (by rfl) (by decide)

private def nine_init :
    WindowTwentyOneBinding.Block submissionArtifact .Osaka 2799 WindowTwentyOneInit.program :=
  WindowTwentyOneSlice.block allWellFormed 1942 17 2799 WindowTwentyOneInit.program
    (by decide) (by rfl) (by rfl) (by decide)

private def nine_iteration :
    WindowTwentyOneBinding.Block submissionArtifact .Osaka 2821 WindowTwentyOneLoop.iterationProgram :=
  WindowTwentyOneSlice.block allWellFormed 1959 438 2821 WindowTwentyOneLoop.iterationProgram
    (by decide) (by rfl) (by rfl) (by decide)

private def nine_finish :
    WindowTwentyOneBinding.Block submissionArtifact .Osaka 3284 WindowTwentyOneReturn.program :=
  WindowTwentyOneSlice.block allWellFormed 2397 5 3284 WindowTwentyOneReturn.program
    (by decide) (by rfl) (by rfl) (by decide)

private def nine_zeroReturn :
    WindowTwentyOneBinding.Block submissionArtifact .Osaka 3290 WindowTwentyOneReturn.zeroProgram :=
  WindowTwentyOneSlice.block allWellFormed 2402 7 3290 WindowTwentyOneReturn.zeroProgram
    (by decide) (by rfl) (by rfl) (by decide)

private def nine_emptyReturn :
    WindowTwentyOneBinding.Block submissionArtifact .Osaka 3298 WindowTwentyOneReturn.emptyProgram :=
  WindowTwentyOneSlice.block allWellFormed 2409 14 3298 WindowTwentyOneReturn.emptyProgram
    (by decide) (by rfl) (by rfl) (by decide)

private def fermat_load : WindowTwentyOneBinding.Block submissionArtifact .Osaka 5190 FermatProgram.loadProgram :=
  WindowTwentyOneSlice.block allWellFormed 3767 3 5190 FermatProgram.loadProgram (by decide) (by rfl) (by rfl) (by decide)
private def fermat_exponent : WindowTwentyOneBinding.Block submissionArtifact .Osaka 5193 FermatProgram.exponentXorProgram :=
  WindowTwentyOneSlice.block allWellFormed 3770 8 5193 FermatProgram.exponentXorProgram (by decide) (by rfl) (by rfl) (by decide)
private def fermat_prime : WindowTwentyOneBinding.Block submissionArtifact .Osaka 5204 FermatProgram.primeFilterProgram :=
  WindowTwentyOneSlice.block allWellFormed 3778 11 5204 FermatProgram.primeFilterProgram (by decide) (by rfl) (by rfl) (by decide)
private def fermat_result : WindowTwentyOneBinding.Block submissionArtifact .Osaka 5254 FermatProgram.returnProgram :=
  WindowTwentyOneSlice.block allWellFormed 3789 16 5254 FermatProgram.returnProgram (by decide) (by rfl) (by rfl) (by decide)
private def fermat_miss : WindowTwentyOneBinding.Block submissionArtifact .Osaka 5273 FermatProgram.missProgram :=
  WindowTwentyOneSlice.block allWellFormed 3805 4 5273 FermatProgram.missProgram (by decide) (by rfl) (by rfl) (by decide)
def fermatPaths : FermatProgram.Paths submissionArtifact .Osaka where
  load := fermat_load
  exponent := fermat_exponent
  prime := fermat_prime
  result := fermat_result
  miss := fermat_miss
  missJump := by exact isValidJumpDest_index 3805 (by rfl)
  legacyJump := by exact isValidJumpDest_index 1830 (by rfl)

private def earlyWord_guard : WindowTwentyOneBinding.Block submissionArtifact .Osaka 5279 EarlyWordProgram.guardProgram :=
  WindowTwentyOneSlice.block allWellFormed 3809 20 5279 EarlyWordProgram.guardProgram (by decide) (by rfl) (by rfl) (by decide)
private def earlyWord_hit : WindowTwentyOneBinding.Block submissionArtifact .Osaka 5306 EarlyWordProgram.hitProgram :=
  WindowTwentyOneSlice.block allWellFormed 3829 15 5306 EarlyWordProgram.hitProgram (by decide) (by rfl) (by rfl) (by decide)
private def earlyWord_miss : WindowTwentyOneBinding.Block submissionArtifact .Osaka 5327 EarlyWordProgram.missProgram :=
  WindowTwentyOneSlice.block allWellFormed 3844 6 5327 EarlyWordProgram.missProgram (by decide) (by rfl) (by rfl) (by decide)
def earlyWordPaths : EarlyWordProgram.Paths submissionArtifact .Osaka where
  guard := earlyWord_guard
  hit := earlyWord_hit
  miss := earlyWord_miss
  helperJump := by exact isValidJumpDest_index 3809 (by rfl)
  missJump := by exact isValidJumpDest_index 3844 (by rfl)
  hitJump := by exact isValidJumpDest_index 3767 (by rfl)
  legacyJump := by exact isValidJumpDest_index 977 (by rfl)

def twentyOnePaths : WindowTwentyOneGasRoute.Paths submissionArtifact .Osaka where
  width := nine_width
  miss := nine_miss
  base := nine_base
  modulus := nine_modulus
  normalize := nine_normalize
  table := nine_table
  init := nine_init
  iteration := nine_iteration
  finish := nine_finish
  zeroReturn := nine_zeroReturn
  emptyReturn := nine_emptyReturn
  hitJump := by
    have h := isValidJumpDest_index 3767 (by rfl)
    exact h
  emptyJump := by
    have h := isValidJumpDest_index 2409 (by rfl)
    exact h
  zeroJump := by
    have h := isValidJumpDest_index 2402 (by rfl)
    exact h
  loopJump := by
    have h := isValidJumpDest_index 1959 (by rfl)
    exact h
  missJump := by
    have h := isValidJumpDest_index 415 (by rfl)
    exact h

end Challenge.Modexp.Submission.Proofs.Bytecode.Artifact
