import Challenge.EvmProof.Program
import Challenge.EvmProof.Stepper
import Challenge.EvmProof.Word
import Challenge.Modexp.Submission.Bytecode

attribute [simp]
  Challenge.EvmProof.Word.word_toNat_add
  Challenge.EvmProof.Word.word_toNat_sub
  Challenge.EvmProof.Word.word_toNat_lt
  Challenge.EvmProof.Word.word_toNat_isZero
  Challenge.EvmProof.Word.word_toNat_lor
  Challenge.EvmProof.Word.word_toNat_land

set_option warningAsError true
set_option maxRecDepth 20000
set_option maxHeartbeats 2000000

namespace Challenge.Modexp.Submission.Proofs.Bytecode.Artifact

open EvmSemantics
open EvmSemantics.EVM
open YulEvmCompiler

def submissionInstructions : List Instr :=
[.push 0 0,
 .op .CALLDATALOAD,
 .push 1 32,
 .op .CALLDATALOAD,
 .push 1 64,
 .op .CALLDATALOAD,
 .push 1 32,
 .op (.Dup { idx := 3 }),
 .op .GT,
 .op (.Dup { idx := 2 }),
 .push 1 32,
 .op .XOR,
 .op .OR,
 .op (.Dup { idx := 1 }),
 .push 1 32,
 .op .XOR,
 .op .OR,
 .push 2 127,
 .op .JUMPI,
 .op (.Dup { idx := 2 }),
 .push 1 96,
 .op .ADD,
 .op (.Dup { idx := 2 }),
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .push 2 1186,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 3 }),
 .push 1 96,
 .op (.Dup { idx := 6 }),
 .op (.Dup { idx := 8 }),
 .op (.Dup { idx := 10 }),
 .op .JUMPDEST,
 .op (.Dup { idx := 5 }),
 .op .CALLDATALOAD,
 .op (.Dup { idx := 5 }),
 .op .CALLDATALOAD,
 .push 1 1,
 .op (.Dup { idx := 2 }),
 .op .SUB,
 .op .XOR,
 .push 3 1787,
 .op .JUMPI,
 .op (.Dup { idx := 0 }),
 .push 32 21888242871839275222246405745257275088696311157297823662689037894645226208583,
 .op .EQ,
 .op (.Dup { idx := 1 }),
 .push 5 4294968272,
 .op .NOT,
 .op .EQ,
 .op .OR,
 .op .ISZERO,
 .push 2 1787,
 .op .JUMPI,
 .op (.Dup { idx := 4 }),
 .op .CALLDATALOAD,
 .op (.Dup { idx := 2 }),
 .push 1 32,
 .op .SUB,
 .push 1 3,
 .op .SHL,
 .op .SHR,
 .op .MOD,
 .push 0 0,
 .op .LT,
 .push 0 0,
 .op .MSTORE,
 .push 1 32,
 .push 0 0,
 .op .RETURN,
 .op .JUMPDEST,
 .op .POP,
 .op .POP,
 .op .POP,
 .push 2 717,
 .op .JUMP,
 .op .JUMPDEST,
 .op (.Dup { idx := 0 }),
 .op .CALLDATALOAD,
 .push 0 0,
 .op .BYTE,
 .op (.Swap { idx := 1 }),
 .op .POP,
 .op .POP,
 .op (.Swap { idx := 0 }),
 .op .JUMP,
 .op .JUMPDEST,
 .op (.Dup { idx := 5 }),
 .op .CALLDATALOAD,
 .op (.Dup { idx := 3 }),
 .push 1 32,
 .op .SUB,
 .push 1 3,
 .op .SHL,
 .op .SHR,
 .op (.Dup { idx := 0 }),
 .push 2 164,
 .op .JUMPI,
 .op (.Dup { idx := 3 }),
 .push 0 0,
 .op .RETURN,
 .op .JUMPDEST,
 .push 0 0,
 .push 0 0,
 .op .JUMPDEST,
 .op (.Dup { idx := 3 }),
 .op (.Dup { idx := 1 }),
 .op .LT,
 .op .ISZERO,
 .push 2 204,
 .op .JUMPI,
 .op (.Dup { idx := 2 }),
 .push 2 187,
 .push 0 0,
 .op (.Dup { idx := 3 }),
 .op (.Dup { idx := 10 }),
 .op .ADD,
 .push 1 135,
 .op .JUMP,
 .op .JUMPDEST,
 .op (.Dup { idx := 4 }),
 .push 2 256,
 .op (.Dup { idx := 5 }),
 .op .MULMOD,
 .op .ADDMOD,
 .op (.Swap { idx := 1 }),
 .op .POP,
 .push 1 1,
 .op .ADD,
 .push 2 167,
 .op .JUMP,
 .op .JUMPDEST,
 .op .POP,
 .op (.Dup { idx := 1 }),
 .push 1 1,
 .op .LT,
 .push 0 0,
 .op .JUMPDEST,
 .op (.Dup { idx := 5 }),
 .op (.Dup { idx := 1 }),
 .op .EQ,
 .push 2 242,
 .op .JUMPI,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 9 }),
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .op .CALLDATALOAD,
 .push 0 0,
 .op .BYTE,
 .push 0 0,
 .push 2 2537,
 .op .JUMP,
 .op .JUMPDEST,
 .op .POP,
 .op .POP,
 .op .POP,
 .push 1 1,
 .op .ADD,
 .push 2 211,
 .op .JUMP,
 .op .JUMPDEST,
 .op .POP,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 6 }),
 .push 1 32,
 .op .SUB,
 .push 1 3,
 .op .SHL,
 .op .SHL,
 .push 0 0,
 .op .MSTORE,
 .op (.Dup { idx := 5 }),
 .push 0 0,
 .op .RETURN,
 .op .JUMPDEST,
 .push 2 9248,
 .op .CALLDATASIZE,
 .push 0 0,
 .op .CALLDATACOPY,
 .push 1 64,
 .op .CALLDATALOAD,
 .op (.Dup { idx := 0 }),
 .push 2 9216,
 .op .MSTORE,
 .push 1 32,
 .op .CALLDATALOAD,
 .push 0 0,
 .op .CALLDATALOAD,
 .op (.Dup { idx := 2 }),
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 3 }),
 .op .ADD,
 .push 1 96,
 .op .ADD,
 .push 2 1024,
 .op .CALLDATACOPY,
 .op (.Dup { idx := 0 }),
 .push 1 96,
 .push 2 5120,
 .op .CALLDATACOPY,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .push 1 96,
 .op .ADD,
 .push 2 6144,
 .op .CALLDATACOPY,
 .push 0 0,
 .op (.Dup { idx := 3 }),
 .op .JUMPDEST,
 .push 0 0,
 .op .NOT,
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .push 2 1024,
 .op .ADD,
 .op .MLOAD,
 .push 0 0,
 .op .BYTE,
 .op (.Swap { idx := 0 }),
 .op (.Swap { idx := 1 }),
 .op .OR,
 .op (.Swap { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .push 2 307,
 .op .JUMPI,
 .op .POP,
 .push 2 338,
 .op .JUMPI,
 .op (.Dup { idx := 2 }),
 .push 2 8192,
 .op .RETURN,
 .op .JUMPDEST,
 .push 1 1,
 .op (.Dup { idx := 3 }),
 .push 2 7167,
 .op .ADD,
 .op .MSTORE8,
 .op (.Dup { idx := 0 }),
 .push 2 5120,
 .push 2 7168,
 .push 2 361,
 .push 2 483,
 .op .JUMP,
 .op .JUMPDEST,
 .op .POP,
 .push 2 9216,
 .op .MLOAD,
 .push 0 0,
 .push 2 2048,
 .op .MCOPY,
 .op (.Dup { idx := 1 }),
 .push 2 7168,
 .push 2 3072,
 .op .MCOPY,
 .push 0 0,
 .op .JUMPDEST,
 .op (.Dup { idx := 1 }),
 .push 1 3,
 .op .SHL,
 .op (.Dup { idx := 1 }),
 .op .EQ,
 .push 2 462,
 .op .JUMPI,
 .op (.Dup { idx := 2 }),
 .push 2 3072,
 .op (.Dup { idx := 0 }),
 .push 2 404,
 .push 2 483,
 .op .JUMP,
 .op .JUMPDEST,
 .op (.Dup { idx := 2 }),
 .push 0 0,
 .push 2 3072,
 .op .MCOPY,
 .op (.Dup { idx := 0 }),
 .push 1 3,
 .op .SHR,
 .push 2 6144,
 .op .ADD,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .push 1 7,
 .op .AND,
 .op .SHL,
 .push 1 255,
 .op .SHR,
 .op .ISZERO,
 .push 2 454,
 .op .JUMPI,
 .op (.Dup { idx := 2 }),
 .push 2 2048,
 .push 2 3072,
 .push 2 447,
 .push 2 483,
 .op .JUMP,
 .op .JUMPDEST,
 .op (.Dup { idx := 2 }),
 .push 0 0,
 .push 2 3072,
 .op .MCOPY,
 .op .JUMPDEST,
 .push 1 1,
 .op .ADD,
 .push 2 381,
 .op .JUMP,
 .op .JUMPDEST,
 .op (.Dup { idx := 2 }),
 .push 2 3072,
 .push 0 0,
 .op .MCOPY,
 .push 2 8192,
 .push 2 479,
 .push 2 555,
 .op .JUMP,
 .op .JUMPDEST,
 .op (.Dup { idx := 2 }),
 .push 0 0,
 .op .RETURN,
 .op .JUMPDEST,
 .push 2 9216,
 .op .MLOAD,
 .op .CALLDATASIZE,
 .push 0 0,
 .op .CALLDATACOPY,
 .push 0 0,
 .op .JUMPDEST,
 .op (.Dup { idx := 4 }),
 .push 1 3,
 .op .SHL,
 .op (.Dup { idx := 1 }),
 .op .EQ,
 .push 2 548,
 .op .JUMPI,
 .push 0 0,
 .push 2 511,
 .push 2 555,
 .op .JUMP,
 .op .JUMPDEST,
 .op (.Dup { idx := 0 }),
 .push 1 3,
 .op .SHR,
 .op (.Dup { idx := 4 }),
 .op .ADD,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .push 1 7,
 .op .AND,
 .op .SHL,
 .push 1 255,
 .op .SHR,
 .op .ISZERO,
 .push 2 540,
 .op .JUMPI,
 .op (.Dup { idx := 2 }),
 .push 2 540,
 .push 2 555,
 .op .JUMP,
 .op .JUMPDEST,
 .push 1 1,
 .op .ADD,
 .push 2 492,
 .op .JUMP,
 .op .JUMPDEST,
 .op .POP,
 .op (.Swap { idx := 2 }),
 .op .POP,
 .op .POP,
 .op .POP,
 .op .JUMP,
 .op .JUMPDEST,
 .push 0 0,
 .push 2 9216,
 .op .MLOAD,
 .op .JUMPDEST,
 .push 0 0,
 .op .NOT,
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 4 }),
 .op .ADD,
 .op .MLOAD,
 .push 0 0,
 .op .BYTE,
 .op (.Dup { idx := 1 }),
 .op .MLOAD,
 .push 0 0,
 .op .BYTE,
 .op .ADD,
 .op (.Dup { idx := 2 }),
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .MSTORE8,
 .push 1 8,
 .op .SHR,
 .op (.Swap { idx := 1 }),
 .op .POP,
 .op (.Dup { idx := 0 }),
 .push 2 561,
 .op .JUMPI,
 .op .POP,
 .push 0 0,
 .push 2 9216,
 .op .MLOAD,
 .op .JUMPDEST,
 .push 0 0,
 .op .NOT,
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .push 2 1024,
 .op .ADD,
 .op .MLOAD,
 .push 0 0,
 .op .BYTE,
 .op (.Dup { idx := 1 }),
 .op .MLOAD,
 .push 0 0,
 .op .BYTE,
 .op .SUB,
 .op (.Dup { idx := 2 }),
 .op (.Swap { idx := 0 }),
 .op .SUB,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .push 2 4096,
 .op .ADD,
 .op .MSTORE8,
 .push 1 255,
 .op .SHR,
 .op (.Swap { idx := 1 }),
 .op .POP,
 .op (.Dup { idx := 0 }),
 .push 2 597,
 .op .JUMPI,
 .op .POP,
 .op .ISZERO,
 .op .OR,
 .op .ISZERO,
 .push 2 651,
 .op .JUMPI,
 .push 2 9216,
 .op .MLOAD,
 .push 2 4096,
 .push 0 0,
 .op .MCOPY,
 .op .JUMPDEST,
 .op (.Swap { idx := 0 }),
 .op .POP,
 .op .JUMP,
 .op .JUMPDEST,
 .push 0 0,
 .op .CALLDATALOAD,
 .push 1 32,
 .op .CALLDATALOAD,
 .push 1 64,
 .op .CALLDATALOAD,
 .op (.Dup { idx := 0 }),
 .push 2 672,
 .op .JUMPI,
 .push 0 0,
 .push 0 0,
 .op .RETURN,
 .op .JUMPDEST,
 .op (.Dup { idx := 2 }),
 .push 1 96,
 .op .ADD,
 .op (.Dup { idx := 2 }),
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .push 1 32,
 .op (.Dup { idx := 3 }),
 .op .GT,
 .push 2 702,
 .op .JUMPI,
 .push 2 1186,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 3 }),
 .push 1 96,
 .op (.Dup { idx := 6 }),
 .op (.Dup { idx := 8 }),
 .op (.Dup { idx := 10 }),
 .push 2 1764,
 .op .JUMP,
 .op .JUMPDEST,
 .push 2 1202,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 3 }),
 .push 1 96,
 .op (.Dup { idx := 6 }),
 .op (.Dup { idx := 8 }),
 .op (.Dup { idx := 10 }),
 .push 2 258,
 .op .JUMP,
 .op .JUMPDEST,
 .push 1 64,
 .op .CALLDATALOAD,
 .op (.Dup { idx := 0 }),
 .push 1 33,
 .op (.Swap { idx := 0 }),
 .op .SUB,
 .push 1 223,
 .op .LT,
 .push 2 1170,
 .op .JUMPI,
 .push 1 32,
 .op .CALLDATALOAD,
 .push 0 0,
 .op .CALLDATALOAD,
 .op (.Dup { idx := 2 }),
 .push 1 31,
 .op .ADD,
 .push 1 5,
 .op .SHR,
 .op (.Dup { idx := 0 }),
 .push 1 5,
 .op .SHL,
 .op (.Dup { idx := 3 }),
 .op (.Dup { idx := 3 }),
 .op .ADD,
 .push 1 96,
 .op .ADD,
 .op (.Dup { idx := 5 }),
 .op (.Dup { idx := 2 }),
 .op .SUB,
 .push 1 3,
 .op .SHL,
 .op (.Dup { idx := 1 }),
 .op .CALLDATALOAD,
 .op (.Swap { idx := 0 }),
 .op .SHR,
 .op .ISZERO,
 .push 2 1176,
 .op .JUMPI,
 .push 1 32,
 .op (.Dup { idx := 6 }),
 .op (.Dup { idx := 2 }),
 .op .ADD,
 .op .SUB,
 .op .CALLDATALOAD,
 .push 1 1,
 .op .AND,
 .op .ISZERO,
 .push 2 1176,
 .op .JUMPI,
 .op (.Dup { idx := 1 }),
 .push 2 2688,
 .op .MSTORE,
 .op .JUMPDEST,
 .op (.Dup { idx := 3 }),
 .push 1 96,
 .op .ADD,
 .push 2 2816,
 .op .MSTORE,
 .push 1 32,
 .op (.Dup { idx := 2 }),
 .op .SUB,
 .op (.Dup { idx := 0 }),
 .push 2 2752,
 .op .MSTORE,
 .op (.Dup { idx := 2 }),
 .push 2 2080,
 .op .ADD,
 .push 2 2784,
 .op .MSTORE,
 .op (.Dup { idx := 2 }),
 .op .CALLDATASIZE,
 .push 0 0,
 .op .CALLDATACOPY,
 .op (.Dup { idx := 6 }),
 .op (.Dup { idx := 2 }),
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 5 }),
 .op .SUB,
 .op .CALLDATACOPY,
 .op (.Swap { idx := 0 }),
 .op .POP,
 .op (.Dup { idx := 0 }),
 .op .MLOAD,
 .op (.Dup { idx := 0 }),
 .push 1 3,
 .op .MUL,
 .push 1 2,
 .op .XOR,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .push 1 2,
 .op .SUB,
 .op .MUL,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .push 1 2,
 .op .SUB,
 .op .MUL,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .push 1 2,
 .op .SUB,
 .op .MUL,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .push 1 2,
 .op .SUB,
 .op .MUL,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .push 1 2,
 .op .SUB,
 .op .MUL,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .push 1 2,
 .op .SUB,
 .op .MUL,
 .push 0 0,
 .op .SUB,
 .push 2 2720,
 .op .MSTORE,
 .op .POP,
 .op .POP,
 .push 2 2833,
 .op .JUMP,
 .op .JUMPDEST,
 .push 2 2688,
 .op .MLOAD,
 .push 2 1024,
 .push 2 1280,
 .op .MCOPY,
 .push 2 2431,
 .push 2 1280,
 .push 2 2792,
 .op .JUMP,
 .op .JUMPDEST,
 .push 2 929,
 .push 2 1536,
 .op (.Dup { idx := 0 }),
 .push 2 1536,
 .push 2 3533,
 .op .JUMP,
 .op .JUMPDEST,
 .op (.Dup { idx := 2 }),
 .op (.Dup { idx := 1 }),
 .op .SHR,
 .push 1 1,
 .op .AND,
 .push 2 256,
 .op .MUL,
 .push 2 1024,
 .op .ADD,
 .push 2 1740,
 .op .JUMP,
 .op .JUMPDEST,
 .op .POP,
 .op (.Dup { idx := 0 }),
 .op .ISZERO,
 .push 2 963,
 .op .JUMPI,
 .push 0 0,
 .op .NOT,
 .op .ADD,
 .push 2 914,
 .op .JUMP,
 .op .JUMPDEST,
 .op .POP,
 .op (.Dup { idx := 2 }),
 .op .ISZERO,
 .push 2 2675,
 .op .JUMPI,
 .push 2 2466,
 .op .JUMP,
 .op .JUMPDEST,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op .EQ,
 .push 2 1042,
 .op .JUMPI,
 .push 2 999,
 .push 2 256,
 .push 2 1280,
 .push 2 256,
 .push 2 3533,
 .op .JUMP,
 .op .JUMPDEST,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .SUB,
 .push 1 5,
 .op .SHL,
 .op (.Dup { idx := 5 }),
 .op .SUB,
 .push 1 96,
 .op .ADD,
 .op .CALLDATALOAD,
 .op (.Dup { idx := 3 }),
 .push 2 736,
 .op .ADD,
 .op .MSTORE,
 .push 2 1034,
 .push 2 256,
 .push 2 768,
 .push 2 256,
 .push 2 1487,
 .op .JUMP,
 .op .JUMPDEST,
 .push 1 1,
 .op .ADD,
 .push 2 975,
 .op .JUMP,
 .op .JUMPDEST,
 .op .POP,
 .op .POP,
 .push 2 2675,
 .push 2 512,
 .push 2 1536,
 .push 2 256,
 .push 2 3533,
 .op .JUMP,
 .op .JUMPDEST,
 .op (.Dup { idx := 4 }),
 .op (.Dup { idx := 1 }),
 .op .EQ,
 .push 2 1132,
 .op .JUMPI,
 .push 2 1691,
 .op .JUMP,
 .op .JUMPDEST,
 .push 2 1088,
 .push 2 256,
 .op (.Dup { idx := 0 }),
 .push 2 256,
 .push 2 3533,
 .op .JUMP,
 .op .JUMPDEST,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op .AND,
 .op .ISZERO,
 .push 2 1114,
 .op .JUMPI,
 .push 2 1113,
 .push 2 256,
 .push 2 512,
 .push 2 256,
 .push 2 3533,
 .op .JUMP,
 .op .JUMPDEST,
 .op .JUMPDEST,
 .push 1 1,
 .op .SHR,
 .op (.Dup { idx := 0 }),
 .push 2 1073,
 .op .JUMPI,
 .op .POP,
 .op .POP,
 .push 1 1,
 .op .ADD,
 .push 2 1061,
 .op .JUMP,
 .op .JUMPDEST,
 .op .POP,
 .push 1 1,
 .op (.Dup { idx := 1 }),
 .push 2 736,
 .op .ADD,
 .op .MSTORE,
 .push 2 1160,
 .push 2 256,
 .push 2 768,
 .push 2 256,
 .push 2 3533,
 .op .JUMP,
 .op .JUMPDEST,
 .op .POP,
 .op .JUMPDEST,
 .op (.Dup { idx := 4 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .push 2 256,
 .op .ADD,
 .op .SUB,
 .op .RETURN,
 .op .JUMPDEST,
 .op .POP,
 .push 2 655,
 .op .JUMP,
 .op .JUMPDEST,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .POP,
 .push 2 655,
 .op .JUMP,
 .op .JUMPDEST,
 .push 2 256,
 .op .JUMPDEST,
 .push 2 1202,
 .op (.Dup { idx := 2 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .push 2 1487,
 .op .JUMP,
 .op .JUMPDEST,
 .push 1 1,
 .op (.Swap { idx := 0 }),
 .op .SUB,
 .op (.Dup { idx := 0 }),
 .push 2 1191,
 .op .JUMPI,
 .op .POP,
 .op .POP,
 .op .JUMP,
 .op .JUMPDEST,
 .push 2 2688,
 .op .MLOAD,
 .op (.Dup { idx := 0 }),
 .push 1 64,
 .op .ADD,
 .op .CALLDATASIZE,
 .push 2 2048,
 .op .CALLDATACOPY,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 3 }),
 .op .ADD,
 .push 1 32,
 .op (.Swap { idx := 0 }),
 .op .SUB,
 .push 1 32,
 .op (.Dup { idx := 4 }),
 .op .SUB,
 .op (.Swap { idx := 3 }),
 .op .POP,
 .op (.Swap { idx := 0 }),
 .op .POP,
 .push 1 32,
 .op (.Dup { idx := 2 }),
 .op .SUB,
 .op (.Swap { idx := 1 }),
 .op .POP,
 .op .JUMPDEST,
 .op (.Dup { idx := 0 }),
 .op .MLOAD,
 .push 0 0,
 .push 2 2784,
 .op .MLOAD,
 .op (.Dup { idx := 4 }),
 .push 2 2688,
 .op .MLOAD,
 .op .ADD,
 .op .JUMPDEST,
 .op (.Dup { idx := 3 }),
 .op (.Dup { idx := 1 }),
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op .MUL,
 .op (.Swap { idx := 1 }),
 .push 0 0,
 .op .NOT,
 .op (.Swap { idx := 1 }),
 .op .MULMOD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op .LT,
 .op (.Dup { idx := 2 }),
 .op .ADD,
 .op (.Swap { idx := 0 }),
 .op .SUB,
 .op (.Dup { idx := 3 }),
 .op .MLOAD,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 2 }),
 .op .ADD,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 2 }),
 .op .LT,
 .op .ADD,
 .op (.Swap { idx := 0 }),
 .op (.Dup { idx := 4 }),
 .op .ADD,
 .op (.Swap { idx := 3 }),
 .op (.Dup { idx := 4 }),
 .op .LT,
 .op .ADD,
 .op (.Swap { idx := 2 }),
 .op (.Dup { idx := 2 }),
 .op .MSTORE,
 .push 1 31,
 .op .NOT,
 .op .ADD,
 .op (.Swap { idx := 0 }),
 .push 1 31,
 .op .NOT,
 .op .ADD,
 .op (.Swap { idx := 0 }),
 .op (.Dup { idx := 5 }),
 .op (.Dup { idx := 1 }),
 .op .GT,
 .push 2 1264,
 .op .JUMPI,
 .op .POP,
 .op .POP,
 .op (.Dup { idx := 0 }),
 .push 2 2080,
 .op .MLOAD,
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .push 2 2080,
 .op .MSTORE,
 .op .LT,
 .push 2 2048,
 .op .MSTORE,
 .push 2 2784,
 .op .MLOAD,
 .op .MLOAD,
 .push 2 2720,
 .op .MLOAD,
 .op .MUL,
 .op (.Dup { idx := 0 }),
 .push 2 2752,
 .op .MLOAD,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op .MUL,
 .op (.Swap { idx := 1 }),
 .push 0 0,
 .op .NOT,
 .op (.Swap { idx := 1 }),
 .op .MULMOD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op .LT,
 .op (.Dup { idx := 2 }),
 .op .ADD,
 .op (.Swap { idx := 0 }),
 .op .SUB,
 .op (.Swap { idx := 0 }),
 .push 0 0,
 .op .LT,
 .op .ADD,
 .push 2 2784,
 .op .MLOAD,
 .push 1 32,
 .op (.Swap { idx := 0 }),
 .op .SUB,
 .push 2 2752,
 .op .MLOAD,
 .push 1 32,
 .op (.Swap { idx := 0 }),
 .op .SUB,
 .op .JUMPDEST,
 .op (.Dup { idx := 0 }),
 .op .MLOAD,
 .push 0 0,
 .op .NOT,
 .op (.Dup { idx := 5 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 6 }),
 .op .MULMOD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op .LT,
 .op .SUB,
 .op (.Dup { idx := 4 }),
 .op (.Dup { idx := 2 }),
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .op (.Swap { idx := 5 }),
 .op .GT,
 .op .SUB,
 .op .SUB,
 .op (.Dup { idx := 3 }),
 .op (.Dup { idx := 3 }),
 .op .MLOAD,
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .op (.Swap { idx := 4 }),
 .op .GT,
 .op .ADD,
 .op (.Swap { idx := 2 }),
 .push 1 32,
 .op (.Dup { idx := 3 }),
 .push 1 31,
 .op .NOT,
 .op .ADD,
 .op (.Swap { idx := 3 }),
 .op .ADD,
 .op .MSTORE,
 .push 1 31,
 .op .NOT,
 .op .ADD,
 .push 2 2080,
 .op (.Dup { idx := 2 }),
 .op .GT,
 .push 2 1388,
 .op .JUMPI,
 .op .POP,
 .op .POP,
 .op (.Swap { idx := 1 }),
 .op .POP,
 .op .POP,
 .op (.Dup { idx := 0 }),
 .push 2 2080,
 .op .MLOAD,
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .push 2 2112,
 .op .MSTORE,
 .op .LT,
 .push 2 2048,
 .op .MLOAD,
 .op .ADD,
 .push 2 2080,
 .op .MSTORE,
 .push 1 31,
 .op .NOT,
 .op .ADD,
 .op (.Dup { idx := 2 }),
 .op (.Dup { idx := 1 }),
 .op .GT,
 .push 2 1250,
 .op .JUMPI,
 .op .POP,
 .op .POP,
 .op .POP,
 .push 2 4316,
 .op .JUMP,
 .op .JUMPDEST,
 .push 2 2688,
 .op .MLOAD,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .ADD,
 .push 1 32,
 .op (.Swap { idx := 0 }),
 .op .SUB,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 4 }),
 .op .ADD,
 .push 1 32,
 .op (.Swap { idx := 0 }),
 .op .SUB,
 .op (.Swap { idx := 2 }),
 .op .POP,
 .op (.Swap { idx := 2 }),
 .op .POP,
 .op .POP,
 .push 2 2784,
 .op .MLOAD,
 .push 0 0,
 .op (.Swap { idx := 2 }),
 .op (.Swap { idx := 0 }),
 .op .JUMPDEST,
 .op (.Dup { idx := 1 }),
 .op .MLOAD,
 .op (.Dup { idx := 3 }),
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Swap { idx := 0 }),
 .op (.Dup { idx := 1 }),
 .op .LT,
 .op (.Swap { idx := 0 }),
 .op (.Dup { idx := 5 }),
 .op .ADD,
 .op (.Swap { idx := 4 }),
 .op (.Dup { idx := 5 }),
 .op .LT,
 .op .OR,
 .op (.Swap { idx := 3 }),
 .op (.Dup { idx := 1 }),
 .op .MSTORE,
 .push 1 31,
 .op .NOT,
 .op .ADD,
 .op (.Swap { idx := 0 }),
 .push 1 31,
 .op .NOT,
 .op .ADD,
 .op (.Swap { idx := 0 }),
 .op (.Swap { idx := 1 }),
 .push 1 31,
 .op .NOT,
 .op .ADD,
 .op (.Swap { idx := 1 }),
 .push 2 2080,
 .op (.Dup { idx := 1 }),
 .op .GT,
 .push 2 1518,
 .op .JUMPI,
 .op .POP,
 .op .POP,
 .op .POP,
 .push 2 2080,
 .op .MSTORE,
 .push 2 4316,
 .op .JUMP,
 .op .JUMPDEST,
 .op (.Dup { idx := 0 }),
 .op .MLOAD,
 .op (.Dup { idx := 2 }),
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op .GT,
 .op (.Swap { idx := 1 }),
 .op .SUB,
 .op (.Dup { idx := 5 }),
 .op (.Dup { idx := 1 }),
 .op .SUB,
 .op (.Swap { idx := 0 }),
 .op (.Dup { idx := 6 }),
 .op .GT,
 .op (.Swap { idx := 0 }),
 .op (.Swap { idx := 1 }),
 .op .OR,
 .op (.Swap { idx := 4 }),
 .op .POP,
 .op (.Dup { idx := 3 }),
 .op .MSTORE,
 .push 1 31,
 .op .NOT,
 .op .ADD,
 .op (.Swap { idx := 0 }),
 .push 1 31,
 .op .NOT,
 .op .ADD,
 .op (.Swap { idx := 0 }),
 .op (.Swap { idx := 1 }),
 .push 1 31,
 .op .NOT,
 .op .ADD,
 .op (.Swap { idx := 1 }),
 .push 2 2080,
 .op (.Dup { idx := 1 }),
 .op .GT,
 .push 2 1574,
 .op .JUMPI,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .ISZERO,
 .push 2 2080,
 .op .MLOAD,
 .op .OR,
 .push 2 319,
 .op .NOT,
 .op .MUL,
 .push 2 2112,
 .op .ADD,
 .push 2 2688,
 .op .MLOAD,
 .op (.Swap { idx := 1 }),
 .op .MCOPY,
 .op .JUMP,
 .op .JUMPDEST,
 .push 2 1658,
 .op (.Dup { idx := 2 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .push 2 3533,
 .op .JUMP,
 .op .JUMPDEST,
 .push 0 0,
 .op .NOT,
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .push 2 1647,
 .op .JUMPI,
 .op .POP,
 .op .POP,
 .op .JUMP,
 .op .JUMPDEST,
 .push 0 0,
 .op .MLOAD,
 .push 1 255,
 .op .SHR,
 .op .ISZERO,
 .push 2 1187,
 .op .JUMPI,
 .push 1 1,
 .push 2 2080,
 .op .MSTORE,
 .push 2 4316,
 .op .JUMP,
 .op .JUMPDEST,
 .op (.Dup { idx := 0 }),
 .push 2 2816,
 .op .MLOAD,
 .op .ADD,
 .op .CALLDATALOAD,
 .push 0 0,
 .op .BYTE,
 .op (.Dup { idx := 1 }),
 .op .ISZERO,
 .push 2 1713,
 .op .JUMPI,
 .push 1 128,
 .push 2 1073,
 .op .JUMP,
 .op .JUMPDEST,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .push 1 1,
 .op .SHR,
 .op .OR,
 .op (.Dup { idx := 0 }),
 .push 1 2,
 .op .SHR,
 .op .OR,
 .op (.Dup { idx := 0 }),
 .push 1 4,
 .op .SHR,
 .op .OR,
 .push 1 1,
 .op .SHR,
 .push 1 1,
 .op .ADD,
 .push 2 2653,
 .op .JUMP,
 .op .JUMPDEST,
 .op (.Dup { idx := 0 }),
 .push 2 1024,
 .op .EQ,
 .push 2 948,
 .op .JUMPI,
 .push 2 948,
 .push 2 1536,
 .op (.Dup { idx := 2 }),
 .push 2 1536,
 .push 2 3533,
 .op .JUMP,
 .op .JUMPDEST,
 .push 1 32,
 .op (.Dup { idx := 1 }),
 .op .GT,
 .op (.Dup { idx := 2 }),
 .push 1 32,
 .op .XOR,
 .op .OR,
 .op (.Dup { idx := 3 }),
 .push 1 32,
 .op .XOR,
 .op .OR,
 .op .ISZERO,
 .push 1 43,
 .op .JUMPI,
 .push 2 145,
 .op .JUMP,
 .op .JUMPDEST,
 .op (.Dup { idx := 0 }),
 .op .ISZERO,
 .push 2 2423,
 .op .JUMPI,
 .op (.Dup { idx := 4 }),
 .op .CALLDATALOAD,
 .op (.Dup { idx := 2 }),
 .push 1 32,
 .op .SUB,
 .push 1 3,
 .op .SHL,
 .op .SHR,
 .push 1 1,
 .push 0 0,
 .op .MSTORE,
 .op (.Dup { idx := 0 }),
 .op .MSIZE,
 .op .MSTORE,
 .op (.Dup { idx := 6 }),
 .op .CALLDATALOAD,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 14 }),
 .op (.Dup { idx := 15 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MSIZE,
 .op .MSTORE,
 .op (.Dup { idx := 14 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MSIZE,
 .op .MSTORE,
 .op (.Dup { idx := 13 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MSIZE,
 .op .MSTORE,
 .op (.Dup { idx := 12 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MSIZE,
 .op .MSTORE,
 .op (.Dup { idx := 11 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MSIZE,
 .op .MSTORE,
 .op (.Dup { idx := 10 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MSIZE,
 .op .MSTORE,
 .op (.Dup { idx := 9 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MSIZE,
 .op .MSTORE,
 .op (.Dup { idx := 8 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MSIZE,
 .op .MSTORE,
 .op (.Dup { idx := 7 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MSIZE,
 .op .MSTORE,
 .op (.Dup { idx := 6 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MSIZE,
 .op .MSTORE,
 .op (.Dup { idx := 5 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MSIZE,
 .op .MSTORE,
 .op (.Dup { idx := 4 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MSIZE,
 .op .MSTORE,
 .op (.Dup { idx := 3 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MSIZE,
 .op .MSTORE,
 .op (.Dup { idx := 2 }),
 .op .MULMOD,
 .op .MSIZE,
 .op .MSTORE,
 .op .POP,
 .push 25 480,
 .op (.Dup { idx := 1 }),
 .push 1 247,
 .op .SHR,
 .op (.Dup { idx := 1 }),
 .op .AND,
 .op .MLOAD,
 .op (.Swap { idx := 1 }),
 .push 1 1,
 .op .SHL,
 .push 1 2,
 .op (.Swap { idx := 2 }),
 .op (.Dup { idx := 9 }),
 .op .CALLDATALOAD,
 .op (.Swap { idx := 0 }),
 .op .JUMPDEST,
 .op (.Dup { idx := 2 }),
 .push 1 4,
 .op .SHR,
 .push 2 544,
 .op .MSTORE,
 .op (.Dup { idx := 2 }),
 .push 2 576,
 .op .MSTORE,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Swap { idx := 14 }),
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .push 2 514,
 .op .MLOAD,
 .op (.Dup { idx := 15 }),
 .op .AND,
 .op .MLOAD,
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .push 2 546,
 .op .MLOAD,
 .op (.Dup { idx := 10 }),
 .op .AND,
 .op .MLOAD,
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .push 2 515,
 .op .MLOAD,
 .op (.Dup { idx := 5 }),
 .op .AND,
 .op .MLOAD,
 .op .MULMOD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Swap { idx := 14 }),
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .push 2 547,
 .op .MLOAD,
 .op (.Dup { idx := 15 }),
 .op .AND,
 .op .MLOAD,
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .push 2 516,
 .op .MLOAD,
 .op (.Dup { idx := 10 }),
 .op .AND,
 .op .MLOAD,
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .push 2 548,
 .op .MLOAD,
 .op (.Dup { idx := 5 }),
 .op .AND,
 .op .MLOAD,
 .op .MULMOD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Swap { idx := 14 }),
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .push 2 517,
 .op .MLOAD,
 .op (.Dup { idx := 15 }),
 .op .AND,
 .op .MLOAD,
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .push 2 549,
 .op .MLOAD,
 .op (.Dup { idx := 10 }),
 .op .AND,
 .op .MLOAD,
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .push 2 518,
 .op .MLOAD,
 .op (.Dup { idx := 5 }),
 .op .AND,
 .op .MLOAD,
 .op .MULMOD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Swap { idx := 14 }),
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .push 2 550,
 .op .MLOAD,
 .op (.Dup { idx := 15 }),
 .op .AND,
 .op .MLOAD,
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .push 2 519,
 .op .MLOAD,
 .op (.Dup { idx := 10 }),
 .op .AND,
 .op .MLOAD,
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .push 2 551,
 .op .MLOAD,
 .op (.Dup { idx := 5 }),
 .op .AND,
 .op .MLOAD,
 .op .MULMOD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Swap { idx := 14 }),
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .push 2 520,
 .op .MLOAD,
 .op (.Dup { idx := 15 }),
 .op .AND,
 .op .MLOAD,
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .push 2 552,
 .op .MLOAD,
 .op (.Dup { idx := 10 }),
 .op .AND,
 .op .MLOAD,
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .push 2 521,
 .op .MLOAD,
 .op (.Dup { idx := 5 }),
 .op .AND,
 .op .MLOAD,
 .op .MULMOD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Swap { idx := 14 }),
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .push 2 553,
 .op .MLOAD,
 .op (.Dup { idx := 15 }),
 .op .AND,
 .op .MLOAD,
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .push 2 522,
 .op .MLOAD,
 .op (.Dup { idx := 10 }),
 .op .AND,
 .op .MLOAD,
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .push 2 554,
 .op .MLOAD,
 .op (.Dup { idx := 5 }),
 .op .AND,
 .op .MLOAD,
 .op .MULMOD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Swap { idx := 14 }),
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .push 2 523,
 .op .MLOAD,
 .op (.Dup { idx := 15 }),
 .op .AND,
 .op .MLOAD,
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .push 2 555,
 .op .MLOAD,
 .op (.Dup { idx := 10 }),
 .op .AND,
 .op .MLOAD,
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .push 2 524,
 .op .MLOAD,
 .op (.Dup { idx := 5 }),
 .op .AND,
 .op .MLOAD,
 .op .MULMOD,
 .op (.Swap { idx := 1 }),
 .push 1 84,
 .op .SHL,
 .op (.Swap { idx := 1 }),
 .push 1 1,
 .op (.Dup { idx := 5 }),
 .op .SUB,
 .op (.Swap { idx := 4 }),
 .push 2 1941,
 .op .JUMPI,
 .push 0 0,
 .op .MSTORE,
 .push 1 32,
 .push 0 0,
 .op .RETURN,
 .op .JUMPDEST,
 .push 0 0,
 .push 0 0,
 .op .MSTORE,
 .push 1 32,
 .push 0 0,
 .op .RETURN,
 .op .JUMPDEST,
 .push 2 2688,
 .op .MLOAD,
 .push 2 1280,
 .push 2 1536,
 .op .MCOPY,
 .op (.Dup { idx := 1 }),
 .push 1 3,
 .op .LT,
 .op (.Dup { idx := 2 }),
 .push 1 7,
 .op .LT,
 .op (.Dup { idx := 3 }),
 .push 1 15,
 .op .LT,
 .op (.Dup { idx := 4 }),
 .push 1 31,
 .op .LT,
 .op .ADD,
 .op .ADD,
 .op .ADD,
 .push 2 914,
 .op .JUMP,
 .op .JUMPDEST,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 3 }),
 .op .EQ,
 .push 0 0,
 .op .MLOAD,
 .push 1 255,
 .op .SHR,
 .op .AND,
 .op .ISZERO,
 .push 2 2504,
 .op .JUMPI,
 .op (.Dup { idx := 0 }),
 .push 1 96,
 .push 2 256,
 .op .CALLDATACOPY,
 .push 2 2675,
 .push 2 512,
 .push 2 256,
 .push 2 1536,
 .push 2 3533,
 .op .JUMP,
 .op .JUMPDEST,
 .op (.Dup { idx := 2 }),
 .push 1 31,
 .op .ADD,
 .push 1 5,
 .op .SHR,
 .op (.Dup { idx := 3 }),
 .op (.Dup { idx := 1 }),
 .push 1 5,
 .op .SHL,
 .op .SUB,
 .push 1 3,
 .op .SHL,
 .push 1 96,
 .op .CALLDATALOAD,
 .op (.Swap { idx := 0 }),
 .op .SHR,
 .op (.Dup { idx := 2 }),
 .push 1 224,
 .op .ADD,
 .op .MSTORE,
 .push 1 1,
 .push 2 975,
 .op .JUMP,
 .op .JUMPDEST,
 .push 1 1,
 .op (.Dup { idx := 6 }),
 .op .SUB,
 .op .JUMPDEST,
 .op (.Dup { idx := 7 }),
 .push 1 1,
 .op (.Dup { idx := 4 }),
 .op (.Dup { idx := 4 }),
 .push 1 7,
 .op .SUB,
 .op .SHR,
 .op .AND,
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .push 1 1,
 .op .ADD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 8 }),
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op .MULMOD,
 .op (.Swap { idx := 5 }),
 .op .POP,
 .op (.Dup { idx := 7 }),
 .push 1 1,
 .op (.Dup { idx := 4 }),
 .op (.Dup { idx := 4 }),
 .push 1 6,
 .op .SUB,
 .op .SHR,
 .op .AND,
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .push 1 1,
 .op .ADD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 8 }),
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op .MULMOD,
 .op (.Swap { idx := 5 }),
 .op .POP,
 .op (.Dup { idx := 7 }),
 .push 1 1,
 .op (.Dup { idx := 4 }),
 .op (.Dup { idx := 4 }),
 .push 1 5,
 .op .SUB,
 .op .SHR,
 .op .AND,
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .push 1 1,
 .op .ADD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 8 }),
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op .MULMOD,
 .op (.Swap { idx := 5 }),
 .op .POP,
 .op (.Dup { idx := 7 }),
 .push 1 1,
 .op (.Dup { idx := 4 }),
 .op (.Dup { idx := 4 }),
 .push 1 4,
 .op .SUB,
 .op .SHR,
 .op .AND,
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .push 1 1,
 .op .ADD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 8 }),
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op .MULMOD,
 .op (.Swap { idx := 5 }),
 .op .POP,
 .op (.Swap { idx := 0 }),
 .push 1 4,
 .op .ADD,
 .op (.Swap { idx := 0 }),
 .op (.Dup { idx := 1 }),
 .push 1 8,
 .op .GT,
 .push 2 2542,
 .op .JUMPI,
 .op (.Swap { idx := 0 }),
 .op .POP,
 .push 0 0,
 .op (.Swap { idx := 0 }),
 .op .POP,
 .push 2 231,
 .op .JUMP,
 .op .JUMPDEST,
 .op (.Dup { idx := 1 }),
 .op .ISZERO,
 .push 2 1073,
 .op .JUMPI,
 .push 2 2688,
 .op .MLOAD,
 .push 2 512,
 .push 2 256,
 .op .MCOPY,
 .push 2 1114,
 .op .JUMP,
 .op .JUMPDEST,
 .op (.Dup { idx := 3 }),
 .push 1 3,
 .op .EQ,
 .push 2 2712,
 .op .JUMPI,
 .op (.Dup { idx := 3 }),
 .push 1 1,
 .op .XOR,
 .push 2 2778,
 .op .JUMPI,
 .push 2 2816,
 .op .MLOAD,
 .op .CALLDATALOAD,
 .push 0 0,
 .op .BYTE,
 .push 1 3,
 .op .XOR,
 .push 2 2778,
 .op .JUMPI,
 .push 1 1,
 .push 2 2732,
 .op .JUMP,
 .op .JUMPDEST,
 .push 2 2816,
 .op .MLOAD,
 .op .CALLDATALOAD,
 .push 1 232,
 .op .SHR,
 .push 3 65537,
 .op .XOR,
 .push 2 2778,
 .op .JUMPI,
 .push 1 16,
 .op .JUMPDEST,
 .op (.Dup { idx := 0 }),
 .push 2 2624,
 .op .MSTORE,
 .push 2 2753,
 .push 2 512,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .push 2 4737,
 .push 2 3537,
 .op .JUMP,
 .op .JUMPDEST,
 .push 0 0,
 .op .NOT,
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .push 2 2732,
 .op .JUMPI,
 .op .JUMPDEST,
 .op .POP,
 .push 2 1160,
 .push 2 256,
 .op (.Dup { idx := 0 }),
 .push 2 512,
 .push 2 3533,
 .op .JUMP,
 .op .JUMPDEST,
 .op (.Dup { idx := 0 }),
 .push 2 1024,
 .push 2 256,
 .op .MCOPY,
 .push 0 0,
 .push 2 1061,
 .op .JUMP,
 .op .JUMPDEST,
 .push 2 2688,
 .op .MLOAD,
 .push 1 128,
 .op .LT,
 .op (.Dup { idx := 0 }),
 .push 1 8,
 .op (.Swap { idx := 0 }),
 .op .SHL,
 .op .JUMPDEST,
 .push 2 2816,
 .op (.Dup { idx := 3 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .push 2 1487,
 .op .JUMP,
 .op .JUMPDEST,
 .push 0 0,
 .op .NOT,
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .push 2 2805,
 .op .JUMPI,
 .op .POP,
 .push 1 5,
 .op .SUB,
 .push 2 1647,
 .op .JUMP,
 .op .JUMPDEST,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 3 }),
 .op .EQ,
 .push 0 0,
 .op .MLOAD,
 .push 1 255,
 .op .SHR,
 .op .AND,
 .op .ISZERO,
 .push 2 2877,
 .op .JUMPI,
 .op (.Dup { idx := 0 }),
 .push 1 96,
 .push 2 256,
 .op .CALLDATACOPY,
 .op (.Dup { idx := 0 }),
 .push 1 96,
 .push 2 2112,
 .op .CALLDATACOPY,
 .push 0 0,
 .push 2 2080,
 .op .MSTORE,
 .push 2 2894,
 .push 2 512,
 .push 2 4316,
 .op .JUMP,
 .op .JUMPDEST,
 .push 1 1,
 .push 2 1024,
 .op .MSTORE,
 .push 2 892,
 .push 2 1024,
 .push 2 1670,
 .op .JUMP,
 .op .JUMPDEST,
 .push 1 1,
 .push 2 2752,
 .op .MLOAD,
 .op .JUMPDEST,
 .op (.Dup { idx := 0 }),
 .op .MLOAD,
 .op .NOT,
 .op (.Dup { idx := 2 }),
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .op (.Swap { idx := 2 }),
 .op .GT,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .push 2 1280,
 .op .ADD,
 .op .MSTORE,
 .op (.Dup { idx := 0 }),
 .push 1 31,
 .op .NOT,
 .op .ADD,
 .op (.Swap { idx := 0 }),
 .push 2 2901,
 .op .JUMPI,
 .op .JUMPDEST,
 .op .POP,
 .op .POP,
 .push 0 0,
 .op .MLOAD,
 .op (.Dup { idx := 0 }),
 .push 0 0,
 .op .SUB,
 .op (.Dup { idx := 1 }),
 .op .AND,
 .op (.Dup { idx := 0 }),
 .push 2 1536,
 .op .MSTORE,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .DIV,
 .op (.Dup { idx := 0 }),
 .push 2 1568,
 .op .MSTORE,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 0 }),
 .push 0 0,
 .op .SUB,
 .op .DIV,
 .push 1 1,
 .op .ADD,
 .push 2 1600,
 .op .MSTORE,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .push 0 0,
 .op .SUB,
 .op .MOD,
 .push 2 1632,
 .op .MSTORE,
 .op (.Dup { idx := 0 }),
 .push 1 3,
 .op .MUL,
 .push 1 2,
 .op .XOR,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .push 1 2,
 .op .SUB,
 .op .MUL,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .push 1 2,
 .op .SUB,
 .op .MUL,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .push 1 2,
 .op .SUB,
 .op .MUL,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .push 1 2,
 .op .SUB,
 .op .MUL,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .push 1 2,
 .op .SUB,
 .op .MUL,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .push 1 2,
 .op .SUB,
 .op .MUL,
 .push 2 1664,
 .op .MSTORE,
 .op .POP,
 .op .POP,
 .op .POP,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 0 }),
 .push 0 0,
 .op .SUB,
 .push 1 3,
 .op .AND,
 .push 1 39,
 .op .MUL,
 .push 2 3164,
 .op .ADD,
 .push 2 1698,
 .op .MSTORE,
 .op .JUMPDEST,
 .op (.Dup { idx := 0 }),
 .op .ISZERO,
 .push 2 3516,
 .op .JUMPI,
 .op (.Dup { idx := 1 }),
 .push 2 512,
 .push 2 2080,
 .op .MCOPY,
 .push 0 0,
 .push 2 2784,
 .op .MLOAD,
 .op .MSTORE,
 .push 2 512,
 .op .MLOAD,
 .push 2 1536,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op .DIV,
 .op (.Swap { idx := 0 }),
 .op .JUMPDEST,
 .op .JUMPDEST,
 .push 2 1600,
 .op .MLOAD,
 .op .MUL,
 .push 2 544,
 .op .MLOAD,
 .push 2 1536,
 .op .MLOAD,
 .op (.Swap { idx := 0 }),
 .op .DIV,
 .op .ADD,
 .push 2 1568,
 .op .MLOAD,
 .op (.Dup { idx := 0 }),
 .push 2 1632,
 .op .MLOAD,
 .op (.Dup { idx := 4 }),
 .op .MULMOD,
 .op (.Dup { idx := 2 }),
 .op .ADDMOD,
 .op (.Swap { idx := 0 }),
 .op .SUB,
 .push 2 1664,
 .op .MLOAD,
 .op .MUL,
 .op (.Dup { idx := 0 }),
 .push 0 0,
 .op .MLOAD,
 .op .MUL,
 .push 2 544,
 .op .MLOAD,
 .op .SUB,
 .push 1 32,
 .op .MLOAD,
 .push 1 128,
 .op .SHR,
 .op (.Dup { idx := 2 }),
 .push 1 128,
 .op .SHR,
 .op .MUL,
 .op .GT,
 .op (.Swap { idx := 0 }),
 .op .SUB,
 .op (.Swap { idx := 0 }),
 .push 2 1568,
 .op .MLOAD,
 .op .GT,
 .op .ISZERO,
 .push 0 0,
 .op .SUB,
 .op .OR,
 .push 0 0,
 .push 1 31,
 .op .NOT,
 .push 2 2784,
 .op .MLOAD,
 .push 0 0,
 .op .NOT,
 .op (.Swap { idx := 0 }),
 .push 2 1698,
 .op .MLOAD,
 .op .JUMP,
 .op .JUMPDEST,
 .push 2 832,
 .op (.Dup { idx := 1 }),
 .op .SUB,
 .op .MLOAD,
 .op (.Dup { idx := 2 }),
 .op (.Dup { idx := 6 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 7 }),
 .op .MULMOD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op .LT,
 .op .SUB,
 .op (.Dup { idx := 5 }),
 .op (.Dup { idx := 2 }),
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .op (.Swap { idx := 6 }),
 .op .GT,
 .op .SUB,
 .op .SUB,
 .op (.Dup { idx := 4 }),
 .op (.Dup { idx := 2 }),
 .op .MLOAD,
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .op (.Swap { idx := 5 }),
 .op .GT,
 .op .ADD,
 .op (.Swap { idx := 3 }),
 .op (.Dup { idx := 1 }),
 .op .MSTORE,
 .op (.Dup { idx := 2 }),
 .op .ADD,
 .op .JUMPDEST,
 .push 2 832,
 .op (.Dup { idx := 1 }),
 .op .SUB,
 .op .MLOAD,
 .op (.Dup { idx := 2 }),
 .op (.Dup { idx := 6 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 7 }),
 .op .MULMOD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op .LT,
 .op .SUB,
 .op (.Dup { idx := 5 }),
 .op (.Dup { idx := 2 }),
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .op (.Swap { idx := 6 }),
 .op .GT,
 .op .SUB,
 .op .SUB,
 .op (.Dup { idx := 4 }),
 .op (.Dup { idx := 2 }),
 .op .MLOAD,
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .op (.Swap { idx := 5 }),
 .op .GT,
 .op .ADD,
 .op (.Swap { idx := 3 }),
 .op (.Dup { idx := 1 }),
 .op .MSTORE,
 .op (.Dup { idx := 2 }),
 .op .ADD,
 .op .JUMPDEST,
 .push 2 832,
 .op (.Dup { idx := 1 }),
 .op .SUB,
 .op .MLOAD,
 .op (.Dup { idx := 2 }),
 .op (.Dup { idx := 6 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 7 }),
 .op .MULMOD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op .LT,
 .op .SUB,
 .op (.Dup { idx := 5 }),
 .op (.Dup { idx := 2 }),
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .op (.Swap { idx := 6 }),
 .op .GT,
 .op .SUB,
 .op .SUB,
 .op (.Dup { idx := 4 }),
 .op (.Dup { idx := 2 }),
 .op .MLOAD,
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .op (.Swap { idx := 5 }),
 .op .GT,
 .op .ADD,
 .op (.Swap { idx := 3 }),
 .op (.Dup { idx := 1 }),
 .op .MSTORE,
 .op (.Dup { idx := 2 }),
 .op .ADD,
 .op .JUMPDEST,
 .push 2 832,
 .op (.Dup { idx := 1 }),
 .op .SUB,
 .op .MLOAD,
 .op (.Dup { idx := 2 }),
 .op (.Dup { idx := 6 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 7 }),
 .op .MULMOD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op .LT,
 .op .SUB,
 .op (.Dup { idx := 5 }),
 .op (.Dup { idx := 2 }),
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .op (.Swap { idx := 6 }),
 .op .GT,
 .op .SUB,
 .op .SUB,
 .op (.Dup { idx := 4 }),
 .op (.Dup { idx := 2 }),
 .op .MLOAD,
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .op (.Swap { idx := 5 }),
 .op .GT,
 .op .ADD,
 .op (.Swap { idx := 3 }),
 .op (.Dup { idx := 1 }),
 .op .MSTORE,
 .op (.Dup { idx := 2 }),
 .op .ADD,
 .push 2 2080,
 .op (.Dup { idx := 1 }),
 .op .GT,
 .push 2 3164,
 .op .JUMPI,
 .op .POP,
 .op .POP,
 .op .POP,
 .push 2 2080,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .op (.Swap { idx := 1 }),
 .op .GT,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 3 }),
 .op .GT,
 .op .GT,
 .op (.Swap { idx := 1 }),
 .op (.Swap { idx := 0 }),
 .op .SUB,
 .op (.Dup { idx := 0 }),
 .push 2 2080,
 .op .MSTORE,
 .op (.Dup { idx := 1 }),
 .op .OR,
 .push 2 3372,
 .op .JUMPI,
 .op .JUMPDEST,
 .op .NOT,
 .op .ADD,
 .push 2 3045,
 .push 2 512,
 .push 2 4316,
 .op .JUMP,
 .op .JUMPDEST,
 .op .ISZERO,
 .push 2 3457,
 .op .JUMPI,
 .op .JUMPDEST,
 .push 0 0,
 .push 2 2784,
 .op .MLOAD,
 .op .JUMPDEST,
 .op (.Dup { idx := 0 }),
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .push 2 2112,
 .op (.Swap { idx := 0 }),
 .op .SUB,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .GT,
 .op (.Swap { idx := 1 }),
 .op .POP,
 .op (.Dup { idx := 3 }),
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 4 }),
 .op .GT,
 .op (.Swap { idx := 3 }),
 .op .POP,
 .op (.Dup { idx := 2 }),
 .op .MSTORE,
 .op (.Swap { idx := 0 }),
 .op (.Swap { idx := 1 }),
 .op .OR,
 .op (.Swap { idx := 0 }),
 .push 1 31,
 .op .NOT,
 .op .ADD,
 .push 2 2111,
 .op (.Dup { idx := 1 }),
 .op .GT,
 .push 2 3384,
 .op .JUMPI,
 .op .POP,
 .push 2 2080,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .push 2 2080,
 .op .MSTORE,
 .op .LT,
 .op .ISZERO,
 .push 2 3378,
 .op .JUMPI,
 .op .JUMPDEST,
 .push 2 2080,
 .op .MLOAD,
 .op (.Dup { idx := 0 }),
 .op .ISZERO,
 .push 2 3359,
 .op .JUMPI,
 .op .POP,
 .op .JUMPDEST,
 .push 0 0,
 .push 2 2784,
 .op .MLOAD,
 .op .JUMPDEST,
 .op (.Dup { idx := 0 }),
 .op .MLOAD,
 .push 2 2112,
 .op (.Dup { idx := 2 }),
 .op .SUB,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op .GT,
 .op (.Swap { idx := 1 }),
 .op .SUB,
 .op (.Dup { idx := 3 }),
 .op (.Dup { idx := 1 }),
 .op .LT,
 .op (.Swap { idx := 0 }),
 .op (.Dup { idx := 4 }),
 .op (.Swap { idx := 0 }),
 .op .SUB,
 .op (.Dup { idx := 3 }),
 .op .MSTORE,
 .op .OR,
 .op (.Swap { idx := 1 }),
 .op .POP,
 .push 1 31,
 .op .NOT,
 .op .ADD,
 .push 2 2111,
 .op (.Dup { idx := 1 }),
 .op .GT,
 .push 2 3463,
 .op .JUMPI,
 .op .POP,
 .push 2 2080,
 .op .MLOAD,
 .op .SUB,
 .push 2 2080,
 .op .MSTORE,
 .push 2 3445,
 .op .JUMP,
 .op .JUMPDEST,
 .op .POP,
 .push 2 2688,
 .op .MLOAD,
 .push 2 1280,
 .push 2 1024,
 .op .MCOPY,
 .push 2 2675,
 .op .JUMP,
 .op .JUMPDEST,
 .push 2 3698,
 .op .JUMPDEST,
 .push 2 2688,
 .op .MLOAD,
 .op (.Dup { idx := 0 }),
 .push 1 128,
 .op .EQ,
 .op (.Swap { idx := 0 }),
 .push 2 256,
 .op .EQ,
 .op .OR,
 .push 2 3561,
 .op .JUMPI,
 .op .POP,
 .push 2 1215,
 .op .JUMP,
 .op .JUMPDEST,
 .push 1 96,
 .op .MLOAD,
 .push 2 2784,
 .op .MLOAD,
 .push 2 2752,
 .op .MLOAD,
 .op .MLOAD,
 .push 2 2720,
 .op .MLOAD,
 .push 2 2752,
 .op .MLOAD,
 .op (.Dup { idx := 6 }),
 .op .ADD,
 .push 1 32,
 .op .MLOAD,
 .push 1 31,
 .op .NOT,
 .push 2 2688,
 .op .MLOAD,
 .push 1 128,
 .op .EQ,
 .push 1 148,
 .op .MUL,
 .push 2 3728,
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .push 2 292,
 .op .ADD,
 .op (.Swap { idx := 3 }),
 .op (.Swap { idx := 10 }),
 .push 0 0,
 .op .NOT,
 .op (.Swap { idx := 3 }),
 .op (.Swap { idx := 10 }),
 .push 1 64,
 .op .MLOAD,
 .op (.Swap { idx := 10 }),
 .push 2 2688,
 .op .MLOAD,
 .op (.Dup { idx := 0 }),
 .op (.Swap { idx := 2 }),
 .push 2 2368,
 .op .MCOPY,
 .op (.Dup { idx := 1 }),
 .push 1 64,
 .op .ADD,
 .op .CALLDATASIZE,
 .push 2 2048,
 .op .CALLDATACOPY,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 4 }),
 .op .ADD,
 .op (.Swap { idx := 1 }),
 .op (.Swap { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .ADD,
 .op (.Dup { idx := 1 }),
 .op .JUMP,
 .op .JUMPDEST,
 .op (.Dup { idx := 9 }),
 .push 2 256,
 .op .ADD,
 .op (.Swap { idx := 13 }),
 .op .POP,
 .push 2 1856,
 .op (.Dup { idx := 10 }),
 .op .SUB,
 .op (.Swap { idx := 0 }),
 .op .POP,
 .push 2 3698,
 .op (.Swap { idx := 1 }),
 .op .POP,
 .push 1 224,
 .op (.Swap { idx := 2 }),
 .op .POP,
 .push 2 292,
 .op (.Dup { idx := 7 }),
 .op .SUB,
 .op (.Swap { idx := 3 }),
 .op .POP,
 .push 2 256,
 .op (.Swap { idx := 14 }),
 .op .POP,
 .push 2 1158,
 .op (.Swap { idx := 15 }),
 .op .POP,
 .push 2 2016,
 .op (.Dup { idx := 10 }),
 .op .SUB,
 .op .CALLDATASIZE,
 .push 2 2048,
 .op .CALLDATACOPY,
 .op .JUMPDEST,
 .op (.Dup { idx := 0 }),
 .op .MLOAD,
 .op (.Dup { idx := 14 }),
 .op .MLOAD,
 .op (.Dup { idx := 7 }),
 .op (.Dup { idx := 2 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 3 }),
 .op .MULMOD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op .LT,
 .op .SUB,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 13 }),
 .op .MLOAD,
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 14 }),
 .op .MSTORE,
 .op (.Dup { idx := 2 }),
 .op .GT,
 .op .SUB,
 .op .SUB,
 .op (.Dup { idx := 5 }),
 .op .JUMP,
 .op .JUMPDEST,
 .op .JUMPDEST,
 .push 2 2560,
 .op .MLOAD,
 .op (.Dup { idx := 8 }),
 .op (.Dup { idx := 3 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 4 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .GT,
 .op .SUB,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 3 }),
 .op .ADD,
 .push 2 2304,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .push 2 2304,
 .op .MSTORE,
 .op (.Dup { idx := 1 }),
 .op .GT,
 .op (.Swap { idx := 3 }),
 .op .GT,
 .op .SUB,
 .op .SUB,
 .op .ADD,
 .op .JUMPDEST,
 .push 2 2528,
 .op .MLOAD,
 .op (.Dup { idx := 8 }),
 .op (.Dup { idx := 3 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 4 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .GT,
 .op .SUB,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 3 }),
 .op .ADD,
 .push 2 2272,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .push 2 2272,
 .op .MSTORE,
 .op (.Dup { idx := 1 }),
 .op .GT,
 .op (.Swap { idx := 3 }),
 .op .GT,
 .op .SUB,
 .op .SUB,
 .op .ADD,
 .op .JUMPDEST,
 .push 2 2496,
 .op .MLOAD,
 .op (.Dup { idx := 8 }),
 .op (.Dup { idx := 3 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 4 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .GT,
 .op .SUB,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 3 }),
 .op .ADD,
 .push 2 2240,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .push 2 2240,
 .op .MSTORE,
 .op (.Dup { idx := 1 }),
 .op .GT,
 .op (.Swap { idx := 3 }),
 .op .GT,
 .op .SUB,
 .op .SUB,
 .op .ADD,
 .op .JUMPDEST,
 .push 2 2464,
 .op .MLOAD,
 .op (.Dup { idx := 8 }),
 .op (.Dup { idx := 3 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 4 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .GT,
 .op .SUB,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 3 }),
 .op .ADD,
 .push 2 2208,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .push 2 2208,
 .op .MSTORE,
 .op (.Dup { idx := 1 }),
 .op .GT,
 .op (.Swap { idx := 3 }),
 .op .GT,
 .op .SUB,
 .op .SUB,
 .op .ADD,
 .op .JUMPDEST,
 .push 2 2432,
 .op .MLOAD,
 .op (.Dup { idx := 8 }),
 .op (.Dup { idx := 3 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 4 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .GT,
 .op .SUB,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 3 }),
 .op .ADD,
 .push 2 2176,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .push 2 2176,
 .op .MSTORE,
 .op (.Dup { idx := 1 }),
 .op .GT,
 .op (.Swap { idx := 3 }),
 .op .GT,
 .op .SUB,
 .op .SUB,
 .op .ADD,
 .op .JUMPDEST,
 .push 2 2400,
 .op .MLOAD,
 .op (.Dup { idx := 8 }),
 .op (.Dup { idx := 3 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 4 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .GT,
 .op .SUB,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 3 }),
 .op .ADD,
 .push 2 2144,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .push 2 2144,
 .op .MSTORE,
 .op (.Dup { idx := 1 }),
 .op .GT,
 .op (.Swap { idx := 3 }),
 .op .GT,
 .op .SUB,
 .op .SUB,
 .op .ADD,
 .op .JUMPDEST,
 .push 2 2368,
 .op .MLOAD,
 .op (.Dup { idx := 8 }),
 .op (.Dup { idx := 3 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 4 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .GT,
 .op .SUB,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 3 }),
 .op .ADD,
 .push 2 2112,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .push 2 2112,
 .op .MSTORE,
 .op (.Dup { idx := 1 }),
 .op .GT,
 .op (.Swap { idx := 3 }),
 .op .GT,
 .op .SUB,
 .op .SUB,
 .op .ADD,
 .op .JUMPDEST,
 .op (.Dup { idx := 0 }),
 .push 2 2080,
 .op .MLOAD,
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .push 2 2080,
 .op .MSTORE,
 .op .LT,
 .op (.Swap { idx := 0 }),
 .op .POP,
 .op (.Dup { idx := 10 }),
 .op .MLOAD,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 10 }),
 .op .MUL,
 .op (.Swap { idx := 0 }),
 .op (.Dup { idx := 8 }),
 .op (.Dup { idx := 2 }),
 .op (.Dup { idx := 13 }),
 .op .MULMOD,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .op (.Swap { idx := 1 }),
 .op .GT,
 .op .ADD,
 .op (.Dup { idx := 9 }),
 .op .JUMP,
 .op .JUMPDEST,
 .push 10 192,
 .op .MLOAD,
 .op (.Dup { idx := 9 }),
 .op (.Dup { idx := 3 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 4 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .GT,
 .op .SUB,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 3 }),
 .op .ADD,
 .push 2 2304,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .push 2 2336,
 .op .MSTORE,
 .op (.Dup { idx := 1 }),
 .op .GT,
 .op (.Swap { idx := 3 }),
 .op .GT,
 .op .SUB,
 .op .SUB,
 .op .ADD,
 .push 1 160,
 .op .MLOAD,
 .op (.Dup { idx := 9 }),
 .op (.Dup { idx := 3 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 4 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .GT,
 .op .SUB,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 3 }),
 .op .ADD,
 .push 2 2272,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .push 2 2304,
 .op .MSTORE,
 .op (.Dup { idx := 1 }),
 .op .GT,
 .op (.Swap { idx := 3 }),
 .op .GT,
 .op .SUB,
 .op .SUB,
 .op .ADD,
 .push 1 128,
 .op .MLOAD,
 .op (.Dup { idx := 9 }),
 .op (.Dup { idx := 3 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 4 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .GT,
 .op .SUB,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 3 }),
 .op .ADD,
 .push 2 2240,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .push 2 2272,
 .op .MSTORE,
 .op (.Dup { idx := 1 }),
 .op .GT,
 .op (.Swap { idx := 3 }),
 .op .GT,
 .op .SUB,
 .op .SUB,
 .op .ADD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 14 }),
 .op .MUL,
 .op (.Dup { idx := 9 }),
 .op (.Dup { idx := 15 }),
 .op (.Dup { idx := 4 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .GT,
 .op .SUB,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 3 }),
 .op .ADD,
 .push 3 2208,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .push 2 2240,
 .op .MSTORE,
 .op (.Dup { idx := 1 }),
 .op .GT,
 .op (.Swap { idx := 3 }),
 .op .GT,
 .op .SUB,
 .op .SUB,
 .op .ADD,
 .op .JUMPDEST,
 .op (.Dup { idx := 14 }),
 .op (.Dup { idx := 9 }),
 .op (.Dup { idx := 3 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 4 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .GT,
 .op .SUB,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 3 }),
 .op .ADD,
 .push 2 2176,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .push 2 2208,
 .op .MSTORE,
 .op (.Dup { idx := 1 }),
 .op .GT,
 .op (.Swap { idx := 3 }),
 .op .GT,
 .op .SUB,
 .op .SUB,
 .op .ADD,
 .op (.Dup { idx := 15 }),
 .op (.Dup { idx := 9 }),
 .op (.Dup { idx := 3 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 4 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .GT,
 .op .SUB,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 3 }),
 .op .ADD,
 .push 2 2144,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .push 2 2176,
 .op .MSTORE,
 .op (.Dup { idx := 1 }),
 .op .GT,
 .op (.Swap { idx := 3 }),
 .op .GT,
 .op .SUB,
 .op .SUB,
 .op .ADD,
 .op (.Dup { idx := 8 }),
 .push 0 0,
 .op .MLOAD,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 4 }),
 .op .MUL,
 .op (.Swap { idx := 3 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 3 }),
 .op .GT,
 .op .SUB,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 3 }),
 .op .ADD,
 .push 2 2112,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .push 2 2144,
 .op .MSTORE,
 .op (.Dup { idx := 1 }),
 .op .GT,
 .op (.Swap { idx := 2 }),
 .op .GT,
 .op .SUB,
 .op .ADD,
 .op .SUB,
 .op (.Dup { idx := 0 }),
 .push 2 2080,
 .op .MLOAD,
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .push 2 2112,
 .op .MSTORE,
 .op .LT,
 .op .ADD,
 .push 2 2080,
 .op .MSTORE,
 .op (.Dup { idx := 4 }),
 .op .ADD,
 .op (.Dup { idx := 2 }),
 .op (.Dup { idx := 1 }),
 .op .GT,
 .op (.Dup { idx := 2 }),
 .op .JUMPI,
 .op (.Dup { idx := 1 }),
 .push 2 4427,
 .op .EQ,
 .push 2 4358,
 .op .JUMPI,
 .op .JUMPDEST,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .JUMPDEST,
 .push 0 0,
 .op .MLOAD,
 .push 2 2112,
 .op .MLOAD,
 .op .LT,
 .push 2 2080,
 .op .MLOAD,
 .op .LT,
 .push 2 4713,
 .op .JUMPI,
 .push 2 4477,
 .op .JUMP,
 .op .JUMPDEST,
 .push 2 2208,
 .op .MLOAD,
 .push 1 96,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op .GT,
 .op (.Swap { idx := 1 }),
 .op .SUB,
 .push 2 1888,
 .op .MSTORE,
 .push 2 4630,
 .op .JUMP,
 .op .JUMPDEST,
 .push 2 4392,
 .push 2 2368,
 .push 2 2624,
 .op .MLOAD,
 .op (.Dup { idx := 8 }),
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .push 2 2624,
 .op .MSTORE,
 .push 2 4316,
 .op .JUMPI,
 .op .POP,
 .op .POP,
 .push 2 3647,
 .push 2 2368,
 .push 2 4316,
 .op .JUMP,
 .op .JUMPDEST,
 .op (.Dup { idx := 6 }),
 .push 2 4168,
 .op .EQ,
 .push 2 4770,
 .op .JUMPI,
 .push 2 2688,
 .op .MLOAD,
 .op (.Dup { idx := 0 }),
 .push 1 64,
 .op .ADD,
 .op .CALLDATASIZE,
 .push 2 2048,
 .op .CALLDATACOPY,
 .op .ADD,
 .push 2 292,
 .op (.Dup { idx := 7 }),
 .op .SUB,
 .op (.Swap { idx := 3 }),
 .op .POP,
 .push 2 5273,
 .op .JUMP,
 .op .JUMPDEST,
 .op (.Dup { idx := 0 }),
 .op .MLOAD,
 .op (.Dup { idx := 0 }),
 .op (.Swap { idx := 14 }),
 .push 0 0,
 .op .SGT,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 8 }),
 .op (.Dup { idx := 2 }),
 .op (.Dup { idx := 2 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 5 }),
 .op .MUL,
 .op (.Swap { idx := 4 }),
 .op .LT,
 .op (.Swap { idx := 2 }),
 .op .MULMOD,
 .op .SUB,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op .LT,
 .op .SUB,
 .push 2 256,
 .op (.Dup { idx := 4 }),
 .op .SUB,
 .op (.Dup { idx := 0 }),
 .op .MLOAD,
 .op (.Dup { idx := 3 }),
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .op (.Swap { idx := 1 }),
 .op .MSTORE,
 .op (.Dup { idx := 2 }),
 .op .GT,
 .op .SUB,
 .op .SUB,
 .push 1 37,
 .op (.Dup { idx := 6 }),
 .op .ADD,
 .op (.Swap { idx := 5 }),
 .op .JUMP,
 .op .JUMPDEST,
 .push 2 2688,
 .op .MLOAD,
 .push 2 256,
 .op .EQ,
 .push 2 4521,
 .op .JUMPI,
 .push 2 2688,
 .op .MLOAD,
 .push 1 128,
 .op .EQ,
 .push 2 4337,
 .op .JUMPI,
 .push 2 2784,
 .op .MLOAD,
 .push 2 2752,
 .op .MLOAD,
 .op (.Dup { idx := 0 }),
 .push 2 1792,
 .op .ADD,
 .op (.Swap { idx := 0 }),
 .push 0 0,
 .op (.Swap { idx := 2 }),
 .push 2 1574,
 .op .JUMP,
 .op .JUMPDEST,
 .push 2 2336,
 .op .MLOAD,
 .push 1 224,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op .GT,
 .op (.Swap { idx := 1 }),
 .op .SUB,
 .push 2 2016,
 .op .MSTORE,
 .push 2 2304,
 .op .MLOAD,
 .push 1 192,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op .GT,
 .op (.Swap { idx := 1 }),
 .op .SUB,
 .op (.Dup { idx := 2 }),
 .op (.Dup { idx := 1 }),
 .op .SUB,
 .op (.Swap { idx := 2 }),
 .op .GT,
 .op .OR,
 .op (.Swap { idx := 0 }),
 .push 2 1984,
 .op .MSTORE,
 .push 2 2272,
 .op .MLOAD,
 .push 1 160,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op .GT,
 .op (.Swap { idx := 1 }),
 .op .SUB,
 .op (.Dup { idx := 2 }),
 .op (.Dup { idx := 1 }),
 .op .SUB,
 .op (.Swap { idx := 2 }),
 .op .GT,
 .op .OR,
 .op (.Swap { idx := 0 }),
 .push 2 1952,
 .op .MSTORE,
 .push 2 2240,
 .op .MLOAD,
 .push 1 128,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op .GT,
 .op (.Swap { idx := 1 }),
 .op .SUB,
 .op (.Dup { idx := 2 }),
 .op (.Dup { idx := 1 }),
 .op .SUB,
 .op (.Swap { idx := 2 }),
 .op .GT,
 .op .OR,
 .op (.Swap { idx := 0 }),
 .push 2 1920,
 .op .MSTORE,
 .push 2 2208,
 .op .MLOAD,
 .push 1 96,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op .GT,
 .op (.Swap { idx := 1 }),
 .op .SUB,
 .op (.Dup { idx := 2 }),
 .op (.Dup { idx := 1 }),
 .op .SUB,
 .op (.Swap { idx := 2 }),
 .op .GT,
 .op .OR,
 .op (.Swap { idx := 0 }),
 .push 2 1888,
 .op .MSTORE,
 .op .JUMPDEST,
 .push 2 2176,
 .op .MLOAD,
 .push 1 64,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op .GT,
 .op (.Swap { idx := 1 }),
 .op .SUB,
 .op (.Dup { idx := 2 }),
 .op (.Dup { idx := 1 }),
 .op .SUB,
 .op (.Swap { idx := 2 }),
 .op .GT,
 .op .OR,
 .op (.Swap { idx := 0 }),
 .push 2 1856,
 .op .MSTORE,
 .push 2 2144,
 .op .MLOAD,
 .push 1 32,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op .GT,
 .op (.Swap { idx := 1 }),
 .op .SUB,
 .op (.Dup { idx := 2 }),
 .op (.Dup { idx := 1 }),
 .op .SUB,
 .op (.Swap { idx := 2 }),
 .op .GT,
 .op .OR,
 .op (.Swap { idx := 0 }),
 .push 2 1824,
 .op .MSTORE,
 .push 2 2112,
 .op .MLOAD,
 .push 0 0,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op .GT,
 .op (.Swap { idx := 1 }),
 .op .SUB,
 .op (.Dup { idx := 2 }),
 .op (.Dup { idx := 1 }),
 .op .SUB,
 .op (.Swap { idx := 2 }),
 .op .GT,
 .op .OR,
 .op (.Swap { idx := 0 }),
 .push 2 1792,
 .op .MSTORE,
 .op .ISZERO,
 .push 2 2080,
 .op .MLOAD,
 .op .OR,
 .push 2 319,
 .op .NOT,
 .push 2 4724,
 .op .JUMP,
 .op .JUMPDEST,
 .push 2 2112,
 .push 2 2688,
 .op .MLOAD,
 .op (.Swap { idx := 1 }),
 .op .MCOPY,
 .op .JUMP,
 .op .JUMPDEST,
 .op .MUL,
 .push 2 2112,
 .op .ADD,
 .push 2 2688,
 .op .MLOAD,
 .op (.Swap { idx := 1 }),
 .op .MCOPY,
 .op .JUMP,
 .op .JUMPDEST,
 .push 2 4427,
 .op (.Swap { idx := 1 }),
 .op .POP,
 .push 2 2336,
 .op (.Swap { idx := 2 }),
 .op .POP,
 .push 7 1856,
 .op .ADD,
 .op (.Dup { idx := 6 }),
 .push 2 4168,
 .op .EQ,
 .push 2 4770,
 .op .JUMPI,
 .push 2 5273,
 .op .JUMP,
 .op .JUMPDEST,
 .op (.Dup { idx := 7 }),
 .push 0 0,
 .op .MLOAD,
 .op (.Dup { idx := 14 }),
 .op (.Dup { idx := 14 }),
 .op (.Dup { idx := 12 }),
 .op (.Dup { idx := 10 }),
 .push 2 2464,
 .op .MLOAD,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Swap { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 0 }),
 .op .MUL,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .GT,
 .op (.Dup { idx := 2 }),
 .op (.Swap { idx := 1 }),
 .op .SUB,
 .op .SUB,
 .push 2 2432,
 .op .MLOAD,
 .op (.Dup { idx := 4 }),
 .op (.Dup { idx := 4 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 5 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .GT,
 .op .SUB,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 3 }),
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .op (.Swap { idx := 3 }),
 .op .GT,
 .op .SUB,
 .op .SUB,
 .push 2 2400,
 .op .MLOAD,
 .op (.Dup { idx := 5 }),
 .op (.Dup { idx := 5 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 6 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .GT,
 .op .SUB,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 3 }),
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .op (.Swap { idx := 3 }),
 .op .GT,
 .op .SUB,
 .op .SUB,
 .push 2 2368,
 .op .MLOAD,
 .op (.Dup { idx := 6 }),
 .op (.Dup { idx := 6 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 7 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .GT,
 .op .SUB,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 3 }),
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .op (.Swap { idx := 3 }),
 .op .GT,
 .op .SUB,
 .op .SUB,
 .op (.Swap { idx := 4 }),
 .op .POP,
 .push 0 0,
 .push 2 4879,
 .push 2 5122,
 .op .JUMP,
 .op .JUMPDEST,
 .push 2 2432,
 .op .MLOAD,
 .push 2 2464,
 .op .MLOAD,
 .push 0 0,
 .op .SGT,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 8 }),
 .op (.Dup { idx := 2 }),
 .op (.Dup { idx := 2 }),
 .op .MULMOD,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op .LT,
 .op (.Swap { idx := 1 }),
 .op .MUL,
 .op (.Swap { idx := 1 }),
 .op .SUB,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op .LT,
 .op .SUB,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 6 }),
 .op .ADD,
 .op (.Swap { idx := 5 }),
 .op (.Dup { idx := 6 }),
 .op .LT,
 .op .SUB,
 .op .SUB,
 .push 2 2400,
 .op .MLOAD,
 .op (.Dup { idx := 8 }),
 .op (.Dup { idx := 3 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 4 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .GT,
 .op .SUB,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 3 }),
 .op .ADD,
 .op (.Dup { idx := 6 }),
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Swap { idx := 6 }),
 .op (.Dup { idx := 7 }),
 .op .LT,
 .op (.Swap { idx := 3 }),
 .op .GT,
 .op .SUB,
 .op .SUB,
 .op .ADD,
 .push 2 2368,
 .op .MLOAD,
 .op (.Dup { idx := 8 }),
 .op (.Dup { idx := 3 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 4 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .GT,
 .op .SUB,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 3 }),
 .op .ADD,
 .op (.Dup { idx := 5 }),
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Swap { idx := 5 }),
 .op (.Dup { idx := 6 }),
 .op .LT,
 .op (.Swap { idx := 3 }),
 .op .GT,
 .op .SUB,
 .op .SUB,
 .op .ADD,
 .op (.Dup { idx := 6 }),
 .op .ADD,
 .op (.Swap { idx := 5 }),
 .op (.Dup { idx := 6 }),
 .op .LT,
 .op (.Swap { idx := 0 }),
 .op .POP,
 .push 2 4992,
 .push 2 5122,
 .op .JUMP,
 .op .JUMPDEST,
 .push 2 2400,
 .op .MLOAD,
 .push 2 2432,
 .op .MLOAD,
 .push 0 0,
 .op .SGT,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 8 }),
 .op (.Dup { idx := 2 }),
 .op (.Dup { idx := 2 }),
 .op .MULMOD,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op .LT,
 .op (.Swap { idx := 1 }),
 .op .MUL,
 .op (.Swap { idx := 1 }),
 .op .SUB,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op .LT,
 .op .SUB,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 5 }),
 .op .ADD,
 .op (.Swap { idx := 4 }),
 .op (.Dup { idx := 5 }),
 .op .LT,
 .op .SUB,
 .op .SUB,
 .push 2 2368,
 .op .MLOAD,
 .op (.Dup { idx := 8 }),
 .op (.Dup { idx := 3 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 4 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .GT,
 .op .SUB,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 3 }),
 .op .ADD,
 .op (.Dup { idx := 5 }),
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Swap { idx := 5 }),
 .op (.Dup { idx := 6 }),
 .op .LT,
 .op (.Swap { idx := 3 }),
 .op .GT,
 .op .SUB,
 .op .SUB,
 .op .ADD,
 .op (.Dup { idx := 6 }),
 .op .ADD,
 .op (.Swap { idx := 5 }),
 .op (.Dup { idx := 6 }),
 .op .LT,
 .op (.Swap { idx := 0 }),
 .op .POP,
 .push 2 5076,
 .push 2 5122,
 .op .JUMP,
 .op .JUMPDEST,
 .push 2 2368,
 .op .MLOAD,
 .push 2 2400,
 .op .MLOAD,
 .push 0 0,
 .op .SGT,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Swap { idx := 0 }),
 .op (.Dup { idx := 7 }),
 .op (.Dup { idx := 2 }),
 .op (.Dup { idx := 2 }),
 .op .MULMOD,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op .LT,
 .op (.Swap { idx := 1 }),
 .op .MUL,
 .op (.Swap { idx := 1 }),
 .op .SUB,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op .LT,
 .op .SUB,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 3 }),
 .op .ADD,
 .op (.Swap { idx := 2 }),
 .op (.Dup { idx := 3 }),
 .op .LT,
 .op .SUB,
 .op .SUB,
 .op (.Dup { idx := 5 }),
 .op .ADD,
 .op (.Swap { idx := 4 }),
 .op (.Dup { idx := 5 }),
 .op .LT,
 .push 2 5232,
 .op .JUMPDEST,
 .op (.Dup { idx := 5 }),
 .op (.Dup { idx := 13 }),
 .op .MUL,
 .op (.Dup { idx := 6 }),
 .op (.Dup { idx := 9 }),
 .op (.Dup { idx := 2 }),
 .op (.Dup { idx := 12 }),
 .op .MULMOD,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .op (.Swap { idx := 1 }),
 .op .GT,
 .op .ADD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 12 }),
 .op .MUL,
 .op (.Dup { idx := 10 }),
 .op (.Dup { idx := 13 }),
 .op (.Dup { idx := 4 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .GT,
 .op .SUB,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 3 }),
 .op .ADD,
 .op (.Dup { idx := 9 }),
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Swap { idx := 10 }),
 .op .POP,
 .op (.Dup { idx := 10 }),
 .op (.Dup { idx := 1 }),
 .op .GT,
 .op (.Swap { idx := 3 }),
 .op .GT,
 .op .SUB,
 .op .SUB,
 .op .ADD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 13 }),
 .op .MUL,
 .op (.Dup { idx := 10 }),
 .op (.Dup { idx := 14 }),
 .op (.Dup { idx := 4 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .GT,
 .op .SUB,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 3 }),
 .op .ADD,
 .op (.Dup { idx := 8 }),
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Swap { idx := 9 }),
 .op .POP,
 .op (.Dup { idx := 9 }),
 .op (.Dup { idx := 1 }),
 .op .GT,
 .op (.Swap { idx := 3 }),
 .op .GT,
 .op .SUB,
 .op .SUB,
 .op .ADD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 14 }),
 .op .MUL,
 .op (.Dup { idx := 10 }),
 .op (.Dup { idx := 15 }),
 .op (.Dup { idx := 4 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .GT,
 .op .SUB,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 3 }),
 .op .ADD,
 .op (.Dup { idx := 7 }),
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Swap { idx := 8 }),
 .op .POP,
 .op (.Dup { idx := 8 }),
 .op (.Dup { idx := 1 }),
 .op .GT,
 .op (.Swap { idx := 3 }),
 .op .GT,
 .op .SUB,
 .op .SUB,
 .op .ADD,
 .op (.Dup { idx := 8 }),
 .op .ADD,
 .op (.Swap { idx := 3 }),
 .op .POP,
 .op .POP,
 .op (.Dup { idx := 2 }),
 .op (.Dup { idx := 7 }),
 .op .GT,
 .op (.Swap { idx := 0 }),
 .op (.Swap { idx := 1 }),
 .op .ADD,
 .op (.Swap { idx := 5 }),
 .op .POP,
 .op .JUMP,
 .op .JUMPDEST,
 .op (.Dup { idx := 3 }),
 .push 2 2208,
 .op .MSTORE,
 .op (.Dup { idx := 2 }),
 .push 2 2176,
 .op .MSTORE,
 .op (.Dup { idx := 1 }),
 .push 2 2144,
 .op .MSTORE,
 .op (.Dup { idx := 0 }),
 .push 2 2112,
 .op .MSTORE,
 .op (.Dup { idx := 4 }),
 .push 2 2080,
 .op .MSTORE,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .POP,
 .push 2 4358,
 .op .JUMP,
 .op .JUMPDEST,
 .op (.Dup { idx := 0 }),
 .op .MLOAD,
 .op (.Dup { idx := 0 }),
 .op (.Swap { idx := 14 }),
 .op .POP,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op .ADD,
 .op (.Swap { idx := 0 }),
 .op (.Dup { idx := 7 }),
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 0 }),
 .op .MUL,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .GT,
 .op (.Dup { idx := 2 }),
 .op (.Swap { idx := 1 }),
 .op .SUB,
 .op .SUB,
 .op (.Swap { idx := 0 }),
 .push 2 2336,
 .op .MSTORE,
 .push 2 3765,
 .op (.Swap { idx := 5 }),
 .op .JUMP]

theorem submissionInstructions_count : submissionInstructions.length = 4058 := by
  decide

theorem assemble_submissionInstructions :
    assemble submissionInstructions = submissionBytecode := by
  apply ByteArray.ext
  simp (config := { maxSteps := 4000000 })
    [assemble, assembleBytes, submissionInstructions, submissionBytecode,
    submissionBytes, Instr.bytes, natToBE]
  repeat' apply And.intro
  all_goals decide

def submissionArtifact : Challenge.EvmProof.ProgramArtifact where
  code := submissionBytecode
  instructions := submissionInstructions
  assembly_eq := assemble_submissionInstructions

theorem allWellFormed :
    Challenge.EvmProof.Stepper.AllWellFormed submissionArtifact .Osaka := by
  simp (config := { maxSteps := 4000000 })
    [Challenge.EvmProof.Stepper.AllWellFormed, submissionArtifact,
    submissionInstructions, Challenge.EvmProof.Stepper.WellFormed,
    YulEvmCompiler.plainOp]
  repeat' apply And.intro
  all_goals decide

def instructionPC (index : Nat) : Nat := submissionArtifact.instructionPC index

theorem decodeAt_op_index (index : Nat) (op : Operation)
    (hget : submissionInstructions[index]? = some (.op op))
    (hopcode : Decode.opcodeOf (Instr.opByte op) = some op)
    (hplain : YulEvmCompiler.plainOp op) :
    Decode.decodeAt submissionBytecode (instructionPC index) = some (op, none) :=
  Challenge.EvmProof.ProgramArtifact.decodeAt_op_index
    submissionArtifact index op hget hopcode hplain

theorem decodeAt_push_index (index : Nat) (width : Fin 33) (value : UInt256)
    (hget : submissionInstructions[index]? = some (.push width value))
    (hfit : value.toNat < 256 ^ width.val) :
    Decode.decodeAt submissionBytecode (instructionPC index) =
      some (.Push ⟨width⟩, some (value, width.val)) :=
  Challenge.EvmProof.ProgramArtifact.decodeAt_push_index
    submissionArtifact index width value hget hfit

theorem isValidJumpDest_index (index : Nat)
    (hget : submissionInstructions[index]? = some (.op .JUMPDEST)) :
    Decode.isValidJumpDest submissionBytecode (instructionPC index) = true :=
  Challenge.EvmProof.ProgramArtifact.isValidJumpDest_index
    submissionArtifact index hget

end Challenge.Modexp.Submission.Proofs.Bytecode.Artifact
