import Challenge.Modexp.Submission.Proofs.Bytecode.PCFast
import Challenge.Modexp.Submission.Proofs.Bytecode.Artifact
set_option warningAsError true
set_option maxRecDepth 20000
set_option maxHeartbeats 2000000
/-!
# Compact multi-limb fallback: located blocks

Generated by `gen_bigc.py` from the frozen bytecode layout.  The fallback
occupies instruction indices 176..450 (pc 258..654).
-/

namespace Challenge.Modexp.Submission.Proofs.Bytecode.BigC

open EvmSemantics
open EvmSemantics.EVM
open YulEvmCompiler
open Challenge.Modexp.Submission.Proofs.Bytecode

def wfOp {op : Operation}
    (hopcode : Decode.opcodeOf (YulEvmCompiler.Instr.opByte op) = some op)
    (hplain : YulEvmCompiler.plainOp op)
    (havailable : op.availableInFork .Osaka = true) :
    Challenge.EvmProof.Stepper.WellFormed .Osaka (.op op) :=
  ⟨hopcode, hplain, havailable⟩

def opAt (index : Nat) (op : Operation)
    (hget : Artifact.submissionInstructions[index]? = some (.op op) := by rfl)
    (hopcode : Decode.opcodeOf (YulEvmCompiler.Instr.opByte op) = some op := by decide)
    (hplain : YulEvmCompiler.plainOp op := by trivial)
    (havailable : op.availableInFork .Osaka = true := by rfl) :
    Challenge.EvmProof.Stepper.Located Artifact.submissionArtifact .Osaka :=
  ⟨index, .op op, hget, wfOp hopcode hplain havailable⟩

def pushAt (index : Nat) (width : Fin 33) (value : UInt256)
    (hget : Artifact.submissionInstructions[index]? =
      some (.push width value) := by rfl)
    (hwf : Challenge.EvmProof.Stepper.WellFormed .Osaka
      (.push width value) := by decide) :
    Challenge.EvmProof.Stepper.Located Artifact.submissionArtifact .Osaka :=
  ⟨index, .push width value, hget, hwf⟩

/-- pc 258..306 -/
def setupPath :
    List (Challenge.EvmProof.Stepper.Located Artifact.submissionArtifact .Osaka) :=
  [opAt 177 .JUMPDEST,
   pushAt 178 2 9248,
   opAt 179 .CALLDATASIZE,
   pushAt 180 0 0,
   opAt 181 .CALLDATACOPY,
   pushAt 182 1 64,
   opAt 183 .CALLDATALOAD,
   opAt 184 (.Dup ⟨0, by decide⟩),
   pushAt 185 2 9216,
   opAt 186 .MSTORE,
   pushAt 187 1 32,
   opAt 188 .CALLDATALOAD,
   pushAt 189 0 0,
   opAt 190 .CALLDATALOAD,
   opAt 191 (.Dup ⟨2, by decide⟩),
   opAt 192 (.Dup ⟨1, by decide⟩),
   opAt 193 (.Dup ⟨3, by decide⟩),
   opAt 194 .ADD,
   pushAt 195 1 96,
   opAt 196 .ADD,
   pushAt 197 2 1024,
   opAt 198 .CALLDATACOPY,
   opAt 199 (.Dup ⟨0, by decide⟩),
   pushAt 200 1 96,
   pushAt 201 2 5120,
   opAt 202 .CALLDATACOPY,
   opAt 203 (.Dup ⟨1, by decide⟩),
   opAt 204 (.Dup ⟨1, by decide⟩),
   pushAt 205 1 96,
   opAt 206 .ADD,
   pushAt 207 2 6144,
   opAt 208 .CALLDATACOPY,
   pushAt 209 0 0,
   opAt 210 (.Dup ⟨3, by decide⟩)]

/-- pc 307..327 -/
def zLoopPath :
    List (Challenge.EvmProof.Stepper.Located Artifact.submissionArtifact .Osaka) :=
  [opAt 211 .JUMPDEST,
   pushAt 212 0 0,
   opAt 213 .NOT,
   opAt 214 .ADD,
   opAt 215 (.Dup ⟨0, by decide⟩),
   pushAt 216 2 1024,
   opAt 217 .ADD,
   opAt 218 .MLOAD,
   pushAt 219 0 0,
   opAt 220 .BYTE,
   opAt 221 (.Swap ⟨0, by decide⟩),
   opAt 222 (.Swap ⟨1, by decide⟩),
   opAt 223 .OR,
   opAt 224 (.Swap ⟨0, by decide⟩),
   opAt 225 (.Dup ⟨0, by decide⟩),
   pushAt 226 2 300,
   opAt 227 .JUMPI]

/-- pc 328..332 -/
def zExitPath :
    List (Challenge.EvmProof.Stepper.Located Artifact.submissionArtifact .Osaka) :=
  [opAt 228 .POP,
   pushAt 229 2 331,
   opAt 230 .JUMPI]

/-- pc 333..337 -/
def zeroRetPath :
    List (Challenge.EvmProof.Stepper.Located Artifact.submissionArtifact .Osaka) :=
  [opAt 231 (.Dup ⟨2, by decide⟩),
   pushAt 232 2 8192,
   opAt 233 .RETURN]

/-- pc 338..360 -/
def nzPath :
    List (Challenge.EvmProof.Stepper.Located Artifact.submissionArtifact .Osaka) :=
  [opAt 234 .JUMPDEST,
   pushAt 235 1 1,
   opAt 236 (.Dup ⟨3, by decide⟩),
   pushAt 237 2 7167,
   opAt 238 .ADD,
   opAt 239 .MSTORE8,
   opAt 240 (.Dup ⟨0, by decide⟩),
   pushAt 241 2 5120,
   pushAt 242 2 7168,
   pushAt 243 2 354,
   pushAt 244 2 476,
   opAt 245 .JUMP]

/-- pc 361..380 -/
def x1Path :
    List (Challenge.EvmProof.Stepper.Located Artifact.submissionArtifact .Osaka) :=
  [opAt 246 .JUMPDEST,
   opAt 247 .POP,
   pushAt 248 2 9216,
   opAt 249 .MLOAD,
   pushAt 250 0 0,
   pushAt 251 2 2048,
   opAt 252 .MCOPY,
   opAt 253 (.Dup ⟨1, by decide⟩),
   pushAt 254 2 7168,
   pushAt 255 2 3072,
   opAt 256 .MCOPY,
   pushAt 257 0 0]

/-- pc 381..391 -/
def eGuardPath :
    List (Challenge.EvmProof.Stepper.Located Artifact.submissionArtifact .Osaka) :=
  [opAt 258 .JUMPDEST,
   opAt 259 (.Dup ⟨1, by decide⟩),
   pushAt 260 1 3,
   opAt 261 .SHL,
   opAt 262 (.Dup ⟨1, by decide⟩),
   opAt 263 .EQ,
   pushAt 264 2 455,
   opAt 265 .JUMPI]

/-- pc 392..403 -/
def eSquarePath :
    List (Challenge.EvmProof.Stepper.Located Artifact.submissionArtifact .Osaka) :=
  [opAt 266 (.Dup ⟨2, by decide⟩),
   pushAt 267 2 3072,
   opAt 268 (.Dup ⟨0, by decide⟩),
   pushAt 269 2 397,
   pushAt 270 2 476,
   opAt 271 .JUMP]

/-- pc 404..432 -/
def e2Path :
    List (Challenge.EvmProof.Stepper.Located Artifact.submissionArtifact .Osaka) :=
  [opAt 272 .JUMPDEST,
   opAt 273 (.Dup ⟨2, by decide⟩),
   pushAt 274 0 0,
   pushAt 275 2 3072,
   opAt 276 .MCOPY,
   opAt 277 (.Dup ⟨0, by decide⟩),
   pushAt 278 1 3,
   opAt 279 .SHR,
   pushAt 280 2 6144,
   opAt 281 .ADD,
   opAt 282 .MLOAD,
   opAt 283 (.Dup ⟨1, by decide⟩),
   pushAt 284 1 7,
   opAt 285 .AND,
   opAt 286 .SHL,
   pushAt 287 1 255,
   opAt 288 .SHR,
   opAt 289 .ISZERO,
   pushAt 290 2 447,
   opAt 291 .JUMPI]

/-- pc 433..446 -/
def eMulPath :
    List (Challenge.EvmProof.Stepper.Located Artifact.submissionArtifact .Osaka) :=
  [opAt 292 (.Dup ⟨2, by decide⟩),
   pushAt 293 2 2048,
   pushAt 294 2 3072,
   pushAt 295 2 440,
   pushAt 296 2 476,
   opAt 297 .JUMP]

/-- pc 447..453 -/
def e4Path :
    List (Challenge.EvmProof.Stepper.Located Artifact.submissionArtifact .Osaka) :=
  [opAt 298 .JUMPDEST,
   opAt 299 (.Dup ⟨2, by decide⟩),
   pushAt 300 0 0,
   pushAt 301 2 3072,
   opAt 302 .MCOPY]

/-- pc 454..461 -/
def e3Path :
    List (Challenge.EvmProof.Stepper.Located Artifact.submissionArtifact .Osaka) :=
  [opAt 303 .JUMPDEST,
   pushAt 304 1 1,
   opAt 305 .ADD,
   pushAt 306 2 374,
   opAt 307 .JUMP]

/-- pc 462..478 -/
def e9Path :
    List (Challenge.EvmProof.Stepper.Located Artifact.submissionArtifact .Osaka) :=
  [opAt 308 .JUMPDEST,
   opAt 309 (.Dup ⟨2, by decide⟩),
   pushAt 310 2 3072,
   pushAt 311 0 0,
   opAt 312 .MCOPY,
   pushAt 313 2 8192,
   pushAt 314 2 472,
   pushAt 315 2 548,
   opAt 316 .JUMP]

/-- pc 479..482 -/
def e5Path :
    List (Challenge.EvmProof.Stepper.Located Artifact.submissionArtifact .Osaka) :=
  [opAt 317 .JUMPDEST,
   opAt 318 (.Dup ⟨2, by decide⟩),
   pushAt 319 0 0,
   opAt 320 .RETURN]

/-- pc 483..491 -/
def mEntryPath :
    List (Challenge.EvmProof.Stepper.Located Artifact.submissionArtifact .Osaka) :=
  [opAt 321 .JUMPDEST,
   pushAt 322 2 9216,
   opAt 323 .MLOAD,
   opAt 324 .CALLDATASIZE,
   pushAt 325 0 0,
   opAt 326 .CALLDATACOPY,
   pushAt 327 0 0]

/-- pc 492..502 -/
def mGuardPath :
    List (Challenge.EvmProof.Stepper.Located Artifact.submissionArtifact .Osaka) :=
  [opAt 328 .JUMPDEST,
   opAt 329 (.Dup ⟨4, by decide⟩),
   pushAt 330 1 3,
   opAt 331 .SHL,
   opAt 332 (.Dup ⟨1, by decide⟩),
   opAt 333 .EQ,
   pushAt 334 2 541,
   opAt 335 .JUMPI]

/-- pc 503..510 -/
def mDoublePath :
    List (Challenge.EvmProof.Stepper.Located Artifact.submissionArtifact .Osaka) :=
  [pushAt 336 0 0,
   pushAt 337 2 504,
   pushAt 338 2 548,
   opAt 339 .JUMP]

/-- pc 511..531 -/
def m2Path :
    List (Challenge.EvmProof.Stepper.Located Artifact.submissionArtifact .Osaka) :=
  [opAt 340 .JUMPDEST,
   opAt 341 (.Dup ⟨0, by decide⟩),
   pushAt 342 1 3,
   opAt 343 .SHR,
   opAt 344 (.Dup ⟨4, by decide⟩),
   opAt 345 .ADD,
   opAt 346 .MLOAD,
   opAt 347 (.Dup ⟨1, by decide⟩),
   pushAt 348 1 7,
   opAt 349 .AND,
   opAt 350 .SHL,
   pushAt 351 1 255,
   opAt 352 .SHR,
   opAt 353 .ISZERO,
   pushAt 354 2 533,
   opAt 355 .JUMPI]

/-- pc 532..539 -/
def mAddPath :
    List (Challenge.EvmProof.Stepper.Located Artifact.submissionArtifact .Osaka) :=
  [opAt 356 (.Dup ⟨2, by decide⟩),
   pushAt 357 2 533,
   pushAt 358 2 548,
   opAt 359 .JUMP]

/-- pc 540..547 -/
def m3Path :
    List (Challenge.EvmProof.Stepper.Located Artifact.submissionArtifact .Osaka) :=
  [opAt 360 .JUMPDEST,
   pushAt 361 1 1,
   opAt 362 .ADD,
   pushAt 363 2 485,
   opAt 364 .JUMP]

/-- pc 548..554 -/
def m9Path :
    List (Challenge.EvmProof.Stepper.Located Artifact.submissionArtifact .Osaka) :=
  [opAt 365 .JUMPDEST,
   opAt 366 .POP,
   opAt 367 (.Swap ⟨2, by decide⟩),
   opAt 368 .POP,
   opAt 369 .POP,
   opAt 370 .POP,
   opAt 371 .JUMP]

/-- pc 555..560 -/
def aEntryPath :
    List (Challenge.EvmProof.Stepper.Located Artifact.submissionArtifact .Osaka) :=
  [opAt 372 .JUMPDEST,
   pushAt 373 0 0,
   pushAt 374 2 9216,
   opAt 375 .MLOAD]

/-- pc 561..590 -/
def aLoopPath :
    List (Challenge.EvmProof.Stepper.Located Artifact.submissionArtifact .Osaka) :=
  [opAt 376 .JUMPDEST,
   pushAt 377 0 0,
   opAt 378 .NOT,
   opAt 379 .ADD,
   opAt 380 (.Dup ⟨0, by decide⟩),
   opAt 381 (.Dup ⟨4, by decide⟩),
   opAt 382 .ADD,
   opAt 383 .MLOAD,
   pushAt 384 0 0,
   opAt 385 .BYTE,
   opAt 386 (.Dup ⟨1, by decide⟩),
   opAt 387 .MLOAD,
   pushAt 388 0 0,
   opAt 389 .BYTE,
   opAt 390 .ADD,
   opAt 391 (.Dup ⟨2, by decide⟩),
   opAt 392 .ADD,
   opAt 393 (.Dup ⟨0, by decide⟩),
   opAt 394 (.Dup ⟨2, by decide⟩),
   opAt 395 .MSTORE8,
   pushAt 396 1 8,
   opAt 397 .SHR,
   opAt 398 (.Swap ⟨1, by decide⟩),
   opAt 399 .POP,
   opAt 400 (.Dup ⟨0, by decide⟩),
   pushAt 401 2 554,
   opAt 402 .JUMPI]

/-- pc 591..596 -/
def aExitPath :
    List (Challenge.EvmProof.Stepper.Located Artifact.submissionArtifact .Osaka) :=
  [opAt 403 .POP,
   pushAt 404 0 0,
   pushAt 405 2 9216,
   opAt 406 .MLOAD]

/-- pc 597..633 -/
def sLoopPath :
    List (Challenge.EvmProof.Stepper.Located Artifact.submissionArtifact .Osaka) :=
  [opAt 407 .JUMPDEST,
   pushAt 408 0 0,
   opAt 409 .NOT,
   opAt 410 .ADD,
   opAt 411 (.Dup ⟨0, by decide⟩),
   pushAt 412 2 1024,
   opAt 413 .ADD,
   opAt 414 .MLOAD,
   pushAt 415 0 0,
   opAt 416 .BYTE,
   opAt 417 (.Dup ⟨1, by decide⟩),
   opAt 418 .MLOAD,
   pushAt 419 0 0,
   opAt 420 .BYTE,
   opAt 421 .SUB,
   opAt 422 (.Dup ⟨2, by decide⟩),
   opAt 423 (.Swap ⟨0, by decide⟩),
   opAt 424 .SUB,
   opAt 425 (.Dup ⟨0, by decide⟩),
   opAt 426 (.Dup ⟨2, by decide⟩),
   pushAt 427 2 4096,
   opAt 428 .ADD,
   opAt 429 .MSTORE8,
   pushAt 430 1 255,
   opAt 431 .SHR,
   opAt 432 (.Swap ⟨1, by decide⟩),
   opAt 433 .POP,
   opAt 434 (.Dup ⟨0, by decide⟩),
   pushAt 435 2 590,
   opAt 436 .JUMPI]

/-- pc 634..641 -/
def sExitPath :
    List (Challenge.EvmProof.Stepper.Located Artifact.submissionArtifact .Osaka) :=
  [opAt 437 .POP,
   opAt 438 .ISZERO,
   opAt 439 .OR,
   opAt 440 .ISZERO,
   pushAt 441 2 644,
   opAt 442 .JUMPI]

/-- pc 642..650 -/
def copyPath :
    List (Challenge.EvmProof.Stepper.Located Artifact.submissionArtifact .Osaka) :=
  [pushAt 443 2 9216,
   opAt 444 .MLOAD,
   pushAt 445 2 4096,
   pushAt 446 0 0,
   opAt 447 .MCOPY]

/-- pc 651..654 -/
def a3Path :
    List (Challenge.EvmProof.Stepper.Located Artifact.submissionArtifact .Osaka) :=
  [opAt 448 .JUMPDEST,
   opAt 449 (.Swap ⟨0, by decide⟩),
   opAt 450 .POP,
   opAt 451 .JUMP]

@[simp] theorem bigCPCs (i : Nat) (hi : 177 ≤ i) (hii : i ≤ 451) :
    Artifact.submissionArtifact.instructionPC i =
      ([251, 252, 255, 256, 257, 258, 260, 261, 262, 265, 266, 268, 269, 270, 271, 272, 273, 274, 275, 277, 278, 281, 282, 283, 285, 288, 289, 290, 291, 293, 294, 297, 298, 299, 300, 301, 302, 303, 304, 305, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 320, 321, 322, 325, 326, 327, 330, 331, 332, 334, 335, 338, 339, 340, 341, 344, 347, 350, 353, 354, 355, 356, 359, 360, 361, 364, 365, 366, 369, 372, 373, 374, 375, 376, 378, 379, 380, 381, 384, 385, 386, 389, 390, 393, 396, 397, 398, 399, 400, 403, 404, 405, 407, 408, 411, 412, 413, 414, 416, 417, 418, 420, 421, 422, 425, 426, 427, 430, 433, 436, 439, 440, 441, 442, 443, 446, 447, 448, 450, 451, 454, 455, 456, 457, 460, 461, 462, 465, 468, 471, 472, 473, 474, 475, 476, 477, 480, 481, 482, 483, 484, 485, 486, 487, 489, 490, 491, 492, 495, 496, 497, 500, 503, 504, 505, 506, 508, 509, 510, 511, 512, 513, 515, 516, 517, 519, 520, 521, 524, 525, 526, 529, 532, 533, 534, 536, 537, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571, 572, 573, 574, 576, 577, 578, 579, 580, 583, 584, 585, 586, 589, 590, 591, 592, 593, 594, 595, 598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611, 612, 615, 616, 617, 619, 620, 621, 622, 623, 626, 627, 628, 629, 630, 631, 634, 635, 638, 639, 642, 643, 644, 645, 646, 647] : List Nat)[i - 177]! := by
  rw [Challenge.Modexp.Submission.Proofs.Bytecode.PCFast.instructionPC_eq_byteLength]
  interval_cases i <;> rfl

@[simp] theorem jump258 : Decode.isValidJumpDest submissionBytecode 251 = true :=
  Artifact.isValidJumpDest_index 177 (by rfl)

@[simp] theorem jump307 : Decode.isValidJumpDest submissionBytecode 300 = true :=
  Artifact.isValidJumpDest_index 211 (by rfl)

@[simp] theorem jump338 : Decode.isValidJumpDest submissionBytecode 331 = true :=
  Artifact.isValidJumpDest_index 234 (by rfl)

@[simp] theorem jump361 : Decode.isValidJumpDest submissionBytecode 354 = true :=
  Artifact.isValidJumpDest_index 246 (by rfl)

@[simp] theorem jump381 : Decode.isValidJumpDest submissionBytecode 374 = true :=
  Artifact.isValidJumpDest_index 258 (by rfl)

@[simp] theorem jump404 : Decode.isValidJumpDest submissionBytecode 397 = true :=
  Artifact.isValidJumpDest_index 272 (by rfl)

@[simp] theorem jump447 : Decode.isValidJumpDest submissionBytecode 440 = true :=
  Artifact.isValidJumpDest_index 298 (by rfl)

@[simp] theorem jump454 : Decode.isValidJumpDest submissionBytecode 447 = true :=
  Artifact.isValidJumpDest_index 303 (by rfl)

@[simp] theorem jump462 : Decode.isValidJumpDest submissionBytecode 455 = true :=
  Artifact.isValidJumpDest_index 308 (by rfl)

@[simp] theorem jump479 : Decode.isValidJumpDest submissionBytecode 472 = true :=
  Artifact.isValidJumpDest_index 317 (by rfl)

@[simp] theorem jump483 : Decode.isValidJumpDest submissionBytecode 476 = true :=
  Artifact.isValidJumpDest_index 321 (by rfl)

@[simp] theorem jump492 : Decode.isValidJumpDest submissionBytecode 485 = true :=
  Artifact.isValidJumpDest_index 328 (by rfl)

@[simp] theorem jump511 : Decode.isValidJumpDest submissionBytecode 504 = true :=
  Artifact.isValidJumpDest_index 340 (by rfl)

@[simp] theorem jump540 : Decode.isValidJumpDest submissionBytecode 533 = true :=
  Artifact.isValidJumpDest_index 360 (by rfl)

@[simp] theorem jump548 : Decode.isValidJumpDest submissionBytecode 541 = true :=
  Artifact.isValidJumpDest_index 365 (by rfl)

@[simp] theorem jump555 : Decode.isValidJumpDest submissionBytecode 548 = true :=
  Artifact.isValidJumpDest_index 372 (by rfl)

@[simp] theorem jump561 : Decode.isValidJumpDest submissionBytecode 554 = true :=
  Artifact.isValidJumpDest_index 376 (by rfl)

@[simp] theorem jump597 : Decode.isValidJumpDest submissionBytecode 590 = true :=
  Artifact.isValidJumpDest_index 407 (by rfl)

@[simp] theorem jump651 : Decode.isValidJumpDest submissionBytecode 644 = true :=
  Artifact.isValidJumpDest_index 448 (by rfl)

end Challenge.Modexp.Submission.Proofs.Bytecode.BigC
