import Challenge.Modexp.Submission.Proofs.Bytecode.Artifact
import Challenge.Modexp.Submission.Proofs.Bytecode.ArtifactSegment

set_option warningAsError true
set_option maxRecDepth 40000
set_option maxHeartbeats 8000000

namespace Challenge.Modexp.Submission.Proofs.Bytecode.ShiftRegion

open Challenge.EvmProof
open EvmSemantics EvmSemantics.EVM YulEvmCompiler
open Challenge.Modexp.Submission.Proofs.Bytecode.ArtifactSegment

def mainProgram : List Instr :=
  [
   .op .JUMPDEST,
   .op (.Dup { idx := 0 }),
   .op (.Dup { idx := 3 }),
   .op .EQ,
   .push 0 0,
   .op .MLOAD,
   .push 1 255,
   .op .SHR,
   .op .AND,
   .op .ISZERO,
   .push 2 3346,
   .op .JUMPI,
   .op (.Dup { idx := 0 }),
   .push 1 96,
   .push 2 256,
   .op .CALLDATACOPY,
   .op (.Dup { idx := 0 }),
   .push 1 96,
   .push 2 4160,
   .op .CALLDATACOPY,
   .push 0 0,
   .push 2 4128,
   .op .MSTORE,
   .push 2 3363,
   .push 2 512,
   .push 2 4669,
   .op .JUMP,
   .op .JUMPDEST,
   .push 1 1,
   .push 2 1024,
   .op .MSTORE,
   .push 2 1300,
   .push 2 1024,
   .push 2 2081,
   .op .JUMP,
   .op .JUMPDEST,
   .push 1 1,
   .push 2 5312,
   .op .MLOAD,
   .op .JUMPDEST,
   .op (.Dup { idx := 0 }),
   .op .MLOAD,
   .op .NOT,
   .op (.Dup { idx := 2 }),
   .op .ADD,
   .op (.Dup { idx := 2 }),
   .op (.Dup { idx := 1 }),
   .op .LT,
   .op (.Swap { idx := 2 }),
   .op .POP,
   .op (.Dup { idx := 1 }),
   .push 2 1280,
   .op .ADD,
   .op .MSTORE,
   .op (.Dup { idx := 0 }),
   .op .ISZERO,
   .push 2 3401,
   .op .JUMPI,
   .push 1 31,
   .op .NOT,
   .op .ADD,
   .push 2 3370,
   .op .JUMP,
   .op .JUMPDEST,
   .op .POP,
   .op .POP,
   .push 0 0,
   .op .MLOAD,
   .op (.Dup { idx := 0 }),
   .push 0 0,
   .op .SUB,
   .op (.Dup { idx := 1 }),
   .op .AND,
   .op (.Dup { idx := 0 }),
   .push 2 1536,
   .op .MSTORE,
   .op (.Dup { idx := 0 }),
   .op (.Dup { idx := 2 }),
   .op .DIV,
   .op (.Dup { idx := 0 }),
   .push 2 1568,
   .op .MSTORE,
   .op (.Dup { idx := 1 }),
   .push 0 0,
   .op .SUB,
   .op (.Dup { idx := 2 }),
   .op (.Swap { idx := 0 }),
   .op .DIV,
   .push 1 1,
   .op .ADD,
   .push 2 1600,
   .op .MSTORE,
   .op (.Dup { idx := 0 }),
   .push 0 0,
   .op .SUB,
   .op (.Dup { idx := 1 }),
   .op (.Swap { idx := 0 }),
   .op .MOD,
   .push 2 1632,
   .op .MSTORE,
   .op (.Dup { idx := 0 }),
   .push 1 2,
   .op .SUB,
   .op (.Dup { idx := 0 }),
   .op (.Dup { idx := 2 }),
   .op .MUL,
   .push 1 2,
   .op .SUB,
   .op .MUL,
   .op (.Dup { idx := 0 }),
   .op (.Dup { idx := 2 }),
   .op .MUL,
   .push 1 2,
   .op .SUB,
   .op .MUL,
   .op (.Dup { idx := 0 }),
   .op (.Dup { idx := 2 }),
   .op .MUL,
   .push 1 2,
   .op .SUB,
   .op .MUL,
   .op (.Dup { idx := 0 }),
   .op (.Dup { idx := 2 }),
   .op .MUL,
   .push 1 2,
   .op .SUB,
   .op .MUL,
   .op (.Dup { idx := 0 }),
   .op (.Dup { idx := 2 }),
   .op .MUL,
   .push 1 2,
   .op .SUB,
   .op .MUL,
   .op (.Dup { idx := 0 }),
   .op (.Dup { idx := 2 }),
   .op .MUL,
   .push 1 2,
   .op .SUB,
   .op .MUL,
   .op (.Dup { idx := 0 }),
   .op (.Dup { idx := 2 }),
   .op .MUL,
   .push 1 2,
   .op .SUB,
   .op .MUL,
   .push 2 1664,
   .op .MSTORE,
   .op .POP,
   .op .POP,
   .op .POP,
   .op (.Dup { idx := 1 }),
   .op .JUMPDEST,
   .op (.Dup { idx := 0 }),
   .op .ISZERO,
   .push 2 3895,
   .op .JUMPI,
   .op (.Dup { idx := 1 }),
   .push 2 512,
   .push 2 4128,
   .op .MCOPY,
   .push 0 0,
   .push 2 5344,
   .op .MLOAD,
   .op .MSTORE,
   .push 2 512,
   .op .MLOAD,
   .push 2 1536,
   .op .MLOAD,
   .op (.Dup { idx := 0 }),
   .op (.Dup { idx := 2 }),
   .op .DIV,
   .op (.Swap { idx := 1 }),
   .op .MOD,
   .push 2 1600,
   .op .MLOAD,
   .op .MUL,
   .push 2 544,
   .op .MLOAD,
   .push 2 1536,
   .op .MLOAD,
   .op (.Swap { idx := 0 }),
   .op .DIV,
   .op .ADD,
   .push 2 1568,
   .op .MLOAD,
   .op (.Dup { idx := 0 }),
   .push 2 1632,
   .op .MLOAD,
   .op (.Dup { idx := 4 }),
   .op .MULMOD,
   .op (.Dup { idx := 2 }),
   .op .ADDMOD,
   .op (.Swap { idx := 0 }),
   .op .SUB,
   .push 2 1664,
   .op .MLOAD,
   .op .MUL,
   .op (.Dup { idx := 0 }),
   .push 0 0,
   .op .MLOAD,
   .op .MUL,
   .push 2 544,
   .op .MLOAD,
   .op .SUB,
   .push 1 32,
   .op .MLOAD,
   .push 1 128,
   .op .SHR,
   .op (.Dup { idx := 2 }),
   .push 1 128,
   .op .SHR,
   .op .MUL,
   .op .GT,
   .op (.Swap { idx := 0 }),
   .op .SUB,
   .op (.Swap { idx := 0 }),
   .push 2 1568,
   .op .MLOAD,
   .op .GT,
   .op .ISZERO,
   .push 0 0,
   .op .SUB,
   .op .OR,
   .push 0 0,
   .push 2 5344,
   .op .MLOAD,
   .push 2 5312,
   .op .MLOAD,
   .push 2 1280,
   .op .ADD,
   .op .JUMPDEST,
   .op (.Dup { idx := 0 }),
   .op .MLOAD,
   .push 0 0,
   .op .NOT,
   .op (.Dup { idx := 5 }),
   .op (.Dup { idx := 2 }),
   .op .MUL,
   .op (.Swap { idx := 1 }),
   .op (.Dup { idx := 6 }),
   .op .MULMOD,
   .op (.Dup { idx := 1 }),
   .op (.Dup { idx := 1 }),
   .op .LT,
   .op .SUB,
   .op (.Dup { idx := 4 }),
   .op (.Dup { idx := 2 }),
   .op .ADD,
   .op (.Dup { idx := 0 }),
   .op (.Swap { idx := 5 }),
   .op .GT,
   .op .SUB,
   .op .SUB,
   .op (.Dup { idx := 3 }),
   .op (.Dup { idx := 3 }),
   .op .MLOAD,
   .op .ADD,
   .op (.Dup { idx := 0 }),
   .op (.Swap { idx := 4 }),
   .op .GT,
   .op .ADD,
   .op (.Swap { idx := 2 }),
   .op (.Dup { idx := 2 }),
   .push 1 31,
   .op .NOT,
   .op .ADD,
   .op (.Swap { idx := 2 }),
   .op .MSTORE,
   .push 32 115792089237316195423570985008687907853269984665640564039457584007913129639904,
   .op .ADD,
   .push 2 4128,
   .op (.Dup { idx := 2 }),
   .op .GT,
   .push 2 3624,
   .op .JUMPI,
   .op .POP,
   .op .POP,
   .push 2 4128,
   .op .MLOAD,
   .op (.Dup { idx := 1 }),
   .op .ADD,
   .op (.Dup { idx := 1 }),
   .op (.Dup { idx := 1 }),
   .op .LT,
   .op (.Swap { idx := 1 }),
   .op .POP,
   .op (.Dup { idx := 2 }),
   .op (.Dup { idx := 1 }),
   .op .LT,
   .op (.Swap { idx := 0 }),
   .op (.Dup { idx := 3 }),
   .op (.Swap { idx := 0 }),
   .op .SUB,
   .op (.Dup { idx := 0 }),
   .push 2 4128,
   .op .MSTORE,
   .op .POP,
   .op .GT,
   .op (.Swap { idx := 0 }),
   .op .POP,
   .op .ISZERO,
   .push 2 3807,
   .op .JUMPI,
   .op .JUMPDEST,
   .push 0 0,
   .push 2 5344,
   .op .MLOAD,
   .op .JUMPDEST,
   .op (.Dup { idx := 0 }),
   .op .MLOAD,
   .op (.Dup { idx := 1 }),
   .push 2 4160,
   .op (.Swap { idx := 0 }),
   .op .SUB,
   .op .MLOAD,
   .op (.Dup { idx := 1 }),
   .op .ADD,
   .op (.Dup { idx := 0 }),
   .op (.Dup { idx := 2 }),
   .op .GT,
   .op (.Swap { idx := 1 }),
   .op .POP,
   .op (.Dup { idx := 3 }),
   .op .ADD,
   .op (.Dup { idx := 0 }),
   .op (.Dup { idx := 4 }),
   .op .GT,
   .op (.Swap { idx := 3 }),
   .op .POP,
   .op (.Dup { idx := 2 }),
   .op .MSTORE,
   .op (.Swap { idx := 0 }),
   .op (.Swap { idx := 1 }),
   .op .OR,
   .op (.Swap { idx := 0 }),
   .push 1 31,
   .op .NOT,
   .op .ADD,
   .push 2 4159,
   .op (.Dup { idx := 1 }),
   .op .GT,
   .push 2 3746,
   .op .JUMPI,
   .op .POP,
   .push 2 4128,
   .op .MLOAD,
   .op (.Dup { idx := 1 }),
   .op .ADD,
   .op (.Dup { idx := 0 }),
   .push 2 4128,
   .op .MSTORE,
   .op .LT,
   .op .ISZERO,
   .push 2 3740,
   .op .JUMPI,
   .op .JUMPDEST,
   .push 2 4128,
   .op .MLOAD,
   .op .ISZERO,
   .push 2 3875,
   .op .JUMPI,
   .push 0 0,
   .push 2 5344,
   .op .MLOAD,
   .op .JUMPDEST,
   .op (.Dup { idx := 0 }),
   .op .MLOAD,
   .push 2 4160,
   .op (.Dup { idx := 2 }),
   .op .SUB,
   .op .MLOAD,
   .op (.Dup { idx := 1 }),
   .op (.Dup { idx := 1 }),
   .op .GT,
   .op (.Swap { idx := 1 }),
   .op .SUB,
   .op (.Dup { idx := 3 }),
   .op (.Dup { idx := 1 }),
   .op .LT,
   .op (.Swap { idx := 0 }),
   .op (.Dup { idx := 4 }),
   .op (.Swap { idx := 0 }),
   .op .SUB,
   .op (.Dup { idx := 3 }),
   .op .MSTORE,
   .op .OR,
   .op (.Swap { idx := 1 }),
   .op .POP,
   .push 1 31,
   .op .NOT,
   .op .ADD,
   .push 2 4159,
   .op (.Dup { idx := 1 }),
   .op .GT,
   .push 2 3822,
   .op .JUMPI,
   .op .POP,
   .push 2 4128,
   .op .MLOAD,
   .op .SUB,
   .push 2 4128,
   .op .MSTORE,
   .push 2 3807,
   .op .JUMP,
   .op .JUMPDEST,
   .push 2 3886,
   .push 2 512,
   .push 2 4669,
   .op .JUMP,
   .op .JUMPDEST,
   .push 0 0,
   .op .NOT,
   .op .ADD,
   .push 3 3508,
   .op .JUMP,
   .op .JUMPDEST,
   .op .POP,
   .push 2 5248,
   .op .MLOAD,
   .push 2 1280,
   .push 2 1024,
   .op .MCOPY,
   .push 2 3138,
   .op .JUMP
  ]

def mainBefore : List Instr := Artifact.submissionInstructions.take 2529
def mainAfter : List Instr := Artifact.submissionInstructions.drop 2953

private theorem mainSplit : Artifact.submissionArtifact.instructions = mainBefore ++ mainProgram ++ mainAfter := by
  rfl

private theorem mainBeforeLength : mainBefore.length = 2529 := by
  decide

private theorem mainBeforePC : (assembleBytes mainBefore).length = 3302 := by
  rfl

theorem mainPcAt (i : Nat) (hi : i ≤ mainProgram.length) :
    Artifact.submissionArtifact.instructionPC (2529 + i) =
      3302 + (assembleBytes (mainProgram.take i)).length :=
  instructionPC_segment_of_bounds Artifact.submissionArtifact mainBefore mainProgram mainAfter
    2529 3302 mainSplit mainBeforeLength mainBeforePC i hi

theorem mainInstructionAt (i : Nat) (hi : i < mainProgram.length) :
    Artifact.submissionArtifact.instructions[2529 + i]? = mainProgram[i]? := by
  simpa only [mainBeforeLength] using
    getElem?_segment Artifact.submissionArtifact mainBefore mainProgram mainAfter mainSplit i hi

theorem mainPcSuccSize (i size : Nat) (hi : i < mainProgram.length)
    (hsize : (mainProgram[i]?.map fun instruction => instruction.bytes.length) = some size) :
    Artifact.submissionArtifact.instructionPC ((2529 + i) + 1) =
      Artifact.submissionArtifact.instructionPC (2529 + i) + size := by
  cases hget : mainProgram[i]? with
  | none => simp [hget] at hsize
  | some instruction =>
      have hs : instruction.bytes.length = size := by simpa [hget] using hsize
      simpa only [hs] using
        instructionPC_succ Artifact.submissionArtifact (2529 + i) instruction
          (by rw [mainInstructionAt i hi, hget])

def earlyProgram : List Instr :=
  [
   .op .JUMPDEST,
   .push 0 0,
   .op .MLOAD,
   .push 2 4160,
   .op .MLOAD,
   .op .LT,
   .push 2 4128,
   .op .MLOAD,
   .op .ISZERO,
   .op .AND,
   .push 2 5165,
   .op .JUMPI,
   .push 2 4925,
   .op .JUMP,
   .op .JUMPDEST,
   .push 2 4256,
   .op .MLOAD,
   .push 1 96,
   .op .MLOAD,
   .op (.Dup { idx := 1 }),
   .op (.Dup { idx := 1 }),
   .op .GT,
   .op (.Swap { idx := 1 }),
   .op .SUB,
   .push 2 3168,
   .op .MSTORE,
   .push 2 5082,
   .op .JUMP
  ]

def earlyBefore : List Instr := Artifact.submissionInstructions.take 3560
def earlyAfter : List Instr := Artifact.submissionInstructions.drop 3588

private theorem earlySplit : Artifact.submissionArtifact.instructions = earlyBefore ++ earlyProgram ++ earlyAfter := by
  rfl

private theorem earlyBeforeLength : earlyBefore.length = 3560 := by
  decide

private theorem earlyBeforePC : (assembleBytes earlyBefore).length = 4669 := by
  rfl

theorem earlyPcAt (i : Nat) (hi : i ≤ earlyProgram.length) :
    Artifact.submissionArtifact.instructionPC (3560 + i) =
      4669 + (assembleBytes (earlyProgram.take i)).length :=
  instructionPC_segment_of_bounds Artifact.submissionArtifact earlyBefore earlyProgram earlyAfter
    3560 4669 earlySplit earlyBeforeLength earlyBeforePC i hi

theorem earlyInstructionAt (i : Nat) (hi : i < earlyProgram.length) :
    Artifact.submissionArtifact.instructions[3560 + i]? = earlyProgram[i]? := by
  simpa only [earlyBeforeLength] using
    getElem?_segment Artifact.submissionArtifact earlyBefore earlyProgram earlyAfter earlySplit i hi

theorem earlyPcSuccSize (i size : Nat) (hi : i < earlyProgram.length)
    (hsize : (earlyProgram[i]?.map fun instruction => instruction.bytes.length) = some size) :
    Artifact.submissionArtifact.instructionPC ((3560 + i) + 1) =
      Artifact.submissionArtifact.instructionPC (3560 + i) + size := by
  cases hget : earlyProgram[i]? with
  | none => simp [hget] at hsize
  | some instruction =>
      have hs : instruction.bytes.length = size := by simpa [hget] using hsize
      simpa only [hs] using
        instructionPC_succ Artifact.submissionArtifact (3560 + i) instruction
          (by rw [earlyInstructionAt i hi, hget])

end Challenge.Modexp.Submission.Proofs.Bytecode.ShiftRegion
