import Challenge.Modexp.Submission.Proofs.Bytecode.Dispatch
import Challenge.Modexp.Submission.Proofs.Bytecode.WindowGuardLogic

set_option warningAsError true
set_option maxRecDepth 20000
set_option maxHeartbeats 2000000

/-!
# Contract for the fixed-width word window

The concrete execution proof for the appended fixed-width route is deliberately
kept behind this small interface.  The rest of the correctness proof only needs
to know that the route is entered from the reference header state, that a miss
restores the pre-existing one-word entry state, and that a hit returns the
specified result.

This file is a source-only scaffold.  A later execution module supplies the
three traces after the generated bytecode artifact has been refreshed.
-/

namespace Challenge.Modexp.Submission.Proofs.Bytecode.WindowRoute

open EvmSemantics
open EvmSemantics.EVM

/-- The exact declared-width predicate tested by the appended route. -/
abbrev Matches := WindowGuardLogic.Matches

/-- State immediately after entering the appended route at pc 3000. -/
abbrev entryState (input : ByteArray) : State :=
  Dispatch.wordRouteEntryState input

/-- A successful route execution, stated without exposing its final-state
implementation to the composition layer. -/
abbrev Handled (input : ByteArray) : Prop :=
  ∃ final : State,
    Nonempty (Challenge.EvmProof.GasSteps (entryState input) final) ∧
      final.isDone = true ∧ final.toResult = .returned (spec input)

/-- Control-flow proof interface of the appended route.

`enter` covers the changed tail of the old one-word dispatcher.  `miss` is the
critical fallback invariant: stack and memory are restored exactly to the
already-proved state at pc 517.
-/
structure Control where
  enter : ∀ input : ByteArray, ValidInput input →
    0 < modulusSize input → modulusSize input ≤ 32 →
    Dispatch.WordRouteEnter input
  miss : ∀ input : ByteArray, ValidInput input →
    0 < modulusSize input → modulusSize input ≤ 32 → ¬ Matches input →
    Dispatch.WordRouteMiss input

/-- The complete proof interface of the appended route. `hit` owns all new
arithmetic and output work; its control fields are proved independently. -/
structure Route extends Control where
  hit : ∀ input : ByteArray, ValidInput input →
    0 < modulusSize input → modulusSize input ≤ 32 → Matches input →
    Handled input

end Challenge.Modexp.Submission.Proofs.Bytecode.WindowRoute
