import Challenge.Modexp.Submission.Proofs.Bytecode.ArtifactChunks.Base

set_option warningAsError true
set_option maxRecDepth 40000
set_option maxHeartbeats 8000000

namespace Challenge.Modexp.Submission.Proofs.Bytecode.ArtifactChunks

open EvmSemantics EvmSemantics.EVM YulEvmCompiler
open Challenge.EvmProof

def instructions0 : List Instr :=
[
 .push 2 5189,
 .op .JUMP,
 .op .JUMPDEST,
 .op (.Dup { idx := 0 }),
 .op .CALLDATALOAD,
 .push 0 0,
 .op .BYTE,
 .op (.Swap { idx := 1 }),
 .op .POP,
 .op .POP,
 .op (.Swap { idx := 0 }),
 .op .JUMP,
 .op .JUMPDEST,
 .push 0 0,
 .op .JUMPDEST,
 .op (.Dup { idx := 2 }),
 .op (.Dup { idx := 1 }),
 .op .LT,
 .op .ISZERO,
 .push 1 41,
 .op .JUMPI,
 .push 0 0,
 .op (.Dup { idx := 1 }),
 .push 1 5,
 .op .SHL,
 .op (.Dup { idx := 3 }),
 .op .ADD,
 .op .MSTORE,
 .push 1 1,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Swap { idx := 0 }),
 .op .POP,
 .push 1 16,
 .op .JUMP,
 .op .JUMPDEST,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .JUMP,
 .op .JUMPDEST,
 .push 0 0,
 .op .JUMPDEST,
 .op (.Dup { idx := 3 }),
 .op (.Dup { idx := 1 }),
 .op .LT,
 .op .ISZERO,
 .push 1 79,
 .op .JUMPI,
 .op (.Dup { idx := 0 }),
 .push 1 5,
 .op .SHL,
 .op (.Dup { idx := 3 }),
 .op .ADD,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .push 1 5,
 .op .SHL,
 .op (.Dup { idx := 3 }),
 .op .ADD,
 .op .MSTORE,
 .push 1 1,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Swap { idx := 0 }),
 .op .POP,
 .push 1 48,
 .op .JUMP,
 .op .JUMPDEST,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .JUMP,
 .op .JUMPDEST,
 .op (.Dup { idx := 2 }),
 .push 0 0,
 .op .SUB,
 .push 0 0,
 .push 0 0,
 .op .JUMPDEST,
 .op (.Dup { idx := 7 }),
 .op (.Dup { idx := 1 }),
 .op .LT,
 .op .ISZERO,
 .push 1 149,
 .op .JUMPI,
 .op (.Dup { idx := 0 }),
 .push 1 5,
 .op .SHL,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 5 }),
 .op .ADD,
 .op .MLOAD,
 .op (.Dup { idx := 4 }),
 .op (.Dup { idx := 2 }),
 .op (.Dup { idx := 8 }),
 .op .ADD,
 .op .MLOAD,
 .op .AND,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op .LT,
 .op (.Dup { idx := 5 }),
 .op (.Dup { idx := 2 }),
 .op .ADD,
 .op (.Dup { idx := 2 }),
 .op (.Dup { idx := 1 }),
 .op .LT,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 6 }),
 .op (.Dup { idx := 11 }),
 .op .ADD,
 .op .MSTORE,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 3 }),
 .op .OR,
 .op (.Swap { idx := 7 }),
 .op .POP,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .POP,
 .push 1 1,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Swap { idx := 0 }),
 .op .POP,
 .push 1 91,
 .op .JUMP,
 .op .JUMPDEST,
 .op .POP,
 .push 0 0,
 .push 0 0,
 .op .JUMPDEST,
 .op (.Dup { idx := 8 }),
 .op (.Dup { idx := 1 }),
 .op .LT,
 .op .ISZERO,
 .push 1 213,
 .op .JUMPI,
 .op (.Dup { idx := 0 }),
 .push 1 5,
 .op .SHL,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 6 }),
 .op .ADD,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 10 }),
 .op .ADD,
 .op .MLOAD,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .SUB,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 3 }),
 .op .LT,
 .op (.Dup { idx := 6 }),
 .op (.Dup { idx := 2 }),
 .op .SUB,
 .op (.Dup { idx := 7 }),
 .op (.Dup { idx := 3 }),
 .op .LT,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 7 }),
 .push 2 1280,
 .op .ADD,
 .op .MSTORE,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 3 }),
 .op .OR,
 .op (.Swap { idx := 8 }),
 .op .POP,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .POP,
 .push 1 1,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Swap { idx := 0 }),
 .op .POP,
 .push 1 153,
 .op .JUMP,
 .op .JUMPDEST,
 .op .POP,
 .op (.Dup { idx := 0 }),
 .op .ISZERO,
 .op (.Dup { idx := 2 }),
 .op .OR,
 .push 0 0,
 .op .SUB,
 .push 0 0,
 .op .JUMPDEST,
 .op (.Dup { idx := 9 }),
 .op (.Dup { idx := 1 }),
 .op .LT,
 .op .ISZERO,
 .push 2 269,
 .op .JUMPI,
 .op (.Dup { idx := 0 }),
 .push 1 5,
 .op .SHL,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 7 }),
 .op .ADD,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .push 2 1280,
 .op .ADD,
 .op .MLOAD,
 .op (.Dup { idx := 4 }),
 .op .NOT,
 .op (.Dup { idx := 2 }),
 .op .AND,
 .op (.Dup { idx := 5 }),
 .op (.Dup { idx := 2 }),
 .op .AND,
 .op .OR,
 .op (.Dup { idx := 3 }),
 .op (.Dup { idx := 10 }),
 .op .ADD,
 .op .MSTORE,
 .op .POP,
 .op .POP,
 .op .POP,
 .push 1 1,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Swap { idx := 0 }),
 .op .POP,
 .push 1 222,
 .op .JUMP,
 .op .JUMPDEST,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .JUMP,
 .op .JUMPDEST,
 .push 2 290,
 .op (.Dup { idx := 5 }),
 .op (.Dup { idx := 4 }),
 .push 1 14,
 .op .JUMP,
 .op .JUMPDEST,
 .push 2 302,
 .op (.Dup { idx := 5 }),
 .op (.Dup { idx := 2 }),
 .push 2 1024,
 .push 1 46,
 .op .JUMP,
 .op .JUMPDEST,
 .push 0 0,
 .op .JUMPDEST,
 .op (.Dup { idx := 5 }),
 .op (.Dup { idx := 1 }),
 .op .LT,
 .op .ISZERO,
 .push 2 391,
 .op .JUMPI,
 .op (.Dup { idx := 0 }),
 .push 1 5,
 .op .SHL,
 .op (.Dup { idx := 3 }),
 .op .ADD,
 .op .MLOAD,
 .push 0 0,
 .op .JUMPDEST,
 .push 2 256,
 .op (.Dup { idx := 1 }),
 .op .LT,
 .op .ISZERO,
 .push 2 378,
 .op .JUMPI,
 .push 1 1,
 .op (.Dup { idx := 2 }),
 .op (.Dup { idx := 2 }),
 .op .SHR,
 .op .AND,
 .push 2 351,
 .op (.Dup { idx := 9 }),
 .op (.Dup { idx := 9 }),
 .op (.Dup { idx := 3 }),
 .push 2 1024,
 .op (.Dup { idx := 11 }),
 .push 1 85,
 .op .JUMP,
 .op .JUMPDEST,
 .push 2 366,
 .op (.Dup { idx := 9 }),
 .op (.Dup { idx := 9 }),
 .push 1 1,
 .push 2 1024,
 .op (.Dup { idx := 0 }),
 .push 1 85,
 .op .JUMP,
 .op .JUMPDEST,
 .op .POP,
 .push 1 1,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Swap { idx := 0 }),
 .op .POP,
 .push 2 321,
 .op .JUMP,
 .op .JUMPDEST,
 .op .POP,
 .op .POP,
 .push 1 1,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Swap { idx := 0 }),
 .op .POP,
 .push 2 304,
 .op .JUMP,
 .op .JUMPDEST,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .JUMP,
 .op .JUMPDEST,
 .push 0 0,
 .op .JUMPDEST,
 .op (.Dup { idx := 2 }),
 .op (.Dup { idx := 1 }),
 .op .LT,
 .op .ISZERO,
 .push 2 465,
 .op .JUMPI,
 .op (.Dup { idx := 0 }),
 .push 1 1,
 .op (.Dup { idx := 4 }),
 .op .SUB,
 .op .SUB,
 .op (.Dup { idx := 0 }),
 .push 1 5,
 .op .SHR,
 .push 1 31,
 .op (.Dup { idx := 2 }),
 .op .AND,
 .push 1 3,
 .op .SHL,
 .op (.Dup { idx := 1 }),
 .push 1 5,
 .op .SHL,
 .op (.Dup { idx := 7 }),
 .op .ADD,
 .push 2 443,
 .push 0 0,
 .op (.Dup { idx := 6 }),
 .op (.Dup { idx := 8 }),
 .op .ADD,
 .push 1 4,
 .op .JUMP,
 .op .JUMPDEST,
 .op (.Dup { idx := 2 }),
 .op .SHL,
 .op (.Dup { idx := 1 }),
 .op .MLOAD,
 .op .OR,
 .op (.Dup { idx := 1 }),
 .op .MSTORE,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .POP,
 .push 1 1,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Swap { idx := 0 }),
 .op .POP,
 .push 2 401,
 .op .JUMP,
 .op .JUMPDEST,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .JUMP,
 .op .JUMPDEST,
 .op (.Dup { idx := 5 }),
 .op .CALLDATALOAD,
 .op (.Dup { idx := 3 }),
 .push 1 32,
 .op .SUB,
 .push 1 3,
 .op .SHL,
 .op .SHR,
 .op (.Dup { idx := 0 }),
 .push 2 490,
 .op .JUMPI,
 .op (.Dup { idx := 3 }),
 .push 0 0,
 .op .RETURN,
 .op .JUMPDEST,
 .push 0 0,
 .push 0 0,
 .op .JUMPDEST,
 .op (.Dup { idx := 3 }),
 .op (.Dup { idx := 1 }),
 .op .LT,
 .op .ISZERO,
 .push 2 530,
 .op .JUMPI,
 .op (.Dup { idx := 2 }),
 .push 2 513,
 .push 0 0,
 .op (.Dup { idx := 3 }),
 .op (.Dup { idx := 10 }),
 .op .ADD,
 .push 1 4,
 .op .JUMP,
 .op .JUMPDEST,
 .op (.Dup { idx := 4 }),
 .push 2 256,
 .op (.Dup { idx := 5 }),
 .op .MULMOD,
 .op .ADDMOD,
 .op (.Swap { idx := 1 }),
 .op .POP,
 .push 1 1,
 .op .ADD,
 .push 2 493,
 .op .JUMP,
 .op .JUMPDEST,
 .op .POP,
 .op (.Dup { idx := 1 }),
 .push 1 1,
 .op .MOD,
 .push 0 0,
 .op .JUMPDEST,
 .op (.Dup { idx := 5 }),
 .op (.Dup { idx := 1 }),
 .op .EQ,
 .push 2 568,
 .op .JUMPI,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 9 }),
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .op .CALLDATALOAD,
 .push 0 0,
 .op .BYTE,
 .push 0 0,
 .push 2 2944,
 .op .JUMP,
 .op .JUMPDEST,
 .op .POP,
 .op .POP,
 .op .POP,
 .push 1 1,
 .op .ADD,
 .push 2 537,
 .op .JUMP,
 .op .JUMPDEST,
 .op .POP,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 6 }),
 .push 1 32,
 .op .SUB,
 .push 1 3,
 .op .SHL,
 .op .SHL,
 .push 0 0,
 .op .MSTORE,
 .op (.Dup { idx := 5 }),
 .push 0 0,
 .op .RETURN,
 .op .JUMPDEST,
 .push 1 31,
 .op (.Dup { idx := 3 }),
 .op .ADD,
 .push 1 5,
 .op .SHR,
 .push 2 600,
 .op (.Dup { idx := 1 }),
 .push 0 0,
 .push 1 14,
 .op .JUMP,
 .op .JUMPDEST,
 .push 2 611,
 .op (.Dup { idx := 1 }),
 .push 2 1024,
 .push 1 14,
 .op .JUMP,
 .op .JUMPDEST,
 .push 2 622,
 .op (.Dup { idx := 1 }),
 .push 2 512,
 .push 1 14,
 .op .JUMP,
 .op .JUMPDEST,
 .push 2 633,
 .op (.Dup { idx := 1 }),
 .push 2 1536,
 .push 1 14,
 .op .JUMP,
 .op .JUMPDEST,
 .push 2 644,
 .push 0 0,
 .op (.Dup { idx := 5 }),
 .op (.Dup { idx := 9 })
]

theorem count0 : instructions0.length = 520 := by
  decide

theorem assemble0 : assemble instructions0 = Challenge.Modexp.submissionSpan0 := by
  apply ByteArray.ext
  simp (config := { maxSteps := 600000 })
    [assemble, assembleBytes, instructions0, Challenge.Modexp.submissionSpan0,
      Instr.bytes, natToBE]
  repeat' apply And.intro
  all_goals decide

theorem wellFormed0 :
    instructions0.all (fun i => decide (Stepper.WellFormed .Osaka i)) = true := by
  simp (config := { maxSteps := 600000 })
    [instructions0, Stepper.WellFormed, YulEvmCompiler.plainOp]
  repeat' apply And.intro
  all_goals decide

end Challenge.Modexp.Submission.Proofs.Bytecode.ArtifactChunks
