import Challenge.Modexp.Submission.Proofs.Bytecode.ArtifactChunks.C0

set_option warningAsError true
set_option maxRecDepth 40000
set_option maxHeartbeats 8000000

namespace Challenge.Modexp.Submission.Proofs.Bytecode.ArtifactChunks

open EvmSemantics EvmSemantics.EVM YulEvmCompiler
open Challenge.EvmProof

def instructions1 : List Instr :=
[
 .push 2 399,
 .op .JUMP,
 .op .JUMPDEST,
 .push 0 0,
 .push 0 0,
 .op .JUMPDEST,
 .op (.Dup { idx := 2 }),
 .op (.Dup { idx := 1 }),
 .op .LT,
 .op .ISZERO,
 .push 2 675,
 .op .JUMPI,
 .op (.Dup { idx := 0 }),
 .push 1 5,
 .op .SHL,
 .op .MLOAD,
 .op (.Dup { idx := 2 }),
 .op .OR,
 .op (.Swap { idx := 1 }),
 .op .POP,
 .push 1 1,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Swap { idx := 0 }),
 .op .POP,
 .push 2 647,
 .op .JUMP,
 .op .JUMPDEST,
 .op .POP,
 .op (.Dup { idx := 0 }),
 .push 2 687,
 .op .JUMPI,
 .op (.Dup { idx := 4 }),
 .push 2 1536,
 .op .RETURN,
 .op .JUMPDEST,
 .push 2 698,
 .op (.Dup { idx := 2 }),
 .push 2 768,
 .push 1 14,
 .op .JUMP,
 .op .JUMPDEST,
 .push 1 1,
 .push 2 768,
 .op .MSTORE,
 .push 0 0,
 .op .JUMPDEST,
 .op (.Dup { idx := 3 }),
 .op (.Dup { idx := 1 }),
 .op .LT,
 .op .ISZERO,
 .push 2 796,
 .op .JUMPI,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 7 }),
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .op .CALLDATALOAD,
 .push 0 0,
 .op .BYTE,
 .push 0 0,
 .op .JUMPDEST,
 .push 1 8,
 .op (.Dup { idx := 1 }),
 .op .LT,
 .op .ISZERO,
 .push 2 782,
 .op .JUMPI,
 .push 2 747,
 .op (.Dup { idx := 6 }),
 .push 0 0,
 .push 1 1,
 .push 2 1024,
 .op (.Dup { idx := 0 }),
 .push 1 85,
 .op .JUMP,
 .op .JUMPDEST,
 .push 2 771,
 .op (.Dup { idx := 6 }),
 .push 0 0,
 .push 1 1,
 .op (.Dup { idx := 5 }),
 .op (.Dup { idx := 5 }),
 .push 1 7,
 .op .SUB,
 .op .SHR,
 .op .AND,
 .push 2 768,
 .push 2 1024,
 .push 1 85,
 .op .JUMP,
 .op .JUMPDEST,
 .push 1 1,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Swap { idx := 0 }),
 .op .POP,
 .push 2 723,
 .op .JUMP,
 .op .JUMPDEST,
 .op .POP,
 .op .POP,
 .op .POP,
 .push 1 1,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Swap { idx := 0 }),
 .op .POP,
 .push 2 706,
 .op .JUMP,
 .op .JUMPDEST,
 .op .POP,
 .push 2 814,
 .op (.Dup { idx := 2 }),
 .push 0 0,
 .push 1 1,
 .push 2 768,
 .push 2 512,
 .push 1 85,
 .op .JUMP,
 .op .JUMPDEST,
 .push 0 0,
 .op .JUMPDEST,
 .op (.Dup { idx := 4 }),
 .op (.Dup { idx := 1 }),
 .op .LT,
 .op .ISZERO,
 .push 2 985,
 .op .JUMPI,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 8 }),
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .op .CALLDATALOAD,
 .push 0 0,
 .op .BYTE,
 .push 0 0,
 .op .JUMPDEST,
 .push 1 8,
 .op (.Dup { idx := 1 }),
 .op .LT,
 .op .ISZERO,
 .push 2 971,
 .op .JUMPI,
 .push 1 1,
 .op (.Dup { idx := 2 }),
 .op (.Dup { idx := 2 }),
 .push 1 7,
 .op .SUB,
 .op .SHR,
 .op .AND,
 .push 2 868,
 .op (.Dup { idx := 7 }),
 .push 0 0,
 .push 2 768,
 .push 2 512,
 .op (.Dup { idx := 0 }),
 .push 2 281,
 .op .JUMP,
 .op .JUMPDEST,
 .push 2 882,
 .op (.Dup { idx := 7 }),
 .push 2 768,
 .push 2 512,
 .push 1 46,
 .op .JUMP,
 .op .JUMPDEST,
 .push 2 901,
 .op (.Dup { idx := 7 }),
 .push 0 0,
 .push 2 768,
 .push 2 256,
 .push 2 512,
 .push 2 281,
 .op .JUMP,
 .op .JUMPDEST,
 .op (.Dup { idx := 0 }),
 .push 0 0,
 .op .SUB,
 .push 0 0,
 .op .JUMPDEST,
 .op (.Dup { idx := 8 }),
 .op (.Dup { idx := 1 }),
 .op .LT,
 .op .ISZERO,
 .push 2 957,
 .op .JUMPI,
 .op (.Dup { idx := 0 }),
 .push 1 5,
 .op .SHL,
 .op (.Dup { idx := 0 }),
 .push 2 512,
 .op .ADD,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .push 2 768,
 .op .ADD,
 .op .MLOAD,
 .op (.Dup { idx := 4 }),
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 3 }),
 .op .XOR,
 .op .AND,
 .op (.Dup { idx := 2 }),
 .op .XOR,
 .op (.Dup { idx := 3 }),
 .push 2 512,
 .op .ADD,
 .op .MSTORE,
 .op .POP,
 .op .POP,
 .op .POP,
 .push 1 1,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Swap { idx := 0 }),
 .op .POP,
 .push 2 906,
 .op .JUMP,
 .op .JUMPDEST,
 .op .POP,
 .op .POP,
 .op .POP,
 .push 1 1,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Swap { idx := 0 }),
 .op .POP,
 .push 2 833,
 .op .JUMP,
 .op .JUMPDEST,
 .op .POP,
 .op .POP,
 .op .POP,
 .push 1 1,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Swap { idx := 0 }),
 .op .POP,
 .push 2 816,
 .op .JUMP,
 .op .JUMPDEST,
 .op .POP,
 .push 0 0,
 .op .JUMPDEST,
 .op (.Dup { idx := 5 }),
 .op (.Dup { idx := 1 }),
 .op .LT,
 .op .ISZERO,
 .push 2 1047,
 .op .JUMPI,
 .op (.Dup { idx := 0 }),
 .push 1 1,
 .op (.Dup { idx := 7 }),
 .op .SUB,
 .op .SUB,
 .op (.Dup { idx := 0 }),
 .push 1 5,
 .op .SHR,
 .push 1 31,
 .op (.Dup { idx := 2 }),
 .op .AND,
 .push 1 3,
 .op .SHL,
 .push 1 255,
 .op (.Dup { idx := 2 }),
 .push 1 5,
 .op .SHL,
 .push 2 512,
 .op .ADD,
 .op .MLOAD,
 .op (.Dup { idx := 2 }),
 .op .SHR,
 .op .AND,
 .op (.Dup { idx := 4 }),
 .push 2 1536,
 .op .ADD,
 .op .MSTORE8,
 .op .POP,
 .op .POP,
 .op .POP,
 .push 1 1,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Swap { idx := 0 }),
 .op .POP,
 .push 2 988,
 .op .JUMP,
 .op .JUMPDEST,
 .op .POP,
 .op (.Dup { idx := 4 }),
 .push 2 1536,
 .op .RETURN,
 .op .JUMPDEST,
 .push 0 0,
 .op .CALLDATALOAD,
 .push 1 32,
 .op .CALLDATALOAD,
 .push 3 64,
 .op .CALLDATALOAD,
 .op .JUMPDEST,
 .op .JUMPDEST,
 .op .JUMPDEST,
 .op (.Dup { idx := 0 }),
 .push 2 1076,
 .op .JUMPI,
 .push 0 0,
 .push 0 0,
 .op .RETURN,
 .op .JUMPDEST,
 .op (.Dup { idx := 2 }),
 .push 1 96,
 .op .ADD,
 .op (.Dup { idx := 2 }),
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .push 1 32,
 .op (.Dup { idx := 3 }),
 .op .GT,
 .push 2 1106,
 .op .JUMPI,
 .push 2 1186,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 3 }),
 .push 1 96,
 .op (.Dup { idx := 6 }),
 .op (.Dup { idx := 8 }),
 .op (.Dup { idx := 10 }),
 .push 2 2175,
 .op .JUMP,
 .op .JUMPDEST,
 .push 2 1202,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 3 }),
 .push 1 96,
 .op (.Dup { idx := 6 }),
 .op (.Dup { idx := 8 }),
 .op (.Dup { idx := 10 }),
 .push 2 584,
 .op .JUMP,
 .op .JUMPDEST,
 .push 1 64,
 .op .CALLDATALOAD,
 .op (.Dup { idx := 0 }),
 .push 1 33,
 .op .GT,
 .push 2 1581,
 .op .JUMPI,
 .push 1 32,
 .op .CALLDATALOAD,
 .push 0 0,
 .op .CALLDATALOAD,
 .op (.Dup { idx := 2 }),
 .push 1 31,
 .op .ADD,
 .push 1 5,
 .op .SHR,
 .op (.Dup { idx := 0 }),
 .push 1 5,
 .op .SHL,
 .op (.Dup { idx := 3 }),
 .op (.Dup { idx := 3 }),
 .op .ADD,
 .push 1 96,
 .op .ADD,
 .op (.Dup { idx := 5 }),
 .op (.Dup { idx := 2 }),
 .op .SUB,
 .push 1 3,
 .op .SHL,
 .op (.Dup { idx := 1 }),
 .op .CALLDATALOAD,
 .op (.Swap { idx := 0 }),
 .op .SHR,
 .op .ISZERO,
 .push 2 1587,
 .op .JUMPI,
 .push 1 32,
 .op (.Dup { idx := 6 }),
 .op (.Dup { idx := 2 }),
 .op .ADD,
 .op .SUB,
 .op .CALLDATALOAD,
 .push 1 1,
 .op .AND,
 .op .ISZERO,
 .push 2 1587,
 .op .JUMPI,
 .op (.Dup { idx := 1 }),
 .push 2 5248,
 .op .MSTORE,
 .op (.Dup { idx := 2 }),
 .push 2 5408,
 .op .MSTORE,
 .op (.Dup { idx := 3 }),
 .push 1 96,
 .op .ADD,
 .push 2 5376,
 .op .MSTORE,
 .push 1 32,
 .op (.Dup { idx := 2 }),
 .op .SUB,
 .op (.Dup { idx := 0 }),
 .push 2 5312,
 .op .MSTORE,
 .op (.Dup { idx := 2 }),
 .push 2 4128,
 .op .ADD,
 .push 2 5344,
 .op .MSTORE,
 .op (.Dup { idx := 2 }),
 .op .CALLDATASIZE,
 .push 0 0,
 .op .CALLDATACOPY,
 .op (.Dup { idx := 6 }),
 .op (.Dup { idx := 2 }),
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 5 }),
 .op .SUB,
 .op .CALLDATACOPY,
 .op (.Swap { idx := 0 }),
 .op .POP,
 .op (.Dup { idx := 0 }),
 .op .MLOAD,
 .op (.Dup { idx := 0 }),
 .push 1 2,
 .op .SUB,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .push 1 2,
 .op .SUB,
 .op .MUL,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .push 1 2,
 .op .SUB,
 .op .MUL,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .push 1 2,
 .op .SUB,
 .op .MUL,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .push 1 2,
 .op .SUB,
 .op .MUL,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .push 1 2,
 .op .SUB,
 .op .MUL,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .push 1 2,
 .op .SUB
]

theorem count1 : instructions1.length = 462 := by
  decide

theorem assemble1 : assemble instructions1 = Challenge.Modexp.submissionSpan1 := by
  apply ByteArray.ext
  simp (config := { maxSteps := 600000 })
    [assemble, assembleBytes, instructions1, Challenge.Modexp.submissionSpan1,
      Instr.bytes, natToBE]
  repeat' apply And.intro
  all_goals decide

theorem wellFormed1 :
    instructions1.all (fun i => decide (Stepper.WellFormed .Osaka i)) = true := by
  simp (config := { maxSteps := 600000 })
    [instructions1, Stepper.WellFormed, YulEvmCompiler.plainOp]
  repeat' apply And.intro
  all_goals decide

end Challenge.Modexp.Submission.Proofs.Bytecode.ArtifactChunks
