import Challenge.Modexp.Submission.Proofs.Bytecode.ArtifactChunks.C1

set_option warningAsError true
set_option maxRecDepth 40000
set_option maxHeartbeats 8000000

namespace Challenge.Modexp.Submission.Proofs.Bytecode.ArtifactChunks

open EvmSemantics EvmSemantics.EVM YulEvmCompiler
open Challenge.EvmProof

def instructions2 : List Instr :=
[
 .op .MUL,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .push 1 2,
 .op .SUB,
 .op .MUL,
 .push 0 0,
 .op .SUB,
 .push 2 5280,
 .op .MSTORE,
 .op .POP,
 .op .POP,
 .push 2 3302,
 .op .JUMP,
 .op .JUMPDEST,
 .push 2 5248,
 .op .MLOAD,
 .push 2 1024,
 .push 2 1280,
 .op .MCOPY,
 .push 2 2837,
 .push 2 1280,
 .push 2 3261,
 .op .JUMP,
 .op .JUMPDEST,
 .push 2 1337,
 .push 2 1536,
 .op (.Dup { idx := 0 }),
 .push 2 1536,
 .push 2 3912,
 .op .JUMP,
 .op .JUMPDEST,
 .op (.Dup { idx := 2 }),
 .op (.Dup { idx := 1 }),
 .op .SHR,
 .push 1 1,
 .op .AND,
 .push 2 256,
 .op .MUL,
 .push 2 1024,
 .op .ADD,
 .push 2 2151,
 .op .JUMP,
 .op .JUMPDEST,
 .op .POP,
 .op (.Dup { idx := 0 }),
 .op .ISZERO,
 .push 2 1371,
 .op .JUMPI,
 .push 0 0,
 .op .NOT,
 .op .ADD,
 .push 2 1322,
 .op .JUMP,
 .op .JUMPDEST,
 .op .POP,
 .op (.Dup { idx := 2 }),
 .op .ISZERO,
 .push 2 3138,
 .op .JUMPI,
 .push 2 2872,
 .op .JUMP,
 .op .JUMPDEST,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op .EQ,
 .push 2 1450,
 .op .JUMPI,
 .push 2 1407,
 .push 2 256,
 .push 2 1280,
 .push 2 256,
 .push 2 3912,
 .op .JUMP,
 .op .JUMPDEST,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .SUB,
 .push 1 5,
 .op .SHL,
 .op (.Dup { idx := 5 }),
 .op .SUB,
 .push 1 96,
 .op .ADD,
 .op .CALLDATALOAD,
 .op (.Dup { idx := 3 }),
 .push 2 736,
 .op .ADD,
 .op .MSTORE,
 .push 2 1442,
 .push 2 256,
 .push 2 768,
 .push 2 256,
 .push 2 1898,
 .op .JUMP,
 .op .JUMPDEST,
 .push 1 1,
 .op .ADD,
 .push 2 1383,
 .op .JUMP,
 .op .JUMPDEST,
 .op .POP,
 .op .POP,
 .push 2 1469,
 .push 2 512,
 .push 2 1536,
 .push 2 256,
 .push 2 3912,
 .op .JUMP,
 .op .JUMPDEST,
 .push 2 3138,
 .op .JUMP,
 .op .JUMPDEST,
 .op (.Dup { idx := 4 }),
 .op (.Dup { idx := 1 }),
 .op .EQ,
 .push 2 1545,
 .op .JUMPI,
 .push 2 2102,
 .op .JUMP,
 .op .JUMPDEST,
 .push 2 1501,
 .push 2 256,
 .op (.Dup { idx := 0 }),
 .push 2 256,
 .push 2 3912,
 .op .JUMP,
 .op .JUMPDEST,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op .AND,
 .op .ISZERO,
 .push 2 1527,
 .op .JUMPI,
 .push 2 1526,
 .push 2 256,
 .push 2 512,
 .push 2 256,
 .push 2 3912,
 .op .JUMP,
 .op .JUMPDEST,
 .op .JUMPDEST,
 .push 1 1,
 .op .SHR,
 .op (.Dup { idx := 0 }),
 .push 2 1486,
 .op .JUMPI,
 .op .POP,
 .op .POP,
 .push 1 1,
 .op .ADD,
 .push 2 1474,
 .op .JUMP,
 .op .JUMPDEST,
 .op .POP,
 .push 1 1,
 .op (.Dup { idx := 1 }),
 .push 2 736,
 .op .ADD,
 .op .MSTORE,
 .push 2 1571,
 .push 2 256,
 .push 2 768,
 .push 2 256,
 .push 2 3912,
 .op .JUMP,
 .op .JUMPDEST,
 .op (.Dup { idx := 4 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .push 2 256,
 .op .ADD,
 .op .SUB,
 .op .RETURN,
 .op .JUMPDEST,
 .op .POP,
 .push 2 1054,
 .op .JUMP,
 .op .JUMPDEST,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .POP,
 .push 2 1054,
 .op .JUMP,
 .op .JUMPDEST,
 .push 2 256,
 .op .JUMPDEST,
 .push 2 1613,
 .op (.Dup { idx := 2 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .push 2 1898,
 .op .JUMP,
 .op .JUMPDEST,
 .push 1 1,
 .op (.Swap { idx := 0 }),
 .op .SUB,
 .op (.Dup { idx := 0 }),
 .push 2 1602,
 .op .JUMPI,
 .op .POP,
 .op .POP,
 .op .JUMP,
 .op .JUMPDEST,
 .push 2 5248,
 .op .MLOAD,
 .op (.Dup { idx := 0 }),
 .push 1 64,
 .op .ADD,
 .op .CALLDATASIZE,
 .push 2 4096,
 .op .CALLDATACOPY,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 3 }),
 .op .ADD,
 .push 1 32,
 .op (.Swap { idx := 0 }),
 .op .SUB,
 .push 1 32,
 .op (.Dup { idx := 4 }),
 .op .SUB,
 .op (.Swap { idx := 3 }),
 .op .POP,
 .op (.Swap { idx := 0 }),
 .op .POP,
 .push 1 32,
 .op (.Dup { idx := 2 }),
 .op .SUB,
 .op (.Swap { idx := 1 }),
 .op .POP,
 .op .JUMPDEST,
 .op (.Dup { idx := 0 }),
 .op .MLOAD,
 .push 0 0,
 .push 2 5344,
 .op .MLOAD,
 .op (.Dup { idx := 4 }),
 .push 2 5248,
 .op .MLOAD,
 .op .ADD,
 .op .JUMPDEST,
 .op (.Dup { idx := 3 }),
 .op (.Dup { idx := 1 }),
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op .MUL,
 .op (.Swap { idx := 1 }),
 .push 0 0,
 .op .NOT,
 .op (.Swap { idx := 1 }),
 .op .MULMOD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op .LT,
 .op (.Dup { idx := 2 }),
 .op .ADD,
 .op (.Swap { idx := 0 }),
 .op .SUB,
 .op (.Dup { idx := 3 }),
 .op .MLOAD,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 2 }),
 .op .ADD,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 2 }),
 .op .LT,
 .op .ADD,
 .op (.Swap { idx := 0 }),
 .op (.Dup { idx := 4 }),
 .op .ADD,
 .op (.Swap { idx := 3 }),
 .op (.Dup { idx := 4 }),
 .op .LT,
 .op .ADD,
 .op (.Swap { idx := 2 }),
 .op (.Dup { idx := 2 }),
 .op .MSTORE,
 .push 1 31,
 .op .NOT,
 .op .ADD,
 .op (.Swap { idx := 0 }),
 .push 1 31,
 .op .NOT,
 .op .ADD,
 .op (.Swap { idx := 0 }),
 .op (.Dup { idx := 5 }),
 .op (.Dup { idx := 1 }),
 .op .GT,
 .push 2 1675,
 .op .JUMPI,
 .op .POP,
 .op .POP,
 .op (.Dup { idx := 0 }),
 .push 2 4128,
 .op .MLOAD,
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .push 2 4128,
 .op .MSTORE,
 .op .LT,
 .push 2 4096,
 .op .MSTORE,
 .push 2 5344,
 .op .MLOAD,
 .op .MLOAD,
 .push 2 5280,
 .op .MLOAD,
 .op .MUL,
 .op (.Dup { idx := 0 }),
 .push 2 5312,
 .op .MLOAD,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op .MUL,
 .op (.Swap { idx := 1 }),
 .push 0 0,
 .op .NOT,
 .op (.Swap { idx := 1 }),
 .op .MULMOD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op .LT,
 .op (.Dup { idx := 2 }),
 .op .ADD,
 .op (.Swap { idx := 0 }),
 .op .SUB,
 .op (.Swap { idx := 0 }),
 .push 0 0,
 .op .LT,
 .op .ADD,
 .push 2 5344,
 .op .MLOAD,
 .push 1 32,
 .op (.Swap { idx := 0 }),
 .op .SUB,
 .push 2 5312,
 .op .MLOAD,
 .push 1 32,
 .op (.Swap { idx := 0 }),
 .op .SUB,
 .op .JUMPDEST,
 .op (.Dup { idx := 0 }),
 .op .MLOAD,
 .push 0 0,
 .op .NOT,
 .op (.Dup { idx := 5 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 6 }),
 .op .MULMOD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op .LT,
 .op .SUB,
 .op (.Dup { idx := 4 }),
 .op (.Dup { idx := 2 }),
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .op (.Swap { idx := 5 }),
 .op .GT,
 .op .SUB,
 .op .SUB,
 .op (.Dup { idx := 3 }),
 .op (.Dup { idx := 3 }),
 .op .MLOAD,
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .op (.Swap { idx := 4 }),
 .op .GT,
 .op .ADD,
 .op (.Swap { idx := 2 }),
 .push 1 32,
 .op (.Dup { idx := 3 }),
 .push 1 31,
 .op .NOT,
 .op .ADD,
 .op (.Swap { idx := 3 }),
 .op .ADD,
 .op .MSTORE,
 .push 1 31,
 .op .NOT,
 .op .ADD,
 .push 2 4128,
 .op (.Dup { idx := 2 }),
 .op .GT,
 .push 2 1799,
 .op .JUMPI,
 .op .POP,
 .op .POP,
 .op (.Swap { idx := 1 }),
 .op .POP,
 .op .POP,
 .op (.Dup { idx := 0 }),
 .push 2 4128,
 .op .MLOAD,
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .push 2 4160,
 .op .MSTORE,
 .op .LT,
 .push 2 4096,
 .op .MLOAD,
 .op .ADD,
 .push 2 4128,
 .op .MSTORE,
 .push 1 31,
 .op .NOT,
 .op .ADD,
 .op (.Dup { idx := 2 }),
 .op (.Dup { idx := 1 }),
 .op .GT,
 .push 2 1661,
 .op .JUMPI,
 .op .POP,
 .op .POP,
 .op .POP,
 .push 2 4669,
 .op .JUMP,
 .op .JUMPDEST,
 .push 2 5248,
 .op .MLOAD,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .ADD,
 .push 1 32,
 .op (.Swap { idx := 0 }),
 .op .SUB,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 4 }),
 .op .ADD,
 .push 1 32,
 .op (.Swap { idx := 0 }),
 .op .SUB,
 .op (.Swap { idx := 2 }),
 .op .POP,
 .op (.Swap { idx := 2 })
]

theorem count2 : instructions2.length = 443 := by
  decide

theorem assemble2 : assemble instructions2 = Challenge.Modexp.submissionSpan2 := by
  apply ByteArray.ext
  simp (config := { maxSteps := 600000 })
    [assemble, assembleBytes, instructions2, Challenge.Modexp.submissionSpan2,
      Instr.bytes, natToBE]
  repeat' apply And.intro
  all_goals decide

theorem wellFormed2 :
    instructions2.all (fun i => decide (Stepper.WellFormed .Osaka i)) = true := by
  simp (config := { maxSteps := 600000 })
    [instructions2, Stepper.WellFormed, YulEvmCompiler.plainOp]
  repeat' apply And.intro
  all_goals decide

end Challenge.Modexp.Submission.Proofs.Bytecode.ArtifactChunks
