import Challenge.Modexp.Submission.Proofs.Bytecode.ArtifactChunks.C2

set_option warningAsError true
set_option maxRecDepth 40000
set_option maxHeartbeats 8000000

namespace Challenge.Modexp.Submission.Proofs.Bytecode.ArtifactChunks

open EvmSemantics EvmSemantics.EVM YulEvmCompiler
open Challenge.EvmProof

def instructions3 : List Instr :=
[
 .op .POP,
 .op .POP,
 .push 2 5344,
 .op .MLOAD,
 .push 0 0,
 .op (.Swap { idx := 2 }),
 .op (.Swap { idx := 0 }),
 .op .JUMPDEST,
 .op (.Dup { idx := 1 }),
 .op .MLOAD,
 .op (.Dup { idx := 3 }),
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Swap { idx := 0 }),
 .op (.Dup { idx := 1 }),
 .op .LT,
 .op (.Swap { idx := 0 }),
 .op (.Dup { idx := 5 }),
 .op .ADD,
 .op (.Swap { idx := 4 }),
 .op (.Dup { idx := 5 }),
 .op .LT,
 .op .OR,
 .op (.Swap { idx := 3 }),
 .op (.Dup { idx := 1 }),
 .op .MSTORE,
 .push 1 31,
 .op .NOT,
 .op .ADD,
 .op (.Swap { idx := 0 }),
 .push 1 31,
 .op .NOT,
 .op .ADD,
 .op (.Swap { idx := 0 }),
 .op (.Swap { idx := 1 }),
 .push 1 31,
 .op .NOT,
 .op .ADD,
 .op (.Swap { idx := 1 }),
 .push 2 4128,
 .op (.Dup { idx := 1 }),
 .op .GT,
 .push 2 1929,
 .op .JUMPI,
 .op .POP,
 .op .POP,
 .op .POP,
 .push 2 4128,
 .op .MSTORE,
 .push 2 4669,
 .op .JUMP,
 .op .JUMPDEST,
 .op (.Dup { idx := 0 }),
 .op .MLOAD,
 .op (.Dup { idx := 2 }),
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op .GT,
 .op (.Swap { idx := 1 }),
 .op .SUB,
 .op (.Dup { idx := 5 }),
 .op (.Dup { idx := 1 }),
 .op .SUB,
 .op (.Swap { idx := 0 }),
 .op (.Dup { idx := 6 }),
 .op .GT,
 .op (.Swap { idx := 0 }),
 .op (.Swap { idx := 1 }),
 .op .OR,
 .op (.Swap { idx := 4 }),
 .op .POP,
 .op (.Dup { idx := 3 }),
 .op .MSTORE,
 .push 1 31,
 .op .NOT,
 .op .ADD,
 .op (.Swap { idx := 0 }),
 .push 1 31,
 .op .NOT,
 .op .ADD,
 .op (.Swap { idx := 0 }),
 .op (.Swap { idx := 1 }),
 .push 1 31,
 .op .NOT,
 .op .ADD,
 .op (.Swap { idx := 1 }),
 .push 2 4128,
 .op (.Dup { idx := 1 }),
 .op .GT,
 .push 2 1985,
 .op .JUMPI,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .ISZERO,
 .push 2 4128,
 .op .MLOAD,
 .op .OR,
 .push 2 1087,
 .op .NOT,
 .op .MUL,
 .push 2 4160,
 .op .ADD,
 .push 2 5248,
 .op .MLOAD,
 .op (.Swap { idx := 1 }),
 .op .MCOPY,
 .op .JUMP,
 .op .JUMPDEST,
 .push 2 2069,
 .op (.Dup { idx := 2 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .push 2 3912,
 .op .JUMP,
 .op .JUMPDEST,
 .push 0 0,
 .op .NOT,
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .push 2 2058,
 .op .JUMPI,
 .op .POP,
 .op .POP,
 .op .JUMP,
 .op .JUMPDEST,
 .push 0 0,
 .op .MLOAD,
 .push 1 255,
 .op .SHR,
 .op .ISZERO,
 .push 2 1598,
 .op .JUMPI,
 .push 1 1,
 .push 2 4128,
 .op .MSTORE,
 .push 2 4669,
 .op .JUMP,
 .op .JUMPDEST,
 .op (.Dup { idx := 0 }),
 .push 2 5376,
 .op .MLOAD,
 .op .ADD,
 .op .CALLDATALOAD,
 .push 0 0,
 .op .BYTE,
 .op (.Dup { idx := 1 }),
 .op .ISZERO,
 .push 2 2124,
 .op .JUMPI,
 .push 1 128,
 .push 2 1486,
 .op .JUMP,
 .op .JUMPDEST,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .push 1 1,
 .op .SHR,
 .op .OR,
 .op (.Dup { idx := 0 }),
 .push 1 2,
 .op .SHR,
 .op .OR,
 .op (.Dup { idx := 0 }),
 .push 1 4,
 .op .SHR,
 .op .OR,
 .push 1 1,
 .op .SHR,
 .push 1 1,
 .op .ADD,
 .push 2 3111,
 .op .JUMP,
 .op .JUMPDEST,
 .op (.Dup { idx := 0 }),
 .push 2 1024,
 .op .EQ,
 .push 2 1356,
 .op .JUMPI,
 .push 2 1356,
 .push 2 1536,
 .op (.Dup { idx := 2 }),
 .push 2 1536,
 .push 2 3912,
 .op .JUMP,
 .op .JUMPDEST,
 .push 1 32,
 .op (.Dup { idx := 1 }),
 .op .GT,
 .op (.Dup { idx := 2 }),
 .push 1 32,
 .op .XOR,
 .op .OR,
 .op (.Dup { idx := 3 }),
 .push 1 32,
 .op .XOR,
 .op .OR,
 .op .ISZERO,
 .push 2 4841,
 .op .JUMPI,
 .push 2 471,
 .op .JUMP,
 .op .JUMPDEST,
 .op .JUMPDEST,
 .op .JUMPDEST,
 .op .JUMPDEST,
 .op (.Dup { idx := 0 }),
 .op .ISZERO,
 .push 2 2829,
 .op .JUMPI,
 .op (.Dup { idx := 4 }),
 .op .CALLDATALOAD,
 .op (.Dup { idx := 2 }),
 .push 1 32,
 .op .SUB,
 .push 1 3,
 .op .SHL,
 .op .SHR,
 .push 1 1,
 .push 0 0,
 .op .MSTORE,
 .op (.Dup { idx := 0 }),
 .push 1 32,
 .op .MSTORE,
 .op (.Dup { idx := 6 }),
 .op .CALLDATALOAD,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 14 }),
 .op (.Dup { idx := 15 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .push 1 64,
 .op .MSTORE,
 .op (.Dup { idx := 14 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .push 1 96,
 .op .MSTORE,
 .op (.Dup { idx := 13 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .push 1 128,
 .op .MSTORE,
 .op (.Dup { idx := 12 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .push 1 160,
 .op .MSTORE,
 .op (.Dup { idx := 11 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .push 1 192,
 .op .MSTORE,
 .op (.Dup { idx := 10 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .push 1 224,
 .op .MSTORE,
 .op (.Dup { idx := 9 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .push 2 256,
 .op .MSTORE,
 .op (.Dup { idx := 8 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .push 2 288,
 .op .MSTORE,
 .op (.Dup { idx := 7 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .push 2 320,
 .op .MSTORE,
 .op (.Dup { idx := 6 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .push 2 352,
 .op .MSTORE,
 .op (.Dup { idx := 5 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .push 2 384,
 .op .MSTORE,
 .op (.Dup { idx := 4 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .push 2 416,
 .op .MSTORE,
 .op (.Dup { idx := 3 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .push 2 448,
 .op .MSTORE,
 .op (.Dup { idx := 2 }),
 .op .MULMOD,
 .push 2 480,
 .op .MSTORE,
 .op .POP,
 .push 2 480,
 .op (.Dup { idx := 1 }),
 .push 1 247,
 .op .SHR,
 .op (.Dup { idx := 1 }),
 .op .AND,
 .op .MLOAD,
 .op (.Swap { idx := 1 }),
 .push 1 4,
 .op .SHL,
 .push 3 2,
 .op (.Swap { idx := 2 }),
 .op (.Dup { idx := 9 }),
 .op .CALLDATALOAD,
 .op (.Swap { idx := 0 }),
 .op .JUMPDEST,
 .op .JUMPDEST,
 .op .JUMPDEST,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Swap { idx := 14 }),
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 13 }),
 .push 1 247,
 .op .SHR,
 .op (.Dup { idx := 15 }),
 .op .AND,
 .op .MLOAD,
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 8 }),
 .push 1 243,
 .op .SHR,
 .op (.Dup { idx := 10 }),
 .op .AND,
 .op .MLOAD,
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 3 }),
 .push 1 239,
 .op .SHR,
 .op (.Dup { idx := 5 }),
 .op .AND,
 .op .MLOAD,
 .op .MULMOD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Swap { idx := 14 }),
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 13 }),
 .push 1 235,
 .op .SHR,
 .op (.Dup { idx := 15 }),
 .op .AND,
 .op .MLOAD,
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 8 }),
 .push 1 231,
 .op .SHR,
 .op (.Dup { idx := 10 }),
 .op .AND,
 .op .MLOAD,
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 3 }),
 .push 1 227,
 .op .SHR,
 .op (.Dup { idx := 5 }),
 .op .AND,
 .op .MLOAD,
 .op .MULMOD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Swap { idx := 14 }),
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 13 }),
 .push 1 223,
 .op .SHR,
 .op (.Dup { idx := 15 }),
 .op .AND,
 .op .MLOAD,
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 8 }),
 .push 1 219,
 .op .SHR,
 .op (.Dup { idx := 10 }),
 .op .AND,
 .op .MLOAD,
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 3 }),
 .push 1 215,
 .op .SHR,
 .op (.Dup { idx := 5 }),
 .op .AND,
 .op .MLOAD,
 .op .MULMOD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 })
]

theorem count3 : instructions3.length = 521 := by
  decide

theorem assemble3 : assemble instructions3 = Challenge.Modexp.submissionSpan3 := by
  apply ByteArray.ext
  simp (config := { maxSteps := 600000 })
    [assemble, assembleBytes, instructions3, Challenge.Modexp.submissionSpan3,
      Instr.bytes, natToBE]
  repeat' apply And.intro
  all_goals decide

theorem wellFormed3 :
    instructions3.all (fun i => decide (Stepper.WellFormed .Osaka i)) = true := by
  simp (config := { maxSteps := 600000 })
    [instructions3, Stepper.WellFormed, YulEvmCompiler.plainOp]
  repeat' apply And.intro
  all_goals decide

end Challenge.Modexp.Submission.Proofs.Bytecode.ArtifactChunks
