import Challenge.Modexp.Submission.Proofs.Bytecode.ArtifactChunks.C3

set_option warningAsError true
set_option maxRecDepth 40000
set_option maxHeartbeats 8000000

namespace Challenge.Modexp.Submission.Proofs.Bytecode.ArtifactChunks

open EvmSemantics EvmSemantics.EVM YulEvmCompiler
open Challenge.EvmProof

def instructions4 : List Instr :=
[
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Swap { idx := 14 }),
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 13 }),
 .push 1 211,
 .op .SHR,
 .op (.Dup { idx := 15 }),
 .op .AND,
 .op .MLOAD,
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 8 }),
 .push 1 207,
 .op .SHR,
 .op (.Dup { idx := 10 }),
 .op .AND,
 .op .MLOAD,
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 3 }),
 .push 1 203,
 .op .SHR,
 .op (.Dup { idx := 5 }),
 .op .AND,
 .op .MLOAD,
 .op .MULMOD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Swap { idx := 14 }),
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 13 }),
 .push 1 199,
 .op .SHR,
 .op (.Dup { idx := 15 }),
 .op .AND,
 .op .MLOAD,
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 8 }),
 .push 1 195,
 .op .SHR,
 .op (.Dup { idx := 10 }),
 .op .AND,
 .op .MLOAD,
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 3 }),
 .push 1 191,
 .op .SHR,
 .op (.Dup { idx := 5 }),
 .op .AND,
 .op .MLOAD,
 .op .MULMOD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Swap { idx := 14 }),
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 13 }),
 .push 1 187,
 .op .SHR,
 .op (.Dup { idx := 15 }),
 .op .AND,
 .op .MLOAD,
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 8 }),
 .push 1 183,
 .op .SHR,
 .op (.Dup { idx := 10 }),
 .op .AND,
 .op .MLOAD,
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 3 }),
 .push 1 179,
 .op .SHR,
 .op (.Dup { idx := 5 }),
 .op .AND,
 .op .MLOAD,
 .op .MULMOD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Swap { idx := 14 }),
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 13 }),
 .push 1 175,
 .op .SHR,
 .op (.Dup { idx := 15 }),
 .op .AND,
 .op .MLOAD,
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 8 }),
 .push 1 171,
 .op .SHR,
 .op (.Dup { idx := 10 }),
 .op .AND,
 .op .MLOAD,
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op (.Dup { idx := 3 }),
 .push 1 167,
 .op .SHR,
 .op (.Dup { idx := 5 }),
 .op .AND,
 .op .MLOAD,
 .op .MULMOD,
 .op (.Swap { idx := 1 }),
 .push 1 84,
 .op .SHL,
 .op (.Swap { idx := 1 }),
 .push 1 1,
 .op (.Dup { idx := 5 }),
 .op .SUB,
 .op (.Swap { idx := 4 }),
 .push 2 2360,
 .op .JUMPI,
 .push 0 0,
 .op .MSTORE,
 .push 1 32,
 .push 0 0,
 .op .RETURN,
 .op .JUMPDEST,
 .push 0 0,
 .push 0 0,
 .op .MSTORE,
 .push 1 32,
 .push 0 0,
 .op .RETURN,
 .op .JUMPDEST,
 .push 2 5248,
 .op .MLOAD,
 .push 2 1280,
 .push 2 1536,
 .op .MCOPY,
 .op (.Dup { idx := 1 }),
 .push 1 3,
 .op .LT,
 .op (.Dup { idx := 2 }),
 .push 1 7,
 .op .LT,
 .op (.Dup { idx := 3 }),
 .push 1 15,
 .op .LT,
 .op (.Dup { idx := 4 }),
 .push 1 31,
 .op .LT,
 .op .ADD,
 .op .ADD,
 .op .ADD,
 .push 2 1322,
 .op .JUMP,
 .op .JUMPDEST,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 3 }),
 .op .EQ,
 .push 0 0,
 .op .MLOAD,
 .push 1 255,
 .op .SHR,
 .op .AND,
 .op .ISZERO,
 .push 2 2910,
 .op .JUMPI,
 .op (.Dup { idx := 0 }),
 .push 1 96,
 .push 2 256,
 .op .CALLDATACOPY,
 .push 2 1469,
 .push 2 512,
 .push 2 256,
 .push 2 1536,
 .push 2 3912,
 .op .JUMP,
 .op .JUMPDEST,
 .op (.Dup { idx := 2 }),
 .push 1 31,
 .op .ADD,
 .push 1 5,
 .op .SHR,
 .op (.Dup { idx := 3 }),
 .op (.Dup { idx := 1 }),
 .push 1 5,
 .op .SHL,
 .op .SUB,
 .push 1 3,
 .op .SHL,
 .push 1 96,
 .op .CALLDATALOAD,
 .op (.Swap { idx := 0 }),
 .op .SHR,
 .op (.Dup { idx := 2 }),
 .push 2 224,
 .op .ADD,
 .op .MSTORE,
 .push 1 1,
 .push 2 1383,
 .op .JUMP,
 .op .JUMPDEST,
 .push 1 1,
 .op (.Dup { idx := 6 }),
 .op .SUB,
 .op (.Dup { idx := 7 }),
 .push 1 1,
 .op (.Dup { idx := 4 }),
 .push 1 7,
 .op .SHR,
 .op .AND,
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .push 1 1,
 .op .ADD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 8 }),
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op .MULMOD,
 .op (.Swap { idx := 5 }),
 .op .POP,
 .op (.Dup { idx := 7 }),
 .push 1 1,
 .op (.Dup { idx := 4 }),
 .push 1 6,
 .op .SHR,
 .op .AND,
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .push 1 1,
 .op .ADD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 8 }),
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op .MULMOD,
 .op (.Swap { idx := 5 }),
 .op .POP,
 .op (.Dup { idx := 7 }),
 .push 1 1,
 .op (.Dup { idx := 4 }),
 .push 1 5,
 .op .SHR,
 .op .AND,
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .push 1 1,
 .op .ADD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 8 }),
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op .MULMOD,
 .op (.Swap { idx := 5 }),
 .op .POP,
 .op (.Dup { idx := 7 }),
 .push 1 1,
 .op (.Dup { idx := 4 }),
 .push 1 4,
 .op .SHR,
 .op .AND,
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .push 1 1,
 .op .ADD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 8 }),
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op .MULMOD,
 .op (.Swap { idx := 5 }),
 .op .POP,
 .op (.Dup { idx := 7 }),
 .push 1 1,
 .op (.Dup { idx := 4 }),
 .push 1 3,
 .op .SHR,
 .op .AND,
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .push 1 1,
 .op .ADD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 8 }),
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op .MULMOD,
 .op (.Swap { idx := 5 }),
 .op .POP,
 .op (.Dup { idx := 7 }),
 .push 1 1,
 .op (.Dup { idx := 4 }),
 .push 1 2,
 .op .SHR,
 .op .AND,
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .push 1 1,
 .op .ADD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 8 }),
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op .MULMOD,
 .op (.Swap { idx := 5 }),
 .op .POP,
 .op (.Dup { idx := 7 }),
 .push 1 1,
 .op (.Dup { idx := 4 }),
 .push 1 1,
 .op .SHR,
 .op .AND,
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .push 1 1,
 .op .ADD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 8 }),
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op .MULMOD,
 .op (.Swap { idx := 5 }),
 .op .POP,
 .op (.Dup { idx := 7 }),
 .push 1 1,
 .op (.Dup { idx := 4 }),
 .op .AND,
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .push 1 1,
 .op .ADD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 8 }),
 .op (.Dup { idx := 0 }),
 .op .MULMOD,
 .op .MULMOD,
 .op (.Swap { idx := 5 }),
 .op .POP,
 .op .POP,
 .push 2 557,
 .op .JUMP,
 .op .JUMPDEST,
 .op (.Dup { idx := 1 }),
 .op .ISZERO,
 .push 2 3133,
 .op .JUMPI,
 .push 2 5248,
 .op .MLOAD,
 .push 2 512,
 .push 2 256,
 .op .MCOPY,
 .push 2 1527,
 .op .JUMP,
 .op .JUMPDEST,
 .push 2 1486,
 .op .JUMP,
 .op .JUMPDEST,
 .op (.Dup { idx := 3 }),
 .push 2 3144,
 .op .POP,
 .op .JUMPDEST,
 .push 1 3,
 .op .EQ,
 .push 2 3180,
 .op .JUMPI,
 .op (.Dup { idx := 3 }),
 .push 1 1,
 .op .XOR,
 .push 2 3247,
 .op .JUMPI,
 .push 2 5376,
 .op .MLOAD,
 .op .CALLDATALOAD,
 .push 0 0,
 .op .BYTE,
 .push 1 3,
 .op .XOR,
 .push 2 3247,
 .op .JUMPI,
 .push 1 1,
 .push 2 3200,
 .op .JUMP,
 .op .JUMPDEST,
 .push 2 5376,
 .op .MLOAD,
 .op .CALLDATALOAD,
 .push 1 232,
 .op .SHR,
 .push 3 65537,
 .op .XOR,
 .push 2 3247,
 .op .JUMPI,
 .push 1 16
]

theorem count4 : instructions4.length = 521 := by
  decide

theorem assemble4 : assemble instructions4 = Challenge.Modexp.submissionSpan4 := by
  apply ByteArray.ext
  simp (config := { maxSteps := 600000 })
    [assemble, assembleBytes, instructions4, Challenge.Modexp.submissionSpan4,
      Instr.bytes, natToBE]
  repeat' apply And.intro
  all_goals decide

theorem wellFormed4 :
    instructions4.all (fun i => decide (Stepper.WellFormed .Osaka i)) = true := by
  simp (config := { maxSteps := 600000 })
    [instructions4, Stepper.WellFormed, YulEvmCompiler.plainOp]
  repeat' apply And.intro
  all_goals decide

end Challenge.Modexp.Submission.Proofs.Bytecode.ArtifactChunks
