import Challenge.Modexp.Submission.Proofs.Bytecode.ArtifactChunks.C4

set_option warningAsError true
set_option maxRecDepth 40000
set_option maxHeartbeats 8000000

namespace Challenge.Modexp.Submission.Proofs.Bytecode.ArtifactChunks

open EvmSemantics EvmSemantics.EVM YulEvmCompiler
open Challenge.EvmProof

def instructions5 : List Instr :=
[
 .op .JUMPDEST,
 .op (.Dup { idx := 0 }),
 .push 2 5184,
 .op .MSTORE,
 .push 2 3221,
 .push 2 512,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .push 2 4788,
 .push 2 3916,
 .op .JUMP,
 .op .JUMPDEST,
 .push 1 1,
 .op (.Swap { idx := 0 }),
 .op .SUB,
 .op (.Dup { idx := 0 }),
 .push 2 3200,
 .op .JUMPI,
 .op .JUMPDEST,
 .op .POP,
 .push 2 1571,
 .push 2 256,
 .op (.Dup { idx := 0 }),
 .push 2 512,
 .push 2 3912,
 .op .JUMP,
 .op .JUMPDEST,
 .op (.Dup { idx := 0 }),
 .push 2 1024,
 .push 2 256,
 .op .MCOPY,
 .push 0 0,
 .push 2 1474,
 .op .JUMP,
 .op .JUMPDEST,
 .push 2 5248,
 .op .MLOAD,
 .push 1 128,
 .op .LT,
 .op (.Dup { idx := 0 }),
 .push 1 8,
 .op (.Swap { idx := 0 }),
 .op .SHL,
 .op .JUMPDEST,
 .push 2 3285,
 .op (.Dup { idx := 3 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .push 2 1898,
 .op .JUMP,
 .op .JUMPDEST,
 .push 0 0,
 .op .NOT,
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .push 2 3274,
 .op .JUMPI,
 .op .POP,
 .push 1 5,
 .op .SUB,
 .push 2 2058,
 .op .JUMP,
 .op .JUMPDEST,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 3 }),
 .op .EQ,
 .push 0 0,
 .op .MLOAD,
 .push 1 255,
 .op .SHR,
 .op .AND,
 .op .ISZERO,
 .push 2 3346,
 .op .JUMPI,
 .op (.Dup { idx := 0 }),
 .push 1 96,
 .push 2 256,
 .op .CALLDATACOPY,
 .op (.Dup { idx := 0 }),
 .push 1 96,
 .push 2 4160,
 .op .CALLDATACOPY,
 .push 0 0,
 .push 2 4128,
 .op .MSTORE,
 .push 2 3363,
 .push 2 512,
 .push 2 4669,
 .op .JUMP,
 .op .JUMPDEST,
 .push 1 1,
 .push 2 1024,
 .op .MSTORE,
 .push 2 1300,
 .push 2 1024,
 .push 2 2081,
 .op .JUMP,
 .op .JUMPDEST,
 .push 1 1,
 .push 2 5312,
 .op .MLOAD,
 .op .JUMPDEST,
 .op (.Dup { idx := 0 }),
 .op .MLOAD,
 .op .NOT,
 .op (.Dup { idx := 2 }),
 .op .ADD,
 .op (.Dup { idx := 2 }),
 .op (.Dup { idx := 1 }),
 .op .LT,
 .op (.Swap { idx := 2 }),
 .op .POP,
 .op (.Dup { idx := 1 }),
 .push 2 1280,
 .op .ADD,
 .op .MSTORE,
 .op (.Dup { idx := 0 }),
 .op .ISZERO,
 .push 2 3401,
 .op .JUMPI,
 .push 1 31,
 .op .NOT,
 .op .ADD,
 .push 2 3370,
 .op .JUMP,
 .op .JUMPDEST,
 .op .POP,
 .op .POP,
 .push 0 0,
 .op .MLOAD,
 .op (.Dup { idx := 0 }),
 .push 0 0,
 .op .SUB,
 .op (.Dup { idx := 1 }),
 .op .AND,
 .op (.Dup { idx := 0 }),
 .push 2 1536,
 .op .MSTORE,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .DIV,
 .op (.Dup { idx := 0 }),
 .push 2 1568,
 .op .MSTORE,
 .op (.Dup { idx := 1 }),
 .push 0 0,
 .op .SUB,
 .op (.Dup { idx := 2 }),
 .op (.Swap { idx := 0 }),
 .op .DIV,
 .push 1 1,
 .op .ADD,
 .push 2 1600,
 .op .MSTORE,
 .op (.Dup { idx := 0 }),
 .push 0 0,
 .op .SUB,
 .op (.Dup { idx := 1 }),
 .op (.Swap { idx := 0 }),
 .op .MOD,
 .push 2 1632,
 .op .MSTORE,
 .op (.Dup { idx := 0 }),
 .push 1 2,
 .op .SUB,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .push 1 2,
 .op .SUB,
 .op .MUL,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .push 1 2,
 .op .SUB,
 .op .MUL,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .push 1 2,
 .op .SUB,
 .op .MUL,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .push 1 2,
 .op .SUB,
 .op .MUL,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .push 1 2,
 .op .SUB,
 .op .MUL,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .push 1 2,
 .op .SUB,
 .op .MUL,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .push 1 2,
 .op .SUB,
 .op .MUL,
 .push 2 1664,
 .op .MSTORE,
 .op .POP,
 .op .POP,
 .op .POP,
 .op (.Dup { idx := 1 }),
 .op .JUMPDEST,
 .op (.Dup { idx := 0 }),
 .op .ISZERO,
 .push 2 3895,
 .op .JUMPI,
 .op (.Dup { idx := 1 }),
 .push 2 512,
 .push 2 4128,
 .op .MCOPY,
 .push 0 0,
 .push 2 5344,
 .op .MLOAD,
 .op .MSTORE,
 .push 2 512,
 .op .MLOAD,
 .push 2 1536,
 .op .MLOAD,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .DIV,
 .op (.Swap { idx := 1 }),
 .op .MOD,
 .push 2 1600,
 .op .MLOAD,
 .op .MUL,
 .push 2 544,
 .op .MLOAD,
 .push 2 1536,
 .op .MLOAD,
 .op (.Swap { idx := 0 }),
 .op .DIV,
 .op .ADD,
 .push 2 1568,
 .op .MLOAD,
 .op (.Dup { idx := 0 }),
 .push 2 1632,
 .op .MLOAD,
 .op (.Dup { idx := 4 }),
 .op .MULMOD,
 .op (.Dup { idx := 2 }),
 .op .ADDMOD,
 .op (.Swap { idx := 0 }),
 .op .SUB,
 .push 2 1664,
 .op .MLOAD,
 .op .MUL,
 .op (.Dup { idx := 0 }),
 .push 0 0,
 .op .MLOAD,
 .op .MUL,
 .push 2 544,
 .op .MLOAD,
 .op .SUB,
 .push 1 32,
 .op .MLOAD,
 .push 1 128,
 .op .SHR,
 .op (.Dup { idx := 2 }),
 .push 1 128,
 .op .SHR,
 .op .MUL,
 .op .GT,
 .op (.Swap { idx := 0 }),
 .op .SUB,
 .op (.Swap { idx := 0 }),
 .push 2 1568,
 .op .MLOAD,
 .op .GT,
 .op .ISZERO,
 .push 0 0,
 .op .SUB,
 .op .OR,
 .push 0 0,
 .push 2 5344,
 .op .MLOAD,
 .push 2 5312,
 .op .MLOAD,
 .push 2 1280,
 .op .ADD,
 .op .JUMPDEST,
 .op (.Dup { idx := 0 }),
 .op .MLOAD,
 .push 0 0,
 .op .NOT,
 .op (.Dup { idx := 5 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 6 }),
 .op .MULMOD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op .LT,
 .op .SUB,
 .op (.Dup { idx := 4 }),
 .op (.Dup { idx := 2 }),
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .op (.Swap { idx := 5 }),
 .op .GT,
 .op .SUB,
 .op .SUB,
 .op (.Dup { idx := 3 }),
 .op (.Dup { idx := 3 }),
 .op .MLOAD,
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .op (.Swap { idx := 4 }),
 .op .GT,
 .op .ADD,
 .op (.Swap { idx := 2 }),
 .op (.Dup { idx := 2 }),
 .push 1 31,
 .op .NOT,
 .op .ADD,
 .op (.Swap { idx := 2 }),
 .op .MSTORE,
 .push 32 115792089237316195423570985008687907853269984665640564039457584007913129639904,
 .op .ADD,
 .push 2 4128,
 .op (.Dup { idx := 2 }),
 .op .GT,
 .push 2 3624,
 .op .JUMPI,
 .op .POP,
 .op .POP,
 .push 2 4128,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op .LT,
 .op (.Swap { idx := 1 }),
 .op .POP,
 .op (.Dup { idx := 2 }),
 .op (.Dup { idx := 1 }),
 .op .LT,
 .op (.Swap { idx := 0 }),
 .op (.Dup { idx := 3 }),
 .op (.Swap { idx := 0 }),
 .op .SUB,
 .op (.Dup { idx := 0 }),
 .push 2 4128,
 .op .MSTORE,
 .op .POP,
 .op .GT,
 .op (.Swap { idx := 0 }),
 .op .POP,
 .op .ISZERO,
 .push 2 3807,
 .op .JUMPI,
 .op .JUMPDEST,
 .push 0 0,
 .push 2 5344,
 .op .MLOAD,
 .op .JUMPDEST,
 .op (.Dup { idx := 0 }),
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .push 2 4160,
 .op (.Swap { idx := 0 }),
 .op .SUB,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .GT,
 .op (.Swap { idx := 1 }),
 .op .POP,
 .op (.Dup { idx := 3 }),
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 4 }),
 .op .GT,
 .op (.Swap { idx := 3 }),
 .op .POP,
 .op (.Dup { idx := 2 }),
 .op .MSTORE,
 .op (.Swap { idx := 0 }),
 .op (.Swap { idx := 1 }),
 .op .OR,
 .op (.Swap { idx := 0 }),
 .push 1 31,
 .op .NOT,
 .op .ADD,
 .push 2 4159,
 .op (.Dup { idx := 1 }),
 .op .GT,
 .push 2 3746,
 .op .JUMPI,
 .op .POP,
 .push 2 4128,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .push 2 4128,
 .op .MSTORE,
 .op .LT,
 .op .ISZERO,
 .push 2 3740,
 .op .JUMPI,
 .op .JUMPDEST,
 .push 2 4128,
 .op .MLOAD,
 .op .ISZERO,
 .push 2 3875,
 .op .JUMPI,
 .push 0 0,
 .push 2 5344,
 .op .MLOAD,
 .op .JUMPDEST,
 .op (.Dup { idx := 0 }),
 .op .MLOAD,
 .push 2 4160,
 .op (.Dup { idx := 2 }),
 .op .SUB,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op .GT,
 .op (.Swap { idx := 1 }),
 .op .SUB,
 .op (.Dup { idx := 3 }),
 .op (.Dup { idx := 1 }),
 .op .LT,
 .op (.Swap { idx := 0 })
]

theorem count5 : instructions5.length = 442 := by
  decide

theorem assemble5 : assemble instructions5 = Challenge.Modexp.submissionSpan5 := by
  apply ByteArray.ext
  simp (config := { maxSteps := 600000 })
    [assemble, assembleBytes, instructions5, Challenge.Modexp.submissionSpan5,
      Instr.bytes, natToBE]
  repeat' apply And.intro
  all_goals decide

theorem wellFormed5 :
    instructions5.all (fun i => decide (Stepper.WellFormed .Osaka i)) = true := by
  simp (config := { maxSteps := 600000 })
    [instructions5, Stepper.WellFormed, YulEvmCompiler.plainOp]
  repeat' apply And.intro
  all_goals decide

end Challenge.Modexp.Submission.Proofs.Bytecode.ArtifactChunks
