import Challenge.Modexp.Submission.Proofs.Bytecode.ArtifactChunks.C5

set_option warningAsError true
set_option maxRecDepth 40000
set_option maxHeartbeats 8000000

namespace Challenge.Modexp.Submission.Proofs.Bytecode.ArtifactChunks

open EvmSemantics EvmSemantics.EVM YulEvmCompiler
open Challenge.EvmProof

def instructions6 : List Instr :=
[
 .op (.Dup { idx := 4 }),
 .op (.Swap { idx := 0 }),
 .op .SUB,
 .op (.Dup { idx := 3 }),
 .op .MSTORE,
 .op .OR,
 .op (.Swap { idx := 1 }),
 .op .POP,
 .push 1 31,
 .op .NOT,
 .op .ADD,
 .push 2 4159,
 .op (.Dup { idx := 1 }),
 .op .GT,
 .push 2 3822,
 .op .JUMPI,
 .op .POP,
 .push 2 4128,
 .op .MLOAD,
 .op .SUB,
 .push 2 4128,
 .op .MSTORE,
 .push 2 3807,
 .op .JUMP,
 .op .JUMPDEST,
 .push 2 3886,
 .push 2 512,
 .push 2 4669,
 .op .JUMP,
 .op .JUMPDEST,
 .push 0 0,
 .op .NOT,
 .op .ADD,
 .push 3 3508,
 .op .JUMP,
 .op .JUMPDEST,
 .op .POP,
 .push 2 5248,
 .op .MLOAD,
 .push 2 1280,
 .push 2 1024,
 .op .MCOPY,
 .push 2 3138,
 .op .JUMP,
 .op .JUMPDEST,
 .push 2 4029,
 .op .JUMPDEST,
 .push 2 5248,
 .op .MLOAD,
 .op (.Dup { idx := 0 }),
 .push 1 128,
 .op .EQ,
 .op (.Swap { idx := 0 }),
 .push 2 256,
 .op .EQ,
 .op .OR,
 .push 2 3940,
 .op .JUMPI,
 .op .POP,
 .push 2 1626,
 .op .JUMP,
 .op .JUMPDEST,
 .push 1 96,
 .op .MLOAD,
 .push 2 5344,
 .op .MLOAD,
 .push 2 5312,
 .op .MLOAD,
 .op .MLOAD,
 .push 2 5280,
 .op .MLOAD,
 .push 2 5312,
 .op .MLOAD,
 .op (.Dup { idx := 6 }),
 .op .ADD,
 .push 1 32,
 .op .MLOAD,
 .push 1 31,
 .op .NOT,
 .push 2 5248,
 .op .MLOAD,
 .push 1 128,
 .op .EQ,
 .push 1 152,
 .op .MUL,
 .push 2 4060,
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .push 2 299,
 .op .ADD,
 .op (.Swap { idx := 3 }),
 .op (.Swap { idx := 10 }),
 .push 0 0,
 .op .NOT,
 .op (.Swap { idx := 3 }),
 .op (.Swap { idx := 10 }),
 .push 1 64,
 .op .MLOAD,
 .op (.Swap { idx := 10 }),
 .push 2 5248,
 .op .MLOAD,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 2 }),
 .op (.Swap { idx := 0 }),
 .push 2 4864,
 .op .MCOPY,
 .op (.Dup { idx := 1 }),
 .push 1 64,
 .op .ADD,
 .op .CALLDATASIZE,
 .push 2 4096,
 .op .CALLDATACOPY,
 .op (.Swap { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .ADD,
 .op (.Dup { idx := 4 }),
 .op .ADD,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 4 }),
 .op .ADD,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op .JUMP,
 .op .JUMPDEST,
 .op (.Dup { idx := 0 }),
 .op .MLOAD,
 .op (.Dup { idx := 14 }),
 .op .MLOAD,
 .op (.Dup { idx := 7 }),
 .op (.Dup { idx := 2 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 3 }),
 .op .MULMOD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op .LT,
 .op (.Dup { idx := 2 }),
 .op (.Swap { idx := 1 }),
 .op .SUB,
 .op .SUB,
 .op (.Swap { idx := 0 }),
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 13 }),
 .op .MLOAD,
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 14 }),
 .op .MSTORE,
 .op .LT,
 .op .ADD,
 .op (.Dup { idx := 5 }),
 .op .JUMP,
 .op .JUMPDEST,
 .push 2 5056,
 .op .MLOAD,
 .op (.Dup { idx := 8 }),
 .op (.Dup { idx := 3 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 4 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .GT,
 .op .SUB,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 3 }),
 .op .ADD,
 .push 3 4352,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .push 2 4352,
 .op .MSTORE,
 .op (.Dup { idx := 1 }),
 .op .GT,
 .op (.Swap { idx := 3 }),
 .op .GT,
 .op .SUB,
 .op .SUB,
 .op .ADD,
 .op .JUMPDEST,
 .push 2 5024,
 .op .MLOAD,
 .op (.Dup { idx := 8 }),
 .op (.Dup { idx := 3 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 4 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .GT,
 .op .SUB,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 3 }),
 .op .ADD,
 .push 3 4320,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .push 2 4320,
 .op .MSTORE,
 .op (.Dup { idx := 1 }),
 .op .GT,
 .op (.Swap { idx := 3 }),
 .op .GT,
 .op .SUB,
 .op .SUB,
 .op .ADD,
 .op .JUMPDEST,
 .push 2 4992,
 .op .MLOAD,
 .op (.Dup { idx := 8 }),
 .op (.Dup { idx := 3 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 4 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .GT,
 .op .SUB,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 3 }),
 .op .ADD,
 .push 3 4288,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .push 2 4288,
 .op .MSTORE,
 .op (.Dup { idx := 1 }),
 .op .GT,
 .op (.Swap { idx := 3 }),
 .op .GT,
 .op .SUB,
 .op .SUB,
 .op .ADD,
 .op .JUMPDEST,
 .push 2 4960,
 .op .MLOAD,
 .op (.Dup { idx := 8 }),
 .op (.Dup { idx := 3 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 4 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .GT,
 .op .SUB,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 3 }),
 .op .ADD,
 .push 3 4256,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .push 2 4256,
 .op .MSTORE,
 .op (.Dup { idx := 1 }),
 .op .GT,
 .op (.Swap { idx := 3 }),
 .op .GT,
 .op .SUB,
 .op .SUB,
 .op .ADD,
 .op .JUMPDEST,
 .push 2 4928,
 .op .MLOAD,
 .op (.Dup { idx := 8 }),
 .op (.Dup { idx := 3 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 4 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .GT,
 .op .SUB,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 3 }),
 .op .ADD,
 .push 3 4224,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .push 2 4224,
 .op .MSTORE,
 .op (.Dup { idx := 1 }),
 .op .GT,
 .op (.Swap { idx := 3 }),
 .op .GT,
 .op .SUB,
 .op .SUB,
 .op .ADD,
 .op .JUMPDEST,
 .push 2 4896,
 .op .MLOAD,
 .op (.Dup { idx := 8 }),
 .op (.Dup { idx := 3 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 4 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .GT,
 .op .SUB,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 3 }),
 .op .ADD,
 .push 3 4192,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .push 2 4192,
 .op .MSTORE,
 .op (.Dup { idx := 1 }),
 .op .GT,
 .op (.Swap { idx := 3 }),
 .op .GT,
 .op .SUB,
 .op .SUB,
 .op .ADD,
 .op .JUMPDEST,
 .push 2 4864,
 .op .MLOAD,
 .op (.Dup { idx := 8 }),
 .op (.Dup { idx := 3 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 4 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .GT,
 .op .SUB,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 3 }),
 .op .ADD,
 .push 3 4160,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .push 2 4160,
 .op .MSTORE,
 .op (.Dup { idx := 1 }),
 .op .GT,
 .op (.Swap { idx := 3 }),
 .op .GT,
 .op .SUB,
 .op .SUB,
 .op .ADD,
 .op .JUMPDEST,
 .op (.Dup { idx := 0 }),
 .push 2 4128,
 .op .MLOAD,
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .push 2 4128,
 .op .MSTORE,
 .op .LT,
 .op (.Swap { idx := 0 }),
 .op .POP,
 .op (.Dup { idx := 10 }),
 .op .MLOAD,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 10 }),
 .op .MUL,
 .op (.Swap { idx := 0 }),
 .op (.Dup { idx := 8 }),
 .op (.Dup { idx := 2 }),
 .op (.Dup { idx := 13 }),
 .op .MULMOD,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .op (.Swap { idx := 1 }),
 .op .GT,
 .op .ADD,
 .op (.Dup { idx := 9 }),
 .op .JUMP,
 .op .JUMPDEST,
 .push 10 192,
 .op .MLOAD,
 .op (.Dup { idx := 9 }),
 .op (.Dup { idx := 3 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 4 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .GT,
 .op .SUB,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 3 }),
 .op .ADD,
 .push 3 4352,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .push 2 4384,
 .op .MSTORE,
 .op (.Dup { idx := 1 }),
 .op .GT,
 .op (.Swap { idx := 3 }),
 .op .GT,
 .op .SUB,
 .op .SUB,
 .op .ADD,
 .push 1 160,
 .op .MLOAD,
 .op (.Dup { idx := 9 }),
 .op (.Dup { idx := 3 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 4 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .GT,
 .op .SUB,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 3 }),
 .op .ADD,
 .push 3 4320,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .push 2 4352,
 .op .MSTORE,
 .op (.Dup { idx := 1 }),
 .op .GT,
 .op (.Swap { idx := 3 }),
 .op .GT,
 .op .SUB,
 .op .SUB,
 .op .ADD,
 .push 1 128,
 .op .MLOAD,
 .op (.Dup { idx := 9 }),
 .op (.Dup { idx := 3 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 4 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .GT,
 .op .SUB,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 3 }),
 .op .ADD,
 .push 3 4288,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .push 2 4320,
 .op .MSTORE,
 .op (.Dup { idx := 1 }),
 .op .GT,
 .op (.Swap { idx := 3 }),
 .op .GT,
 .op .SUB,
 .op .SUB,
 .op .ADD,
 .op (.Dup { idx := 13 }),
 .op (.Dup { idx := 9 }),
 .op (.Dup { idx := 3 })
]

theorem count6 : instructions6.length = 494 := by
  decide

theorem assemble6 : assemble instructions6 = Challenge.Modexp.submissionSpan6 := by
  apply ByteArray.ext
  simp (config := { maxSteps := 600000 })
    [assemble, assembleBytes, instructions6, Challenge.Modexp.submissionSpan6,
      Instr.bytes, natToBE]
  repeat' apply And.intro
  all_goals decide

theorem wellFormed6 :
    instructions6.all (fun i => decide (Stepper.WellFormed .Osaka i)) = true := by
  simp (config := { maxSteps := 600000 })
    [instructions6, Stepper.WellFormed, YulEvmCompiler.plainOp]
  repeat' apply And.intro
  all_goals decide

end Challenge.Modexp.Submission.Proofs.Bytecode.ArtifactChunks
