import Challenge.Modexp.Submission.Proofs.Bytecode.ArtifactChunks.C6

set_option warningAsError true
set_option maxRecDepth 40000
set_option maxHeartbeats 8000000

namespace Challenge.Modexp.Submission.Proofs.Bytecode.ArtifactChunks

open EvmSemantics EvmSemantics.EVM YulEvmCompiler
open Challenge.EvmProof

def instructions7 : List Instr :=
[
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 4 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .GT,
 .op .SUB,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 3 }),
 .op .ADD,
 .push 3 4256,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .push 2 4288,
 .op .MSTORE,
 .op (.Dup { idx := 1 }),
 .op .GT,
 .op (.Swap { idx := 3 }),
 .op .GT,
 .op .SUB,
 .op .SUB,
 .op .ADD,
 .op .JUMPDEST,
 .op (.Dup { idx := 14 }),
 .op (.Dup { idx := 9 }),
 .op (.Dup { idx := 3 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 4 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .GT,
 .op .SUB,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 3 }),
 .op .ADD,
 .push 3 4224,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .push 2 4256,
 .op .MSTORE,
 .op (.Dup { idx := 1 }),
 .op .GT,
 .op (.Swap { idx := 3 }),
 .op .GT,
 .op .SUB,
 .op .SUB,
 .op .ADD,
 .op (.Dup { idx := 15 }),
 .op (.Dup { idx := 9 }),
 .op (.Dup { idx := 3 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 4 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .GT,
 .op .SUB,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 3 }),
 .op .ADD,
 .push 3 4192,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .push 2 4224,
 .op .MSTORE,
 .op (.Dup { idx := 1 }),
 .op .GT,
 .op (.Swap { idx := 3 }),
 .op .GT,
 .op .SUB,
 .op .SUB,
 .op .ADD,
 .push 0 0,
 .op .MLOAD,
 .op (.Dup { idx := 9 }),
 .op (.Dup { idx := 3 }),
 .op (.Dup { idx := 2 }),
 .op .MUL,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 4 }),
 .op .MULMOD,
 .op (.Dup { idx := 0 }),
 .op (.Dup { idx := 2 }),
 .op .GT,
 .op .SUB,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 3 }),
 .op .ADD,
 .push 3 4160,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .push 2 4192,
 .op .MSTORE,
 .op (.Dup { idx := 1 }),
 .op .GT,
 .op (.Swap { idx := 3 }),
 .op .GT,
 .op .SUB,
 .op .SUB,
 .op .ADD,
 .op (.Swap { idx := 0 }),
 .op .POP,
 .op (.Dup { idx := 0 }),
 .push 2 4128,
 .op .MLOAD,
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .push 2 4160,
 .op .MSTORE,
 .op .LT,
 .op .ADD,
 .push 2 4128,
 .op .MSTORE,
 .op (.Dup { idx := 4 }),
 .op .ADD,
 .op (.Dup { idx := 2 }),
 .op (.Dup { idx := 1 }),
 .op .GT,
 .op (.Dup { idx := 2 }),
 .op .JUMPI,
 .op (.Dup { idx := 1 }),
 .push 2 4788,
 .op .EQ,
 .push 2 4712,
 .op .JUMPI,
 .op .JUMPDEST,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .POP,
 .op .POP,
 .push 2 4669,
 .op .POP,
 .op .JUMPDEST,
 .push 0 0,
 .op .MLOAD,
 .push 2 4160,
 .op .MLOAD,
 .op .LT,
 .push 2 4128,
 .op .MLOAD,
 .op .ISZERO,
 .op .AND,
 .push 2 5165,
 .op .JUMPI,
 .push 2 4925,
 .op .JUMP,
 .op .JUMPDEST,
 .push 2 4256,
 .op .MLOAD,
 .push 1 96,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op .GT,
 .op (.Swap { idx := 1 }),
 .op .SUB,
 .push 2 3168,
 .op .MSTORE,
 .push 2 5082,
 .op .JUMP,
 .op .JUMPDEST,
 .push 3 5184,
 .op .MLOAD,
 .op (.Dup { idx := 6 }),
 .op .JUMPDEST,
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .push 2 5184,
 .op .MSTORE,
 .push 2 4739,
 .op .JUMPI,
 .push 2 3231,
 .op (.Swap { idx := 15 }),
 .op .POP,
 .push 2 4650,
 .op .JUMP,
 .op .JUMPDEST,
 .push 2 4755,
 .op (.Dup { idx := 15 }),
 .push 2 4669,
 .op .JUMP,
 .op .JUMPDEST,
 .op .JUMPDEST,
 .op .JUMPDEST,
 .op .JUMPDEST,
 .op .JUMPDEST,
 .op .JUMPDEST,
 .op .JUMPDEST,
 .op .JUMPDEST,
 .push 2 5248,
 .op .MLOAD,
 .op (.Dup { idx := 0 }),
 .push 2 512,
 .push 2 4864,
 .op .MCOPY,
 .op (.Dup { idx := 0 }),
 .push 1 64,
 .op .ADD,
 .op .CALLDATASIZE,
 .push 2 4096,
 .op .CALLDATACOPY,
 .op .ADD,
 .push 2 299,
 .op (.Dup { idx := 7 }),
 .op .SUB,
 .op (.Swap { idx := 3 }),
 .op .POP,
 .push 0 0,
 .op (.Swap { idx := 13 }),
 .op .POP,
 .op .JUMPDEST,
 .op (.Dup { idx := 0 }),
 .op .MLOAD,
 .op (.Dup { idx := 0 }),
 .op (.Swap { idx := 14 }),
 .push 0 0,
 .op .SGT,
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op .ADD,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 8 }),
 .op (.Dup { idx := 2 }),
 .op (.Dup { idx := 2 }),
 .op .MULMOD,
 .op (.Swap { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op .LT,
 .op (.Swap { idx := 1 }),
 .op .MUL,
 .op (.Swap { idx := 1 }),
 .op .SUB,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op .LT,
 .op (.Dup { idx := 2 }),
 .op (.Swap { idx := 1 }),
 .op .SUB,
 .op .SUB,
 .op (.Swap { idx := 0 }),
 .op (.Dup { idx := 3 }),
 .push 2 3648,
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .op .MLOAD,
 .op (.Dup { idx := 2 }),
 .op .ADD,
 .op (.Dup { idx := 0 }),
 .op (.Swap { idx := 1 }),
 .op .MSTORE,
 .op .LT,
 .op .ADD,
 .push 1 38,
 .op (.Dup { idx := 6 }),
 .op .ADD,
 .op (.Swap { idx := 5 }),
 .op .JUMP,
 .op .JUMPDEST,
 .op (.Dup { idx := 5 }),
 .op .CALLDATALOAD,
 .op (.Dup { idx := 0 }),
 .push 32 21888242871839275222246405745257275088696311157297823662689037894645226208583,
 .op .EQ,
 .op (.Dup { idx := 1 }),
 .push 5 4294968272,
 .op .NOT,
 .op .EQ,
 .op .OR,
 .op .ISZERO,
 .push 2 2199,
 .op .JUMPI,
 .op (.Dup { idx := 5 }),
 .op .CALLDATALOAD,
 .push 1 1,
 .op (.Dup { idx := 2 }),
 .op .SUB,
 .op .EQ,
 .op .ISZERO,
 .push 2 2199,
 .op .JUMPI,
 .op (.Dup { idx := 4 }),
 .op .CALLDATALOAD,
 .op (.Dup { idx := 2 }),
 .push 1 32,
 .op .SUB,
 .push 1 3,
 .op .SHL,
 .op .SHR,
 .op .MOD,
 .push 0 0,
 .op .LT,
 .push 0 0,
 .op .MSTORE,
 .push 1 32,
 .push 0 0,
 .op .RETURN,
 .op .JUMPDEST,
 .push 2 5248,
 .op .MLOAD,
 .push 2 256,
 .op .EQ,
 .push 2 4973,
 .op .JUMPI,
 .push 2 5248,
 .op .MLOAD,
 .push 1 128,
 .op .EQ,
 .push 2 4691,
 .op .JUMPI,
 .push 2 5344,
 .op .MLOAD,
 .push 2 5312,
 .op .MLOAD,
 .op (.Dup { idx := 0 }),
 .push 2 3072,
 .op .ADD,
 .push 2 4160,
 .op .POP,
 .op (.Swap { idx := 0 }),
 .push 0 0,
 .op (.Swap { idx := 2 }),
 .push 2 1985,
 .op .JUMP,
 .op .JUMPDEST,
 .push 2 4384,
 .op .MLOAD,
 .push 1 224,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op .GT,
 .op (.Swap { idx := 1 }),
 .op .SUB,
 .push 2 3296,
 .op .MSTORE,
 .push 2 4352,
 .op .MLOAD,
 .push 1 192,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op .GT,
 .op (.Swap { idx := 1 }),
 .op .SUB,
 .op (.Dup { idx := 2 }),
 .op (.Dup { idx := 1 }),
 .op .SUB,
 .op (.Swap { idx := 2 }),
 .op .GT,
 .op .OR,
 .op (.Swap { idx := 0 }),
 .push 2 3264,
 .op .MSTORE,
 .push 2 4320,
 .op .MLOAD,
 .push 1 160,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op .GT,
 .op (.Swap { idx := 1 }),
 .op .SUB,
 .op (.Dup { idx := 2 }),
 .op (.Dup { idx := 1 }),
 .op .SUB,
 .op (.Swap { idx := 2 }),
 .op .GT,
 .op .OR,
 .op (.Swap { idx := 0 }),
 .push 2 3232,
 .op .MSTORE,
 .push 2 4288,
 .op .MLOAD,
 .push 1 128,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op .GT,
 .op (.Swap { idx := 1 }),
 .op .SUB,
 .op (.Dup { idx := 2 }),
 .op (.Dup { idx := 1 }),
 .op .SUB,
 .op (.Swap { idx := 2 }),
 .op .GT,
 .op .OR,
 .op (.Swap { idx := 0 }),
 .push 2 3200,
 .op .MSTORE,
 .push 2 4256,
 .op .MLOAD,
 .push 1 96,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op .GT,
 .op (.Swap { idx := 1 }),
 .op .SUB,
 .op (.Dup { idx := 2 }),
 .op (.Dup { idx := 1 }),
 .op .SUB,
 .op (.Swap { idx := 2 }),
 .op .GT,
 .op .OR,
 .op (.Swap { idx := 0 }),
 .push 2 3168,
 .op .MSTORE,
 .op .JUMPDEST,
 .push 2 4224,
 .op .MLOAD,
 .push 1 64,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op .GT,
 .op (.Swap { idx := 1 }),
 .op .SUB,
 .op (.Dup { idx := 2 }),
 .op (.Dup { idx := 1 }),
 .op .SUB,
 .op (.Swap { idx := 2 }),
 .op .GT,
 .op .OR,
 .op (.Swap { idx := 0 }),
 .push 2 3136,
 .op .MSTORE,
 .push 2 4192,
 .op .MLOAD,
 .push 1 32,
 .op .MLOAD,
 .op (.Dup { idx := 1 }),
 .op (.Dup { idx := 1 }),
 .op .GT,
 .op (.Swap { idx := 1 }),
 .op .SUB,
 .op (.Dup { idx := 2 }),
 .op (.Dup { idx := 1 })
]

theorem count7 : instructions7.length = 465 := by
  decide

theorem assemble7 : assemble instructions7 = Challenge.Modexp.submissionSpan7 := by
  apply ByteArray.ext
  simp (config := { maxSteps := 600000 })
    [assemble, assembleBytes, instructions7, Challenge.Modexp.submissionSpan7,
      Instr.bytes, natToBE]
  repeat' apply And.intro
  all_goals decide

theorem wellFormed7 :
    instructions7.all (fun i => decide (Stepper.WellFormed .Osaka i)) = true := by
  simp (config := { maxSteps := 600000 })
    [instructions7, Stepper.WellFormed, YulEvmCompiler.plainOp]
  repeat' apply And.intro
  all_goals decide

end Challenge.Modexp.Submission.Proofs.Bytecode.ArtifactChunks
