import Challenge.Modexp.Benchmark.Artifact
import Challenge.Modexp.Submission.Bytecode
import Challenge.Modexp.Submission.Isolation.Forward
import Challenge.Modexp.Submission.LocalPatch.PointerFrontier64Bindings

set_option warningAsError true
set_option maxRecDepth 20000
set_option maxHeartbeats 5000000

/-!
The candidate-dependent endpoint of the frozen frontier64 pointer refinement.

`Benchmark.bytecode` is generated by the protected benchmark preparer from the
submitted `bytecode.hex`.  `PointerFrontier64.code` is the independently checked local
literal used by the concrete decoder/layout/refinement modules.  Their exact
byte equality is the only bridge added here.
-/

namespace Challenge.Modexp.Submission.Isolation.Candidate

/-- The generated protected artifact is definitionally the exact 5,439-byte
pointer candidate checked by `PointerFrontier64Bindings`. -/
set_option maxRecDepth 40000 in
theorem submittedBytes :
    Challenge.Modexp.Benchmark.bytecode =
      Challenge.Modexp.Submission.LocalPatch.PointerFrontier64.code := by
  rfl

/-- Closed nonidentity refinement for the exact generated candidate bytes. -/
def refinement :
    ForwardRefinement Challenge.Modexp.submissionBytecode
      Challenge.Modexp.Benchmark.bytecode := by
  rw [submittedBytes]
  exact Challenge.Modexp.Submission.LocalPatch.PointerFrontier64.refinement

end Challenge.Modexp.Submission.Isolation.Candidate

#print axioms Challenge.Modexp.Submission.Isolation.Candidate.refinement
