import {readFileSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
const root='Challenge/Ripemd160/Submission/';
const old=name=>execFileSync('git',['show','HEAD:'+root+name],{encoding:'utf8'});
const layout=JSON.parse(readFileSync(root+'check/inline-layout.json','utf8'));
const hex=readFileSync(root+'check/inline.hex','utf8');
const bytes=Buffer.from(hex.trim(),'hex');
const encode = xs=>Buffer.from(xs.flatMap(x=>x.width===undefined?[x.opcode]:[0x5f+x.width,...Array.from({length:x.width},(_,i)=>Number((BigInt(x.value)>>BigInt(8*(x.width-i-1)))&255n))]));
const instr=x=>x.width===undefined?'op 0x'+x.opcode.toString(16).padStart(2,'0'):'.push '+x.width+' '+x.value;
const byteLines=bs=>Array.from({length:Math.ceil(bs.length/12)},(_,i)=>'  '+[...bs.subarray(i*12,i*12+12)].map(x=>'0x'+x.toString(16).padStart(2,'0')).join(', ')).join(',\n');
const extra=layout.instructions.slice(layout.originalCount);
const boundaries=[0,...layout.quads.map(q=>q.index-layout.originalCount),extra.length];
// Cut at every quad's end too, keeping bridge and cleanup bytes separate.
for(const q of layout.quads)boundaries.push(q.index-layout.originalCount+q.code.length);
const cuts=[...new Set(boundaries)].sort((a,b)=>a-b);
const chunks=cuts.slice(0,-1).map((x,i)=>extra.slice(x,cuts[i+1]));
let data='import Challenge.EvmProof.Program\nimport EvmSemantics.EVM.Decode\n\nset_option warningAsError true\nset_option maxRecDepth 100000\nset_option maxHeartbeats 8000000\n\nnamespace Challenge.Ripemd160.Submission.InlineData\nopen EvmSemantics EvmSemantics.EVM YulEvmCompiler Challenge.EvmProof\n\ndef op (b : UInt8) : Instr :=\n  match Decode.opcodeOf b with\n  | some o => .op o\n  | none => .op .INVALID\n\n';
for(let i=0;i<chunks.length;i++)data+=`def instructions${i} : List Instr := [\n  ${chunks[i].map(instr).join(',\n  ')}\n]\n\nabbrev bytes${i} : ByteArray := ByteArray.mk #[\n${byteLines(encode(chunks[i]))}\n]\n\ntheorem assembly${i} : assemble instructions${i} = bytes${i} := by decide\n\n`;
data+='def instructions : List Instr := '+chunks.map((_,i)=>'instructions'+i).join(' ++ ')+'\n';
data+='@[simp] theorem instructions_length : instructions.length = '+extra.length+' := by rfl\n';
data+='abbrev bytes : ByteArray := '+chunks.map((_,i)=>'bytes'+i).join(' ++ ')+'\n';
data+='theorem assembly : assemble instructions = bytes := by\n  simp only [instructions, bytes, '+chunks.map((_,i)=>'assembly'+i).join(', ')+', ArtifactSegment.assemble_append]\n';
// The append lemma is local to the submission but independent of its artifact.
data=data.replace('import EvmSemantics.EVM.Decode','import EvmSemantics.EVM.Decode\nimport Challenge.Ripemd160.Submission.Proofs.Bytecode.ArtifactSegment');
data=data.replace('ArtifactSegment.assemble_append', 'Challenge.Ripemd160.Submission.Proofs.Bytecode.ArtifactSegment.assemble_append');
data+='end Challenge.Ripemd160.Submission.InlineData\n';
const changes=new Map([['InlineData.lean',data],['bytecode.hex',hex]]);
let b=old('Bytes.lean').replace('import Init.Data.ByteArray','import Init.Data.ByteArray\nimport Challenge.Ripemd160.Submission.InlineData');
let byteOffset=0;
b=b.replace(/(abbrev submissionByteChunk\d+ : ByteArray := ByteArray.mk #\[)\n([\s\S]*?)\n\]/g,(_,head,body)=>{const size=[...body.matchAll(/0x[\da-f]{2}/g)].length;const result=head+'\n'+byteLines(bytes.subarray(byteOffset,byteOffset+size))+'\n]';byteOffset+=size;return result;});
b=b.replace(' ++ submissionByteChunk15\n',' ++ submissionByteChunk15\n ++ Submission.InlineData.bytes\n').replace('submissionBytes.size = 5233','submissionBytes.size = '+bytes.length);
b=b.replace(/(@\[simp\] theorem referenceBytes_size[^]*?)(\n\n)/, '$1\n  rfl$2');
changes.set('Bytes.lean',b);
changes.set('Bytecode.lean',old('Bytecode.lean').replace('submissionBytecode.size = 5233','submissionBytecode.size = '+bytes.length).replace('  simp [submissionBytecode]\n','  exact referenceBytes_size\n'));
let a=old('Proofs/Bytecode/Artifact.lean');
let instructionOffset=0;
a=a.replace(/(private def submissionInstructionsChunk\d+ : List Instr :=\n\[)\n([\s\S]*?)\n\]/g,(_,head,body)=>{const size=[...body.matchAll(/op 0x|\.push /g)].length;const result=head+'\n  '+layout.instructions.slice(instructionOffset,instructionOffset+size).map(instr).join(',\n  ')+',\n]';instructionOffset+=size;return result;});
a=a.replace(' ++ submissionInstructionsChunk15\n',' ++ submissionInstructionsChunk15\n ++ Submission.InlineData.instructions\n').replace('submissionInstructions.length = 3146','submissionInstructions.length = '+layout.instructions.length);
a=a.replace('submissionInstructionsChunk15_length]','submissionInstructionsChunk15_length, Submission.InlineData.instructions_length]');
byteOffset=0;
a=a.replace(/(private theorem submissionInstructionsChunk\d+_assemble : assembleBytes submissionInstructionsChunk\d+ = \[)\n([\s\S]*?)\n\]/g,(_,head,body)=>{const size=[...body.matchAll(/0x[\da-f]{2}/g)].length;const result=head+'\n'+byteLines(bytes.subarray(byteOffset,byteOffset+size))+'\n]';byteOffset+=size;return result;});
a=a.replace('    submissionBytecode, submissionBytes]','    submissionBytecode, submissionBytes, Submission.InlineData.assembly]');
let pc=0; const pcs=layout.instructions.map(x=>{const p=pc;pc+=x.width===undefined?1:x.width+1;return p;});
a=a.replace(/instructionPC (\d+) = 0x[\da-f]+/g,(_,i)=>'instructionPC '+i+' = 0x'+pcs[Number(i)].toString(16));
changes.set('Proofs/Bytecode/Artifact.lean',a);
const name=process.argv[2];
const text=changes.get(name);
if(text===undefined)throw Error('choose '+[...changes.keys()].join(', '));
let existing='';try{existing=readFileSync(root+name,'utf8');}catch{}
console.log('*** Begin Patch\n'+(existing?'*** Update File: '+process.cwd()+'/'+root+name+'\n@@\n'+existing.trimEnd().split('\n').map(l=>'-'+l).join('\n')+'\n':'*** Add File: '+process.cwd()+'/'+root+name+'\n')+text.trimEnd().split('\n').map(l=>'+'+l).join('\n')+'\n*** End Patch');
